### PR TITLE
Automatically detect the language of the user

### PR DESCRIPTION
**Pull request by thierryOrdissimo**
- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

Test Plan: inspired by the lib 'os-locale'

### CODE REVIEW

**Comment by luixxiul** [comment]
I think we need some OSes in other languages than English. I have Japanese ones.

**Comment by thierryOrdissimo** [comment]
Thank you, I am bad in English.

**Comment by luixxiul** [comment]
I confirmed this worked for me on OS X in Japanese :-)

**Comment by luixxiul** [comment]
What if detected languages are not available on Brave? Will English be automatically selected in this case?

**Comment by thierryOrdissimo** [comment]
Really it does not walk. I reach a patch which corrects problem by proving the availability of the language in 'Brave '.

**Comment by luixxiul** [comment]
Thanks! it would be nice if you provide us a test in https://github.com/brave/browser-laptop/tree/master/test

**Comment by thierryOrdissimo** [comment]
Add localeTest.js #4997

**Comment by luixxiul** [comment]
I confirmed it worked on Ubuntu for German (Deutsch) by cherry-picking the commits and creating the packaged build. If someone will confirm on macOS for another language I think it's good to go.

**Comment by bbondy** [comment]
Sorry for letting this sit for too long I wasn't sure what to do with it.
BrianJ recommends we get this from the electron side and that base/win/i18n has a more reliable way.  Thanks for the patch and consideration though.

**Comment by luixxiul** [comment]
I see, but I'd strongly recommend that to be implemented by 1.0.

**Comment by luixxiul** [comment]
I opened two tickets for the task: brave/muon#133 and #6435

**Pull request closed without merging**
