### PR TITLE
Redo: Add copy to clipboard for about brave page

### LINKED ISSUE #6183: Regression : Alignment off for about:about
Only reproducible with the PR from:
https://github.com/brave/browser-laptop/issues/5790#issuecomment-265839135

**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
Visiting about:about 'List of about pages' is flush left with no margin.

**Expected behavior:**
'List of about pages' should left-align under 'About pages' header.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on os x

- Brave Version:
0.12.15 RC2

- Steps to reproduce:
    1. Visit about:about

- Screenshot if needed:
screen shot 2016-12-13 at 11 24 29 am

- Any related issues:

### PR DESCRIPTION
**Pull request by luixxiul**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

Closes #6183

Test Plan:
1. Visit about:about

### CODE REVIEW

**Comment by luixxiul** [comment]
Closing for now

**Comment by bsclifton** [comment]
@luixxiul I think this was a good fix :smile: 

@gyandeeps as the original author, would you be interesting in reviewing these changes? You had originally submitted https://github.com/brave/browser-laptop/pull/6107 and that commit along with some tweaks were pulled into this PR by @luixxiul.  I think his fixes are great :smile:

If it looks good, you should be able to create a new branch and cherry-pick both commits in (I can help with that, if you're not sure).  Would be great to get this one closed out :smile:

**Comment by gyandeeps** [comment]
I can do that but i saw that the reverted commit has eb again committed here: https://github.com/brave/browser-laptop/commit/5324f3c64449b2043ffce4a7d9ba86ece2f88591

Let me know what your thoughts are and will act accordingly. thanks

**Comment by bsclifton** [comment]
@gyandeeps perfect- I missed that :smile: I just now confirmed that your change is there and working great!  So we just need to fix the alignment on about:about.  I'll get that taken care of

**Comment by gyandeeps** [comment]
@bsclifton Here is the fix for about:about title: https://github.com/brave/browser-laptop/pull/6299

**Pull request closed without merging**
