### PR TITLE
Enable importing passwords from Firefox

### LINKED ISSUE #9292: Import passwords from Firefox
including passwords list and never saved list

### PR DESCRIPTION
**Pull request by evq**
Auditors: @darkdh 

requires https://github.com/brave/muon/pull/216
closes #9292

Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@evq can you please squash your commits

**Comment by NejcZdovc** [comment]
Please add github auto-closing keyword into squashed commit

**Comment by bsclifton** [comment]
Holding off on merge until Muon code is accepted

Changes look great- nice work, @evq 😄

**Comment by cezaraugusto** [comment]
muon code was accepted, @evq could you pls rebase?

**Comment by cezaraugusto** [comment]
also pls remove label once you do, thanks!

**Comment by evq** [comment]
I rebased, waiting on a muon build to retest then I will push / remove the label

**Comment by evq** [comment]
@cezaraugusto I just pushed my rebased version, though I don't seem to be able to remove the label

**Comment by bridiver** [comment]
@evq does this have any moun dependencies?

**Comment by darkdh** [comment]
muon dep has already been merged 
https://github.com/brave/muon/pull/216

**Comment by bridiver** [comment]
this needs to wait for a 4.2.x build (and update b-l 0.19) before merging. Should be ready by tomorrow

**Comment by evq** [comment]
@bridiver is this good to merge since bd36f33a updated muon to `4.2.2`?

**Comment by hh-here** [comment]
I suspect that there's something I don't 'get'.
I'm running: Linux Mint 17.3 Rosa
&
Brave | 0.19.6
-- | --
rev | 3be25d4
Preferences; Import Now; Saved Passwords => A box which tells me that it has done the biz' for both Chromium Version 59.0.3071.109
&
Firefox 54.0 (64-bit)
Then with Password Manager = Brave Built In
Security; Manage Passwords => No passwords have been saved

Q1. Are the passwords managed / saved elsewhere?
Q2. Is there something I have missed?

PS. The Firefox importing was a couple of seconds, the Chromium was 10s of seconds.

**Pull request merged**
