### PR TITLE
Remove perWindowState from immutableData if there are no frames in it

### LINKED ISSUE #10768: Private tab in its own window causes that window to be white on relaunch (and sometimes unusable)
## Test plan

https://github.com/brave/browser-laptop/pull/11169#issue-260846709

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When a Private tab is in its own window prior to Brave being is closed/relaunched, that window appears all white on relaunch and is in some cases unusable.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS, verified on Win by @kjozwiak 

- Brave Version (revision SHA):
0.18.24

- Steps to reproduce:
    1. Launch Brave. 
    2. Load two tabs with any two sites. 
    3. Create a new Private tab and load a site.
    4. Tear off/detach the Private tab so it is now in its own window. (you now have two windows)
    5. Close/relaunch Brave.
    6. Window which had the Private tab displays all white.
    
- Actual result:
Window which had the Private tab displays all white (appears dead). You can however type in the URL bar and load a site.

- Expected result:
Window should either display what your selection for what 'a new tab shows' or not be there at all since it held a private tab prior to closing Brave.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes, 0.18.23

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Launch Brave. 
    2. Load two tabs with any two sites. 
    3. Create a new Window (you now have two windows). Create a Private tab and load a site. Close the normal tab that was in this window.
    4. Close/relaunch Brave.
    5. Window which had the Private tab displays all white. Note - this time you can't reuse this window. If you type in the URL bar, the tab loads with site tab name, but no content displays in the tab.

- Screenshot if needed:
Prior to close:
screen shot 2017-09-01 at 4 02 55 pm

After relaunch:
screen shot 2017-09-01 at 4 03 33 pm

- Any related issues:

### PR DESCRIPTION
**Pull request by syuan100**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

## Test Plan:
- Open Browser
- Create 2 tabs and navigate to websites of your choice
- Create a private tab and navigate to a website of your choice
- Tear off the private tab so it creates a new window
- Quit the browser
- Reopen the browser and only 1 window should show up

Fixes #10768 

## Reviewer Checklist:
@bsclifton 

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

**Comment by syuan100** [comment]
I would label this PR, but I don't think I have the rights still

**Comment by luixxiul** [comment]
@syuan100 would you please rebase?

**Comment by bsclifton** [comment]
@syuan100 sorry for the extremely long time for review ☹️  (It's definitely my fault this hasn't been reviewed yet)

I just rebased and this is on my radar again

**Comment by syuan100** [comment]
Hey! No worries I know that you guys had a lot on your plate ;) nice job with Mercury!

I might just redo my changes on a fresh branch. Let me know if that would be easier. The rebase was a bit messy @_@

**Comment by syuan100** [comment]
@bsclifton ^

**Comment by bsclifton** [comment]
@syuan100 no worries- this PR should be good to go! I ensured it's correct by rebasing against master and checking against your original commits 😄

**Pull request merged**
