### PR TITLE
Allow favicon fetching code to fetch CORS-enabled images without tain…

### LINKED ISSUE #14742: favicon.js fails with cross origin href due to lacking required attribute (security)
### Description
The favicon loaded on https://guided.adobe.com used to work, but now it errors with a canvas DOM security error due to the favicon.js lacking the `crossOrigin` attribute to allow access.

### Test plan / Steps to Reproduce

1. Visit https://guided.adobe.com, an uncaught error will happen & the application will halt suggesting using Brave & other browsers (this is a regression between March '18 & now).

**Actual result:**
`resolve(canvas.toDataURL('image/png'))` fails with a DOM error

```
VM447:1 Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at eval (eval at img.onload (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/content/scripts/favicon.js:13:7), <anonymous>:1:8)
    at Image.img.onload (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/content/scripts/favicon.js:13:7)
(anonymous) @ VM447:1
img.onload @ favicon.js:13
load (async)
Promise @ favicon.js:7
getBase64FromImageUrl @ favicon.js:2
(anonymous) @ favicon.js:25
```

**Expected result:**
`resolve(canvas.toDataURL('image/png'))` succeeds

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.23.31 
V8: 6.7.288.46 
rev: 3148acef36dba0fce89108638bb27927c4937f90 
Muon: 7.1.5 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**
Yes

### Additional Information
This error did not exist when I made guided.adobe.com public in March'18.

### PR DESCRIPTION
**Pull request by Slava**
…ing the canvas

Fixes #14742

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by riastradh-brave** [comment]
If canvas.toDataURL can raise an exception, then as a defensive measure, can we also surround it by `try { ... } catch (e) { reject(e) }`, or is there a reason not to do that?

**Comment by Slava** [comment]
@riastradh-brave as far as I can tell, we wouldn't do any further error-handling on the promise anyway. And the thrown error does not block the execution of anything else?

We can put a try-catch for cleaner code, but if an error occurs for whatever new reason we don't have a way to respond anyway?

**Comment by bsclifton** [comment]
@avoidwork this will be in our next release- which should be happening within 1/1.5 weeks 😄

**Comment by avoidwork** [comment]
yay! thanks!

**Comment by bsclifton** [comment]
master 7ddb011f55bfcea4ae464fece1e57daa3d0bd48e
0.24.x 6e2d6e1426b5af1cc738767530f4a20a5d73c13e
0.23.x 7d0bd10bf8cb47f56e19797b67ebce445233dd32

**Comment by BrendanEich** [comment]
Yeah, the CORS crossOrigin property is not as well known as it should be. Thanks again @avoidwork for reporting and pushing on this.

**Comment by riastradh-brave** [comment]
I didn't mean using try/catch _instead of_ setting crossOrigin -- rather, _in addition to_, as a defensive measure in case anything else goes wrong, so that in that case the promise is correctly rejected when it fails.

**Comment by riastradh-brave** [comment]
Got it.  Sounds good, then!

**Pull request merged**
