### PR TITLE
Set frame to empty map when unavailable

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Auditors: @bridiver, @bbondy

### CODE REVIEW

**Comment by bbondy** [comment]
@darkdh is this PR needed? it seems like it at least needs a rebase.

**Comment by darkdh** [comment]
Yes, I will rebase it !

**Comment by darkdh** [comment]
These sequential changes(13649691e59c16c7a59709370e0d3520dd943177, 0423e539c3180e65f2dac2bde89157886a63f2ff and this one e59e2eef374d37befb7c284b303e51a85d99a84a)  is removed by 7fb2e4c30c98b592c00fc390648f99672a6caad7.
However, the event still emit after webcontent destroyed. 
I'm not sure if we still want this workaround or not. CC @bridiver

**Comment by bridiver** [comment]
@darkdh I think it actually isn't needed anymore. I made some other changes in muon that appear to have fixed the `isFocused` issue

**Comment by luixxiul** [comment]
Please close this PR if not needed anymore, thanks.

**Pull request closed without merging**
