### PR TITLE
Multi channel - embed channel identifier in build and show in about dialog

### PR DESCRIPTION
**Pull request by aekeus**
This is step 1 in the laptop browser multi channel project. We are embedding the channel in the binary but not asking for updates from a particular channel (which will be step 2).

### CODE REVIEW

**Comment by bbondy** [comment]
This looks good to me @aekeus if you want to merge (after rebasing)

**Comment by aekeus** [comment]
Ok, thanks. Will do.

**Comment by aekeus** [comment]
Ping @bbondy on this pull request - a few things changed since the last time you looked at it. This has now been tested with the deployed back-end changes on both osx and winx64.

**Comment by bbondy** [comment]
Thanks!

**Pull request merged**
