### PR TITLE
Add field separators to getSiteKey

### LINKED ISSUE #6936: getSiteKey needs field separators
screen shot 2017-01-31 at 12 39 44 am

marked as a security issue since it allows untrusted data (the site URL) to modify trusted data (the partition number)

i think it would be best for this to land before the site refactor code is released, otherwise you would have to do a siteKey migration from the old format.

### PR DESCRIPTION
**Pull request by darkdh**
fix #6936

Auditors: @diracdeltas, @bbondy

Test Plan: Covered by automation test

Note: No migration for old sites data due to still not releasing

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

### CODE REVIEW

**Comment by luixxiul** [comment]
This will not be included in 0.13.1

**Comment by diracdeltas** [comment]
is 6e9eb572562a6ad31c96d0cab9eb4c5975b5bd4e in 0.13.1? if so, it would be much easier for this to also be in 0.13.1 to avoid the data migration issue.

**Comment by luixxiul** [comment]
CC @bbondy for resetting the milestone :pray:

**Comment by darkdh** [comment]
https://github.com/brave/browser-laptop/pull/5587 is in 0.13.2. The original 0.13.1 has moved to 0.13.2

**Pull request merged**
