### PR TITLE
Fix mysterious searx favicon disappearing in builds

### PR DESCRIPTION
**Pull request by diracdeltas**
fix https://github.com/brave/browser-laptop/issues/14653

for some reason, renaming the searx favicon to something that doesn't have
'searx' in the filename makes it reappear. note this is only a bug in packaged builds.

Test Plan:
1. make a packaged build
2. open brave
3. hit ':x' in urlbar. searx favicon should appear.

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by diracdeltas** [comment]
specifically, this fixes https://github.com/brave/browser-laptop/issues/14653#issuecomment-404295945 (not the entire issue - that was done in an earlier PR)

**Comment by bsclifton** [comment]
master 4c7e194aa805924472593297b89058712d453f8f
0.24.x fc9e4af0b7fe89f928aa2b280b4467a24a520fab
0.23.x 11f9e319aa89fb93988d33868d02e73759f3c982

**Comment by riastradh-brave** [comment]
??????!????!?!!!?

**Comment by diracdeltas** [comment]
@bbondy only in packaged builds. i tried renaming the file to various other things like `searx.png` / `searx.svg` / `favicon_searx.png` and those were also broken.

**Pull request merged**
