### PR TITLE
Create a Buffer Window in order to pre-render and open new windows faster

### LINKED ISSUE #12437: Windows should load more instantly
As part of the performance initiative, it has been determined that a task to attack is the time a user must wait for new windows to be created and rendered, before creating / viewing the tab(s) for that window.

Adding timing to measure this from window creation to when react has finished rendering, it seems to take 1s to render a window (+1s/-0.5s depending on system).

### PR DESCRIPTION
**Pull request by petemill**
A buffer window is created at startup, and any time a previous buffer window is detached in order to be utilized as a real window.
This type of window is not shown and has no tabs (pinned or non-pinned) until it is shown.
State is not persisted for Buffer Windows until they are utilized as real windows.

A new command-line flag is introduced: '--debug-window-events' which shows logging around Buffer Window creation and utilization, as well as all other window events. No additional logging should be present without this flag.

I had built some of this functionality for #11720 (Tabs transitions) in order to decrease the time to detach a tab to a new window. At the same time, a request came through Asana for the performance initiative to do this same thing for every window. This PR is the result of adapting the code from #11720 for all (compatible) window creation.

Fix #12437

#### Window creation
- Brave starts with 1 window
- A new window can be opened
   - The window opens instantly without any wait

#### Window + frame creation
- Open a tab that has links on it
- Right-click any link and choose 'Open in New Window'
   - The window opens instantly, and the tab with the link's url is opened

#### Window persistance
 - Open at least 2 windows, with at least 2 tabs in each
 - Quit Brave
 - Open Brave again
     - All windows and tabs are re-opened
     - No extra windows are re-opened

#### Pinned tabs
 - Open 2 windows
 - Pin a tab in window 1
    - Tab is pinned in window 1 and window 2
 - Open a new window
     - Window opens instantly
     - new window (3) has the pinned tab

#### Window focus (especially for Windows OS due to brave/muon#424)
- Create a new window
    - The window opens instantly
    - The window gets focus instantly
    - The window does not lose focus, and the urlbar can be typed in without any further action
Especially on Windows: ensure that always when a new window is created, that the new window gets and keeps focus (in the url bar for example)

#### Detach tab to new window
- Create 1 window with mulitple tabs
- Detach a tab (right-click --> Detach, or drag the tab away from Window)
    - Ensure the tab's new window was created from a buffer window
    - Ensure the window is positioned correctly by the mouse cursor (if dragged out), as per previous version of Brave.

#### Popup window
- Open two windows with two different sites in each window
- Pin 1 site in 1 window
   - Site will be pinned in Window 1 and Window 2
- Visit http://www.popuptest.com/goodpopups.html
- Click "Good Popup #1"
     - Popup should open in a new window
     - Popup window should be buffer window
     - Popup window should be sized small (according to the popup request)
     - Popup window **should not have any pinned tabs**
- Pin 1 site in window 2
     - Window 1 and Window 2 should get the new pinned site
     - Popup window should still not have any pinned tabs

#### Logging
 - start Brave with the flag `--debug-window-events`
    - observe console log entries for all window events

 - start brave without the above flag
    - observe no console log entries

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [x] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

Reviewer Checklist:

- [x] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by petemill** [comment]
On the Windows platform, new windows that are created from Buffer Windows have their focus stolen by the next created Buffer Window (which happens immediately) due to https://github.com/brave/muon/issues/424

**Comment by petemill** [comment]
This is no longer blocked since brave/muon#424 is fixed, and is ready for review @bsclifton. I added a few test cases to this PR.

**Comment by NejcZdovc** [comment]
@petemill please rebase

**Comment by petemill** [comment]
@NejcZdovc good catch - rebased!

**Comment by petemill** [comment]
Thanks @bsclifton for finding those issues. I have fixed those issues and updated the description with three additional test cases:
- Popup windows (use buffer window and behave as previously)
- Tab detaching to new window uses buffer window
- Restarting Brave does not result in additional restored Window each time.

I also found that the focused window wasn't restored as the focused window on app restart. I fixed it because I thought it was a regression introduced here, but looks like it wasn't, so I created another PR for it at #13161

**Comment by bsclifton** [comment]
master 4c54e81077d8b7d1580925769e76fd25ae4dbbb1
0.22.x ad9306a865ae50a56b03dac6e59f634bd2322346
0.21.x in progress...

**Pull request merged**
