### PR TITLE
New database for verifying publishers

### LINKED ISSUE #11678: pivot to new publisher verified database
cf., https://github.com/brave/internal/issues/128

ideally, this would be incorported into hotfix3, the week of november 13, 2017

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #11678

-----------
- [x] Plan A:
- create wallet on the latest master
- switch to this branch
- check that folder `ledger-publishersV2.leveldb` is deleted in the user profile
-----------
- [x] Plan B (publisher is not verified):
- create wallet
- visit https://slo-tech.com and stay on that site for 15s
- go back to ledger table and verify that there is no verify icon
-----------
- [x] Plan C (publisher is verified, but didn't opt-in display):
- create wallet
- visit https://clifton.io and stay on that site for 15s
- go back to ledger table and verify that there is no verify icon
-----------
- [x] Plan D (publisher is verified and did opt-in display):
- create wallet
- visit https://duckduckgo.com/ and stay on that site for 15s
- go back to ledger table and verify that there is verify icon
-----------
Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by mrose17** [comment]
LGTM.

**Comment by bsclifton** [comment]
@NejcZdovc just to confirm:
- ledger-publishersV2.leveldb should be deleted (it is!)
- ledger-rulesV2.leveldb should still be there

**Comment by NejcZdovc** [comment]
@bsclifton correct

**Comment by bsclifton** [comment]
master 8ea4abefc09b863a0e77358ce9c025e6e64ee268
0.21.x 1c17c51f4d44eb98604e02b32f332f0985e5c5d2
0.20.x d02501e4f16c79d512d025d0744b7e76383b92de
0.19.x @NejcZdovc can you help me cherry-pick this one?

**Comment by NejcZdovc** [comment]
@bsclifton merged into 0.19 c786a97ac2609c57f2926b12e2987f0fba429ed5

**Pull request merged**
