### PR TITLE
PR numbers attached to release notes for 0.9.5

### PR DESCRIPTION
**Pull request by luixxiul**
cc: @bbondy

### CODE REVIEW

**Comment by bbondy** [comment]
Thanks!
Could you rebase off of master? There was one other note added.

**Comment by luixxiul** [comment]
Maybe breaking something.. :-( Will you please resolve the conflict?

**Comment by luixxiul** [comment]
Sorry for many commits.. this was my first rebase :persevere:

**Comment by bbondy** [comment]
Sorry this really mangles the commit history, please do a new pull request with only one commit for the changes, which is rebased off of master. Thanks.

**Pull request closed without merging**
