### PR TITLE
update extension apis for https://github.com/brave/muon/commit/ecfb71…

### PR DESCRIPTION
**Pull request by bridiver**
required for muon api changes
cc @bbondy

### CODE REVIEW

**Comment by bbondy** [comment]
is this safe to merge?

**Comment by bridiver** [comment]
Not without the muon side

**Comment by luixxiul** [comment]
If you have time please open an associated issue to explain what should be fixed with the PR. Thanks!

**Comment by bridiver** [comment]
@luixxiul nothing is fixed with this change. The purpose is to migrate node APIs to pure JS

**Pull request merged**
