### PR TITLE
Refactor clearBrowsingDataPanel.js with commonForm

### LINKED ISSUE #8192: Refactor clearBrowsingDataPanel with commonForm
**Describe the issue you encountered:** Refactor clearBrowsingDataPanel with commonForm

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #8192
Addresses #7989 

- Added CommonFormSmall
- Added data-test-id and testIds
- Removed clearBrowsingDataPanel from forms.less
- Updated test code

Auditors:

Test Plan:
1. Open Clear browsing data panel from the menu
2. Test the cancel button works
3. Reopen the panel
4. Test the clear button works

screenshot 2017-04-11 1 04 19

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

### CODE REVIEW

**Comment by luixxiul** [comment]
Note: most of camel cases should be fixed after https://github.com/brave/browser-laptop/pull/8136 is merged.

**Comment by luixxiul** [comment]
@cezaraugusto Updated.

**Comment by luixxiul** [comment]
@cezaraugusto I think the tests would pass: https://travis-ci.org/luixxiul/browser-laptop/jobs/224590108#L1802

**Comment by luixxiul** [comment]
However on my local machine I got these errors:

````
  Clear Browsing Panel
    with saved state values
      1) saves the history switch state
    with history
      2) "before each" hook for "shows clearing options"
    with closedFrames
      3) "before each" hook for "clears closedFrames"
    with site settings
      4) "before each" hook for "clears site settings and permissions"


  0 passing (1m)
  4 failing

  1) Clear Browsing Panel with saved state values saves the history switch state:
     WaitUntilTimeoutError: element ([data-test-id="clearBrowsingDataButton"]) still not visible after 10000ms
      at isVisible("[data-test-id="clearBrowsingDataButton"]") - waitForVisible.js:37:22

  2) Clear Browsing Panel with history "before each" hook for "shows clearing options":
     Promise was rejected with the following reason: Error: unknown error: Cannot read property 'appStoreRenderer' of undefined
  Error

  3) Clear Browsing Panel with closedFrames "before each" hook for "clears closedFrames":
     Promise was rejected with the following reason: Error: unknown error: Cannot read property 'appStoreRenderer' of undefined
  Error

  4) Clear Browsing Panel with site settings "before each" hook for "clears site settings and permissions":
     Promise was rejected with the following reason: Error: unknown error: Cannot read property 'appStoreRenderer' of undefined
  Error
````

I think something is needed to complete the tests successfully, yet I'm not sure what it is.

**Comment by NejcZdovc** [comment]
@luixxiul I run this test locally, it works on `refactoring-aphrodite` on this branch I get this errors:

```
  Clear Browsing Panel
    with saved state values
      1) saves the history switch state
    with history
      2) shows clearing options
      3) clears the browsing history
    with closedFrames
      ✓ clears closedFrames (350ms)
    with site settings
      4) clears site settings and permissions


  1 passing (1m)
  4 failing

  1) Clear Browsing Panel with saved state values saves the history switch state:
     WaitUntilTimeoutError: element ([data-l10n-id="security"]) still not visible after 10000ms
      at isVisible("[data-l10n-id="security"]") - waitForVisible.js:37:22

  2) Clear Browsing Panel with history shows clearing options:
     WaitUntilTimeoutError: element ([data-l10n-id="security"]) still not visible after 10000ms
      at isVisible("[data-l10n-id="security"]") - waitForVisible.js:37:22

  3) Clear Browsing Panel with history clears the browsing history:
     WaitUntilTimeoutError: element ([data-l10n-id="security"]) still not visible after 10000ms
      at isVisible("[data-l10n-id="security"]") - waitForVisible.js:37:22

  4) Clear Browsing Panel with site settings clears site settings and permissions:
     WaitUntilTimeoutError: element ([data-l10n-id="security"]) still not visible after 10000ms
      at isVisible("[data-l10n-id="security"]") - waitForVisible.js:37:22
```

**Comment by luixxiul** [comment]
@NejcZdovc do you have any clues? I don't.

**Comment by NejcZdovc** [comment]
@luixxiul I rerun it again and now it's all green. Not sure what was wrong in the first run.

**Pull request merged**
