### PR TITLE
[WIP] Add settings for new tab behaviour

### PR DESCRIPTION
**Pull request by kingscott**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist; didn't need to, there was [one](https://github.com/brave/browser-laptop/issues/2106) created.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Ran `git rebase -i` to squash commits if needed.
## Frontend tasks
- [x] Add drop-down selector to choose what the new tab will load
## Logic tasks
- [x] Hook up drop-down to given options new tab page
- [x] Hook up drop-down to home page
- [x] Hook up down-down to user's search engine
- [x] Handle use case 1: user opens new tab via '+' in tab bar
- [ ] Handle use case 2: user opens new tab via hamburger menu

Fixes https://github.com/brave/browser-laptop/issues/2106

### CODE REVIEW

**Comment by bbondy** [comment]
Thanks @kingscott !

@cezaraugusto could you merge this into your newtab branch then close this pull request? Thanks. We want to merge this at the same time as your work.

**Comment by kingscott** [comment]
@bbondy Still need to fix the case where the user opens a new tab with the keyboard.

**Comment by bbondy** [comment]
OK @kingscott do you anticipate doing that soon or should we pull in the code and add it?

**Comment by kingscott** [comment]
Yes I do @bbondy. Was going to do my best to get it done this week. Should I send you (or someone else) a message on Slack based on status close to the end of this week?

**Comment by bbondy** [comment]
Cool thanks, either Slack or here is fine.

**Comment by bsclifton** [comment]
Original branch was deleted and the patches here are super out of date-

I cherry picked commits, manually resolved the items, and squashed the commits into a branch on my fork:
https://github.com/brave/browser-laptop/compare/master...bsclifton:newtab-preferences?expand=1

I'm going to close this PR and I'll take over the remaining work :smile:

**Pull request closed without merging**
