### PR TITLE
Fixes #2444: Pressing down on URL bar should open autosuggest

### LINKED ISSUE #2444: Pressing down on URL bar should open autosuggest
Expected:
When there are other suggestions based on the current URL load, pressing down doesn't help bring up the autocomplete.

Actual:
When there are other suggestions based on the current URL load, pressing down does nothing.

### PR DESCRIPTION
**Pull request by willy-b**
- Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.

### CODE REVIEW

**Comment by willy-b** [comment]
Oops, it looks like some checks have failed.
However, the AppVeyor errors seem to be in an early part of the build process (npm preinstall/install ; installing bloom-filter-cpp?) which was not modified. I didn't change any dependencies, so confused how the 'npm install' step got broken. Looking into it.

See below:
appveyor_builderror_1
appveyor_builderror_2

**Comment by bbondy** [comment]
We don't have AppVeyor fully setup yet so you can ignore that. Also Travis will intermittently fail so no worries there.

**Comment by willy-b** [comment]
OK, consistent with that, the Travis test failures are all timeouts:
travisintegrationtests

I'll still look into those tests locally and see if these timeouts might be reflecting a UI slowdown from the changes.

**Comment by bbondy** [comment]
This is a little different behaviour than what I was expecting and what chrome/firefox does.
Could you only show when there is an onKeyDown event?

**Comment by willy-b** [comment]
Whoops, thought the issue was asking for dropdown on mouse-down! :-).

**Comment by bbondy** [comment]
perfect, thanks for the patch!

**Pull request merged**
