### PR TITLE
Use translation for confirmation dialog for all password deletion

### PR DESCRIPTION
**Pull request by vinicentus**
Fixes https://github.com/brave/browser-laptop/issues/13181

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

**Additional infromation:**
We'll also have to update other translations if this passes

### CODE REVIEW

**Comment by bsclifton** [comment]
@vinicentus can you squash your commits and update the commit message to include:
`Fixes https://github.com/brave/browser-laptop/issues/13181`?

If you're not sure how I'd be glad to help with that part 😄

**Comment by vinicentus** [comment]
@bsclifton squashed the commits and added auto closing keyword. Everything went fine after some googling 😃

**Comment by vinicentus** [comment]
@bsclifton Why did this get pushed so far back in milestones? Because the code seems to be ok I think we could push it in [0.22.x (Beta Channel)](https://github.com/brave/browser-laptop/milestone/78) or something?

**Comment by bsclifton** [comment]
@vinicentus our current milestones are a little loaded up- took a while to find a place to land this.  I'm reviewing now and should be able to merge to master if all checks out 😄 👍

**Comment by bsclifton** [comment]
Congrats on your first patch, @vinicentus 😄 🎉

**Comment by vinicentus** [comment]
Thanks! The test plan seems good! 😄 Already tested it earlier with a similar test plan.

**Pull request merged**
