### PR TITLE
Fresh profile setup

### PR DESCRIPTION
**Pull request by arsalankhalid**
Hi brave team, 

I've been looking for documentation or any mention of how to create a fresh profile, or let alone create a new one, and to my surprise  there wasn't much info on profiles and the creation of new ones for development purposes. I could however be blatantly wrong, and happy to be corrected :) 

I think this PR is similar to the bug pointed out in #12077, but this issue refers more so to simply refreshing your local profile. Overall, I think there's a gap here that can be easily addressed with a script such as this, but I'm certain this script is hacky. With code like:

a chmod 777, it seemed to be the only way around getting access to the brave-dev folder, and to simply overwrite your profile, rather than to create a copied folder with a timestamp associated with it. Happy to improve this PR, but wanted to gage what the openness to this is, as I imagine there would be some hit-back on the fact that there's a .zip in the root directory, think that may not be the best path, as well as security friendly approach - so looking for some direction here.  

Arsalan

@NejcZdovc, @srirambv 

## Submitter Checklist:
- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [x] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Reviewer Checklist:

- [ PENDING] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests
Any specific required/preferred?

### CODE REVIEW

**Comment by arsalankhalid** [comment]
Hmm it seems a few un-warrenting commits got put into this branch somehow, apologize for that - I'll fix that. Certainly don't want a merge commit of master, and old PRs to be a part of this.

**Comment by arsalankhalid** [comment]
@bsclifton I realized this could actually be done through code, but no one's gotten back to me yet. Can someone please provide a quick review?

**Comment by bsclifton** [comment]
Here's a more platform-aware way that you can achieve this:

```sh
if [ "$(uname -s)" == "Darwin" ]; then
  sudo rm -rf ~/Library/Application\ Support/brave-development
elif [[ "$(uname -s)" == *"MINGW64_NT-"* ]]; then
  rm -rf ~/AppData/Roaming/brave-development/
elif [ "$(uname -o)" == "Cygwin" ]; then
  rm -rf ~/AppData/Roaming/brave-development/
else
  rm -rf ~/.config/brave-development/
fi
```

**Comment by arsalankhalid** [comment]
@bsclifton just saw this, been absolutely destroyed at work. Your comments are awesome, I'll take a go  at getting this fixed up :)

**Comment by bsclifton** [comment]
Closing as stale

**Pull request closed without merging**
