### PR TITLE
Use language name for sort order instead of identifier. Fix a few outdated comments

### PR DESCRIPTION
**Pull request by aekeus**
Issue: #3955

Auditors: @bbondy, @alexwykoff

Test Plan:

  i. Open about:preferences
  ii. Ensure languages are in alphabetical order in select

### CODE REVIEW

**Comment by Liunkae** [comment]
With this change, the languages will be sorted by their _English_ names. This could be a little confusing for non-English users since the language list has no logical order in their language (the language names themselves are localized).

If we go with sorting by language name, I suggest we also sort the list in other languages. (Another issue should be opened for that, though.)

**Comment by luixxiul** [comment]
I strongly agree, How about following Wikipedia?

**Comment by Liunkae** [comment]
@luixxiul How does Wikipedia sort languages?

Also, I found this old issue for my previous point (#1747).

**Comment by bbondy** [comment]
no objection since it doesn't make it worse but I think doing a sort within the render in react would be better because it would work with all langs

**Pull request merged**
