### PR TITLE
Added release notes link to about:brave

### PR DESCRIPTION
**Pull request by srirambv**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:
1. Open about:brave
2. Should contain `Browse faster and safer with Brave.` below `About Brave`
3. Should have a new section `Release Notes`
4. Clicking  on hyperlink should open GitHub release page

~~app.properties file alphabetized for easier readability and future new additions, new values for the PR in line 35, 177-180~~

Closes: #6130

### CODE REVIEW

**Comment by bsclifton** [comment]
@srirambv can you resolve the conflicts? This just needs a rebase.  I can review in the meantime and then accept quickly if everything looks good 😄  thanks!

**Comment by srirambv** [comment]
@bsclifton conflicts resolved

**Comment by srirambv** [comment]
Changed href to use the installed ver to open the release notes page. Thanks to @NejcZdovc for the help

**Comment by bradleyrichter** [comment]
"Release Notes" should get the same style as "Version Information" because "About Brave" should be the primary title.

I don't think we need a lion icon here, and it would upset the alignment unless we make it a 2 column layout.

**Comment by NejcZdovc** [comment]
@srirambv Link implementation looks good

**Comment by bsclifton** [comment]
I made a quick commit w/ the feedback 😄 
screen shot 2017-04-04 at 11 20 02 am

**Comment by srirambv** [comment]
Thanks for the quick update @bsclifton  👍

**Pull request merged**
