### PR TITLE
wrapper for urlbar inputs

### PR DESCRIPTION
**Pull request by psimyn**
this probably causes more problems than it solves...

Main issue I was trying to resolve was `position: absolute` on lock icon, loadtime and bookmark icon causing issues with centering/layout of title.

Also adds some conditional rendering for title/input modes, instead of both always being there

### CODE REVIEW

**Comment by bbondy** [comment]
> this probably causes more problems than it solves...

That line makes me worry, is this ready for review?

**Comment by psimyn** [comment]
@bbondy that line was due to it not being linked to a specific issue :)

Hold off on review until I fix tests though - 2 remaining breakages due to urlBar element not existing in titleMode (and vice-versa). If that ends up being huge effort I'll go back to hiding with css, but only rendering relevant elements seems a better solution.

**Comment by psimyn** [comment]
@bbondy tests should be fixed now. Main functional change from this is removing title/urlbar when not in use - made some tests a bit funny but they match up with what a user actually sees.

Let me know what you think

**Comment by bbondy** [comment]
Thanks, merging

**Pull request merged**
