### PR TITLE
Add style standard to style doc

### LINKED ISSUE #8340: Discussion: CSS methodologies (OOCSS/BEM/SMACSS/...) in creating/refactoring with Aphrodite
- Describe the issue you encountered:
https://github.com/brave/browser-laptop/commit/234cfba499ababd498b73ca31065219f9e369d4c#commitcomment-21773452

> Adding styles without semantic rules is a quite bad habit, which actually has resulted in creating CSS preprocessors like LESS and SCSS, and I notice that such a case started happenning on our project as well. We should consider the way of avoiding it somehow. I'm afraid of it that otherwise it would be very difficult to keep style consistency.

@cezaraugusto and @bsclifton agree with me that some kind of methodology to avoid styles from scattering and keep them consistent should be adopted, until Aphrodite will start supporting nesting styles like we do with LESS. By creating components with one of the methodologies it will be easy to nest the code blocks later.

At first we need to discuss which methodology we are going to use. At a glance BEM will be suited for us. See: https://github.com/brave/browser-laptop/pull/7831/files#diff-fa59d1e0221a5bee94fd2abd9b96dcfdR158

### PR DESCRIPTION
**Pull request by cezaraugusto**
Auditors: @luixxiul
Close #8340

We have standardjs to take care of coding practices but we're still loose about how we deal with styles. As codebase grows it gets harder to follow a convention. This update adds new coding practices while writing styles and enforce using our adapted BEM pattern.

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@cezaraugusto can we put this into linter? eslint custom rule maybe?

**Comment by cezaraugusto** [comment]
I was thinking about that yesterday, a custom eslint rule would be ideal. We can take `StyleSheet.create` as the identifier and work from there looking for spaces/quotes and other rules we want to check.

Didn't have time to look closer but worth considering, so ++. I created an issue to track this #9181

**Comment by luixxiul** [comment]
I would add the reason why we are going to choose BEM over other methodologies (1. following BEM should avoid visual regressions nicely, 2. BEM makes it possible for us to make preparations for style nesting in advance, though it is not sure if it could be implemented to `Aphrodite`).

Also I found a typo on the file. I'm going to fix it and push the fix.

**Comment by luixxiul** [comment]
This is the fix: https://github.com/luixxiul/browser-laptop/commit/0bfcb6ad7e1156b2e71b35bc2cdd4bbffcdcff93

please cherry-pick and squash it, thanks.

**Comment by cezaraugusto** [comment]
thanks, added some reasons on why we choose BEM, feel free to edit if you have more/better ones

**Pull request merged**
