### PR TITLE
l10n of ledger advanced settings modal window

### LINKED ISSUE #4786: l10n of ledger advanced settings modal window
**Describe the issue you encountered:** buttons on ledger advanced settings modal window are broken.

clipboard01

**Expected behavior:** Buttons should not word-wrap.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.5 RC1
- Any related issues: #2096

### PR DESCRIPTION
**Pull request by jkup**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fix #4786

Auditors @luixxiul @bsclifton 

Test Plan:

1. Change language to Japanese
2. Go to Preferences > Payments
3. Click on Advanced Settings (gray button at the top right)
4. Make sure buttons are not broken like in this screenshot

broken

### CODE REVIEW

**Comment by luixxiul** [comment]
Let's consider other languages than Japanese too.

**Comment by srirambv** [comment]
#5771 the text is fine but the buttons are too big and the done button is slipping below the recovery wallet button

**Comment by luixxiul** [comment]
@srirambv it should be fixed once #5705 is merged

**Comment by jkup** [comment]
Where are we at on this ticket? @luixxiul I saw you had a few related CSS commits go through. Should I close this PR for now?

**Comment by luixxiul** [comment]
@jkup yeah I think so. thanks in advance.

**Pull request closed without merging**
