### PR TITLE
Fix scroll bar issues on bravery panel

### LINKED ISSUE #9296: Hide empty scrollbar on bravery panel
**Describe the issue you encountered:**
https://github.com/brave/browser-laptop/pull/9078#issuecomment-306670958
> not a blocker but let's track this one for the next polish, overflow for tracker list should be auto here to avoid empty scrollbar when there's no overflow:
>
> screen shot 2017-06-06 at 11 42 27 pm

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #9016

### LINKED ISSUE #9802: scroll bar issues on shields
**Describe the issue you encountered:** There are two known issues on the scroll bar on bravery panel.

1. cursor:text on the scroll bar should be replaced

  clipboard03

2. Scroll bar should not appear when there is only one blocked resource on the list

- Brave Version (revision SHA): 0.17.13

- Steps to reproduce:
    1. Open twitter.com
    2. Open the bravery panel
    3. Click the stat to display the list
    
- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

### PR DESCRIPTION
**Pull request by luixxiul**
Fixes #9802 
Fixes #9296

Auditors: @cezaraugusto

Test Plan:
1. Open twitter.com
2. Open the bravery panel
3. Expand a resouce list
4. Hover on the scroll bar
5. Make sure the cursor does not become `cursor:text`

Test Plan 2:
1. Open https://https-everywhere.badssl.com/
2. Expand a resouce list
3. Make sure that the scroll bar does not appear

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by luixxiul** [comment]
Please test on Windows as well to make sure that the scroll bar does no longer appear with one blocked resource, thanks!

**Comment by luixxiul** [comment]
@cezaraugusto do you think this also closes #9296 too?

**Comment by cezaraugusto** [comment]
yes just updated PR description

**Comment by cezaraugusto** [comment]
btw moving to 0.20.x

**Pull request merged**
