### PR TITLE
Fixes #2914: Pressing Esc key activates the URL Bar

### LINKED ISSUE #2914: Pressing Esc key activates the URL Bar
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Pressing Esc key on a page changes focus to URL Bar (whether hidden or always visible)

**Expected behavior:**
Standard behavior is F6 should focus to URL. Esc is only used to stop page load.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.2 Dev RC1

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by willy-b**
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.

### CODE REVIEW

**Comment by bbondy** [comment]
k passing to @bridiver to review

**Comment by bridiver** [comment]
I noticed that some of the existing tests weren't running because of overlapping definitions. I'm fixing that now and then I'll get back to this PR

**Comment by bridiver** [comment]
https://github.com/brave/browser-laptop/pull/3057

**Comment by bbondy** [comment]
I think this is superseded by the above so will close this. Sorry about that.

**Comment by willy-b** [comment]
Haha, it's all good -- the bug is fixed, no "sorry" needed :-D. This was a zero effort 1-line change in any case.

**Pull request closed without merging**
