### PR TITLE
Persist pinned tab order when a tab is moved by any means

### LINKED ISSUE #13264: pinned tabs do not retain order when moved with keyboard shortcut
### Description
If you reorder your pinned tabs using the keyboard shortcut (ctrl+shift+pg up/down), and then close/reopen Brave, your pinned tabs order is not maintained. 

### Test plan / Steps to Reproduce

  1. Clean profile with 0.21.11.
  2. Open several tabs with several sites.
  3. Pin some of the tabs. Note pinned order.
  4. Move pinned tabs around using keyboard shortcut described in #11313
  5. Note new order.
  6. Close/Reopen Brave.

**Actual result:**
Reordered pinned tabs are back to their original placement.

**Expected result:**
Pinned tabs should retain the order you set using the keyboard shortcut.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.21.11
V8 | 6.4.388.41
rev | e146cd8
Muon | 5.0.5
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
n/a

### Additional Information
If you drag and drop pinned tabs into a new order this is kept.

### PR DESCRIPTION
**Pull request by petemill**
...such as extension, keyboard shortcut or drag.

Previously only dragging a pinned tab to a new order would cause the new order of pinned tabs to be persisted.

Fix #13264

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
On #13264 

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bsclifton** [comment]
I believe this also fixes https://github.com/brave/browser-laptop/issues/8543

**Comment by bsclifton** [comment]
master 4ae1b6d88be54824a91e12749c2f0d0477ca877d
0.22.x 63647e18dff245c73b7b2fd9d9476c9f23735ffb
0.21.x working through this

**Comment by hugobuddel** [comment]
Does this mean that the pinned tab order should now always be the same across windows? Because they aren't on my screen (Linux, 0.22.669) and I'm wondering whether I could/should file a bug report.

**Comment by hugobuddel** [comment]
The simplest way for me to get the pinned tab order inconsistent is by pinning a new tab. The window where the tab is pinned will have the pin on the first position, the other windows somewhere at the end. Is this worthy of a bug report?

New windows seem to have the newly pinned tab somewhere at the end. (It is not exactly at the end, the last pin is a duplicate pinned tab that I can't remove, #10179).

**Comment by hugobuddel** [comment]
Here a screencap where I

1. Unpin the duplicate pinned tabs (from pinboard),
2. Open a new window with ctrl-n, one of the pinned tabs is back, (also note that the menu bar appears)
3. Close the newly pinned tab, the pin reappears,
4. Goto 3

output_optimized2

**Pull request merged**
