### PR TITLE
If auto-suggest is off, then always show included publishers

### PR DESCRIPTION
**Pull request by mrose17**
Fixes https://github.com/brave/browser-laptop/issues/6592

Auditor: @bsclifton 

Test plan: turn off auto-suggest, go to a new publisher site, click the BTC button to the right of the icon, then immediately go to about:preferences#payments ... the publisher should be listed regardless of the view parameters for the site.

### CODE REVIEW

**Comment by bsclifton** [comment]
@mrose17 I rebased this against the `0.13.0-build` branch and it's not working :frowning_face: 

Steps to repro:
1. grab the code (`git checkout issue-6592`)
2. remove or rename your session directory (ex: 
`mv ~/Library/Application\ Support/brave-development`)
3. Launch watcher with `npm run watch` in terminal 1
4. In terminal 2 launch `npm run start`
5. Visit `en.wikipedia.org` and hit the bitcoin button
6. Immediately visit Preferences > Payments; notice that it's not showing in the table

**Comment by bsclifton** [comment]
Rebased to resolve all conflicts; will start looking into what's wrong

**Comment by cezaraugusto** [comment]
Worth sharing for others interested in reviewing, some modules were updated so it's required to `npm i` to checkout this PR.

**Comment by luixxiul** [comment]
Can anyone fix this error on Travis?

https://travis-ci.org/brave/browser-laptop/builds/191866157#L4648

>   1) Payments Panel can setup payments "before each" hook for "shows welcome page":
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at windowHandles() - brave.js:201:32

**Comment by luixxiul** [comment]
Changed the milestone as the base branch has been set to `0.13.1-branch`

**Pull request closed without merging**
