### PR TITLE
Cambio en el icono de Bookmark import

### PR DESCRIPTION
**Pull request by PedroJ1**
- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

### CODE REVIEW

**Comment by bsclifton** [comment]
@PedroJ1 porque cerrado? Tienes una screenshot de la icono nuevo?

**Comment by PedroJ1** [comment]
I thought that close the Pull request would be the best option to see that it was an error. I was teaching in a project of the University how to contribute helping to the Brave community making a change in Brave development and publishing the changes in the original repository of Brave, but finally I clicked on "Create Pull Request" by mistake. (The icon is the Brave logo, it hasn't sense, it was only an example to how to make a change in Brave development). My apologies.

screenshot from 2017-05-03 18-28-49

**Comment by bsclifton** [comment]
@PedroJ1 no need to apologize- that is really cool! 🦁  Please let us know if there's anything you or students need help with.  Thanks for sharing our project 😄

**Comment by PedroJ1** [comment]
Ok I'll keep it on mind. Thank you very much, all the best 😊

**Pull request closed without merging**
