### PR TITLE
Improve UI/UX of bookmark popup

### LINKED ISSUE #2894: Improve UI/UX of bookmark popup
The current bookmark popup appears in the center of the BM bar and has that "not finished" look.

image

Let's improve the styling and UX with this design:

image

- The editable field for the path should not be necessary as the user can either edit it before pressing the BM button, or edit it later. (we can gauge feedback or add a method later)

- the name of the BM should be taken from the page title (if existing) and open as selected so typing can begin

- the bookmark is created when the Add button is pressed, but this dialog allows the user to append changes in the form of the text or location
- if the location is changed, the BM must actually be moved
- remove will remove the BM, uncheck the BM icon and close the dialog
- Done accepts and closed the dialog with info as shown
- close-button = done
- the default folder is the Bookmarks toolbar
- a "View all bookmarks" link/button on the bottom provides a shortcut to the bookmarks manager. (about:bookmarks)
- the popup should open at the location of the bookmark button

- address keyboard navigation flow as described below by @neeklamy 
- recall last use folder after initial default to Bookmarks Bar

(note: the UI behind the popup in this image will be specified in a separate issue)

Part 2 of this UI task is to extend the component for use as the bookmark edit dialog. It should appear at the actual bookmark which is being edited on the BM bar.

image

- size extends to make room for the URL field
- title changes to "Edit Bookmark"
- button text changes to "Cancel/Save"

cc @bsclifton

### PR DESCRIPTION
**Pull request by jkup**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fix #2894, #4854, #4864 and #3282 via @rohanthacker's changes!

Auditors @bsclifton @bradleyrichter 

Test Plan:

Make sure of a few things:

+ Bookmark is automatically created when you click the orange star
+ Bookmark doorhanger aligns with orange star
+ View all bookmarks page takes you to about:bookmarks

### CODE REVIEW

**Comment by bsclifton** [comment]
Checking it out right now, already noticed a few things (doh)

Launching w/ an empty tab, the icon is off:
screen shot 2016-10-13 at 10 56 01 pm

After you visit a site though, it fixes itself and looks OK.  However, the star icon (when a site is favorited) moves up and down when you have the magic titlebar feature on and show/hide the URL bar.

When you click it to trigger a bookmark, I can tell it's trying to put an overlay there, but it's in the wrong area. I ran into a similar issue when doing the titlebar (but mine was in main.js, where your overlay appears to be in addEditBookmark). Here's a pic:
screen shot 2016-10-13 at 10 56 20 pm

**Comment by bsclifton** [comment]
@jkup notes left :smile: hopefully, I didn't do something wrong when testing (I grabbed latest from your branch `bookmark-popup`).  Please let me know and I can retest 

@bradleyrichter when you click the star when it's already bookmarked, the title still says "Bookmark added". If the site is bookmarked already and you click that, should we even show a title at all?

**Comment by jkup** [comment]
Wanted to run these fixes by you:

@bsclifton I don't think this technically needs to be a dialog anymore right? I think it can just be a div with some similar behaviors. I just removed the dialog class which fixes that shadow issue but I may be overlooking something.

@bbondy the positioning bug that @bsclifton found is because we are pushing an empty browserButton which has a width and a height but no content. Can I just return null here? https://github.com/brave/browser-laptop/pull/4726/files#diff-b9cf7ede0a812496eace3679483c2c40R129

**Comment by bbondy** [comment]
yes null is fine

**Comment by bradleyrichter** [comment]
wow. a breath of fresh UI air!

some initial problems I found:

1 - needs to Close on click-outside.
2 - pressing the star while open also closes (same as click-outside)
3 - with door hanger closed, clicking a marked star opens the hanger with "edit bookmark" as the title (not "bookmark added")
4 - ideally, the URL is stored in whatever state the URL is in when the hanger closes, not when it opens. This allows the user to actually edit the URL in the URL box to modify the bookmark info.

For styling issues, we can work on it in person.

**Comment by bsclifton** [comment]
Looking really good! :smile: All the same things Brad said above... plus the empty button issue you already mentioned (on about pages, including new tab)

@bradleyrichter the "View all bookmarks" seems a little hard to read, gray on gray.

**Comment by bradleyrichter** [comment]
no worries. We'll shine er' up on Thursday...

(spec image:)

image

**Comment by bsclifton** [comment]
I think this should also fix:
https://github.com/brave/browser-laptop/issues/2347

**Comment by bsclifton** [comment]
Tested on Mac and also Windows 10. Looks and works good- great job :smile:

**Pull request merged**
