### PR TITLE
Copy animation in backup wallet

### PR DESCRIPTION
**Pull request by arsalankhalid**
For issue #6459 

- [X] Ran `git rebase -i` to squash commits (if needed).
- [X] Tagged reviewers and labelled the pull request
@NejcZdovc , @bsclifton 

Cheers.

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@arsalankhalid please squash commits

**Comment by NejcZdovc** [comment]
@arsalankhalid thank you for you PR. Can we please adjust this one and just add text bellow the button, when button is clicked. Text should fade out after 5s.

Something like this:
image

**Comment by arsalankhalid** [comment]
Ah OK, keep the button and no img then. Sure will fade out the text

**Comment by arsalankhalid** [comment]
Sorry team been a bit busy, will update and push today :)

**Comment by arsalankhalid** [comment]
Cleaning my branch ignore for now

**Comment by NejcZdovc** [comment]
PR ignored 😃

**Comment by NejcZdovc** [comment]
@arsalankhalid just checking how are things?

**Comment by arsalankhalid** [comment]
Hey @NejcZdovc sorry got pulled away and went on vacation, I'll hit this up and clear this out on the weekend. My fault, shouldn't have taken so long...

**Comment by NejcZdovc** [comment]
@arsalankhalid no worries, hope that you enjoyed your vacation

**Comment by arsalankhalid** [comment]
Sorry guys, i'll definitely push my update tomorrow, i've been a terrible loaft.

**Pull request closed without merging**
