### PR TITLE
Added open tab setting

### LINKED ISSUE #6907: Command-click opens tab at far right of window, not adjacent
- Did you search for similar issues before submitting this one?

Yes

- Describe the issue you encountered:

I want to open a link in a new tab. Doing so from the context menu opens the tab immediately to the right, as expected, even if there are other tabs to the right. Doing so with the command-click keyboard shortcut opens the new tab at the far right of the window.

- Platform (Win7, 8, 10? macOS? Linux distro?):

OS X El Capitan 10.11.6

- Brave Version (revision SHA):

0.13.0 (8ca0127)

- Steps to reproduce:
    1. Open multiple tabs in a single window
    2. Focus on tab in the middle of the window
    3. Command-click a link

- Actual result:
New tab from link opens at far right of window.

- Expected result:
New tab from link opens immediately to the right of the current tab.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Unknown

- Is this an issue in the currently released version?
Yes. New issue in 0.13.0.

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

Resolves #6907

## Auditors
@bradleyrichter @bsclifton

## Test Plan
- set desired option in tab settings
- new tab should be opened according to this settings

### CODE REVIEW

**Comment by NejcZdovc** [comment]
waiting for #6971 to be resolved

**Comment by NejcZdovc** [comment]
@bradleyrichter should I close this PR?

**Comment by bradleyrichter** [comment]
yes, for now. tx.

**Comment by NejcZdovc** [comment]
Closing based on https://github.com/brave/browser-laptop/issues/6907#issuecomment-276743779

**Comment by bsclifton** [comment]
@NejcZdovc even though the code here isn't used, thanks for troubleshooting and sticking with this issue (along with @bridiver and @bbondy) to completion 😄

**Pull request closed without merging**
