### PR TITLE
Revert "Add accelerator keys to create new session tabs"

### LINKED ISSUE #12956: AltGr + Number opens up a new session tab
## Test plan

https://github.com/brave/browser-laptop/pull/13042#issue-167512154

----

The shortcut for <tt>New Tab</tt> is the same as @ (at-sign) on Nordic keyboards. That's pretty annoying when typing in email addresses in web forms... 
Just realized that when I type square brackets (as in the subject) I open new tabs as well...
So the result after this posting is 4 new tabs... 🐛 

I can't find anywhere I can change it myself. 
Are this option missing in the menues, or do I oversee something? 

Thanks in advance, 
Rasmus

### PR DESCRIPTION
**Pull request by petemill**
Reverts brave/browser-laptop#10364

Fix #12956

test plan (Windows):
- visit site with an input box (duckduckgo.com)
- Attempt to insert special character (<kbd>altgr</kbd>+<kbd>3</kbd>)
- Observe character is inserted and new session tab is not opened

### CODE REVIEW

**Comment by vinicentus** [comment]
How about `Cmd + Alt + partitionNumber for MacOS` and `Ctrl + Shift + partitionNumber` for Windows and Linux?
#13015

**Comment by bsclifton** [comment]
@vinicentus that is a good suggestion; however, it would still affect <kbd>altgr</kbd>. It is possible to detect alt vs altgr via event handlers (see https://github.com/brave/browser-laptop/blob/6fb1ad5ca10fea5dd8b9cdf3b6400b1784c08f8b/app/renderer/components/main/main.js#L147 for an example).

If electron/muon doesn't allow for distinguishing between <kbd>alt</kbd> and <kbd>altgr</kbd>, that might have to be the route taken

**Comment by petemill** [comment]
0.22.x c6b61ece3
0.21.x caf84cf2d
0.20.x 632d435b7

**Comment by enjikaka** [comment]
When is this released? Cannot respons to people in slack without opening new tabs all the time since @ in nordic keyboards is AltGr+2

**Comment by NejcZdovc** [comment]
@enjikaka it's targeted for the next week

**Pull request merged**
