### PR TITLE
Fix newtab's test "lets you pin a tile"

### PR DESCRIPTION
**Pull request by cezaraugusto**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Auditors: @bbondy

Test Plan:

* Test `lets you pin a tile (and shows the pinned icon afterwards)` should pass

### CODE REVIEW

**Comment by bsclifton** [comment]
This increases the timeout for this visible check to 3 seconds... Should we consider bumping up the default timeout? ([currently 1 second](https://github.com/brave/browser-laptop/blob/master/test/lib/brave.js#L566))

**Comment by bbondy** [comment]
I haven't actually seen this failing again, but I think it was intermittent. @cezaraugusto did you reproduce it failing or was this a guess at a fix?

**Comment by bbondy** [comment]
I bet lowering the waitForInterval would help speed up tests a lot too

**Comment by cezaraugusto** [comment]
@bbondy I could reproduce only once. My guess is that since we don't define which selector we want to target it searches for all (even if it'll target the first) and the first found may not be visible yet, which is why you saw `RuntimeError: element not visible`. The fix would be setting `nth-child(1)`. 

Increasing timeout was just me making sure element could be found without errors. May not be required for it to pass. 

I removed timeout (PR updated) but feel free to close this if it's not necessary/currently working.

**Comment by bbondy** [comment]
This has merge conflicts but I think it's a no-op anyway because of the documentation on webdriver's click function says this:

> element to click on. If it matches with more than one DOM-element it automatically clicks on the first element

So I think this PR, if merged, wouldn't help the issue from failing intermittent.

**Comment by bbondy** [comment]
reference: http://webdriver.io/api/action/click.html

**Comment by cezaraugusto** [comment]
Yes, my comment above was that even targeting the first element by default, error might happen while searching for targets. Explicitly referencing element was a way to avoid that. Not sure about it so ok to close.

WebDriver docs loses only for Immutable docs on my topSites 🙂

**Pull request closed without merging**
