### PR TITLE
Telemetry

### PR DESCRIPTION
**Pull request by aekeus**
This pull request adds telemetry calls to the browser for C.I. measurement.

Testing will require the provisioning of a vault-collector instance and a number of configuration steps outlined in docs/telemetry.md

### CODE REVIEW

**Comment by posix4e** [comment]
You must resolve conflicts

**Comment by aekeus** [comment]
Thanks @posix4e. Will resolve before 0.13.1 merge date.

**Comment by aekeus** [comment]
Conflicts resolved

**Comment by bsclifton** [comment]
Running into trouble running the following test:
`npm run test -- --grep="Clear Browsing Panel with saved state values saves the history switch state"`

it's throwing the following error:
```
1) Clear Browsing Panel with saved state values saves the history switch state:
     Promise was rejected with the following reason: Error: unknown error: Cannot read property 'appStoreRenderer' of undefined
```

**Comment by bsclifton** [comment]
OK revisited this and turns out the problem was me :smile: I was running `npm run watch` not `npm run watch-test`.  I reran the tests which [failed in the CI build](https://travis-ci.org/brave/browser-laptop/builds/188546693) and all of them passed :smile: Merging!

**Comment by bsclifton** [comment]
@aekeus is there an associated issue for this?

**Comment by aekeus** [comment]
Yes, implements #6265

**Pull request merged**
