### PR TITLE
Remove outline from addPublisher urlbar button

### LINKED ISSUE #6760: Remove outline from addPublisher urlbar button
Per @bradleyrichter request, new addPublisher icon inside urlbar shouldn't have an outline.

### PR DESCRIPTION
**Pull request by cezaraugusto**
Auditors: @bsclifton

Close #6760

Test Plan: Click and hold addPublisher button. There should be no outline.

### CODE REVIEW

**Comment by luixxiul** [comment]
Since #6047 was reverted with 2aa39bb, we should revert this too, right?

**Comment by cezaraugusto** [comment]
btw this was superseded by #6862 when refactoring to Aphrodite so np on revert

**Comment by bsclifton** [comment]
@luixxiul sure we can revert it too. I'll remove the milestone also

**Comment by bsclifton** [comment]
Reverted with https://github.com/brave/browser-laptop/commit/07451654a72e8f6f292d5f045bd513d41a4e4ce3

**Pull request merged**
