### PR TITLE
Cancel the margin-left of browserButton with groupedItem

### LINKED ISSUE #11288: The first browserButton with 'groupedItem' should have margin-left: 0
## Test plan

https://github.com/brave/browser-laptop/pull/11290#issue-263055746

----

### Description

The first browserButton with 'groupedItem' should have `margin-left: 0`. `':first-child'` pseudo-class should take care of that. 

Note that the buttons have to have a parent. Beginning with Selectors Level 4, that is no longer required.

### Steps to Reproduce

  1. Open about:styles
  2. Click `buttons`

**Actual result:**

The first button in a group has the margin-left.

**Expected result:**

It should not.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

 
Brave: 0.21.0 
V8: 6.1.534.41 
rev: d6447e8f595ad42d9bc47407d1727c75c7b239cf 
Muon: 4.4.25 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.3.5 
libchromiumcontent: 61.0.3163.100

**Reproducible on current live release:**

### Additional Information

On the new add funds dialog:

image

The `ETH` button has the left margin.

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #11288

Auditors: @cezaraugusto

Test Plan:
1. Open about:styles
2. Click 'buttons'
3. Make sure the first button in a group does not have the left margin

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by luixxiul** [comment]
As a follow up I'll add a comment to `about:styles#buttons` about https://github.com/brave/browser-laptop/pull/11290/files#diff-0ff973318abdc5c07f55cefe86bd5ed7R221 (`The buttons have to have a parent. Beginning with Selectors Level 4, that is no longer required`, adding a link to the MDN knowledge base's article which I referred)

**Comment by luixxiul** [comment]
@cezaraugusto would you mind adding this to `0.21.x`? cc @bbondy

**Comment by cezaraugusto** [comment]
0.21.x fc9c8ef4e

**Comment by bbondy** [comment]
confirmed it is already there:
0.21.x: dc237ec2737e2f5404121a137c59b8c399ce2fd2
master: 9e730c5bf84facbbc7ba723d24dcc1c395c90b40

**Comment by luixxiul** [comment]
thanks!

**Pull request merged**
