### PR TITLE
Tab style updates x 8

### LINKED ISSUE #2869: Tab preview animation on Windows 7 and Windows 10
**Describe the issue you encountered:** Tab preview animation seems to be not working properly on Windows 7. It shows the preview on hover. Tested on VM.

tabpreview

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7
- Brave Version: 0.11.2 Beta2
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues: #2862

### LINKED ISSUE #11249: Tab colour has weird fade in paint effect when switching
### Description

Tab colour has weird fade in paint effect when switching

### Steps to Reproduce

  1. Build from master
  2. Visit brianbondy.com, tab colour has weird paint effect
  3. Open any about page, same weird effect

**Actual result:**

tabcolour

**Expected result:**
Should paint entire tab 

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.21.0
-- | --
V8 | 6.1.534.41
rev | de5f381
Muon | 4.4.25

**Reproducible on current live release:**

No
### Additional Information

cc: @cezaraugusto

### LINKED ISSUE #12454: UX | Design : Tab hover UX
Some minor UX issues I have w/ tabs in the Brave browser:

1. Hovering on each inactive tab by default, enables a preview of the page. As it is quite easy to accidentally hover into the tab zone, the current experience is jarring when you have many tabs open. 

Might I suggest a subtle transition animation (fade in) similar to the one you're already using for new tabs. The preview for each inactive tab will more user friendly. 

2. The hover state for each inactive tab is currently a slight shift in tone of grey. While this is similar to Chome, I wonder if this could be improved by making the hover state even more obvious. This would make it more accessible for users with visual impairment, low screen brightness, for users who have adjusted screen resolution, or users w/ many tabs. 

3. While hovering over a tab, user can create a new tab. However, the new tab is immediately presented while the hover is still over the previous tab. This UX could be improved, as the user's mental model becomes inconsistent with what they have previously learnt. I think this is where a more obvious "active tab" could help. 

Hope this helps! Liking everything else so far!

### LINKED ISSUE #12721: Tab background gradient is visible when switching tabs
### Description
When switching tabs, a gradient is visible for a brief moment. This adds to the feeling of jank.

### Steps to Reproduce

  1. Activate a themed dark tab (e.g. new tab page)
  2. Switch tabs (e.g. using ctrl-tab)

**Actual result:**
Janky visual transition

**Expected result:**
Smooth transition

issue-tab-background-gradient-transition-visible

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.20

### LINKED ISSUE #12722: Some favicons are distorted
### Description
Dark themed tabs apply a filter to favicons which often distorts them beyond recognition or does not fit in with the rest of Brave's flat(ter) visual style.

### Steps to Reproduce
Ensure themed tabs are on (the default)

  1. Visit apple.com in active tab

**Actual result:**
Favicon is blurred beyond recognitino

**Expected result:**
Favicon is Apple logo

image

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.19

**Reproducible on current live release:**
yes

### LINKED ISSUE #12803: Theme color is displayed incorrectly due to transparency
### Description
If a theme color is provided with an alpha transparency channel, we preserve that transparency when displaying the theme color on the tab control background. This then causes the theme color to be blended with the tab bar background color, making the theme color match incorrectly.

### Steps to Reproduce

  1. Visit apple.com
  2. Observe tab theme color when tab is active
  3. Observe apple.com's navigation bar color

**Actual result:**
Colors do not match

**Expected result:**
Colors match

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.19 / 0.20

**Reproducible on current live release:**
👍

### PR DESCRIPTION
**Pull request by petemill**
### 1. Tab / Top Nav updated colors 🎨 
A small iteration towards new styles including:
- New colors from @bradleyrichter 
- Everything more ~painstakingly~ perfectly aligned
- Horizontal and vertical spacing improvements, including very slightly taller tabs
- Tab audio icon gets new color, hover state and tooltip
- Some miscellaneous code cleanup / refactoring for performance and maintainability

#### Was (0.20)
image

#### Now
image
_Note: exact style has been tweaked via design team since this screenshot._

### 2. Tab title text gets sub-pixel antialiasing 🔍 

The tab title text was being forced to be rendered on a GPU layer. This is useful when performing transformations, but this was occuring even when the tab is static. Using the GPU has a slight hit to text rendering quality since it cannot use sub-pixel antialiasing, whereas CPU rendering can.

_These are not great representations. I recommend using the zoom function of Mac / Windows, or taking a screenshot and magnifying in order to validate:_

### 3. Preview mode tab style 📑 
Fix #12454 
Closes #2869

Makes it more apparent that the tab is doing something out of context - being previewed and not being made active - by providing a transition as if the tab were 'pulled out' for special inspection.
Also adds more of a style to the frame itself, to reduce user-confusion that the frame is active, and not simply a preview.
Cross-fade of frame content was implemented (and awesome), but removed due to performance / low animation framerate.
This can be fixed and re-implemented with single-webview, which will require a
different css architecture for this potential feature anyway.
The tab animation itself is sometimes not as smooth as I'd like. That is also caused by multiple webviews hiding and showing, and could be revisited after single-webview.

brave-tab-preview-1
_Note: exact style has been tweaked via design team since this screenshot._

### 4. Tighten up transitions 🔧 
Including:
- Hover (and preview if enabled) transition comes in fast 💨, and fades out ~luxuriously~slowly 🐌 
- No transition for switching between active and inactive state

### 5. Adjust filter for favicons on dark themed tabs 🌫 
This was causing big issues for some favicons which. We experimented with a bunch of different blends at https://codepen.io/petemill/pen/XVovva
Fix #12722 

#### Was
image

#### Now
image

### 6. Tab gradient background transition fix (overflow text) 💨 
Fix #12721 (Tab background gradient visible when switching tabs)
Fix #11249 (Tab color has weird fade in paint effect when switching)
A regression introduced with 0.20.x

#### Was (slowed down to 10% speed)
issue-tab-background-gradient-transition-visible

#### Now
issue-tab-background-gradient-transition-visible-fixed
_Note that the background transition has mostly been removed as part of this PR anyway, since active tab style change should be instant, just like the content_

### 7. Tab Close Button style ✖️ 
- Background of button does not show until hover
- Color of button (when not hovered) is the same as text
- Button gets active state (i.e. when mouse is down on button, background color changes)

### 8. Remove transparency from theme color 🔵 
Fix #12803

#### Was:
image

#### Now:
image

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

Test Plan:
Confirm visuals as above. Note that some minor tweaks have been made since the above screenshots were taken, through iterations with design/product team members.

Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by petemill** [comment]
Needs squash and double-check cleanliness

**Comment by petemill** [comment]
Preview builds containing these changes were shared with design / product team members, and the current iteration was a result of a team effort from that. Therefore, the visuals approved as far as I'm concerned (pending additional future planned enhancements).

**Comment by petemill** [comment]
Leaving multiple commits in this PR intact since:
- They will help review each change somewhat separately.
- The commit messages may help future maintenance.

But leaving this as one PR since:
- All the changes work with eachother, visually, and should not be merged independently.

**Comment by cezaraugusto** [comment]
@petemill is this ready for review?

**Comment by petemill** [comment]
Sure is @cezaraugusto!

**Comment by petemill** [comment]
This is ready for review again @cezaraugusto @bsclifton! I've updated the description with some additional optimizations. I'm ready to draw a line under this set of enhancements and get it in to a release (targeted for 0.22). Thanks!

**Comment by cezaraugusto** [comment]
_merged with confidence ®_

**Comment by cezaraugusto** [comment]
cc @petemill I'm having some conflicts while cherry-picking against 0.23.x/0.22.x mind doing it?

**Comment by petemill** [comment]
@cezaraugusto thanks! I may have to do the merge 0.22 because the aphrodite stuff is in 0.23 probably!

**Comment by petemill** [comment]
@cezaraugusto same thoughts!

**Comment by petemill** [comment]
0.23.x a372f09948914e87ceec65c454f881a64a64ee4a
0.22.x 2024044da809dcf77a16303475286208ac2d80a4

**Comment by bradleyrichter** [comment]
@petemill A user asked if we could reduce the blend fade timing when returning from the preview to the current tab? I agree it could be shorter.

**Comment by petemill** [comment]
@bradleyrichter the content area fade is timed to be the same timing as the Tab element returning to normal (non-preview), which itself is timed to be the same as the hover color returning when preview has not been activated.
Start hover / preview: a quick 200ms (ease-out)
Finish hover / preview: a luxurious 400ms (ease-in)

I took these timings from hovering over the Tabs of _...another browser..._ which felt good, and I did already decrease them quite a bit because of our more exaggerated preview movement. But perhaps we can have a quicker content-area fade back to current tab's content, and not synchronize with the tab animation timings, especially since we don't cross-fade the tab content anyway (yet).

**Comment by bradleyrichter** [comment]
@petemill Yes. Perfect. Please try reducing only the page fade-out to current tab by 50% of current. 

The rest feels good as is.

**Comment by petemill** [comment]
@bradleyrichter sounds good, I'll have to do it in another PR since this is merged. Will create one for the combined tweaks.

**Pull request merged**
