### PR TITLE
Retool the ledger updates into the 0.13.1-branch

### LINKED ISSUE #6551: add a 48-hour to review notification for the ledger
unless disabled, 24h prior to settlement, a notification is generated for the user. add a second notification at 48h, with the same options (including "no more notifications")

### PR DESCRIPTION
**Pull request by mrose17**
Auditor @bsclifton 

Also fixes #6551 of the "sonorious seven"

Test Plan:

1. go to about:preferences#payments
2. set auto-suggest sites to off
3. go to a site in another tab
4. click on the BTC icon
5. go back to the first tab and see if the site is present

### CODE REVIEW

**Comment by luixxiul** [comment]
Something seems to be wrong based on Travis: https://travis-ci.org/brave/browser-laptop/builds/192881925#L4354

**Comment by bsclifton** [comment]
@luixxiul I believe the Chromedriver for latest version is not uploaded. We'll likely need new prebuilts

**Comment by mrose17** [comment]
@bsclifton - can we please get this into either master or 0.13.1 ? thanks!

**Comment by luixxiul** [comment]
Rebase needed

**Pull request merged**
