### PR TITLE
Update react to ~15.6.1

### LINKED ISSUE #10126: Update react to ~15.6.1
**Describe the issue you encountered:** Update react to `~15.6.1`.

Changelog since `15.5.4`:
https://github.com/facebook/react/releases/tag/v15.6.0
https://github.com/facebook/react/releases/tag/v15.6.1

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #10126

Test Plan:
1. automated tests should pass
2. general regression manual tests should pass

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bsclifton** [comment]
Is there a reason we want to upgrade? (something we need to upgrade for?)

Upgrading for the sake of having the latest version may introduce bugs ☹️

**Comment by luixxiul** [comment]
actually no, it needs testing.

**Comment by bsclifton** [comment]
I'd like to propose closing this PR (and the original issue) until there's a need to update it

cc: @bbondy, @alexwykoff

**Comment by bbondy** [comment]
I think we should upgrade to latest but on master, there's often perf things and also we don't want to fall too far behind because it could become more of a pain when we need to because of for example several deprecated things.  Sometimes they will have a warning in one version then remove the next, and if you skip the one then you miss that warning and go right to not having the api.

**Pull request merged**
