### PR TITLE
Fixes include/exclude when updating db

### LINKED ISSUE #12621: Disable auto-include publisher causes existing publishers to be excluded
### Description
Disable auto-include publisher causes existing publishers to be excluded

### Steps to Reproduce
  1. Clean install 0.19.133
  2. Enable payments, visit some publishers to add entry in ledger table 
  3. Disable `auto-include`, visit a new site, all entries gets disabled

**Actual result:**
On 0.19.133
ledgeryt
On 0.19.131
ledgeryt-131

**Expected result:**
Should not exclude all existing publishers form the table

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.131 | 0.19.133
-- | -- | --
rev | da2f347 | e05a8ef
Muon | 4.5.36| 4.5.38
libchromiumcontent | 63.0.3239.132 | 63.0.3239.132
V8 | 6.3.292.49| 6.3.292.49
Node.js | 7.9.0 | 7.9.0
Update Channel | Release | Release
OS Platform | Microsoft Windows | Microsoft Windows
OS Release | 10.0.16299 | 10.0.16299
OS Architecture | x64 | x64

**Reproducible on current live release:**
No

### Additional Information
Same behaviour on 0.20.x as well
cc: @NejcZdovc @bridiver @bsclifton

### PR DESCRIPTION
**Pull request by NejcZdovc**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

Resolves #12621

Auditors:

## Test Plan:
(you need to be quick bellow 3min for all steps)
1. clean profile
2. enable payments
3. go to https://www.youtube.com/watch?v=kLiLOkzLetE (wait there for 15s)
4. go back to payments, make sure that channel is there
5. toggle auto-include off
6. go to https://www.youtube.com/watch?v=8s1CWeoRHYI (wait there for 15s)
7. go back to payments, make sure that new channel is there
8. wait there for 4min
9. visit some new site and go back to payments

Youtube and Chris Were Digital should be excluded, but not Brave channel

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bsclifton** [comment]
@NejcZdovc following the test plan, this is what I get:
screen shot 2018-01-15 at 1 29 46 pm

**Comment by NejcZdovc** [comment]
@bsclifton youtube should be excluded, because it's on the exclusion list. Maybe you didn't wait long enough for db to be downloaded? Did you visit some new site after 5min to trigger re-render?

**Comment by NejcZdovc** [comment]
Just tried it locally and youtube is excluded, but I needed to visit a site

**Comment by bsclifton** [comment]
master 18040b9a7a1e978bbf0703228fa4bd40178ee6aa
0.21.x faa928ba7c4f506dbb0dc7c6a93e5171f52255ef
0.20.x de5970f003ca534c0ff0718ac4b06cacd752408b

**Pull request merged**
