### PR TITLE
History fixes and misc about page fixes

### LINKED ISSUE #4794: Autocomplete does not add history entries
**Did you search for similar issues before submitting this one?**

No.

**Describe the issue you encountered:**

Using autocomlete to open pages does not add entries to the history.

**Expected behavior:**

Every page should be logged in the history with its last access time.
- Platform (Win7, 8, 10? macOS? Linux distro?): Fedora 24
- Brave Version: 0.12.5-1
- Steps to reproduce:
  1. Use autocomplete to navigate to page
  2. Inspect history

http://webm.land/media/QHH0.webm
- Any related issues:

### LINKED ISSUE #4812: "View Page Source" on about:history opens nothing
**Describe the issue you encountered:** If you click "view page source" of the common context menu on about:history, nothing is shown

clipboard01

**Expected behavior:** it should be either removed or grayed out
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.5 RC1
- Any related issues: #4811

### LINKED ISSUE #5072: about:history omits recent history
about:history only displays browsing history more than ~22h57m old. History data seems correct as missing browsing history does appear once sufficient time has passed but the display should include everything upto the most recent browsing history.

Ubuntu 16.10
Brave: 0.12.5
Electron: 1.4.14
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

### LINKED ISSUE #5382: clicking entries on about:history is laggy
**Describe the issue you encountered:** clicking entries on about:history is laggy. You have to wait ~0.5s until the entry you click is actually selected.

**Expected behavior:** it should be selected instantly

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Steps to reproduce:
    1. Open about:history
    2. Click an entry
    3. Wait ~0.5s until the entry is selected

- Any related issues:

### LINKED ISSUE #5497: Magnifying glass shown on about pages on Master build
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Magnifying glass shown on about pages on Master build. Also the text is not center aligned

**Expected behavior:**
Should not show the magnifying glass icon for the about pages

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
master

- Screenshot if needed:
 image

  Icons suggested by @bradleyrichter 
  image

  cc: @bsclifton

### LINKED ISSUE #5542: History not being updated on first-time site visit
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When visiting a website, about:history should be updated with each new access, which is not happening unless you refresh the page (2nd access).

**Expected behavior:**
About:history should be updated on the first website visit.

- Platform (Win7, 8, 10? macOS? Linux distro?): n/a

- Brave Version: 0.10.9

- Steps to reproduce:
    1. Open Brave
    2. Visit a website
    3. Check about:history
    4. Visited site is not there
    5. Go back to website, refresh page
    6. Site is updated on about:history

- Screenshot if needed: n/a

- Any related issues:
Not really related to the issue but being affected: #5511

### PR DESCRIPTION
**Pull request by bsclifton**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

## The big history-fixer-upper
- History code was refactored
  - one step forward with regard to #3502
  - session helper created for aboutHistory (tests added)
  - history specific methods broke out into historyUtil (tests added)
  - history stores it's data in AppStore.about.history (similar structure to new tab code)

- about:history is only updated when something changed
  -  number of calls to render on about:history is drastically reduced (should fix #5382; please reopen if not)
  - entries are added on visit (as expected) and show on about:history instantly
    - Fixes #5542
    - Fixes #4794
    - Fixes #5072

- about:brave text update
Implements followup feedback for #5436 (comment)

Auditors: @cezaraugusto, @darkdh

Test Plan:
1. Launch Brave and go to about:history
2. With history open, open a new tab and visit a site you have never been to before (hint: just append #1234567 to the end of URL)
3. Switch back to history tab and confirm entry shows
4. Open another new tab; in the URL bar, type an entry for a site you HAVE been to before (which shows in the autocomplete)
5. Instead of hitting enter, pick the URL from the autocomplete drop down (use arrow keys and press enter,  OR  click)
6. Visit about:history again and confirm this entry shows
7. On about:history, click some of the entries. They should show their selection status in a faster manner than before

Advanced test notes:
- After exiting Brave, you can view the session file to confirm the details used in about:history and about:brave are removed and NOT stored to disk

## Remove unnecessary/broken/useless context menu items for about pages
Fixes #4812

## Update icon for about pages to fa-list (except for about:newtab)
Fixes #5497

Auditors: @bradleyrichter

Test Plan:
1. Launch Brave and visit about:about
2. Open each of the links and confirm it's the `fa-list` icon

## Screenshots
Here's one showing:
- fixing the casing on component names in about:brave
- new "fa-list" urlbar icon
- context menu has  items removed from about pages
  - save as
   - print
   - view source
   - inspect element

screen shot 2016-11-11 at 5 13 56 pm

### CODE REVIEW

**Comment by bsclifton** [comment]
**NOTE**: _This is going to conflict with https://github.com/brave/browser-laptop/pull/5531 and will need a rebase (since that PR will be accepted first)_

**Comment by bsclifton** [comment]
@bradleyrichter screenshot (with description) added :smile:

**Comment by bsclifton** [comment]
Closing this for now so that it doesn't accidentally get merged.  Will either reopen or submit a new PR once it's ready for review again :smile:

**Comment by bradleyrichter** [comment]
It looks like our icons are riding high for some reason. But this will look nice.

**Pull request closed without merging**
