### PR TITLE
Make toolbar messages non-selectable

### PR DESCRIPTION
**Pull request by Aeyoun**
Not bothering with the below because the process overhead involved for fixing two CSS rules is uncalled for.

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

1. Help menu: Check for updates
2. Try to select text in the notification message toolbar

### CODE REVIEW

**Comment by bbondy** [comment]
@bradleyrichter could you comment on if you want this text selectable or not? Thanks.

**Comment by bradleyrichter** [comment]
Non selectable is preferred.

**Comment by bbondy** [comment]
++ thanks.

**Comment by luixxiul** [comment]
@bradleyrichter should ``cursor: default`` be set to ``.message``?

**Pull request merged**
