### PR TITLE
Payment UI 1.0

### LINKED ISSUE #7348: update ledger settings UI area to match 1.0 features/changes
## Test plan
UI should match this mock up (see detailed notes below)

image

**item 1:** convert advanced settings text button into an icon button. Convert Payments History link into icon button in same location.

**item 2:** move Add funds... button to column 3.

**Item 3:** Break out and add "Last contribution" string to column 1, row 2.

**Item 4:** Break out and add "Next contribution" string to column 2, row 2.

**Item 5:** Add style for non-editable edit-box form element.

### PR DESCRIPTION
**Pull request by NejcZdovc**
## Test Plan
- layout should be the same as is on mock in issue #7348

## Description
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

Resolves #7348

**NOTE**
- table header will be fixed later #7647

## Auditors
@bsclifton @bradleyrichter

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@bsclifton @cezaraugusto @bradleyrichter Now that #7481 is in, this PR can be reviewed

**Comment by bsclifton** [comment]
Looks good! Comments left (if action should be taken, let's do as a follow up).  Thanks 😄

**Comment by bradleyrichter** [comment]
@NejcZdovc yes, it would be great to have the icon in grey for the "no history yet" state.

**Comment by bsclifton** [comment]
Follow up task created for ya, @NejcZdovc 😄 
https://github.com/brave/browser-laptop/issues/7693

**Pull request merged**
