### PR TITLE
Add new "empty new tab" option in preferences (for what new tab does)

### PR DESCRIPTION
**Pull request by bsclifton**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

screen shot 2016-11-16 at 12 13 47 pm

*includes tests* :smile: 

Fixes https://github.com/brave/browser-laptop/issues/5682

Please note: choosing this option does NOT put focus in the URL bar. Is this OK?
cc: @diracdeltas

Auditors: @bradleyrichter, @bbondy

Test Plan:
1. Launch Brave and go to preferences
2. Change "A new tab shows" to "empty new tab"
3. Open a new tab; notice it's about:blank

### CODE REVIEW

**Comment by bradleyrichter** [comment]
@bsclifton I'll pull this in and edit the strings and commit those.

**Comment by bsclifton** [comment]
Working with @bradleyrichter on this one... not ready to be accepted yet

**Comment by bradleyrichter** [comment]
current proposal:

image

**Comment by bbondy** [comment]
> Please note: choosing this option does NOT put focus in the URL bar. Is this OK?

No it should still react like a new tab page and put the focus in the URL bar. I think this option should modify how about:newtab works to not render anything (return null) and not use about:blank. 

I'm going to move it to 0.12.11.

**Comment by bsclifton** [comment]
Awesome- I think it makes sense pushing this back a release to make sure it's solid. We hashed out some ideas on Slack and it would be good not to rush it :smile:

**Comment by luixxiul** [comment]
@bradleyrichter what is "My dashboard" there?

**Comment by bradleyrichter** [comment]
Dashboard is the new proposed name for the thing otherwise know as the new tab page.

**Comment by bsclifton** [comment]
Ready for re-review :smile: 

Here's what the choice dropdown looks like:
screen shot 2016-11-21 at 12 18 50 am

Things to note:
- I updated the only occurrence of "homepage" to "home page" (see screenshot)
- Regardless of whether you pick Blank page or Dashboard, you go to about:newtab. This means the URL bar is focused
- new webdriver test created for blank about:newtab check

**Comment by bsclifton** [comment]
Rebased, resolved conflicts with tests, and made sure tests pass great :smile: Ready for re-review, @bbondy 

Picture as proof that I'm not crazy :smile: 
screen shot 2016-11-21 at 11 00 23 pm

**Comment by bbondy** [comment]
looks like app/extensions/brave/locales/en-US/preferences.properties has a conflict, could you rebase?

**Comment by bbondy** [comment]
Pls also run through automated if you don't mind, review of code looks good.

**Comment by bbondy** [comment]
++ thanks!

**Comment by bsclifton** [comment]
@bbondy thanks for checking this out and merging :blush:

**Pull request merged**
