### PR TITLE
Fix snapd installation

### PR DESCRIPTION
**Pull request by hugobuddel**
brave should be lowercase: https://github.com/brave/browser-laptop/commit/3caebfd6742983b5f9d7d8bc9806656d02fbc7df#commitcomment-24878164

Ticket: #11409 

@Raindeer44 could you review?

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [X] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by Raindeer44** [comment]
Yup, my fault. I capitalized Brave in other parts of the page (in regular text where it should be capitalized). DIdn't mean to change any of the actual commands, didn't catch this one. Thanks @hugobuddel!

**Comment by posix4e** [comment]
lgtm. How did we test this?

**Comment by Raindeer44** [comment]
@posix4e I had tested by manually typing in the command, instead of copy-paste like I should have. My fingers must have autocorrected it for me.

**Comment by posix4e** [comment]
OK lgtm

**Pull request merged**
