### PR TITLE
Bookmarks now show under Bookmarks menu

### LINKED ISSUE #3022: Menu should only be built once
We currently build a menu from template multiple times.
We should instead only do this only once, the call to `Menu.buildFromTemplate` returns a menu object and we can use it to find items in the menu and update them as needed.

The problem that happens is when a menu is regenerated and the menu is expanded, then clicks on menu items won't work. This happens especially around when the app starts if you try to quit the menu item click doesn't work.

### LINKED ISSUE #3098: Bookmark status not considered on first page browser loads
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
If you launch Brave and have it set to re-open your last windows, if the site you were last visiting was bookmarked it doesn't show (in the bookmarks menu) as bookmarked.

**Expected behavior:**
I should see the menu item checked

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
0.11.4

- Steps to reproduce:
    1. Open a site you have bookmarked
    2. Verify site shows as checked in the bookmarks menu (item is called "Bookmark Page")
    2. In prefs, make sure browser is set to start with tabs from last time
    3. Close browser
    4. Re-open Brave
    5. Check the menu; it'll show as NOT bookmarked although it is
    6. Visit another page in a new tab
    7. Go back to original tab- menu now shows as checked

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by bsclifton**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

- Adds user's bookmarks under Bookmarks menu [menu temporarily disabled, code still there].
  - Manually applied [patch from issue](https://github.com/brave/browser-laptop/issues/1993)
  - Small refactor in siteUtil.js; trying to make sure bookmark code is consistent between bookmarks menu and bookmarks toolbar.
  - Added subfolders to bookmarks in menu
  - Folder menu items with 0 children no longer include empty submenu
  - Refactored code in menu.js; all submenus are defined above the template definition.
  - Bookmark menu selections now respect secondary keys
- Reworked menu so that it only ever builds the static items once. Fixes #3022 
  - The Bookmarks/History menus will now properly rebuild themselves when the appStore's sites list changes (site is bookmarked, new site added to history)
  - Fixed bug where initial browser's initial state thinks the first page loaded is NOT bookmarked, even when it is. Fixes #3098
- Testing updates to siteUtils
  - Lots of unit tests
  - Updated siteUtil.getBookmarks to default to [] if no items found
  - Adds npm tasks for running unit tests OR spectron tests in isolation (not the whole suite)

### CODE REVIEW

**Comment by bsclifton** [comment]
Ready for review :smile:

cc: @bridiver @bbondy

**Comment by bbondy** [comment]
I'd like to wait until https://github.com/brave/browser-laptop/issues/3022 is fixed as well. Could you do another commit for that in this same PR?

**Comment by bsclifton** [comment]
Sure- I'll start looking at this tomorrow

**Comment by bsclifton** [comment]
Ready for review! Please note that this does NOT enable favicons in the menu, because those are more complicated.  I've captured that information in https://github.com/brave/browser-laptop/issues/3050

**Comment by bsclifton** [comment]
@bbondy [per your comment](https://github.com/bsclifton/browser-laptop/commit/b385ba7f38719ee6c200a1ac0b76b69790668bc3#commitcomment-18630721) I backed out the change that adds the dynamic parts of the bookmarks menu.

It should be safe to merge this now, as it won't rebuild the menu. I'm working on the history menu right now too, so I can dig in and properly handle dynamic menus :smile:

**Comment by bbondy** [comment]
great, thanks! Merging. This won't be in 0.11.5 btw which is good anyway because it'll give us time to find any issues with the menus.

**Comment by alexwykoff** [comment]
For QA: To be clear, this is not inclusive of the hamburger menu.

**Pull request merged**
