### PR TITLE
Fix wide bravery panel to stop covering the webview

### LINKED ISSUE #11878: Shields menu cover entire browser view when clicked on view count
## Test plan

https://github.com/brave/browser-laptop/pull/11880#issue-272623676

----

### Description
Shields menu cover entire browser view when clicked on view count

### Steps to Reproduce
  1. Build from #11727 
  2. Visit YouTube and view couple of videos
  3. Click on shields, expand the adblock count to see details
  4. Shields menu covers 90% of the browser window. Doesn't happen on when shields is set to compact view

**Actual result:**
Normal Shields menu 
image
Compact Shields menu
image

**Expected result:**
Shields should not cover the browser window 

**Reproduces how often:**
Consistently on that PR. was able to see it on two different profile

### Brave Version

**about:brave info:**

Brave | 0.22.0
-- | --
V8 | 6.2.414.36
rev | 145f454
Muon | 4.5.14

**Reproducible on current live release:**
No

### Additional Information
cc: @luixxiul @bradleyrichter

### LINKED ISSUE #11899: Add "trimming" to long URLs in Shields Panel blocked URLs
This layout problem can be solved and simplified by trimming the extra path info past the first slash.

The link itself should remain linked and allow for rt-click menu access to "copy link".

image

Actual URL:

https://googleads.g.doubleclick.net/pagead/viewthroughconversion/1036322744/?value=0&label=AgenCNqg-QMQuI-U7gM&guid=ON&script=0&url=creditcards.chase.com%2Faudiences%2F62334757

Displayed URL:
https://googleads.g.doubleclick.net/

### PR DESCRIPTION
**Pull request by luixxiul**
Fixes #11878
Fixes #11899
Follow-up to #9839

Auditors:

Test Plan 1:
1. Open https://chiebukuro.yahoo.co.jp/
2. Click the adblock count
3. Make sure panel width does not change

Test Plan 2:
1. Open https://longextendedsubdomainnamewithoutdashesinordertotestwordwrapping.badssl.com/
2. Open the wide bravery panel
3. Make sure the panel does not cover the webview

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by srirambv** [comment]
Just one concern, shields panel has scroll bars which is quite distracting and not very appealing
image

**Comment by luixxiul** [comment]
I think it's not a regression. This is on 0.19.88.

32432301-6cfa0a9a-c31a-11e7-87ca-52b4b3ea69ea

Why wouldn't we talk about that on another issue and leave it as it is for now?

**Comment by srirambv** [comment]
@luixxiul not the horizontal scroll bar in the details section, the vertical scroll bar on the shields menu itself from my screenshot above.

**Comment by luixxiul** [comment]
I am wondering if it is due to the new row of fingerprinting protection. would you mind checking if it is not?

**Comment by srirambv** [comment]
manually verified test plan 1 & 2. Works fine. But with more ad block count, vertical scrollbar is still seen and hides `Edit settings` and `Reload buttons`. Setting `braveryPanelBodyList` to 220px from 300px doesn't show the vertical scrollbar
scrollbar

**Comment by luixxiul** [comment]
Fine! Since that is out of scope of this PR (ie. the issue has existed before this PR), I'm going to address that stuff with another PR.

**Comment by NejcZdovc** [comment]
@srirambv don't forget to cherry pick it into 0.21 and 0.20

**Comment by luixxiul** [comment]
@srirambv if you are not how to, mind asking @NejcZdovc to do so (as I'm not quite sure how to and I don't want to break anything)?

**Comment by NejcZdovc** [comment]
master 21fba11
0.21 f40134ae8
0.20

**Comment by luixxiul** [comment]
thanks guys :-)

**Comment by srirambv** [comment]
This is still happening on the latest beta build (a2ba3e8)
Here's how it looks https://youtu.be/OGfow9czqUA

**Comment by luixxiul** [comment]
is it broken on 0.20.9 ?

**Comment by srirambv** [comment]
Nope not broken on 0.20.9 Works fine

**Pull request merged**
