### PR TITLE
Add frame display index and use for tab selection

### LINKED ISSUE #1983: Tab cycling order needs to update when tab is pinned
**Describe the issue you encountered:**
When I converted a tab to a pinned tab, using allt/cmd-tab to cycle among them treated it as if it were in its original unpinned position.

**Expected behavior:**
Pinned tabs should move to the first tabs in the cycling order (when starting from the leftmost tab)

- Platform (Win7, 8, 10? OS X? Linux distro?):
Windows 10 and OS X

- Brave Version:
Brave: 0.10.0
Electron: 0.37.8
libchromiumcontent: 50.0.2661.102
V8: 5.0.71.48
Node.js: 5.10.0
Update channel: dev

- Steps to reproduce:
    1. Pin tab among a group of tabs. Tab shifts left to the pinned area
    2. Use cmd-tab to cycle among tabs

Related #149

### PR DESCRIPTION
**Pull request by ayumi**
Fixes #1983 and #149

### CODE REVIEW

**Comment by luixxiul** [comment]
Does this fix #149 too?

**Comment by ayumi** [comment]
@luixxiul yes

**Comment by luixxiul** [comment]
I see. Including it also in the commit message and push -f again would be appreciated, if you don't mind.

**Comment by ayumi** [comment]
Thanks for the suggestion– I updated the commit and PR.

**Comment by diracdeltas** [comment]
looks great to me! thanks @ayumi!

**Pull request merged**
