### PR TITLE
Add 'unauthorized' downloadItem state

### LINKED ISSUE #7747: File download hangs if Brave does not have write permission to target directory
## Test plan

https://github.com/brave/browser-laptop/pull/10882#issue-256550198

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
From community 
https://community.brave.com/t/file-download-hangs-if-brave-does-not-have-write-permission-to-target-directory/1719

- Platform (Win7, 8, 10? macOS? Linux distro?):
Macbook Pro OSX 10.12.3

- Brave Version (revision SHA):
Macbook Pro OSX 10.12.3

- Steps to reproduce:
    1. Download a file and try to save in a folder where user needs to enter credentials to access the folder
    2.
    3.
    

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by syuan100**
When a user downloads a file to a location that they do not have access to, it currently just says "Downloading... 0%". This is to add a download state to indicate that the user doesn't have access to the director they are trying to download into.

Commit list:
- Add new download state
- Update state if directory is unauthorized
- Update electron download state change
- Add 'Unauthorized' download state to 'clear completed downloads' reducer
- Add isUnauthorized getter
- Add unauthorized state as part of condition for hiding progress display
- Add isUnauthorized to condition for rendering a download item
- Set unauthorized as a stop condition for downloads
- Set getL10nId for unauthorized downloads
- Add 'unauthorized' as a style class for finished download items
- Add downloadUnauthorized locale id for all languages
- Update tests
- Fix styling
- Change failed download wording
- Update download item logic to hide unneeded links
- Update tooltip to show localized download status

Fixes #7747

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [  ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:
1. Create a protected directory
2. Right click an Image in Brave and select Save As...
3. Attempt to save it in the protected directory
4. Download should stop and say "Failed - Unauthorized Access to Download Location"

Reviewer Checklist:

Tests
`npm run test -- --grep="downloadItem"`

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

**Comment by syuan100** [comment]
@bsclifton not sure who to ask, but I don't think I have the necessary privileges to tag reviewers or add labels. Thank you for looking at my PR!

**Comment by syuan100** [comment]
Also not sure why it shows so many files changed? I merged brave/master back into my branch before making the PR. Am I doing something wrong?

**Comment by bsclifton** [comment]
@syuan100 would you be able to revise your PR so that (with your language files) you only modify the `en-US` ones? (ex: app/extensions/brave/locales/en-US/downloads.properties)

We have a translation system which will auto-populate the fields for other languages (using the en-US locale as a template)

**Comment by bsclifton** [comment]
@syuan100 just noticed you updated this (thanks!)

Will review soon 😄

**Comment by bsclifton** [comment]
@syuan100 I rebased this- would you mind checking if everything looks OK still? Thanks 😄

**Comment by syuan100** [comment]
@bsclifton this is how chrome does it. Maybe a tool tip?
screen shot 2017-11-10 at 9 11 40 am

**Comment by bradleyrichter** [comment]
Tooltip would be a sufficient fix as I don’t want to introduce varying widths.

**Comment by bsclifton** [comment]
@syuan100 that would be perfect! 😄

**Comment by syuan100** [comment]
Looks like I'll need to rewrite some tests. However looks like it's working well!

screen shot 2017-11-11 at 8 46 50 pm

**Comment by bsclifton** [comment]
@syuan100 way to go; that looks great! 😄 👍 

I can help you with the tests, if you'd like?

**Comment by syuan100** [comment]
@bsclifton thanks, that would be great :) then I can take a look at how y'all write tests too for the next pull!

**Comment by bsclifton** [comment]
master f59521660d9f9ad246a943f0c74398fd278f7353
0.21.x afc067a107b39ae7e8b4744bbfc891a11eedbd4e

**Comment by luixxiul** [comment]
@syuan100 Kudos 👍

**Comment by syuan100** [comment]
yay! :D 🍾

**Pull request merged**
