### PR TITLE
[Proposal] Add breakpoints to CSS to make navbar responsive

### PR DESCRIPTION
**Pull request by vrde**
I noticed that the navigation bar is too narrow when the width of the browser is small.
I added a media query to make the navigation bar go to `100%` when the viewport is less than `600px`.

## Before
image

## After
image

### CODE REVIEW

**Comment by diracdeltas** [comment]
Looks great on linux but urlbar overlaps with window controls on OS X
screen shot 2016-03-28 at 7 45 55 pm

**Comment by vrde** [comment]
@diracdeltas thanks for the feedback. I'll add some padding for Mac OS only. I think the best approach is to add a CSS class to the `body` or `html` tag, with the name of the platform: something like `platform--macos`, `platform--linux`, and so on, so we can have custom CSS for specific platforms if we need.

**Comment by bbondy** [comment]
Ya, you could use `cx` on the Window component to include process.paltform
Something like:

```
<div id='windowContainer'
className={cx({
  windowContainer: true,
  [process.platform]: true
})}
/>
```

**Comment by bbondy** [comment]
```
const cx = require('../lib/classSet.js')
```

**Comment by vrde** [comment]
I was super busy the whole week, tomorrow I'll commit some new changes :)

**Comment by vrde** [comment]
@diracdeltas: can you try again and tell me how it works on your mac?

**Comment by diracdeltas** [comment]
Looking better. On a blank tab, the forward button disappears (which is intentional?) but no overlap occurs. However, the window controls still overlap a bit when there is a reload button present:
screen shot 2016-04-07 at 5 27 53 pm

**Comment by vrde** [comment]
Update:
 - responsive navbar (should be fine for Mac as well)
 - ellipsis for long titles
 - load time shows millis when it's <1000ms, seconds when >1000ms

anim

**Comment by vrde** [comment]
I've updated my branch with `master`. I have a problem compiling the styles because the `braveBtn` assets are missing:
```
    ERROR in ./~/css-loader!./~/less-loader!./less/navigationBar.less
    Module not found: Error: Cannot resolve 'file' or 'directory' ../app/img/braveBtn.png in /home/vrde/repos/browser-laptop/less
     @ ./~/css-loader!./~/less-loader!./less/navigationBar.less 6:4421-4455
    
    ERROR in ./~/css-loader!./~/less-loader!./less/navigationBar.less
    Module not found: Error: Cannot resolve 'file' or 'directory' ../app/img/braveBtn2x.png in /home/vrde/repos/browser-laptop/less
     @ ./~/css-loader!./~/less-loader!./less/navigationBar.less 6:4473-4509
    
    ERROR in ./~/css-loader!./~/less-loader!./less/navigationBar.less
    Module not found: Error: Cannot resolve 'file' or 'directory' ../app/img/braveBtn3x.png in /home/vrde/repos/browser-laptop/less
     @ ./~/css-loader!./~/less-loader!./less/navigationBar.less 6:4527-4563
```

If I comment out `navigationBar.less:235` the compilation goes through and my PR works as expected.

**Comment by bridiver** [comment]
@vrde they moved to app/extensions/brave/img

**Comment by vrde** [comment]
> they moved to app/extensions/brave/img

Thanks, I fixed the paths.

**Comment by bridiver** [comment]
don't forget to delete the old app/gen directory, it looks like the files there were added to the commit

**Comment by vrde** [comment]
> don't forget to delete the old app/gen directory, it looks like the files there were added to the commit

ouch, didn't know about that. Hope everything is fine now.

**Comment by diracdeltas** [comment]
lgtm except now the title in `titleMode` is somewhat off-center.
screen shot 2016-04-18 at 5 26 55 pm

**Comment by vrde** [comment]
> lgtm except now the title in titleMode is somewhat off-center.

you are right. I just pushed some new changes that should fix that. The solution now is a bit more convoluted but I added some comments.

**Comment by diracdeltas** [comment]
works fine for me but need @bradleyrichter to sign off on design changes.

before on OS X:
screen shot 2016-04-21 at 1 24 41 pm

after:
screen shot 2016-04-21 at 1 24 29 pm

(may need a git rebase?)

**Comment by bradleyrichter** [comment]
@vrde Breakpoints look great. Please make sure the styles are retained. I don't think you intented to remove the shading, right?

**Comment by vrde** [comment]
> Breakpoints look great. Please make sure the styles are retained. I don't think you intented to remove the shading, right?

@bradleyrichter: Yep, you are right. Fixed now.


> (may need a git rebase?)

@diracdeltas: do you want me to squash the commits in this PR? I just updated my branch with your `master`, but I have an error when building:
```
    ERROR in ./app/locale.js
    Module not found: Error: Cannot resolve module 'l20n' in /home/vrde/repos/browser-laptop/app
     @ ./app/locale.js 7:13-28
```
Any idea on how to fix this?

**Comment by diracdeltas** [comment]
> Any idea on how to fix this?

running `npm install` should fix it

**Comment by diracdeltas** [comment]
lgtm but @bbondy or someone with a windows dev environment should test this on windows

**Comment by bbondy** [comment]
@aekeus would you mind doing final sign off on this on Windows? And if it's good, then merge? Thanks.

**Comment by aekeus** [comment]
Looks great on Windows. Merging.

**Comment by vrde** [comment]
:tada: thanks everyone for the support, happy to see this merged :dancers:

**Comment by bbondy** [comment]
looks great, thanks @vrde

**Pull request merged**
