### PR TITLE
Fix crash of password reducer

### PR DESCRIPTION
**Pull request by darkdh**
Fixes https://github.com/brave/browser-laptop/issues/13408

Auditors: @petemill, @bsclifton

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
See https://github.com/brave/browser-laptop/issues/13408

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

**Comment by kjozwiak** [comment]
@petemill @darkdh do we have a bug created for this? QA's script doesn't include PR's when generating the manual passes so we'll need a bug so we don't miss QAing this whenever it lands into a milestone.

**Comment by petemill** [comment]
We could merge this and create the issue in order to get rid of the error logs, but it would be great to fix the UX issue that this signifies, in that if a tab closes, we do not currently close the notification to save the password from that tab, which we should because we cannot comply with any of the user's button choices after the tab is closed anyway.

**Comment by bsclifton** [comment]
Working on some unit tests for this 😄 👍

**Comment by bsclifton** [comment]
master 8e3dd4bbaacaee6d99064c830cf7e387b392ea0d
0.23.x bbe54e242d5f9a5aceb15977521d3e59b9747935
0.22.x 14e386f036afa2868bd56d2dfdd1a71323b75c9a
0.21.x 198db118e5a5659f31a57343ba56cb992c3a12fb

**Pull request merged**
