### PR TITLE
Fix: Add right margin when url bar is in focus (fixes #5814)

### LINKED ISSUE #5814: Load time shown in URL bar needs left padding when URL is selected
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Page load time shown in URL bar needs left padding when URL is selected. 

**Expected behavior:**
Should retain the left padding when the URL text is selected

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
master

- Steps to reproduce:
    1. Open any site wait till the full page is loaded
    2. Page load time has padding when URL text is not selected
    3. On URL selection the padding is lost and the time shown is right next to the last character selected in the URL

- Screenshot if needed:
image
image

- Any related issues:
cc: @bradleyrichter @bsclifton

### PR DESCRIPTION
**Pull request by gyandeeps**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

SAme as mentioned in issue #5814

### CODE REVIEW

**Comment by luixxiul** [comment]
Does it have to be in Windows specific styles?

**Comment by gyandeeps** [comment]
Issue said all platforms. Did i make changes inside the wrong file?

**Comment by gyandeeps** [comment]
Thanks @luixxiul . Fixed it and now it applies to all platforms.

**Comment by luixxiul** [comment]
CI passed: https://travis-ci.org/brave/browser-laptop/builds/185821617

**Pull request merged**
