### PR TITLE
Localize download delete confirmation

### LINKED ISSUE #7958: Delete confirmation message ("Delete?") should be able to be localizable
**Describe the issue you encountered:** Delete confirmation message ("Delete?") should be able to be localizable.

https://github.com/brave/browser-laptop/commit/c5026e58fff408a5bdf831d6c32fad39531260ef#diff-f544daf754a6ad72801af50dbb179b6eR94

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA): 0.14.0 RC1

- Steps to reproduce:
    1. Download a file
    2. Click the bin icon on the download item
    
- Extra QA steps:
    1. Localize the string on Transifex
    2. Update localization files 
    3. Change the language setting
    4. Download a file
    5. Click the bin icon
    6. Make sure the message is successfully displayed in the same language

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by Liunkae**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fixes #7958

### CODE REVIEW

**Comment by luixxiul** [comment]
would you please squash the commits?

**Comment by Liunkae** [comment]
Squashed.

By the way, I think we should consider dropping the squash policy since we have squash on merge in GitHub.
image

**Comment by luixxiul** [comment]
@Liunkae I don't like the feature as sometimes commits are squashed by the merger before the author does. Also it breaks by default the verified signature of commits, which I do not want to see.

**Comment by Liunkae** [comment]
@luixxiul Thanks! You also make good points about commit squashing.

**Pull request merged**
