### PR TITLE
add advanced webrtc IP handling preference

### PR DESCRIPTION
**Pull request by diracdeltas**
fix https://github.com/brave/browser-laptop/issues/13668

## Test Plan:
1. go to about:preferences#advanced
2. at the bottom, it should show a webrtc policy select menu which defaults
   to 'default'
3. turn on fingerprinting protection to 'block all'
4. go to https://browserleaks.com/webrtc. it should not show any IPs
5. turn off fingerprinting protection on that page. now it should show IPs
6. in about:preferences#advanced, set webrtc policy to 'default public
   interface only'
7. reload https://browserleaks.com/webrtc. it should only show the
   public IP.
8. in about:preferences#advanced, set webrtc policy to 'disable
   non-proxied UDP'
9. reload https://browserleaks.com/webrtc. it should show no IPs.
10. in about:preferences#advanced, set webrtc policy to 'default public
    and private interfaces'
11. reload https://browserleaks.com/webrtc. it should show both IPs.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [x] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bsclifton** [comment]
@diracdeltas @bradleyrichter does it make sense to have this new setting on the `Advanced` page? Or would it make more sense to be on the `Security` page? Doesn't seem like an intuitive place to find it

**Comment by diracdeltas** [comment]
@bsclifton i  put it in advanced because probably 99.9% of users won't know what the options mean or care to change the default. it could go either way. it's more of a networking setting than a security setting.

**Comment by bsclifton** [comment]
Clicking the `What do these policies mean` links me to https://cs.chromium.org/chromium/src/content/public/common/webrtc_ip_handling_policy.h

Looking at the comments in the code, I'm able to map these constants (and the comments above them) to what we have in our drop-down... but I think it might be very difficult for users to do so (unless they're also programmers).

I think it's good for a rev1 though- just something to keep in mind. Can definitely be improved in iterations 😄

**Comment by diracdeltas** [comment]
@bsclifton noted. that's partly why i put it in advanced. :)

**Comment by bsclifton** [comment]
master 0640d1e879c9848d52f263ba69e46cb0ac653e0b
0.23.x 290aeae233ea61a31e21bc30bed7efa1e3a2bd7e
0.22.x efb654257cf8299efb1287faa46eea16fd860bc9

**Pull request merged**
