### PR TITLE
Revert "Hide Enpass until it's supported in muon"

### PR DESCRIPTION
**Pull request by andrewalker**
This reverts commit 29a8223c19a8127f195bf0c3bd46ebea1dbe5270.

According to issue #7778, particularly the comment by @mcg, support for Enpass is already working. According to @bsclifton, in the same thread, we should just create the pull request for it. So I thought I'd just go ahead and do it :)

I rebuilt and enabled on my machine (OS X) and it worked fine.

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

- Enable enpass password manager
- Autofill some passwords
- Check that it doesn't crash

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by cezaraugusto** [comment]
hey @andrewalker thanks for taking this one!

Can I ask you to go ahead and add this extension in our extensions panel as well? 

If you go to extensionsUtil.js file in [this line](https://github.com/brave/browser-laptop/blob/master/app/renderer/lib/extensionsUtil.js#L41) you'll see that enpass is commented. To enable it you can just copy how other extensions properties work, so making it like:

```js
 {
    id: enpass,
    name: 'enpass',
    description: 'enpassDesc',
    icon: 'img/extensions/enpass-128.png'
  }
```

should work fine. After that you can include the extension icon (attached below) under `app/extensions/brave/img/extensions` and name it (for parity with other extensions) as `enpass-128.png`. 

To test all that just go to about:preferences#extensions and check if extension works from there. If you have some trouble let me know and thanks again ;)

### extension image

enpass-128

**Comment by andrewalker** [comment]
Hi @cezaraugusto, thank you for the instructions. I updated what you requested. I just amended the commit, to keep history simple once it's merged 😄 
It rebuilt fine, and I retested enabling Enpass. Everything worked well. But to be honest, I didn't notice any change, because the extension was already showing up there even before I added it to extensionsUtil.js. Is this expected?

**Comment by cezaraugusto** [comment]
that's a good question: aside from built-in extensions, no extension is installed by default so we need a "dumb" data to aware users that a given extension is available. 

You're seeing the extension because you have enabled it before under the password manager -- likely when you tested to see if extension works. If you clear your data and try to install it inside extensions tab, the extension will not be available until you activate. 

Resuming: your first change made it avail under password manager and the second for extension tab -- which can only see installed extensions and dummy content (what you did next).

**Comment by bsclifton** [comment]
Nice to get this working! Thanks, @andrewalker 😄

**Comment by luixxiul** [comment]
This was reverted. See: https://github.com/brave/browser-laptop/pull/10246

**Comment by andrewalker** [comment]
@luixxiul thanks for the update! Although, as asked in the pull request, I would really like to understand what went on :)

**Pull request merged**
