### PR TITLE
add metamask to available extensions

### PR DESCRIPTION
**Pull request by kevinlawler**
brave/browser-laptop#8671

already added to vault manifest & live on server
brave/vault-updater#43

Auditors:
@bridiver @bsclifton @jonathansampson

### CODE REVIEW

**Comment by bridiver** [comment]
the resizing is normal, but we could probably eliminate it by debouncing `setPopupWindowDetail` in `popupWindow.js`

**Comment by bsclifton** [comment]
@bridiver I wonder if that same logic is affecting LastPass (the popup is sized incorrectly when DPI is increased)

**Comment by bsclifton** [comment]
Moving to 0.19.x because there is code this depends on (see https://github.com/brave/browser-laptop/pull/9585)

**Comment by luixxiul** [comment]
Does this close #8671?

**Comment by bsclifton** [comment]
@luixxiul I don't think so- cc: @jonathansampson

**Pull request merged**
