### PR TITLE
Created session helper for newTabState

### PR DESCRIPTION
**Pull request by bsclifton**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Created session helper for newTabState

- site will only be added if it's a bookmark or history item
- site will only be removed if it's a bookmark or history item
- site moves are now ignored
- favicon is now updated for the newTabState (which is a different list than AppState.sites)

Fixes https://github.com/brave/browser-laptop/issues/5357
Fixes https://github.com/brave/browser-laptop/issues/5310

Auditors:
@bridiver - check out the new session helper; hope I did this right :)

@darkdh - this fixes the folder delete issue by ignoring folders

@cezaraugusto - move is no longer tracked (which is fine; we don't care about the order of
the items with regard to their position in bookmarks toolbar, which is what moveSite is for).
Also, see the new session helper (which we can use for ordering by # visits)

Test Plan:
1. Launch Brave and visit brave.com
2. Open a new tab (about:newtab) and confirm you see brave.com there (favicon should show also)
3. Visit about:history and delete the visit you just made to brave.com
4. Confirm it's now gone in about:newtab

### CODE REVIEW

**Comment by darkdh** [comment]
lgtm

**Comment by cezaraugusto** [comment]
awesome! lgtm :ok_hand:

**Comment by bridiver** [comment]
nice cleanup! Please add some tests and what do you think about naming it `aboutNewTabState`? When I first looked at it I thought it was code that applied to any new tab and took me a minute to realize that it was specifically for the `about:newtab` page.

**Comment by bsclifton** [comment]
@bridiver added test cases :smile: Took a while to get it all sorted, but really glad I added them

While writing the tests, I realized that the remove wasn't working and ended up updating the code to only add the site info, (not the tags).  If you look at siteUtil.removeSite, it never actually deletes the entry (unless the tags are empty). By excluding the tags, the remove will always work (instead of keeping the entry for history)

**Comment by bridiver** [comment]
++

**Pull request merged**
