### PR TITLE
Refactor addEditBookmarkHanger.js with commonForm

### LINKED ISSUE #6040: Apply commonForm to addEditBookmarkHanger.js
## Test plan

https://github.com/brave/browser-laptop/pull/8136#issue-220448998

----

https://github.com/brave/browser-laptop/pull/6035#issuecomment-265066728

> Bonus points for replacing that heavy black close button with the svg from the stop loading button.  :  )
> 
> screenshot 2016-12-06 14 24 31
>
> @bradleyrichter I have replaced the close button for the modal dialog with the SVG button in 21ece29#diff-a12551e83f49ce14bb3d831f382ff9acR106 of #6009 

This is a sub-task of #6040

#8010

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #6040
Addresses #7989

- Added `CommonFormBookmarkHanger` to commonForm.js
- Added `globalStyles.spacing.bookmarkHangerMaxWidth` to global.js
  Max-width of the bookmark hanger was set to 350px. Also, setting white-space:normal makes it possible for lines to be wrapped.

- Applied `Dialog` to addEditBookmarkHanger.js instead of addEditBookmark.js
- Added cancel button with `this.onClose` as 'fa fa-close' was removed

- Added const `arrowUp` and `dialogHanger`
- Added `styles.bookmarkHanger` which is applied if `!this.props.isModal`
- Copied `CommonFormSection` and `CommonFormTitle` from commonForm.js, adding `CommonFormBookmarkHangerTitle` to addEditBookmarkHanger.js
  The margin-top of the title should be reduced if `this.props.isModal`.

- Changed backgroundColor of commonForm to `#fff`

- Add zindex to elements on navigation bar to let tests pass
  The value was set to higher than that of dialog, which is 3000.

- Updated test code

Also:
- Replaced divs with sections
- Removed styles from form.less
- Removed `wideButton` from buttons
- Added testIds to buttons

Auditors:

Test Plan 1:
1. Open about:preferences
2. Disable Home button
3. Click the star icon on the URL bar
4. Make sure the arrow up appears exactly under the star
5. Open about:preferences
6. Enable Home button
7. Click the star icon again
8. Make sure th arrow up appears exactly under the star

Test Plan 2:
1. Open about:bookmarks
2. Click the star icon on the URL bar
3. Click "Done"
4. Click the star icon again
5. Click "Remove"
6. Make sure the bookmark is successfully removed

Test Plan 3:
1. Click "Add Folder" icon on about:bookmarks
2. Click "Cancel"
3. Make sure the dialog is closed

Test Plan 4:
1. Create a bookmark folder on about:bookmarks
2. Edit the folder via context menu on about:bookmarks
3. Click "Remove"
4. Make sure the folder is successfully removed

Test Plan 5:
1. Click the star icon on about:bookmarks
2. Click "Cancel"
3. Make sure the dialog is closed
4. Click the star icon again
5. Create a bookmark
6. Edit the bookmark via context menu
7. Click "Remove"
8. Make sure the bookmark is successfully removed

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

### CODE REVIEW

**Comment by luixxiul** [comment]
screenshot 2017-04-09 14 25 20
screenshot 2017-04-09 14 25 28
screenshot 2017-04-09 14 25 40
screenshot 2017-04-09 14 25 58
screenshot 2017-04-09 14 26 10
screenshot 2017-04-09 14 26 22

**Comment by bradleyrichter** [comment]
@luixxiul Can you please find a way to add shadow to the triangle nub as part of this refactor? It is barely visible in it's current form.

**Comment by cezaraugusto** [comment]
rebase pls

**Comment by luixxiul** [comment]
@bradleyrichter I updated the arrow with box-shadow. 

screenshot 2017-04-18 22 50 57 screenshot 2017-04-18 22 51 13

**Comment by luixxiul** [comment]
> Please also move the window up so the point of the nub is between the legs of the arrow button, similar to chrome.

I tried but I cannot find an easy way of fixing it without changing default behavior (ie clicking the star button twice displays "edit bookmark" dialog); the fix should be related with z-index, which is out of scope of this PR, so I think it is a good idea to deal with the issue with another PR.

Without changing z-index you'll get this:

screenshot 2017-04-19 1 35 46

**Comment by luixxiul** [comment]
@cezaraugusto thanks for reviewing. I just missed the camel case stuff, will fix it later.

**Comment by luixxiul** [comment]
@cezaraugusto Is there any lint tool available out there like standard.js to avoid such a case?

If not, I think it is worth trying to create our own one (though I myself am not sure how to.)

**Comment by luixxiul** [comment]
@cezaraugusto ready for re-review. If it looks good to you, please set ready-to-merge label. I will then squash  the commits to merge the test plans and sign the commit with GPG, thanks!

**Pull request merged**
