### PR TITLE
Auto-open bookMarksToolbar when page is bookmarked. Closes #1487

### LINKED ISSUE #1487: auto-open bookmarks bar the first time user presses bookmark button (star)
If already open, leave open.

later - add some animation similar to Firefox (mac)

### PR DESCRIPTION
**Pull request by cezaraugusto**
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.

### CODE REVIEW

**Comment by bsclifton** [comment]
Is this behavior always wanted? I love the bookmarks toolbar personally, but some folks might prefer to only use the Bookmarks Manager page

**Comment by bradleyrichter** [comment]
@bsclifton actually, we may change things up since adding BMs to the bar is not even always wanted.

Bookmarks is a big, multi-piece project and we are getting there in pieces. Let's keep this on the back burner for now.

**Comment by bbondy** [comment]
thanks @cezaraugusto, I talked to @bradleyrichter and we can merge this but could you do a couple changes:

i) As implemented, if a user tries to hide the bar because they hate bookmark toolbars, then it will keep popping up after each bookmark. Could you only do this when there are no bookmarks and no bookmark folders?

ii) Could you add a test for it appearing on first bookmark and not re-appearing after 2nd bookmark if it's not shown?

**Comment by cezaraugusto** [comment]
@bbondy all good, will do it.

**Comment by cezaraugusto** [comment]
Closing it in favor of #2571

**Pull request closed without merging**
