### PR TITLE
handle sites that check navigator.plugins

### PR DESCRIPTION
**Pull request by bridiver**
allow adobe to auto-detect install
todo - add flash enable message box to adobe install page when flash is installed
todo - reload page after enabling flash for pages that detect navigation.plugins
partial fix for #6306

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:
1. Go to Pandora.com
2. Click on adobe flash link
3. Install flash
4. Enable flash
5. Go to Pandora.com
6. Click on adobe flash link
7. Message box should open
8. Deny
9. Reload Pandora.com
10. Click on adobe flash link
11. Allow
12. Reload Pandora.com 

Flash should be enabled

cc @diracdeltas

### CODE REVIEW

**Comment by diracdeltas** [comment]
it should auto-reload when clicking 'allow' if possible. however, when i manually reload, Flash doesn't seem to load.

**Comment by bridiver** [comment]
@diracdeltas for the navigator.plugins sites? That's listed in the todo

**Comment by bridiver** [comment]
but this PR isn't meant to cover that case so I think we can still merge unless there are other problems and take care of the rest in a follow up

**Comment by diracdeltas** [comment]
@bridiver i'm trying this out on pandora. when i click 'remember' and reload manually it still doesn't seem to load flash

**Comment by diracdeltas** [comment]
i do see the flash allowed site setting in about:preferences#security though

**Comment by bridiver** [comment]
I think both issues are from using prebuilt instead of electron master. Let me know if you see the same thing after updating

**Comment by diracdeltas** [comment]
merging for now since code lgtm

**Pull request merged**
