### PR TITLE
don't load tabs until the become active or previewed

### LINKED ISSUE #1794: New or restored tabs shouldn't load unless they are active or preview

### PR DESCRIPTION
**Pull request by bridiver**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

Fixes #1794 #470

### CODE REVIEW

**Comment by bbondy** [comment]
Nice quick win, thanks!

**Comment by luixxiul** [comment]
Does this cover pinned tabs too?

**Comment by bridiver** [comment]
I thought so, but pinned tabs don't store state so the favicon doesn't show up. Disabled lazy load for pinned tabs in https://github.com/brave/browser-laptop/commit/9c021eac82e1d7ec63952f36f62302a303840206

**Comment by luixxiul** [comment]
I'd prefer enabling lazy load for pinned tabs, though

**Pull request merged**
