### PR TITLE
Adds history limit into the historySites

### LINKED ISSUE #10895: History limit in the state
**Describe the issue you encountered:**

With site split PR I accidentally removed history limit in the state, so right now we are saving all history sites in the state without any limitations.

### PR DESCRIPTION
**Pull request by NejcZdovc**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #10895

Auditors:

## Test Plan:
covered with automated tests

## Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@bbondy we use to do this inside `appStore` where we had direct access to `store` variable. But I am not sure how we can debounce it in the reducer where we need to return state from it.

This is the old implementation: https://github.com/brave/browser-laptop/blob/0.18.x/js/stores/appStore.js#L348

**Comment by bbondy** [comment]
@NejcZdovc you can just debounce an action that will limit it on demand.  When the action actually goes through to the reducer it can be done sync at a lower frequency.

**Comment by NejcZdovc** [comment]
@bbondy but if we debounce action, then history will not be update for a minute, which means that if you visit a site and go to `about:history` right after that you will not see it there and we will have the same problem that we have for top sites

**Comment by bbondy** [comment]
The debounce only has to apply for enforcing the fuzzy limit, not for doing the add.

**Comment by bbondy** [comment]
I was thinking you can have an action to clean up and wrap that in a debounced function that you call.  That call calls the action, and when the action hits the store it does the trimming.

**Comment by bsclifton** [comment]
@bbondy can you please re-review when you have a chance? 😄

**Comment by NejcZdovc** [comment]
this is not ready yet, we need to add debounce

**Comment by bsclifton** [comment]
master a24496c14dbe6d5c0320ef947a7a26380adf8f69
0.21.x b36d1eb2c807f91bd7428c3b441341ffce1828d7
0.20.x f49ba730c4b8c66bbaa62c47235583e588f51da0

**Pull request merged**
