### PR TITLE
updates for the ledger for thursday

### PR DESCRIPTION
**Pull request by mrose17**
- do not flicker the "Create wallet" button when creating a wallet --  https://github.com/brave/browser-laptop/issues/3376

### CODE REVIEW

**Comment by diracdeltas** [comment]
this PR currently does not fix the flickering wallet issue for me

**Comment by mrose17** [comment]
is it possible for a PR to be neither `creating` nor `created`: *no*

**Comment by mrose17** [comment]
i tested it 5 times and each time, it worked ok. let me look again.

**Comment by diracdeltas** [comment]
> is it possible for a PR to be neither creating nor created: no

what about before the `create wallet` button is clicked?

**Comment by mrose17** [comment]
superseded by https://github.com/brave/browser-laptop/pull/3432

**Pull request closed without merging**
