### PR TITLE
Address bar should be active for about:newtab

### LINKED ISSUE #3712: Address bar should be active for about:newtab
**Did you search for similar issues before submitting this one?**

No

**Describe the issue you encountered:**

Address bar is not "active" when it should be

**Expected behavior:**

Address bar "active", so user could add the web address without need to click on it.

- Platform (Win7, 8, 10? macOS? Linux distro?): 

Ubuntu

- Brave Version:  

Brave: 0.11.6

- Steps to reproduce:
    
1- Open a new tab
2- Switch to the new blank tab
3- Go back to the tab you were browsing before you opened the new tab
4- Go to the blank new tab you opened in step 1

On step 4, the address bar should be "active", so users could be able to write the web address without need to click on it.

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by Sh1d0w**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

This issue was fixed via #3718
but was returned with feedback from the QA.

Now it should properly handle switching to new tab via shortcut or mouse.

Fixes #3712 
Auditors:
@bbondy

Test Plan:
While switching to a new tab eighter via shortcut or mouse click
the url bar should be focused.

### CODE REVIEW

**Comment by bbondy** [comment]
thanks would you mind adding some tests for this?

**Comment by bbondy** [comment]
does url bar active mean auto complete can be open? Just making sure we have to treat focused and active separately.  And can we get an accurate view of focused with this state always?

**Comment by Sh1d0w** [comment]
@bbondy 

1. URL_BAR_ACTIVE = true - it is visible and not hidden by the page title
2. URL_BAR_SELECTED = true - means the text you have typed in is selected ([also url bar gains focus](https://github.com/Sh1d0w/browser-laptop/blob/283048910f37e1dc05fc19a2736dd3b337320036/js/stores/windowStore.js#L566))
3. URL_BAR_FOCUSED = true - means the focus is on the url bar 

Now these are 3 different states, and they can lay different results if combined together. For example if you type something in the url bar, blur and trigger focus, the cursor will blink at the end of the text. But if you do the same and instead trigger url bar selected and the focus the text you typed in will be selected and if you start typing you will overwrite it.

I tried to replicate the behaviour of FF and Chrome when you switch tabs.

Will add some more tests today or tomorrow. If this blocks the current release you can move it for the next one.

**Comment by bbondy** [comment]
Thanks, I'll merge but pls add some tests because the interactions can break in the future.

**Pull request merged**
