### PR TITLE
Build: Upgrade to use webpack 2

### PR DESCRIPTION
**Pull request by gyandeeps**
- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Upgrade to use Webpack 2

### CODE REVIEW

**Comment by luixxiul** [comment]
I tested the PR yesterday and I think I got some errors related with WebTorrent and clipboard. @gyandeeps  could you please confirm?

**Comment by gyandeeps** [comment]
I tried the regular build and the dev watch build. Which one are you talking about @luixxiul ?

**Comment by Liunkae** [comment]
@luixxiul I was getting those errors on master too. Removing `node_modules` seems to have fixed it.

**Comment by gyandeeps** [comment]
Team - Should I leave this open or close it ?

**Comment by bsclifton** [comment]
Hi @gyandeeps,

I personally don't have any experience or knowledge of webpack2; I don't feel suited to review this.  

Because it's sat for a while and nobody else has volunteered to review yet (and there isn't an issue for it), maybe it's best to be closed for now.  Please do feel free to share more documentation 😄  I would like to learn about the advantages of upgrading

**Comment by luixxiul** [comment]
+1. Let's open an issue to investigate advantage of webpack 2.

**Pull request closed without merging**
