### PR TITLE
Add verified option to Add Funds button shortcut

### LINKED ISSUE #6754: Refinements to Add Funds URL Include Button
- [x] remove blue selected outline (only the URL bar should display tab-selection outline)
   - was implemented with https://github.com/brave/browser-laptop/pull/6761
- [x] replace BTC icon with new Heart icons
- [x]  fix render gap to match left-side bookmark button

image

image

### PR DESCRIPTION
**Pull request by cezaraugusto**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Auditors: @bsclifton

Fix #6754

Test Plan: Covered by automated test
```
npm run test -- --grep="Show as verified if publisher is a verified publisher" 
```

Visual changes:

screen shot 2017-01-25 at 22 47 35
screen shot 2017-01-25 at 22 47 50
screen shot 2017-01-25 at 22 49 27

* The publisher icon was changed from BTC to Verified icon; 
* Now a verified publisher is shown as green (same pattern as seen on about:preferences);
* Enabled publisher is set as a yellow icon;
* Disabled (not receiving any $) publisher is set to gray.

### CODE REVIEW

**Comment by cezaraugusto** [comment]
@clifton AFAIU that's how it should work. Enabled are yellow, disabled can be either gray (for unverified) or green (verified).

/cc @bradleyrichter

**Comment by bradleyrichter** [comment]
This is an interesting problem. Let's get @ayumi 's opinion.

So as implemented:

grey - not verified, don't fund
green - verified, don't fund
gold - fund (verified not indicated)

I think adding some animated state change to show the coin jump or something similar would enhance the clarity of the gold-state.

I think the green state could be confused as funded until you first press the button and see the gold state.

Thoughts anyone?

**Comment by ayumi** [comment]
first @cezaraugusto thanks for your work, this looks sweet! :)

On the green vs yellow I agree with @bradleyrichter. To me green is good and it looks more pleasant compared to yellow. Thus if we show verified sites as green it could suggest to users that green is already good and no action is required.

I can understand the utility of the colors because it distinguishes verified publishers and reps our system; but maybe this is too much info for users, who simply want to contribute to a site they like.

How do peeps feel about:
- Changing the publisher verified state to be more subdued (e.g. hover or secondary click)
- Removing the yellow icon so it's just gray or green

**Comment by cezaraugusto** [comment]
what about having the verified publisher to be the same as unverified (gray), but with a small verified badge on bottom-right? Similar approach as Slack does with unread messages, but with the verified green badge on it, and at the bottom. Like:

screen shot 2017-01-27 at 18 13 50

**Comment by bradleyrichter** [comment]
@cezaraugusto I think that is on the right track. I think we need to keep verified green as it is for publishers as it works well there. (like in publishers.brave.com and the ledger list)

here is a version of yours above:

image



or



image

**Comment by cezaraugusto** [comment]
@bradleyrichter IMO being the icon small, a verified badge a little off icon's container would help users see more clearly that publisher is verified and would avoid confusion if that was or wasn't part of icon aesthetic.

**Comment by ayumi** [comment]
An option to help us ship would be to keep this PR simple and go with gray/green for contributing and a basic tooltip for verified/not verified; then decide on verified status in another :gift:.

**Comment by cezaraugusto** [comment]
updated PR to make use of Aphrodite

**Comment by bradleyrichter** [comment]
ok, great feedback!

After some more thought, I have a new batch to look at.

1. 4 states was too many. Using the badge may have made this more understandable but its too much.

2. I gave up the gold (no pun intended) as I agree, the GREEN is much more powerful. 

3. In order to use filled green we need to change the verified icon in the ledger list or users may be confused that it means "funded".

4. I may want to change the sliders to green instead of orange to tie this all together. 


So, here are 3 variations. Consider the additional meaning of the checkmark and if it should be used, and where.

image


note: there is no difference between verified-funded and unverified-funded mainly to simplify, and because the user made the decision to fund so it doesn't really matter after that.

Also - on mouse hover, the icon should "preview" the funded state.

**Comment by bbondy** [comment]
Hey @cezaraugusto what's left here?  I'd like to push to 0.13.2 if there are no objections if this isn't ready for review today. Thanks!

**Comment by cezaraugusto** [comment]
@bbondy it's ready to go, may need a follow-up based on how we want the publisher icon, which is just a matter of changing images, but speaking of code it's ready and feature works ok.

**Comment by bradleyrichter** [comment]
final art for this version:

image


and associated ledger list item states: (for reference)

image

**Comment by bradleyrichter** [comment]
[URL_fund_buttons.zip](https://github.com/brave/browser-laptop/files/740455/URL_fund_buttons.zip)

**Comment by luixxiul** [comment]
the milestone was reset to 0.13.3

**Comment by cezaraugusto** [comment]
Updated to match new design spec:

**Verified publisher - No fund**
screen shot 2017-02-01 at 03 15 58

**Verified publisher - Fund ok**
screen shot 2017-02-01 at 03 16 13

**Unverified publisher - No fund**
screen shot 2017-02-01 at 03 16 22

**Unverified publisher - Fund**
screen shot 2017-02-01 at 03 16 30

**Comment by cezaraugusto** [comment]
Based on [Brad's comment above](https://github.com/brave/browser-laptop/pull/6862#issuecomment-276198497) I created a follow-up issue here: #6974

**Comment by bradleyrichter** [comment]
yeah...thank you @cezaraugusto !

**Comment by bsclifton** [comment]
@cezaraugusto is this ready for review? (IIRC, it is- been a while, just wanted to check)

**Comment by cezaraugusto** [comment]
@bsclifton yes sorry, I forgot the label

**Comment by da2x** [comment]
This new icon can very easily **be mistaken for a security or trust indicator!** Please reconsider sticking **anything green with a checkmark (or padlock)** anywhere near the address field of a web browser.

**Comment by diracdeltas** [comment]
echoing @da2x's concern. would help if the icon were orange and farther away from the urlbar (such as next to the lion icon)

**Comment by cezaraugusto** [comment]
cc @bradleyrichter

**Comment by bradleyrichter** [comment]
@da2x Great observation. I think users are used to looking at the left end of the URL so the right-placement should help.

WDT of this simple color change? (more of a coin-like color)

image

**Comment by da2x** [comment]
> I think users are used to looking at the left end of the URL

Not in right-to-left scripts. You’re making assumptions as to what user agents others might have used prior to Brave.

Get rid of the checkbox too. People with red–green color blindness see gray with a checkmark. People with blue–yellow color blindness wouldn’t see the difference between grey and orange. You can’t rely on colors alone to represent state.

Icon-wise, this is a tough one to get right. You want to convey a lot of foreign concepts with just one icon. The different states doesn’t make it any easier. The BitCoin currency symbol is quite detailed and doesn’t really look all that good at small sizes. It doesn’t convey any relationship with the publisher, however.

Maybe use different icons inside the hexagon:

* Verified: hand giving out coin: https://cdn1.iconfinder.com/data/icons/banking/512/E1-256.png
* Disabled: hand giving out coin with diagonal slash: https://cdn1.iconfinder.com/data/icons/banking/512/E1-256.png 
* Empty wallet: wallet with diagonal slash https://d30y9cdsu7xlg0.cloudfront.net/png/3685-200.png

Not great, but possibly some ideas. As I said, it’s a lot of information to convey for such a small widget.

**Comment by da2x** [comment]
P.S.: I’d say Brave could need with a security review team that are given 5 min. to review UI changes to catch issues like this.

**Comment by bradleyrichter** [comment]
So, we need the check mark but I moved it to become a badge. It references the verified publisher status that will be understood by the user after they have used the ledger list.

Regarding right-reading languages, the user is still accustomed to seeing the green secure lock icon in the front of the URL. This icon is always on the opposite end. (but green has been reduced to a minimum to be sure)

New zoom'd image:
image


Rough mockup of actual size:
image


new SVG icons:
[fund_icons.zip](https://github.com/brave/browser-laptop/files/749566/fund_icons.zip)



Regarding color blindness, the yellow seems to provide enough contrast in both on and off states.
image


image


image

**Comment by da2x** [comment]
I don’t believe anyone can be fooled to think it’s a trust or security indicator anymore, and it’s much cuter too. Won’t the checkmark look like a orange smudge on a standard resolution screen?

The heat icon may be confused with a bookmarking feature as some browsers use the heart icons to mean favorites/bookmarks. Though the heart icon means all sorts of different things in all sorts of different apps, so who knows what most people associate it with.

**Pull request merged**
