### PR TITLE
Better hot reload

### LINKED ISSUE #1171: Implement React Hot Loader
## Comment by @bsclifton
We can consider implementing React Hot Loader:
http://gaearon.github.io/react-hot-loader/

## Original post
Hello,

I'm trying to make a skin for Brave, while I'm developing the whole app refreshes and the live editing is not working. Do you have a starting point to find out what's the problem? 

This video is when I try to modify the css https://cloudup.com/cQYrU8W0TSP

### PR DESCRIPTION
**Pull request by jide**
This adds react-hmre for hot-reloading on changes while keeping browser state.

Fixes #1171

### CODE REVIEW

**Comment by jide** [comment]
Changing webpack's `devtool` to `cheap-module-source-map` speeds up things **a lot**, since the issue is also about speed, I thought I should include it here.

**Comment by luixxiul** [comment]
@bbondy would you please review this one when you have some time?

**Comment by bbondy** [comment]
I seems like this is deprecated and the website mentions highly experimental.  They suggest React Hot Loader 3, is it possible to use that instead? Maybe for this PR only include the cheap source maps.  Sorry for the delay in reviewing.

**Comment by jide** [comment]
I tried to use react hot loader 3 (and 2), but the API is different, and I could not figure how to do it properly because of the way props are passed to <Window/> from ipc.

So maybe it's more reasonable to only change devtool for now.

**Comment by jide** [comment]
Ah, I found that comment I made, it was here https://github.com/brave/browser-laptop/issues/1171#issuecomment-271045087

**Comment by bsclifton** [comment]
This PR is welcome, but I'm going to close since there hasn't been activity. Please feel free to explain more about the change + ping the reviewer again.

Sorry this hasn't been an ideal experience; this appears to be a low priority issue and didn't generate enough discussion. I personally am not authoritative enough with WebPack to review / dispute this change

**Comment by bsclifton** [comment]
@jide since you had originally done this (LONG time ago)- we've upgraded to webpack 3. Is this change still applicable? If so, did you want to rebase and provide more info? (ex: testing steps for a reviewer)

**Comment by jide** [comment]
@bsclifton Change is still applicable yes. I'll come back with a rebased PR and info.

**Comment by bsclifton** [comment]
@jide I'll close this for now, but please do feel free to rebase/reopen 😄 

When you had originally submitted, I didn't have enough webpack experience to properly review (maybe other reviewers were in same boat).  I do feel comfortable enough now to review this 😄

**Pull request closed without merging**
