### PR TITLE
Fix/hamburger menu appearance

### PR DESCRIPTION
**Pull request by Hapcy**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist. - It exists: #4921
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed). - I don't think the commits need squashing.

Test Plan:

1. Open browser.
2. Click hamburger menu icon.
3. Click it again.
4. Observe as the hamburger menu's context menu doesn't reappear but disappears.

### CODE REVIEW

**Comment by Liunkae** [comment]
+1 👍  Works great!

**Comment by bsclifton** [comment]
@Liunkae I formally assigned you, in case you wanted to approve. If it looks good, go ahead and drop the `ready-for-merge` label in (and remove the `ready-for-review` one).  Thanks :smile:

**Comment by bsclifton** [comment]
[Recent CI passed](https://travis-ci.org/brave/browser-laptop/builds/186330354), merging! Thanks for the change, @Hapcy :smile:

**Comment by bsclifton** [comment]
Great job w/ the tests, BTW :smile:

**Pull request merged**
