### PR TITLE
Update Standard@9.0.0

### LINKED ISSUE #7492: Update to Standard@9.0.0 - rules "no-multiple-empty-lines", "no-useless-return", "generator-star-spacing", "padded-blocks"
Version 9.0.0 introduced major changes that changed lint rules for several files.

This work will be split to avoid regressions. From [Standard changelog](https://github.com/feross/standard/blob/v9.0.0/CHANGELOG.md#new-rules) those rules were added:

(note that `changed rules` didn't affect our repo)

* Disallow mixing different operators without parens (no-mixed-operators)
* [x] __Enforce 1 newline at end of file (previously 1 or 2 were ok) (no-multiple-empty-lines)__
* Disallow Unused Expressions (no-unused-expressions)
* [x] __Disallow redundant return statements (no-useless-return)__
* Disallow Incorrect Early Use (no-use-before-define)
* Enforce that Promise rejections are passed an Error object as a reason (prefer-promise-reject-errors)
* Enforce comparing typeof expressions against string literals (valid-typeof)
* [x] __Enforce spacing around * in generator functions (generator-star-spacing)__
* Disallow Unnecessary Labels (no-extra-label)
* Disallow spacing between template tags and their literals (template-tag-spacing)
* [x] __Disallow padding within switch statements and classes (padded-blocks)__
* Enforce that Symbols are passed a description (symbol-description)

This issue addresses rules marked as checked.

### PR DESCRIPTION
**Pull request by cezaraugusto**
Auditors: @bsclifton

Fix #7492
Follow-up of #7495 and #7785

Will also help with standard version inconsistency between repo/travis (#7794)

This PR addressed the following new rules:

```
no-mixed-operators (follow-up with 1 occurency)
no-unused-expressions
prefer-promise-reject-errors
valid-typeof
no-useless-escape
```

Test plan:

1. Run `npm run lint`
2. Should have no linting errors

### CODE REVIEW

**Comment by diracdeltas** [comment]
Note that this doesn't fully address #7794 because Travis is using latest Standard (9.0.2?) instead of 9.0.0. I believe we still need #7795 to fix that.

**Comment by cezaraugusto** [comment]
how Travis handle deps updates? I think we can update this to match current Travis version

**Comment by diracdeltas** [comment]
@cezaraugusto i think there is a bug in how travis invalidates caches; others report similar issues at https://github.com/travis-ci/travis-ci/issues/3758. i'm not sure if shrinkwrapping helps but it might.

**Comment by diracdeltas** [comment]
anyway i reverted caching on master for now

**Pull request merged**
