### PR TITLE
Button tweak prefs font nicer

### LINKED ISSUE #6003: adjust fonts in prefs and other about pages to use helv neue on mac, and arial on win

### PR DESCRIPTION
**Pull request by bradleyrichter**
auditors:

@bbondy 
@luixxiul 
@jkup 

Please check on windows and with Japanese.

This closes #6003 

#5916

### CODE REVIEW

**Comment by luixxiul** [comment]
on about:about,

screenshot 2016-12-03 13 45 35

**Comment by bradleyrichter** [comment]
fixes: #6004

**Comment by luixxiul** [comment]
44433c7 should fixes the bookmark dialog into these:

screenshot 2016-12-03 14 54 05
screenshot 2016-12-03 14 54 59

**Comment by luixxiul** [comment]
with 1df8dc3

screenshot 2016-12-03 17 24 45

**Comment by bbondy** [comment]
++

**Pull request merged**
