### PR TITLE
TOS FOR THE TOS THRONE

### LINKED ISSUE #11942: Add link on about:preferences#payments panel to Brave Payments Contributors Terms of Service
as noted in the mockup above, there should be a link on about:preferences#payments labelled "Terms of Service" that opens a new tab at https://basicattentiontoken.org/contributor-terms-of-service/

**New mock for ledger table**

### PR DESCRIPTION
**Pull request by cezaraugusto**
Closes #11942 
Auditors: @bsclifton 

screen shot 2017-11-15 at 7 51 47 pm
screen shot 2017-11-15 at 7 51 13 pm
screen shot 2017-11-15 at 7 51 00 pm
screen shot 2017-11-15 at 7 50 37 pm

### CODE REVIEW

**Comment by jenn-rhim** [comment]
looks great to me! two thumbs-up!!

**Comment by jenn-rhim** [comment]
looks great to me. two thumbs-up!!

**Comment by bsclifton** [comment]
master 1ff77176504cf336294ba7eb6c764bfb5a3e6ed4
0.21.x b0d0603819b8c5c60a6b9fc84d9711e021bec13d
0.20.x ba1e1be9a0256ff93041373d627ee5d81fcddfb8
0.19.x @cezaraugusto can you help me merge this one?

**Comment by cezaraugusto** [comment]
0.19.x 1d0556f6b890b11c787a05d57c2cbedeaa8862dc

**Pull request merged**
