### PR TITLE
Improved Polish translation

### LINKED ISSUE #13702: Incorrect Polish Translation
### Description
_Reload Tab_ is translated incorrectly as _Odświerz_.

### Steps to Reproduce
1. Use the Polish language
2. View the _Reload Tab_ label

**Actual result:**
Translation is incorrect.

**Expected result:**
Translation should say _Odśwież_ (not the diacritic above the z).

### Brave Version
0.22.13

**about:brave info:**
``` 
Brave: 0.22.13 
V8: 6.5.254.41 
rev: a8cfb160479f1d00d0769368eb440030182bb83b 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181
```

**Reproducible on current live release:**
Yes

### Additional Information
Translation is found here: https://github.com/brave/browser-laptop/blob/d0531ac7576132e9793fe1ff065492e4c219aa8b/app/extensions/brave/locales/pl-PL/menu.properties#L138

### PR DESCRIPTION
**Pull request by TheAresjej**
I improved the Polish translation and fix #13702

### CODE REVIEW

**Comment by bsclifton** [comment]
Thanks for the PR, @TheAresjej 😄 

Per the issue, you can get started with translations by checking out the guide here:
https://github.com/brave/browser-laptop/blob/master/docs/translations.md

You can sign up for Transifex and put the proper translations in place. If we merge these ones, they'll get overwritten next time we pull translations. So translating in Transifex is the way to go

I'll close this issue- let us know if you need help during that setup process

**Comment by TheAresjej** [comment]
@bsclifton Ready! Can you add this to the latest beta version? 😃

**Comment by bsclifton** [comment]
@TheAresjej have you created an account on transifex.com?
https://www.transifex.com/brave/brave-laptop/

**Comment by TheAresjej** [comment]
Yes, the translation is ready! 😃

**Pull request closed without merging**
