### PR TITLE
Export bookmarks

### LINKED ISSUE #1002: Provide a way to export bookmarks
Since we have a way to import now, we should really have a way to export too.

## Test Plan
First scenario
- Go to Bookmarks menu
- Select Export Bookmarks
- Select destination
- Bookmarks are exported

Second scenario
- Go to Bookmarks Manager
- Click on Export icon
- Select destination
- Bookmarks are exported

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

Resolves #1002

## Auditors
@bbondy @bsclifton

## Test Plan
Moved to https://github.com/brave/browser-laptop/issues/1002#issue-138549029

## Automated tests
- `npm run watch-test`
- `npm run unittest -- --grep="Bookmarks export"`

### CODE REVIEW

**Comment by luixxiul** [comment]
Sweet! love to see this implemented soon :-)

**Comment by bbondy** [comment]
@NejcZdovc would you mind rebasing this PR? Thanks!

**Comment by NejcZdovc** [comment]
@bbondy rebased

**Comment by NejcZdovc** [comment]
@bbondy This PR is finished but you were checking out only first commit, this PR has 3 commits.

**Comment by bsclifton** [comment]
@bradleyrichter do you have any thoughts on how this looks?
screen shot 2017-02-01 at 12 47 46 am

You can export via Bookmarks menu and also by going to Bookmarks Manager (shown in screenshot).  It's not clear to me (unless I hover or click) which one is import and which is export

(down arrow is export, up arrow is import)

**Comment by bradleyrichter** [comment]
@bsclifton it needs improved icons. WIP for me.

**Comment by NejcZdovc** [comment]
@bradleyrichter what should be the next step?

**Comment by bradleyrichter** [comment]
I'm landing new icons right here, later today.

**Comment by bradleyrichter** [comment]
new import/export buttons ready for feedback:

image

**Comment by bsclifton** [comment]
@bradleyrichter I really like it! 😄

**Comment by bradleyrichter** [comment]
new SVGs for these icons:

[browser_bookmark_manager_icons.zip](https://github.com/brave/browser-laptop/files/746534/browser_bookmark_manager_icons.zip)

**Comment by NejcZdovc** [comment]
@bradleyrichter added new icons. New layout:

image

**Comment by bradleyrichter** [comment]
@NejcZdovc Can you try adding some padding between them? About 5 px or equivalent. 

And what is the best way to get our mouse-hover highlight to work? Use CSS with the SVG?

**Comment by NejcZdovc** [comment]
@bradleyrichter I was just updating padding when you wrote about it :) We are doing hover with CSS

New layout (changed from 7px to 10px)
image

**Comment by bradleyrichter** [comment]
ha ha...

Now I see that the new folder button looks bigger than the import/export. Can you try enlarging the import/export buttons?

**Comment by luixxiul** [comment]
I started feeling a bit that the import and export icons should not be on the "Folders" row (because it is not the folders that are to be imported or exported); instead right or left of the search form would be better. wdyt @bradleyrichter ?

**Comment by NejcZdovc** [comment]
@bradleyrichter icons are aligned, maybe it's an optical thing?

image

**Comment by NejcZdovc** [comment]
@luixxiul what about on the right side where you have add bookmark icon?

**Comment by bradleyrichter** [comment]
@luixxiul I think your suggestion is good. It's more hierarchically correct.

image

**Comment by NejcZdovc** [comment]
@bradleyrichter I like the new position. Move implemented. What do you think?

**Comment by luixxiul** [comment]
Looking good :+1:  except when you minimize the window:

screenshot 2017-02-03 14 21 23

I'd make an adjustment in a follow up task as that's a minor issue.

**Comment by bradleyrichter** [comment]
I think I'll have an icon revision soon but functionally it looks good.

**Comment by NejcZdovc** [comment]
If you will prepare them before the end of `0.13.3` milestone, I can add it in this PR, otherwise I would merge it and add it later.

**Comment by bsclifton** [comment]
[Most tests passed with CI](https://travis-ci.org/brave/browser-laptop/builds/197962239); those which didn't, I ran locally and verified they work. Feature is good to go! Merging

**Comment by StuartWilloughby** [comment]
This appears to have broken in 0.19.70. Clicking on Export does not generate a file.

**Pull request merged**
