### PR TITLE
Sorted the entire ledger before display.

### LINKED ISSUE #12119: Entire ledger should be sorted before display
### Description
Naturally (ex: just by using Brave), the transactions shown in History under Preferences > Payments will be in order. The newest transactions will be at the top and the older ones towards the bottom.  However, you can (for testing purposes) generate a fake history which would put things in the wrong order (this was fixed with https://github.com/brave/browser-laptop/pull/12118)

The original sorting fix was done by @josiah-keller when fixing https://github.com/brave/browser-laptop/issues/11300 and works great.  However, it has the following problems:
- it runs each time the view is shown
- it only sorts what is stored in `ledgerData.get('transactions')`. If the state has things out of order, this could potentially leave out entries.  Thanks to @NejcZdovc for sharing this logic in `getStateInfo`:
  https://github.com/brave/browser-laptop/blob/9da47f43e115281e30dc2452fe458e8fadff6a42/app/browser/api/ledger.js#L1333-L1335

  If the timestamp is older than a year, the for loop stops ☹️ 
  https://github.com/brave/browser-laptop/blob/9da47f43e115281e30dc2452fe458e8fadff6a42/app/browser/api/ledger.js#L1382

The ideal fix would:
- run one time
- sort on startup

The change could go here:
https://github.com/brave/browser-laptop/blob/9da47f43e115281e30dc2452fe458e8fadff6a42/app/browser/api/ledger.js#L1782

`parsedData` contains the raw JSON blob for the `ledger-state.json`, which includes all the transactions.  The sort that was done in https://github.com/brave/browser-laptop/pull/12118 could be done here too, before the call to `getStateInfo`

### Brave Version

**about:brave info:**

**Reproducible on current live release:**
yes- but only by hand-editing the `ledger-state.json`

### Additional Information

cc: @josiah-keller in case you wanted to give this one a shot 😄

### PR DESCRIPTION
**Pull request by sergiorojasa**
Fix #12119
@bsclifton 
Submitter Checklist:

- [X] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [X] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [X] Ran `git rebase -i` to squash commits (if needed).
- [X] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:
1. Simulate payment history: npm run add-simulated-payment-history 50
2. Build from source: npm run watch
3. Run the program: npm start
4. Check the order of payment history: Go to brave setting, under Payments, click on "Your Payment History" and check that the order is from newest to oldest.

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by sergiorojasa** [comment]
When I remove sorted function in from history.js the payment history display the payment from oldest the newest.

**Comment by bsclifton** [comment]
@sergiorojasa I didn't forget about you 😄  The holidays have been busy- apologies that I haven't got a chance to properly check this out again.  I'll try to finish the review today. Thanks for hanging in there! 😄

**Comment by bsclifton** [comment]
@sergiorojasa unfortunately this is showing an unknown repository- which means I can't cherry-pick the commit.  It looks like you may have deleted your fork and re-created it.  In the future, as long as you're working in a branch (in your fork), you shouldn't have to delete the fork 😄 

I manually tested the above and have adjusted it just a bit (also removing the older code).  I'll open a new PR with these changes

**Comment by bsclifton** [comment]
@sergiorojasa please check out my PR at https://github.com/brave/browser-laptop/pull/12448 which I've adjusted your logic just a little bit

**Comment by sergiorojasa** [comment]
Okay

**Pull request closed without merging**
