### PR TITLE
Fixed draggable areas of window.

### PR DESCRIPTION
**Pull request by bsclifton**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fixed draggable areas of window.
- parent item marks all as draggable
- child items exclude themself as needed
- parent level draggable is disregarded if modal is open, menu is open, etc (using shouldAllowWindowDrag)

Fixes https://github.com/brave/browser-laptop/issues/4235

Auditors: @bbondy

Here's a live demo on Windows 7
- red areas are draggable
- yellow areas are excluding themselves from this (marked as no-drag)
fix-drag-area

### CODE REVIEW

**Comment by bbondy** [comment]
can we ship the red/yellow? 😛

**Comment by bsclifton** [comment]
Still investigating why the min/max/close are not clickable when magnification is at 150%. I created a bare bones electron project to help understand why and have reproduced some drag issues
https://github.com/bsclifton/electron-quick-start

**Comment by bsclifton** [comment]
Opened an upstream issue https://github.com/electron/electron/issues/7347

Looking through the electron source now to collect more info and understand the root cause

**Comment by bsclifton** [comment]
This patch can be accepted as soon as https://github.com/brave/electron/pull/63 is merged! :smile: 

@bbondy - if you were able to review the electron change, apply it, and then re-test this patch you should be pleasantly surprised :smile:

**Comment by bbondy** [comment]
++

**Comment by alexwykoff** [comment]
Note for QA: Be sure to check cursor-in-address bar vs not. These two different modes may have results you did not expect : 
drag_test

**Pull request merged**
