### PR TITLE
Update Aphrodite to 1.2.3

### LINKED ISSUE #10062: Update aphrodite to 1.2.4
## Test plan
https://github.com/brave/browser-laptop/issues/10234
1. Make sure the issue reported on #10029 does not happen again

----

See https://github.com/Khan/aphrodite/blob/master/CHANGELOG.md for changelog

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #10062
Unblock #9851

Auditors:

Test Plan:
1. Make sure the issue reported on #10029 does not happen again

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

CC @jonathansampson @cezaraugusto

### CODE REVIEW

**Comment by luixxiul** [comment]
I'm going to add a comment as a reminder for https://github.com/brave/browser-laptop/issues/10029

**Comment by cezaraugusto** [comment]
looks good but we still rely on some code for `classLIst` so I'll mark this as blocked until they're done, doing that now.

**Comment by luixxiul** [comment]
@cezaraugusto sweet, thanks! I think it would be great if the automated test/lint to detect that classList is used somewhere is set up. Is it possible?

**Comment by bsclifton** [comment]
Closing as this is old and there may be other work needed before we can accept

**Comment by cezaraugusto** [comment]
fyi blocking issue is #10551

**Pull request closed without merging**
