### PR TITLE
0.24.x (Chromium 69)

### PR DESCRIPTION
**Pull request by bsclifton**
Currently a work in progress; this has all the feature work for the following milestone:
https://github.com/brave/browser-laptop/milestone/125

Don't merge until QA approved 😄

### CODE REVIEW

**Comment by kjozwiak** [comment]
@bsclifton QA finished going through the following manual passes:

* Manual test run on OS X for 0.23.x w/ Chromium 69 (Release Channel) [#15205](https://github.com/brave/browser-laptop/issues/15205)
* Manual test run on Windows x64 for 0.23.x w/ Chromium 69 (Release Channel) [#15206](https://github.com/brave/browser-laptop/issues/15206)
* Manual test run on Linux for 0.23.x w/ Chromium 69 (Release Channel) [#15207](https://github.com/brave/browser-laptop/issues/15207)

QA has spot checked [`0.24.0`](https://github.com/brave/browser-laptop/releases/tag/v0.24.0dev) and didn't find any issues. I guess we can wait till tomorrow afternoon to see if anyone else finds any issues during the dog fooding period.

**Comment by GeetaSarvadnya** [comment]
Performed high level testing on all the functionalities for 0.24.0, did not find any major issues. Windows looks good.

**Comment by LaurenWags** [comment]
spot checks on macOS looked good - no new issues found.

**Comment by btlechowski** [comment]
Spot checked Linux. LGTM.

**Pull request merged**
