### PR TITLE
Revert "Merge pull request #13504 from jasonrsadler/gen-backup-remind"

### PR DESCRIPTION
**Pull request by bsclifton**
Revert https://github.com/brave/browser-laptop/pull/13504 in **master only**

***Already reverted in 0.22.x-release3 and 0.23.x (see https://github.com/brave/browser-laptop/pull/13504#issuecomment-389268717)***

Auditors: @jasonrsadler

### CODE REVIEW

**Comment by bsclifton** [comment]
looks like there are a problem with unit tests on master

Reverting this worked fine (lint / unit tests passed) on 0.22.x-release3 and 0.23.x. When I run `npm run unittest` on master, I'm getting the same 10 failures as above. Will need to look at recent PRs to find root cause

**Comment by NejcZdovc** [comment]
@bsclifton this PR is a problem https://github.com/brave/browser-laptop/pull/14073

**Comment by jasonrsadler** [comment]
@davidtemkin and @mandar-brave are good to undo revert

**Comment by bsclifton** [comment]
Closing as (after discussion) we'd like to keep this feature

**Pull request closed without merging**
