### PR TITLE
Remove contribution range from PDF statement

### LINKED ISSUE #6896: remove redundant dateline in contributions PDF
here is what we have now:

the last line was intended to give a timeframe, but is redundant, so remove it!

### PR DESCRIPTION
**Pull request by mrose17**
Fixes #6896

Auditor: @bsclifton 

Test Plan:
1. Generate a PDF contribution statement
2. Verify that the contribution range you see here as the last line isn't there any more.
729d24fa-e49a-11e6-8b9f-a831ba1ff6e0

### CODE REVIEW

**Comment by willy-b** [comment]
note: this does give a range if the current contribution is not your first one (then it is not redundant)

**Comment by NejcZdovc** [comment]
Maybe keep it and only display it when range is available?

**Comment by mrose17** [comment]
@NejcZdovc - you've convinced me. i'm going to withdraw this issue and the PR. could you make the line more useful? i'm also not really keen on the design placement either, but that's another matter!

**Comment by NejcZdovc** [comment]
@mrose17 @willy-b can you tackle this?

**Comment by willy-b** [comment]
@NejcZdovc sure, happy to!

**Comment by willy-b** [comment]
@mrose17 , I fixed this as per @nejczdovc's suggestion (https://github.com/willy-b/browser-laptop/commit/a510c87d1598b6e75043bf2924e36643355e4e7e).

Example: Two consecutive statements
-  where 1st has no date range (since 1st payment):
statementpdf_norange

- 2nd does have a date range (begins with date of last statement):
statementpdf_yesrange


should I open a new PR against #6896?

**Comment by willy-b** [comment]
note: @mrose17 responded to my question in a comment on my commit  (https://github.com/willy-b/browser-laptop/commit/a510c87d1598b6e75043bf2924e36643355e4e7e#commitcomment-20667505):
"thanks! go ahead and submit an issue/PR for this fix and we should be good."

so, opening a separate PR

**Pull request closed without merging**
