### PR TITLE
Flashing favicon fix

### LINKED ISSUE #13487: Taco Bell favicon flashes on mouseover
### Description
Introduced with #12565. Haven't been able to reproduce on any other sites apart from tacobell.com.
Thanks for the find @bsclifton 

### Steps to Reproduce

  1. Have a tab with tacobell.com's favicon
  2. Mouse over tab

**Actual result:**

  3. Icon flashes on and off

**Expected result:**
Icon remains visible

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

No

### PR DESCRIPTION
**Pull request by jayyyin**
Resolves #13487

This appears to have fixed the issue, let me know if this may cause issues down the line.

fixed bug 13487

### CODE REVIEW

**Comment by jayyyin** [comment]
realized that this fix breaks the gradient affect for all tabs... looking for a better solution.

**Comment by jayyyin** [comment]
to reiterate what I wrote on the issue,

"I found that the cache-control for the headers of those files contain the 'no-cache' tag, I'm currently looking into how this could be handled, but this issue was in chromium at some point it seems but I can't seem to find how it was handled code wise, I'm having some trouble navigating the structure of the code to find where the code to download the favicons are, some help would be appreciated"

**Comment by bsclifton** [comment]
Closing as stale - additional work needed to fix this without regressing the styles. Please do feel free to reopen if you look at this again, @jayyyin 😄

**Comment by jayyyin** [comment]
@bsclifton yah, sorry if I've been off the grid for a while, recently got a full time job, been keeping me busy so far, I will return to this in the near future when I'm back to being a student.

**Pull request closed without merging**
