### PR TITLE
Allow adblock checking within the same origin

### LINKED ISSUE #11004: Allow adblock checking within the same origin
Currently we only do same origin adblock checks for a couple websites.  We should be doing it for all sites for the best blocking results.

### PR DESCRIPTION
**Pull request by bbondy**
Fix #11004

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bbondy** [comment]
pls hold on reviewing, just adding some tests in another commit first.

**Comment by bbondy** [comment]
OK good to go.

**Comment by bbondy** [comment]
Mentioned on Slack but this isn't meant to review all filtering list rules.  Some won't work like the example you gave but it works the same as uBlock and other adblockers.  We should fix cases like this, if we care about them in our maintained lists on github.com/brave/adblock-lists

**Comment by diracdeltas** [comment]
@bbondy noted. in #1353 i asked whether this was an issue that should be fixed in the adblock module and you mentioned (https://github.com/brave/browser-laptop/issues/1353#issuecomment-209698848) that we should add a check for first-partiness in app/adblock.js. so this appeared to be a regression

**Comment by bbondy** [comment]
Yep but things change in a year and a half. 

We don't have the same adblock library we had back then, we now have lists we maintain which we didn't then, and also we were consciously trying to not block first party things then. I'm going to re-open that one and fix with an adblock definition update.

**Pull request merged**
