### PR TITLE
added option to disable the block count badge

### LINKED ISSUE #8613: Option to disable blocked count badge (on Lion)
Kindly add an option to disable the badge.

### PR DESCRIPTION
**Pull request by kumarrishav**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

Fixes #8613

Test Plan: Screen shot attached

**Enabled by default**
screen shot 2017-05-05 at 1 50 05 am

**Counter can be seen on lion icon**
screen shot 2017-05-05 at 1 50 22 am

**After disabling**
screen shot 2017-05-05 at 1 50 35 am

**No counter anymore on lion icon**
screen shot 2017-05-05 at 1 50 46 am

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@kumarrishav can you please add closing keyword in your commit?

**Comment by kumarrishav** [comment]
@NejcZdovc Sorry, but i didn't get this:  add closing keyword in your commit? did you mean , 'Add fix #8613'  in commit?

**Comment by NejcZdovc** [comment]
@kumarrishav not a problem. Commit message should look like this:
https://github.com/brave/browser-laptop/pull/8658/commits/c2a12260b7f6ff966195650860b36f6c4a54a85b

First title/description, then a issue that is resolved with this PR, then auditors and then test plan.

**Comment by kumarrishav** [comment]
Thanks @NejcZdovc

**Comment by NejcZdovc** [comment]
perfect, thank you

**Comment by NejcZdovc** [comment]
@kumarrishav sorry for a little confusion, but we didn't specify the position correctly. Can you please do it like this:

image

Also this setting shouldn't be part of bravery settings, but part of general settings. Here is the example of the implementation: https://github.com/brave/browser-laptop/blob/master/js/about/preferences.js#L196

Sorry again and thank you for this PR

**Comment by kumarrishav** [comment]
Oh okay. Sure.  Thanks @NejcZdovc for providing mocks. Removing review request for now.

**Comment by bradleyrichter** [comment]
Thanks @kumarrishav !

**Comment by kumarrishav** [comment]
Updated as per Mock provided. @NejcZdovc @bradleyrichter @bsclifton review?
screen shot 2017-05-05 at 3 24 17 am

**Pull request merged**
