### PR TITLE
add transition polishment for switch buttons

### PR DESCRIPTION
**Pull request by cezaraugusto**
switchbtnanimatedtoggle

Auditors: @jkup 

/cc @bradleyrichter 

Test Plan:

* enable/disable any switch button
* notice that switch indicator moves smoothly

### CODE REVIEW

**Comment by jkup** [comment]
Code LGTM. Good to ship as long as @bradleyrichter approves the animation time (feels a bit slow to me!)

**Comment by bbondy** [comment]
I think the animation time is a bit slow too

**Comment by bradleyrichter** [comment]
Time should be barely noticeable.

**Comment by cezaraugusto** [comment]
ok thanks all for the feedback. I'll reduce from 400ms to 200ms as it's the common number for most transitions.

**Comment by cezaraugusto** [comment]
Updated to 100ms, ready for review

**Comment by bbondy** [comment]
++

**Comment by bbondy** [comment]
Please add an issue though and link it up in the commit.

**Pull request merged**
