### PR TITLE
use location because src is not always updated

### PR DESCRIPTION
**Pull request by bridiver**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

partial fix for #2473

check for test errors before merging
@bbondy @diracdeltas

### CODE REVIEW

**Comment by bbondy** [comment]
I think there's a good chance this could cause some regressions, can we wait until after 0.11.1 release to merge in?

**Comment by diracdeltas** [comment]
this does seem to cause a bunch of test errors

**Comment by diracdeltas** [comment]
pages don't load for me at all with this change

**Comment by bridiver** [comment]
yep, I was actually going to update this because I realized I missed a few things

**Comment by bbondy** [comment]
sorry this bitrot since before, if we should still add this please update the PR.

**Pull request closed without merging**
