### PR TITLE
Add support for 32 bit linux builds

### PR DESCRIPTION
**Pull request by posix4e**
This is will change the name of our deb packages to have x64 instead of amd64. Do we care? RPMs will also be x64 instead of x86_64. Happy to keep it as is if we prefer

### CODE REVIEW

**Comment by Liunkae** [comment]
Fixes #2468.

**Comment by bsclifton** [comment]
IIRC, someone had made a PR to specifically have RPMs have x86_64 (which I think is the arch for 64 bit on Red Hat OSes)... let me check

**Comment by bsclifton** [comment]
Here we go :smile: 

@posix4e what do you think? (see notes)
https://github.com/brave/browser-laptop/pull/4723

**Comment by posix4e** [comment]
I think this is pretty much all good on chrome54? Good to target muon?

**Comment by luixxiul** [comment]
So did the 32 bit build become available already?

**Comment by bsclifton** [comment]
cc @posix4e

**Comment by posix4e** [comment]
Soon!

**Pull request closed without merging**
