### PR TITLE
new Brave button hover states

### LINKED ISSUE #5528: add code for new Brave button hover states
current brave button has a darken filter for it's hover state

new button icons include shadow and glow for hover indication

image

files:

bravebtn_hover
bravebtn2x_hover
bravebtn3x_hover

### PR DESCRIPTION
**Pull request by jkup**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fix #5528

Test Plan:

Hover over the Brave lion in the top right corner and make sure it looks like the GIF below.

@bradleyrichter this is what it looks like now. is this right?

lion

### CODE REVIEW

**Comment by bbondy** [comment]
Assuming this doesn't cause a problem without it on 0.12.9 I'm moving this to 0.12.10.
@bradleyrichter this is waiting on your feedback pls.

**Comment by bradleyrichter** [comment]
I think this is missing the new images I committed yesterday? And the grey effect should be removed.

**Comment by bradleyrichter** [comment]
New pngs Commit number: 881b722

**Comment by bbondy** [comment]
This needs rebasing pls

**Comment by jkup** [comment]
@bbondy rebased!

@bradleyrichter I see, I started on this ticket without knowing you needed to add some more assets. Is it looking right now? (see GIF above)

**Comment by bradleyrichter** [comment]
@jkup It looks correct but now we can remove the dark filter in the CSS.

**Comment by bsclifton** [comment]
I like it! :lion:

**Comment by jkup** [comment]
@bradleyrichter @bsclifton I removed the dark filter but now I can hardly tell the difference between the two images. I updated the GIF in the description. Should we just go ahead and ship for now?

**Comment by bradleyrichter** [comment]
@jkup perfect. Now I can modify the hover image and get it working perfectly through the magic of pixels.  ;   )

Merge it into master and I'll hot-fix the PNG file.

**Pull request merged**
