### PR TITLE
Resolve package.json engine.node version conflicts

### LINKED ISSUE #5616: Dependencies have conflicting engine.node versions
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:**
ledger-balance, ledger-client, ledger-geoip, and ledger-publisher specify engine.node versions == 5.6.0, whereas browser-laptop is node >= 6.1.0.

This prevents yarn install which fails on conflicting dependencies.

**Expected behavior:**
The engine.node versions of the libraries and browser-laptop should agree.

- Platform (Win7, 8, 10? macOS? Linux distro?): Mac OS

- Brave Version: 0.12.9 dev rc1 / a65761f6fb07ff018841323814d5b327867a0593

### PR DESCRIPTION
**Pull request by ayumi**
Fix #5616

No functional changes.

Auditors: @bbondy @mrose17

Test Plan:
1. `rm -rf node_modules`
2. `rm -rf ~/.electron/`
3. `npm install`
4. Confirm browser works.

Test Plan (yarn):
1. `rm -rf node_modules`
2. `rm -rf ~/.electron/`
3. `yarn cache clean`
4. `yarn install`
5. Confirm browser works.

### CODE REVIEW

**Comment by mrose17** [comment]
works great for yarn 0.16.1, but fails on electron fetch for yarn 0.17.0

        error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/Users/ayu/Library/Caches/Yarn/npm-electron-download-2.1.3-5aba4ea1c4e7d8c033233f5c0187746eb3b0a7b6'".

**Comment by ayumi** [comment]
`yarn install` does seem to be broken on 0.17.0 (relevant issue? https://github.com/yarnpkg/yarn/issues/1725). However this commit is a step forward because it fixes the node.engine conflict so I think it's legit.

**Comment by mrose17** [comment]
i suggest: add something to the README about using `yarn 0.16.1` and then commit.

**Comment by ayumi** [comment]
@mrose17 good idea

**Comment by ayumi** [comment]
yarn 0.17.6 works to install dependencies for me now.

**Comment by mrose17** [comment]
great!

**Pull request merged**
