### PR TITLE
check existence of suggestions

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

STR:
1. browse an arbitrary site
2. click url bar and press arrow down
3. There will be an empty `suggestions`

### CODE REVIEW

**Comment by bbondy** [comment]
It took me a bit to figure out but I think this is to get rid of a console error right?
Looks great, thanks!

**Comment by darkdh** [comment]
Yes, it's for console error.

**Comment by luixxiul** [comment]
@bbondy will this be included 0.11.1?

**Comment by bbondy** [comment]
I don't think it blocks anything critical, but if we respin we'll include it. I think we're likely to respin, so probably. I'll mark the milestone for now.

**Comment by bbondy** [comment]
yep it's merged now.

**Pull request merged**
