### PR TITLE
In nav bar bookmarked star, check only the specific siteKey

### LINKED ISSUE #8703: URL bar, on every keystroke the browser re-checks if the current location is bookmarked
With 10,000 bookmarks, this adds 80ms to every keystroke.

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Instrument `siteUtil.isSiteBookmarked()` by adding to the beginning `const startTime = new Date().getTime()` and to the end console.log(`isSiteBookmarked() ${new Date().getTime() - startTime}`).
    2. Start a new profile and import 10,000 bookmarks.
    3. Type in the URL bar and observe logs.
    
- Actual result:
2 calls for 40 ms / keystroke

- Expected result:
No calls. (It should only check if the location changes.)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. The "forsaken" sync group has a lot of bookmarks. It might help you if you're testing.

- Any related issues:
#7453

### PR DESCRIPTION
**Pull request by ayumi**
Fix #8703

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

### CODE REVIEW

**Comment by ayumi** [comment]
@bsclifton @darkdh hmm so this is almost good! except it doesn't work when you bookmark into a folder (because folderId is part of siteKey)

**Comment by NejcZdovc** [comment]
@ayumi what is the status on this one?

**Comment by ayumi** [comment]
@NejcZdovc Just working on tests

**Comment by ayumi** [comment]
@NejcZdovc closing in favor of #8894

**Pull request closed without merging**
