### PR TITLE
Changed Contact info in about:safebrowsing

### LINKED ISSUE #6781: Change contact info on about:safebrowsing
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
about:safebrowsing still shows as support+laptop@brave.com as contact. Since support is moved to community.brave.com, this should be changed.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
All

- Screenshot if needed:
image

- Any related issues:

### PR DESCRIPTION
**Pull request by iamVP7**
Instead of sharing mail id, added community website link where people can collect the website that need not be blcoked

Fix #6781

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

### CODE REVIEW

**Comment by alexwykoff** [comment]
As @luixxiul mentioned in https://github.com/brave/browser-laptop/issues/6781#issuecomment-277782803, site-feedback is feedback about the community proper.  I will create a new category related to site blocking and will comment again with the url.

**Comment by alexwykoff** [comment]
https://community.brave.com/c/site-blocking created, please add a commit with this update and we should be good to go

**Comment by Liunkae** [comment]
@iamVP7 Please squash the commits, and we'll be ready to merge!

**Comment by bbondy** [comment]
++

Thanks @iamVP7 and @alexwykoff. By the way you can do this at merge time:
screenshot 2017-02-15 20 01 36

Not always, but only when having the extra commits doesn't have value.

**Pull request merged**
