### PR TITLE
Icon SVG updates and very small padding tweaks

### PR DESCRIPTION
**Pull request by rossmoody**
- Updated navigationBar icon sizing and svg code
- Updated Browser window icons (bookmarks, history, settings)
- Preferences page icon and styling tweaks

### CODE REVIEW

**Comment by rossmoody** [comment]
@petemill @bradleyrichter Branch for general icon polish excluding some of the latest reverts to the shields functionality.

**Comment by BrendanEich** [comment]
BTW the block count removal makes this more than an icon SVG change.

**Comment by bbondy** [comment]
So I see from the above this is being merged into brave:feature/icon-style-refresh-1 which has other changes like count removal explicitly . https://github.com/brave/browser-laptop/commit/2f3dc5deee22aec6f15c5366be7fe80c5a8e3b63 .

**Comment by rossmoody** [comment]
Yeah, this PR is meant to serve only as sizing adjustments and styling updates for icons already in the place. The shield changes (which I actually arrived to the team right in the middle of) will be flushed out very early this week with Brave logo and block counter intact.

**Comment by petemill** [comment]
Just to confirm the style and icon changes are WIP, and do not yet have a PR, though targeted at 0.23. This PR is simply some tweaks and do not contain shield icon or any direction has-blocked-something state change. The overall issue for the window style changes is at #13981

**Comment by bradleyrichter** [comment]
And this branch has been a playground that Pete creates one-off test builds from. We cherry pick into main branches when they are approved and ready.

Shields lion revert was put on revert-status on Wednesday May 23 through slack-internal.

**Pull request merged**
