### PR TITLE
Move NoScript icon into URL bar. This fixes draggability dead area

### PR DESCRIPTION
**Pull request by bsclifton**
## Test plan

1. Make sure the non-draggable area specified in #5792 is draggable
2. Make sure every button on the navigation bar is clickable
3. Open https://jsfiddle.net/
4. Block scripts from the top right lion icon
5. Make sure the noScript button on the navigation bar is clickable

## Description

Fixes https://github.com/brave/browser-laptop/issues/5792

Auditors: @bradleyrichter, @luixxiul

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

screen shot 2017-04-11 at 11 51 08 am

### CODE REVIEW

**Comment by Jacalz** [comment]
This looks great, have nerver liked the no scrip icon 👍 Great job 👍

**Comment by Jacalz** [comment]
Will add this to my test for the next version of 0.14.2 👍

**Comment by bsclifton** [comment]
Great catch, @luixxiul!  I just pushed a fix, can you try it?

**Comment by diracdeltas** [comment]
some noscript info tests are failing: https://travis-ci.org/brave/browser-laptop/jobs/221100103#L4839

**Comment by bsclifton** [comment]
@diracdeltas good catch! 😄  Thanks- will check those out

**Comment by bsclifton** [comment]
[NoScript tests passed](https://travis-ci.org/brave/browser-laptop/jobs/221112464)- merging!

**Pull request merged**
