### PR TITLE
Fixes deprecated prop types

### LINKED ISSUE #8152: React prop-types
**Describe the issue you encountered:**
Based on https://facebook.github.io/react/docs/typechecking-with-proptypes.html, we need to add external prop-types library.

We are getting this error now:
` "Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead."`

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

Resolves #8152

Auditors: @bsclifton @bbondy

### CODE REVIEW

**Comment by bbondy** [comment]
Could you rebase this? Thanks!

**Comment by bbondy** [comment]
I'd be ok even just removing prop types in favour of future work with flow. Happy to accept this conversion PR though either way once rebased.

**Comment by NejcZdovc** [comment]
@bbondy let's leave this types for now and when we move to flow, we can remove it. Created an issue to track this #8168

**Comment by NejcZdovc** [comment]
@bbondy rebased

**Pull request merged**
