### PR TITLE
Computed theme color

### PR DESCRIPTION
**Pull request by bbondy**
Going to merge all of this, but @diracdeltas please review when you get a chance.

### CODE REVIEW

**Comment by diracdeltas** [comment]
lgtm

**Comment by diracdeltas** [comment]
this is showing different colors for my two gmail tabs
screen shot 2016-02-09 at 2 11 04 pm
screen shot 2016-02-09 at 2 10 57 pm

**Comment by bbondy** [comment]
beige/yellow color present at all towards the top -- left, middle or right?
Does page have a theme color meta tag?
Reproducible ?

**Comment by diracdeltas** [comment]
the yellow is from the gmail "loading" status bar at the top middle, which
appears for a second and then goes away. i'm guessing the color is getting
set during the interval where the bar is visible.

**Comment by bbondy** [comment]
We could perhaps keep a list of overrides for tab color per host. Thoughts?

**Comment by diracdeltas** [comment]
That could work. Curious why we got rid of Vibrant; i generally liked those colors better

**Comment by bbondy** [comment]
Vibrant uses a lot of CPU, selected wrong colors sometimes and caused some pages to crash the renderer process which there is no easy fix to, see:
https://github.com/brave/browser-laptop/issues/657
https://github.com/brave/browser-laptop/issues/600

See my note about context.drawImage.

**Pull request merged**
