### PR TITLE
List needed dependancies

### PR DESCRIPTION
**Pull request by PFCKrutonium**
For building, you know?

### CODE REVIEW

**Comment by bbondy** [comment]
Thanks for the pull request. 

- What does it fail on if you don't have Python? We aren't using it explicitly anywhere that I know of.
- I don't believe NSIS is a dependency anymore, there is some outdated info about an old installer we had in the README mentioning it but is being removed in a pull request I did earlier today. 
- Please add a new docs/prerequisites.md and link to it from the readme instead.

**Comment by PFCKrutonium** [comment]
If you build without python, sqlite3 fails to compile.

I will remove the NSIS Link

Will do.

**Comment by bbondy** [comment]
Thanks! btw you could also make changes, `git add -u`, `git commit --amend`, and then `git push -f` into your branch and it'll auto update the pull request.
Thanks again for doing this and for the follow up changes.

**Comment by PFCKrutonium** [comment]
TBH I have no idea how to, I did this all online via the website. I'm going to do it all properly via normal git and make a new PR for my own sake.

**Comment by bbondy** [comment]
that works too, thanks!

**Comment by PFCKrutonium** [comment]
@bbondy Question, should I set up the file to easily document reqs for Linux/OS X? Also, does it compile on Linux/OS X yet?

**Comment by bbondy** [comment]
Yes but we can put it all in the same doc under subsections

docs/prerequisites.md

```
# Prerequisites

## Windows

...
```

We can fill in other platforms over time.

**Pull request closed without merging**
