### PR TITLE
Fixes recovery seed when you recover wallet with funds

### LINKED ISSUE #12672: restarting the browsers corrupts the seed of recovered wallets
### Description

Restarting the browser when you have a recovered wallet will corrupt the backup seed, which will appear as `a` in the UI. Example:

screen shot 2018-01-16 at 7 19 08 pm

When attempting to contribute/reconcile in this state, the user will receive the following error:

```
ledger client error(1): {}
Error: HTTP response 422 for PUT /v2/wallet/bf72fae7-2e44-41ad-9b24-fea34177ce09
  at request.request (C:\Users\kamil\AppData\Local\brave\app-0.19.131\resources\app.asar\app\browser\api\ledger.js:1318:9)
  at Function.defaultSession.webRequest.fetch (C:\Users\kamil\AppData\Local\brave\app-0.19.131\resources\app.asar\js\lib\request.js:55:5)
```

### Steps to Reproduce

**_Note: This can be reproduced on `Production` as well._**

  1. launch brave using `LEDGER_ENVIRONMENT=staging LEDGER_VERBOSE=true brave`
  2. enable payments via `about:preferences#payments`
  3. recover wallet via `Advanced Settings`
  4. close brave
  5. `vim ledger-state.json` and you'll notice that the seed is appearing correctly within the file
  6. relaunch brave using `LEDGER_ENVIRONMENT=staging LEDGER_VERBOSE=true brave`
  7. go into `about:preferences#payments` and check the backup code (it will appear as `a`)
  8. `vim ledger-state.json` and you'll notice the following

```
"keyinfo": {
   "seed": {
    "0": 0,
     "1": 0
  }
```

**_Other useful information:_**

When you get into the above state, you can fix it by going through the following:

* remove `ledger-state.json`
* relaunch brave and restore the wallet using the same recovery key
* close brave
* relaunch brace once again and this time around, the keys will stick and will appear correctly

I'm not sure why removing `ledger-state.json` and requiring a second restore fixes the issue.

**Actual result:**

recoveryissue

**Expected result:**

Restarting the browser shouldn't corrupt the seed on restored wallets.

**Reproduces how often:**

100% reproducible using the STR mentioned above.

### Brave Version

**about:brave info:**

> Brave: 0.19.136 - Reproducible 
> rev: 1659471cf1b1016568f63a6ab3e35b604d7e3db3 
> Muon: 4.7.1 
> libchromiumcontent: 64.0.3282.85 

**Reproducible on current live release:**

Yes, currently reproduced `0.19.134` which is the current release:

> Brave: 0.19.134 - Reproducible 
> rev: 316cfa522ffe6a558fe9f2f3f299c0c602dfb691 
> Muon: 4.5.38 
> libchromiumcontent: 63.0.3239.132 

### Additional Information

* macOS 10.13.2 x64 - Reproduced (reproduced by @LaurenWags as well)
* Ubuntu 17.10 x64 - Reproduced

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

Resolves #12672

Auditors:

Test Plan: defined in #12672

Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by kjozwiak** [comment]
It seems like I'm having issues importing keys via `.txt` files under Ubuntu. When attempting to import a wallet via a recovery file, I keep receiving `Recovery Failed: Please re-enter keys or try different keys`. However, importing the same key under macOS works without any issues. I've tried several other keys and ran into the same thing. However, pasting the same exact key will recover without any issues.

**_STR:_**

* before launching, `rm -rf ~/.config/brave-development/`
* launch brave via `LEDGER_VERBOSE=true LEDGER_ENVIRONMENT=staging npm start`
* enable payments via `about:preferences#payments`
* once enabled, attempt to restore the staging wallet using the `qa.txt` (should fail)
* rather than recovering using the file, recover via copy/paste (this should work correctly)

If you go through the STR above on macOS, recovering via `qa.txt` works without issues.

Staging Wallet Used: [qa.txt](https://github.com/brave/browser-laptop/files/1640343/qa.txt)

_**Example:**_

recvoryprfail

_I went through the following test cases on both macOS & Linux:_

* recovered several keys via copy/paste and restarted the browser a few times
* checked `ledger-state.json` and ensured that the seed is intact every time the browser is restarded
* recovered several keys via importing `.txt` recovery file (doesn't seem to be working under Ubuntu)
* Contributed/Reconciled and ensured I didn't receive any `422` errors which were usually because of the seed being corrupted.

@bsclifton @NejcZdovc please take a look. Let me know if you need anymore information... I was using the following PR for both macOS/Ubuntu:

```
kjozwiak@kjozwiak-VM:~/projects/browser-laptop$ git log -1
commit d1a97345877fc3e6a409492bc20dd40f60927af8 (HEAD -> recoveryKeyCorruption)
Author: NejcZdovc <nejc.zdovc@3zsistemi.si>
Date:   Wed Jan 17 07:56:51 2018 +0100

    Fixes recovery seed when you recover wallet with funds
    
    Resolves #12672
    
    Auditors:
    
    Test Plan:
```

**Comment by kjozwiak** [comment]
Looks like it's working correctly under `0.19.134` (current release) & `0.19.137` (current C64 preview). Seems like this is related to the PR.

**Comment by bsclifton** [comment]
master 6cb43036844d62ea8cc8c3c068eaab5794e710a7
0.21.x f4f8fcf9edccee2a189feb7b94465884bb5b9f34
0.20.x 604100100577c6bd853cfd2d883af4c3145bb801
0.19.x @NejcZdovc can you help me merge into 0.19.x?

**Comment by NejcZdovc** [comment]
@kjozwiak tried on the latest master (before merge) and it's broken as well. Will create another issue just for this.

@bsclifton merged fbbfbe013f9fe8113a93dae7545c83477f74b4c5

**Pull request merged**
