### PR TITLE
Adding script to push back reconcileStamp

### PR DESCRIPTION
**Pull request by ryanml**
## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:

1. Run Brave with a fresh profile using: `LEDGER_ENVIRONMENT=staging LEDGER_NO_FUZZING=true LEDGER_NO_DELAY=true npm start`
2. Note the current contribution date in `about:preferences#payments`
3. Add a few publishers to the synopsis
4. Close Brave
5. Run `npm push-back-next-reconcile-stamp`
6. Restart Brave with the command in step 1. Ensure that the contribution is overdue and attempts to Process.
7. Repeat steps 1 - 4.
8. Run `npm push-back-next-reconcile-stamp numWeeks` (Where numWeeks is a single integer, such as 3. This best left under 4 so that the new contribution date can be noted without pushing it to overdue)
9. Confirm that the contribution date matches as expected (Ex: Was July 21st, ran with numWeeks as 2, is now July 7th)

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by srirambv** [comment]
@ryanml  `npm run push-back-reconcile-stamp numWeeks` just pushes the date back but doesn't trigger reconcile?

**Comment by jasonrsadler** [comment]
@srirambv Did you have `npm start/watch` running? The running state will take precedence and overwrite on exit.

**Comment by srirambv** [comment]
@jasonrsadler yes I had `npm run watch` in one window and then on second window `npm run push-back-reconcile-stamp 2` . It just pushed back the date but didn't trigger immediate reconcile.

**Comment by jasonrsadler** [comment]
And then afterwards you did `npm start` with all the no_fuzzing, staging, no_delay, etc?

**Comment by srirambv** [comment]
Here's the recording on a clean profile.

**Comment by ryanml** [comment]
@srirambv thanks for providing.

When you pass a specific number of weeks with the expectation that reconcile is triggered, it should be enough weeks in the past that the stamp is behind the current date.

Given that the new date in your example (July 26th) hasn't happened yet there won't be a reconcile.

To confirm the custom weeks arg works, try passing in at least `4`

**Comment by jasonrsadler** [comment]
^ this.

It hasn't pushed reconcileStamp back far enough.

**Comment by srirambv** [comment]
ah my bad. The pushback date is still ahead of current date which is why it didn't trigger reconcile. But shouldn't pushback date push it back to number of weeks from current date?

**Comment by ryanml** [comment]
I guess this is where my vocab comes in to play :) 

I see pushing "back" as going "back" in time

If we supremely dislike this I can change to `push-forward`

**Comment by srirambv** [comment]
We could say `push-back-next-reconcile-stamp` 😃

**Comment by ryanml** [comment]
@srirambv changed to `push-back-next-reconcile-stamp` :D thanks for the suggestion

**Comment by bsclifton** [comment]
Closing as stale since there hasn't been any action on this. It would be awesome (with brave-core) to look at creating helper scripts for Brave Rewards (populating with random data, etc)

**Pull request closed without merging**
