### PR TITLE
Alphabetize locale.js

### LINKED ISSUE #12061: Alphabetize locale.js
### Description

Alphabetize `locale.js`.

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #12061

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bsclifton** [comment]
@luixxiul this one has nice intentions, but please keep in mind that this type of change can cause a lot of problems with rebasing and cherry-picking.  Any change to this file in a branch will have to manually resolve this conflict- same with cherry-picking to older branches (0.21.x, 0.20.x, 0.19.x)

**Comment by luixxiul** [comment]
I'd agree- should I close this PR for now?

**Comment by bsclifton** [comment]
@luixxiul Up to you- I definitely don't want to discourage cleanup 😄  There are two options I think (and I'm good with either one)
1. Squash this PR up to one commit and then prepare a similar PR for 0.19.x, 0.20.x, and 0.21.x also (so that any change going forward is organized) 😄  
2. Close this PR and the issue for now

**Comment by luixxiul** [comment]
OK, so I'm going to close this PR until 0.19.x is frozen 👍

**Comment by NejcZdovc** [comment]
@luixxiul I would wait until 0.20 is released, because 0.21 and 0.22 should be smaller and we will release it faster now (hope so)

**Comment by luixxiul** [comment]
> I would wait until 0.20 is released

Ah right, that's the one I was talking about 😊

**Pull request closed without merging**
