### PR TITLE
Return 0% when download totalBytes is 0 or undefined

### PR DESCRIPTION
**Pull request by diracdeltas**
Fix https://github.com/brave/browser-laptop/issues/10264

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:
Download a large file and hit 'pause' immediately. It should not show Infinity% downloaded.

Reviewer Checklist:

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

**Comment by bbondy** [comment]
++

**Comment by bbondy** [comment]
Actually I think we didn't used to show anything at all. Will this show 0% always for downloads that don't specify a content length in the reply?

**Comment by diracdeltas** [comment]
@bbondy i think it would have shown NaN% or Infinity% previously

**Comment by bbondy** [comment]
I mean originally we didn't show anything at all. There is a case where there is no known % because we don't know the content length being downloaded. For example if that happens with a 3GB file we shouldn't show 0% the whole time it is downloading.  Do you know if that will happen?

**Comment by diracdeltas** [comment]
@bbondy pretty sure that is unaffected by this PR. looks like that check happens in app/renderer/components/download/downloadItem.js using totalBytes

**Pull request merged**
