### PR TITLE
Delete genericForm and commonDialog from forms.less

### LINKED ISSUE #8010: Discard .genericForm and .commonForm from forms.less
**Describe the issue you encountered:**
Discard `.genericForm`. See: https://github.com/brave/browser-laptop/issues/8009#issue-218569501

> Currently there are only three other instances where .genericForm is applied (autofillAddressPanel.js, autofillCreditCardPanel.js, and addEditBookmarkHanger.js), and in every case styles which genericForm defines are overwritten by what commonForm is going to do so (title color, padding inside the dialog, etc). Keeping both of them is a cause of style inconsistency.

- [x] loginRequired.js (#8009) - merged to `refactoring-aphrodite` with #8011
- [x] autofillAddressPanel.js (#8099) - merged to `refactoring-aphrodite` with #8105
- [x] autofillCreditCardPanel.js (#8100) - merged to `refactoring-aphrodite` with #8105
- [x] addEditBookmarkHanger.js (#6040) - merged to `refactoring-aphrodite` with #8136

Also remove `.commonForm` from form.less (as it was already refactored into the aphrodite component).

- [x] autofillAddressPanel.js (#8099) - merged to `refactoring-aphrodite` with #8105
- [x] autofillCreditCardPanel.js (#8100) - merged to `refactoring-aphrodite` with #8105
- [x] checkDefaultBrowserDialog.js (#8137) - merged to `refactoring-aphrodite` with #8154  

Any related issues: #7989 and #7990

### PR DESCRIPTION
**Pull request by luixxiul**
~~**Requires #8105, #8011, #8136, and #8154**~~

Closes #8010
Addresses #7989

Auditors:

Test Plan: n/a

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

### CODE REVIEW

**Comment by luixxiul** [comment]
Every PR which has blocked this PR was merged, so it should be OK to merge this.

**Comment by NejcZdovc** [comment]
@luixxiul should we still merge this into `refactoring-aphrodite` or should we merge it into master already?

**Comment by luixxiul** [comment]
It should be merged to `refactoring-aphrodite` yet. Later I will push the final PR.

**Comment by NejcZdovc** [comment]
Ok, let's merge this one

**Pull request merged**
