### PR TITLE
Provide popup coords on keypress

### LINKED ISSUE #8034: LastPass opens in wrong position when activated by keyboard
## Test Plan
1. Use Preferences > Security to change password manager to LastPass
2. Tab focus from address-bar to LastPass icon
3. Press Enter
4. Popup should open beneath extension icon

## Original issue description
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered: If you tab over to LastPass from the URL bar and press Enter, the popup appears in the wrong location on the screen.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 3de60d5

- Steps to reproduce:
    1. Enable & configure LastPass
    2. Focus URL Bar
    3. Press tab once
    4. Press enter
    
- Actual result: LastPass popup appears at the left of the window.

- Expected result: LastPass popup should appear beneath the LastPass icon on the right.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version? Yes

- Can this issue be consistently reproduced? Yes

- Any related issues:

### PR DESCRIPTION
**Pull request by jonathansampson**
## Test Plan
1. Use Preferences > Security to change password manager to LastPass
2. Tab focus from address-bar to LastPass icon
3. Press Enter
4. Popup should open beneath extension icon

## Description
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fixes #8034

### CODE REVIEW

**Comment by cezaraugusto** [comment]
@jonathansampson can you rebase that?

**Comment by jonathansampson** [comment]
@cezaraugusto Just did another rebase. Let me know if that worked.

**Comment by NejcZdovc** [comment]
@jonathansampson you have some lint errors

**Comment by jonathansampson** [comment]
@NejcZdovc I'll take care of those a.s.a.p. Thanks!

**Comment by jonathansampson** [comment]
@NejcZdovc Linting issues resolved.

**Pull request merged**
