### PR TITLE
Issue 9508

### PR DESCRIPTION
**Pull request by bridiver**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
Is this something that we need to pull in 0.17?

**Comment by bsclifton** [comment]
@bridiver have you manually tested this? or rather, do you have some recommended steps to test? As a reviewer, I want to make sure `tab` is set and that `IsDestroyed()` exists / is safe to call.  Otherwise, changes look great 😄

**Comment by bridiver** [comment]
well, I saw this happen and changed the code, but it's not easy to repro. It definitely doesn't break anything

**Comment by bsclifton** [comment]
Moving to 0.18.x after noticing this patch has dependencies

**Comment by bridiver** [comment]
there are no dependencies

**Comment by bsclifton** [comment]
Pulling this back into `0.17.x` after experiencing the null frame issue

**Comment by luixxiul** [comment]
Is it acceptable for 0.17 series then?

**Pull request merged**
