### PR TITLE
Removes drag from arrow

### LINKED ISSUE #14274: Arrow should not be allowed to drag and drop on Brave Payments BAT logo page
### Description
Arrow should not be allowed to drag and drop on Brave Payments BAT logo page

### Steps to Reproduce

1. Drag and drop the arrow
2. Verify Arrow can be drag and drop

**Actual result:**

After  drag and drop of Arrow (->), 'Hmm..not quite Please try again' message is   displayed

arrow drag and drop issue

**Expected result:**

Arrow   should not be drag and dropped and message should be displayed only for BAT   logo drag and drop

**Reproduces how often:**
100%

### Brave Version
0.22.723

**about:brave info:**

Brave | 0.22.723
V8 | 6.6.346.32
rev | edb3e88
Muon | 6.0.12
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.170

**Reproducible on current live release:**

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves #14274

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
- enable payments
- claim promotion
- make sure that you can't dnd the arrow

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@jasonrsadler other elements shouldn't be a problem imho

**Comment by jasonrsadler** [comment]
out

**Comment by NejcZdovc** [comment]
@jasonrsadler fixed

**Comment by jasonrsadler** [comment]
It looks like any element in the page can be dragged here:
out

**Comment by jasonrsadler** [comment]
If you think this can cause major headaches UX-wise, I think we should consider putting the captcha in a modal. wdyt?

**Comment by NejcZdovc** [comment]
@jasonrsadler I think that we should only block what is in the overlay. If you dnd helpful tips in you are doing what you suppose to do. Prove that you are a human 😃

**Comment by jasonrsadler** [comment]
🤣 

Should we run that by UX?

**Comment by NejcZdovc** [comment]
@jasonrsadler I think that's not necessary. This overlay was provided by Brad

**Comment by NejcZdovc** [comment]
master b68fba6
0.23 3d99280c5
0.22 dba03ff34

**Pull request merged**
