### PR TITLE
Trigger tab preview based on frame key

### PR DESCRIPTION
**Pull request by cezaraugusto**
- Auditors: @bsclifton, @luixxiul
- Close: #7606

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:
### Static ordering
1. Open 3 tabs with different websites
2. Make first active
3. Hover over second
4. Close it
5. Third tab (now second) should show as a preview 

### dynamic ordering
1. Open 3 tabs with different websites
2. Ensure you reorder tabs by drag-n-drop
3. Make first active
4. Hover over second
5. Close it
6. Third tab (now second) should show as a preview 

### when previous frame is not active
1. Open 5 tabs
2. Make third active
3. Hover over fourth
4. Close it
5. Fifth tab (now fourth) should show as a preview 

## when next tab is null
1. Open 3 tabs with different websites
2. Close the 3rd tab
3. no preview is triggered

## when frame is closed by close tab shortcut
1. Open 3 tabs with different websites
2. Make first active
3. Close it by shortcut (<kbd>cmd/ctrl</kbd>+<kbd>w</kbd>)
4. No preview is triggered

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by cezaraugusto** [comment]
works as-is but a new state is needed from #8852 so setting as blocked until that is approved

**Comment by bbondy** [comment]
Pls rebase and remove the needs rebase tag when done. Thanks.

**Comment by cezaraugusto** [comment]
rebased, removed `PR/blocked` tag as well I'll rework #8852 if needed, if this is approved first

**Comment by luixxiul** [comment]
Is this change covered with automated tests?

**Comment by cezaraugusto** [comment]
@luixxiul I didn't include new ones but they are covered with existing tests for tab previews

**Comment by luixxiul** [comment]
@cezaraugusto the question occurred to me because of the issue here: https://github.com/brave/browser-laptop/issues/10103

**Comment by cezaraugusto** [comment]
ok np, that's related thanks for opening

**Pull request merged**
