### PR TITLE
Removed the hacks of the buttons on the navigation bar (for Windows)

### LINKED ISSUE #5928: URL bar issues on Chromium54 build(0.13.0 preview2)
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
URL bar issues on Chromium54 build(0.13.0 preview2)

**Expected behavior:**
Should align properly

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 2

- Steps to reproduce:
    1. Reload button is not properly aligned
    2. Stop reload button is not properly aligned
    3. Bookmark icon is bottom aligned
    4. URL bar is not aligned with the bookmark icon
    5. Window buttons have extra padding on top when the browser is maximized

- Screenshot if needed:
image

   image
 
   ezgif com-video-to-gif

- Any related issues:
cc: @bsclifton @jkup @bradleyrichter

### PR DESCRIPTION
**Pull request by luixxiul**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fixes #5928

Thanks to #5739 and #5750 (#5737) these hacks are no longer necessary.

Auditors: @srirambv @bsclifton 

Test Plan:
1. Enable Home Button
2. Open some pages in the same tab to enable backButton and forwardButton
3. Make sure every place of the buttons are clickable
4. Make sure height and width of the buttons remain the same (34x24, 26x24)
5. Make sure stopButton is centered
6. Make sure the bookmark icon is properly aligned on each platforms

### CODE REVIEW

**Comment by luixxiul** [comment]
With the commit it should be like this:
clipboard01

**Comment by bradleyrichter** [comment]
@luixxiul I am having de ja vu here. Is this a PR to fix an unwinding of your older PR that already fixed this? Or did that one never make it in?

**Comment by luixxiul** [comment]
@bradleyrichter At that time I was not sure of the hacks for Windows, which I removed with the commit.

**Comment by bradleyrichter** [comment]
perfect!

**Comment by bsclifton** [comment]
looks beautiful! great job :smile: 

image

**Comment by bbondy** [comment]
love it :D

**Pull request merged**
