### PR TITLE
Browser crash with payment enabled when clearing browsing data

### LINKED ISSUE #8659: Browser crash with payment enabled when clearing browsing data
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Browser crash with payment enabled when clearing browsing data

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.2
rev	71f7dfd

- Steps to reproduce:
    1. Clean install 0.15.2 preview 2 and launch from console
    2. Clear browsing data, console shows error  (screenshot 1)
    3. Enable payments, doesn't work(#8632) 
    4. Kill the app and copy an old `ledger-synopsis` file and paste it in `%appadata%`
    5. Relaunch the app from console
    6. Enable payments, should work
    7. Clear browsing data, browser crahses (screenshot 2)
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
error
ezgif com-optimize

- Any related issues:
cc: @mrose17 @bsclifton

### PR DESCRIPTION
**Pull request by mrose17**
https://github.com/brave/browser-laptop/commit/40abc0c780050eb0b8dd42c15
065d1c784268b47#diff-8a9bac13ef6264feb2b6da7c18d86b3cL733 and
https://github.com/brave/browser-laptop/commit/40abc0c780050eb0b8dd42c15
065d1c784268b47#diff-8a9bac13ef6264feb2b6da7c18d86b3cL746 you’ll see
that the old code had a catch to deal with clean-up errors. The new
code doesn’t. This fixes that in filtering.js … whether or not there
should be a catch is a different issue.

Also, in tabs.js, I consistently get a crash when starting up my test
browser, this fixes that.

Fixes #8659 ... this has nothing to do with the ledger, afaik...

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

1. start browser
2. oh, the places you will go!
3. clear all browser data via preferences>security
4. no crash: winner!

### CODE REVIEW

**Comment by bridiver** [comment]
actually it looks like the catch was hiding the fact that the method was always throwing an exception. You're right that we don't want to add a catch, we want to fix the method call so it doesn't throw an exception every time

**Comment by mrose17** [comment]
@bridiver - i agree, but this is outside of my area, so i'm deferring to you, @bsclifton and @bbondy to figure out the rea fix...

**Comment by bsclifton** [comment]
@bridiver before I can test this out, I need your help resolving the merge conflict.  It conflicts with the commit you did most recently: https://github.com/brave/browser-laptop/commit/33e3fca1025ff91e656567c0ad4e862ecc312000

**Comment by mrose17** [comment]
@bsclifton -please resolve the conflicts in favor of my PR. it supersedes the checkin done by @bridiver

**Comment by alexwykoff** [comment]
need to get to stable release so needs to be finished, also needs test plan

**Comment by mrose17** [comment]
@bsclifton - conflicts resolved.

**Comment by bsclifton** [comment]
awesome, thanks @mrose17 😄 

Per request from @alexwykoff, do you mind adding a test plan?

**Comment by mrose17** [comment]
@bsclifton - done.

**Pull request merged**
