### PR TITLE
Add currency symbols where appropriate

### LINKED ISSUE #3533: Add currency symbols where appropriate
Using a library like https://www.npmjs.com/package/currency-symbol-map it would be nice to add currency symbols on the ledger settings pages for the appropriate currency type.

It looks like "currency" is stored in state as a string (https://github.com/brave/browser-laptop/blob/master/docs/state.md#L403), so we should just be able to pipe it through a library like the one above and then prepend it to the currency number.

### PR DESCRIPTION
**Pull request by jkup**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fix #3533

Auditors @bsclifton @cezaraugusto 

Test Plan:

1. Go to Preferences > Payments
2. Check the payment amount, the current balance, and your payment history and make sure they all have $ for currency.
screen shot 2016-12-16 at 1 25 07 am

### CODE REVIEW

**Comment by bsclifton** [comment]
How is `this.props.ledgerData.get('currency')` determined? I'm guessing it's based on the IP?

@jkup can you screenshot the places where currency is updated? I'm also curious how the formatting looks for other currency

**Comment by jkup** [comment]
@bsclifton yep it's based on the IP. I added a screenshot of what this looks like for USD but I'm a little hesitant to ship this ticket because after talking with @mrose17 it turns out faking the currency is difficult to do.

I suppose my only real worry is that we support some currency that doesn't exist in this package's currency map (https://github.com/bengourley/currency-symbol-map/blob/master/map.js) so it will default to USD instead. Thoughts?

**Comment by mrose17** [comment]
the list is fairly comprehensive, so i'm no worried about it.

we do not have plans to turn on additional currencies right now, so i don't think this is a priority.

i would do the PR and then mark the issue closed.

**Comment by cezaraugusto** [comment]
++ lgtm

**Comment by bsclifton** [comment]
Thanks for the update! Looks good :smile:

**Comment by luixxiul** [comment]
Note: `npm i` is required to fix the error

````
Uncaught TypeError: getSymbolFromCurrency is not a function{TypeError: getSymbolFromCurrency is not a function
````

**Comment by jkup** [comment]
@luixxiul yep this is how adding npm packages works

**Comment by bradleyrichter** [comment]
@cezaraugusto This PR is useful but needs to be corrected ASAP to show the ISO 4217 currency code (3 letters) instead of the symbol.

**Comment by bsclifton** [comment]
This was reverted; removing milestone

**Pull request merged**
