### PR TITLE
Fixes tab page index after tab close

### LINKED ISSUE #9922: Tabs are not updated after tabpage close
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
When you close the last tab in a page tab you get empty tabs toolbar.
- Platform (Win7, 8, 10? macOS? Linux distro?):
all
- Brave Version (revision SHA):
dc76f0a
- Steps to reproduce:
    1. open two tab pages
    2. close the last tab in the tab page
    
- Actual result:
image

- Expected result:
Tab page is switched correctly.
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
no
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #9922

Auditors: @cezaraugusto

Test Plan:
-  open two tab pages
- close the last tab in the tab page

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
So this issue regressed because of this line https://github.com/brave/browser-laptop/commit/51b876d68161eff79b7e559a770424b6848bc8f9#diff-f5a0b45b8323a469e78cf98fb0c49b8fR470

So when we close a tab, we set hover tab to the next tab, so that we display close icon if mouse is still in the next tab. But the problem is that hover state is now set and condition mentioned above will be true. This means that tab page will not be update.

@cezaraugusto what do you think that we should do?

**Comment by cezaraugusto** [comment]
I think we would be better if we do not depend on hoverState at all. The change I did fix the issue which was related to hover state but turns out to be fragile given this case wasn't covered, and there may be many others too.

Instead, we should look for active tab changes and update tabPage based on that. We're tracking it in https://github.com/brave/browser-laptop/issues/9911. I should be taking that soon but lmk if you're interested in taking.

**Comment by NejcZdovc** [comment]
If you already now what to do, please do it. Can you please add your fix to this PR, because I already updated test so that is working correctly now and failing for this use case?

**Comment by cezaraugusto** [comment]
ok I'm unable to push to your fork so I'm going close this and create a new branch cherry-picking your commit.

**Pull request closed without merging**
