### PR TITLE
Fixes context menu not working on tabsbar

### LINKED ISSUE #9524: Context menu not working for tabs toolbar
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Context menu not working for tabs toolbar
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
1007e8c
- Steps to reproduce:
    1. Right click on tabs toolbar (on empty space)
    
- Actual result:
You get an error
- Expected result:
Context menu opens
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
no
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #9524 

Auditors: @bsclifton

Test Plan:
- right click on tabs toolbar (on empty space)
- context menu should open

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
This issue is not solving any specific problems as you fond on windows. This PR only fixes a regression where we are passing wrong params into the function. We can track issue for this problem in #8320.

**Comment by bsclifton** [comment]
@NejcZdovc gotcha- works for me 😄

**Comment by srirambv** [comment]
I see the bookmarks toolbar context menu show up in a specific place when I right click on the empty space. Other places it bring up the browser context menu. @NejcZdovc  @bsclifton Is this expected ?

**Comment by NejcZdovc** [comment]
@srirambv context menu in bookmarks toolbar is not working for windows. More info here https://github.com/brave/browser-laptop/issues/4244#issuecomment-309352965

**Comment by bsclifton** [comment]
@srirambv what @NejcZdovc said 😄 

https://github.com/brave/browser-laptop/issues/4244 will need to be solved in order to have draggable areas that don't return the Windows system menu (ex: same menu that shows when you right click on a titlebar)

**Pull request merged**
