### PR TITLE
Context menu upgrades

### PR DESCRIPTION
**Pull request by bsclifton**
Per https://github.com/brave/browser-laptop/issues/1253

- menu on URL nearly matches spec (just missing "search with X")
- menu for selection nearly matches spec (missing "look up X")
- menu on page bg nearly matches spec (missing bravery menu)
- menu for tab nearly matches spec (move to new window needs functionality)

I need help working through the remaining items (search, bravery menu, move tab to new window)

### CODE REVIEW

**Comment by bsclifton** [comment]
Some screen caps:

**Comment by aekeus** [comment]
This looks good to me! Tested manually as well as code inspected.@bbondy or @diracdeltas would you like to confirm these changes as well?

**Comment by aekeus** [comment]
Thanks @bsclifton for the commit!

**Comment by bsclifton** [comment]
You're welcome @aekeus! :smile: If you'd like, I can back out the incomplete items (since they were just implemented by putting a disabled menu item in place). The accompanying code has "//TODO:" blocks in the parts I didn't know about implementing

Let me know and definitely curious what @bbondy and @diracdeltas think :smiley:

**Comment by bbondy** [comment]
Thanks @bsclifton I'll merge this but ya please comment out the disabled items for now.  Leaving it as is just commented for now is fine.  Do that in a  followup, thanks!

**Pull request merged**
