### PR TITLE
added release notes for 0.13.0

### PR DESCRIPTION
**Pull request by alexwykoff**
Auditors: @bbondy, @luixxiul

### CODE REVIEW

**Comment by luixxiul** [comment]
@alexwykoff does this include #5705 and above to #5959 on https://github.com/brave/browser-laptop/issues/6335#issue-196707969?

**Comment by alexwykoff** [comment]
I intentionally removed pulls from this set of release notes. Presumably all PRs should have appropriate tracking issues.

**Comment by luixxiul** [comment]
Some not, for example https://github.com/brave/browser-laptop/pull/5705 which fixed more than what its tracking issue covered at first. Also there are commits which are tagged 0.12 but should be included since 0.13.

**Comment by luixxiul** [comment]
For example https://github.com/brave/browser-laptop/issues/5753

**Comment by bbondy** [comment]
stale, so closing this PR.

**Pull request closed without merging**
