### PR TITLE
Update index-dev.html

### PR DESCRIPTION
**Pull request by bkardell**
re: issue #329, async gone wrong? bundle depends on webpack-dev-server...

### CODE REVIEW

**Comment by bkardell** [comment]
hmm I'm getting npm test errors regardless of this change... something is weird.

**Comment by bkardell** [comment]
Hmm ok... I looked all over, was unable to find anything related to this that seemed it could plausibly be causing the build failure I was getting here last night, so I just pulled and basically did a commit with no changes to cause it to retrigger and now it passes.  Weird.  I guess possible explanation is that something was amiss with the build itself, or there is a bad test, or the async nature makes the test conditions racey?  I'm gonna leave this here and head to work for the day until someone comments further.  If necessary I can try to squash the commits.

**Comment by diracdeltas** [comment]
Yeah, some of our tests are flakey :(. Anyway this fixes the console errors for me, so I'll cherry-pick the fix. Thanks!

**Comment by bkardell** [comment]
Thank you!  ...annnd the build failed.

**Pull request closed without merging**
