### PR TITLE
Build: Make babel tranpile smarter by using chrome version (fixes #6367)

### LINKED ISSUE #6367: Build: Only transpile JS which is not supported based on chrome version
**Did you search for similar issues before submitting this one?**
n/a
**Describe the issue you encountered:**

Currently, we transpile all the JavaScript to ES5 code. But I think we can be smart by using https://github.com/babel/babel-preset-env to only tranpile code which is not supported by a particular version of chrome (I guess we can say 54 now). 

**Expected behavior:**

This will help us to run most of the code we write as it is. Chrome as better perfs on certain ES6 features i guess.

- Platform (Win7, 8, 10? macOS? Linux distro?):
all
- Brave Version (revision SHA):
master

### PR DESCRIPTION
**Pull request by gyandeeps**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan: N/A

### Before

```sh
    aboutPages.entry.js    2.62 MB       0  [emitted]  aboutPages
           app.entry.js    2.32 MB       1  [emitted]  app
```

### After

```sh
    aboutPages.entry.js    2.52 MB       0  [emitted]  aboutPages
           app.entry.js    2.16 MB       1  [emitted]  app
```

### CODE REVIEW

**Comment by bbondy** [comment]
Thanks!

**Comment by bsclifton** [comment]
@gyandeeps great find! :smile:

**Comment by hzoo** [comment]
Awesome to see this! Wanted to leave some comments (as a Babel maintainer):

Instead of chrome 54 (since brave is on 56 now), you can do something like

```js
"targets": {
  "browsers": ["last 2 Chrome versions"]
}
```

Although now that I think about it, we should add one for brave 😝? A package was made for electron https://github.com/babel/babel-preset-env/pull/144

I'd recommend using the `useBuiltIns` option to reduce the number of polyfills loaded as well. https://github.com/babel/babel-preset-env#usebuiltins if you use `babel-polyfill` (although not sure if that is loaded or not in the source?

**Comment by bbondy** [comment]
thanks for the tips @hzoo 
@gyandeeps would you mind trying to use useBuiltIns and always use latest for target

**Comment by hzoo** [comment]
Might need some help with determining where the polyfill is loaded in (if it is at all?)

The way it works currently is that it literally tries to find `import "babel-polyfill";` in your code (or require) and then replace that code with the individual imports so it needs to be imported in the entry point file rather than in a script tag or the webpack entry point etc

**Comment by gyandeeps** [comment]
Thanks @hzoo for feedback.

* I dont think `babel-polyfill` is used in source code.
* Since we know what version of chrome we use then i guess i can update it to `56`.

So just change the chrome version. Any thing i am missing?

**Pull request merged**
