### PR TITLE
Fixes usage of ledger advance settings in the ledger table

### LINKED ISSUE #7987: toggle excluding a site from ledger sometimes removes it from the list
mac os 0.14 and latest master

steps to repro (starting from a clean profile):
1. enable payments
2. visit nytimes.com for at least 8 seconds or until it appears in the synopsis table
3. set minimum visits to 5 instead of 1
4. exclude nytimes.com by toggling the switch

result:
nytimes.com suddenly disappears from the list when the switch is toggled

expected result:
when minimum visits is set to N, all sites with less than N visits should disappear immediately. the current behavior is very confusing because toggling the exclude switch should not remove the site from the list.

a similar issue exists for increasing the minimum time. if i increase it from 8 seconds to 1 minute, a site with 9 seconds remains in the ledger table. however if i then toggle the include switch on that site, it doesn’t disappear from the list, so the problem isn't as bad.

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Resolves #7987

### Auditors
@mrose17 @diracdeltas

### Test Plan
- enable payments
- visit site for at least 8 seconds or until it appears in the synopsis table
- set minimum visits to 5 instead of 1
- site shouldn't be in the ledger table

### CODE REVIEW

**Comment by diracdeltas** [comment]
test plan worked, but some synopsis tests may be failing due to this: https://travis-ci.org/brave/browser-laptop/jobs/218608197#L3227. they failed locally for me too.

**Comment by diracdeltas** [comment]
specifically this fails on this branch but passes on master (locally):

```
> npm run test -- --grep='synopsis'

> brave@0.14.1 test /Users/yan/repos/browser-laptop
> cross-env NODE_ENV=test mocha "test/**/*Test.js" "--grep=synopsis"



  synopsis
    ✓ no table if empty synopsis (46ms)
    1) creates synopsis table after visiting a site
    2) can sort synopsis table
    ✓ can disable site (2683ms)

  PublisherToggle component
    default behaviour (when autoSuggest is ON)
      ✓ show as enabled if site is on synopsis list (siteSettings is empty)
      ✓ show as enabled if hostPattern is on siteSettings list (synopsis is empty)
      ✓ show as enabled if url exists in locationInfo (both synopsis and siteSettings are empty)


  5 passing (46s)
  2 failing

  1) synopsis creates synopsis table after visiting a site:
     Promise was rejected with the following reason: timeout
  Error

  2) synopsis can sort synopsis table:
     WaitUntilTimeoutError: element ([data-l10n-id="publisher"]) still not visible after 10000ms
      at isVisible("[data-l10n-id="publisher"]") - waitForVisible.js:37:22
```

**Comment by NejcZdovc** [comment]
@diracdeltas fixed, I needed to add back one property, because it's used in `ledger-publisher`, so we can use this hack for test (visit time is set to 0s when in executing tests)

**Comment by diracdeltas** [comment]
lgtm, thanks for looking into this

**Pull request merged**
