### PR TITLE
Update localization files

### PR DESCRIPTION
**Pull request by luixxiul**
Auditors: @aekeus

Test Plan:

Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by luixxiul** [comment]
CC @bsclifton

**Comment by Jacalz** [comment]
I don’t know if it is just me but I could not find any Swedish in there 😅

**Comment by luixxiul** [comment]
I'm not sure if the script I ran (npm run download-language) is configured to fetch Swedish resources from Transifex platform.

**Comment by Jacalz** [comment]
Is it possible to configure it ti di that?

**Comment by bbondy** [comment]
@Jacalz the code for this is in  tools/downloadLanguages.js and it enumerates the app/extensions/brave/locales folder for each language.  Best to track a new issue if you are sure there are translations being missed pls.

**Comment by bbondy** [comment]
master: d0531ac7576132e9793fe1ff065492e4c219aa8b
0.21.x: 1ea316e686a73eebfc6fcf75265392d070c333ba
0.20.x: d45d7b83eda708bd072c22b98a4b54d37ad0b403

Normally localization updates go only in master but I happen to know 0.20.x, 0.21.x and master are very similar so it's ok this time.

**Pull request merged**
