### PR TITLE
Update file-loader to 0.11.2

### LINKED ISSUE #10203: update file-loader to v0.11.2
**Describe the issue you encountered:** update file-loader to v0.11.2, which is the latest available as a npm package before v1.0.0.

changelog: https://github.com/webpack-contrib/file-loader/blob/743aef27df5a594d8c02df407ae03d15b7a92a64/CHANGELOG.md

v1.0.0 is available on their GitHub repo ([changelog](https://github.com/webpack-contrib/file-loader/compare/v0.11.2...v1.0.0?short_path=4ac32a7#diff-4ac32a78649ca5bdd8e0ba38b7006a1e)). It includes a breaking change concerning Webpack standard NodeJS engines range and Webpack peerDependency range, which requires an update of webpack to version 2 or 3.

The update of webpack has been abandoned once https://github.com/brave/browser-laptop/pull/8048, and we should work on that at first to update file-loader to v1.0.0 or higher.

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): master branch

- Extra QA steps:
    1. `rm -rf node_modules && rm -rf ~/.electron && npm i`
    2. `npm run watch`
    3. `npm start`
    4. Make sure the images are properly displayed on the browser

- Any related issues:

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #10203

Test Plan:
1. `rm -rf node_modules && rm -rf ~/.electron && npm i`
2. `npm run watch`
3. `npm start`
4. Make sure the images are properly displayed on the browser

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bsclifton** [comment]
@luixxiul can you please rebase? I resolved the conflict locally but you must have disabled pushing to your branch (I get a permissions error when pushing the resolved version to your repo)

**Comment by NejcZdovc** [comment]
@luixxiul @bsclifton should we update to version 1.x, now that we have webpack 3?

**Comment by bsclifton** [comment]
@NejcZdovc I believe that requires refactoring, right?  If not, I would be in favor of that

**Comment by NejcZdovc** [comment]
@bsclifton I am not familiar with this package, but based on @luixxiul comment here https://github.com/brave/browser-laptop/issues/10203#issue-246568057, webpack was the blocker for version 1.x.

**Comment by NejcZdovc** [comment]
But based on the change log I don't see any problems. We would need to test it out

**Comment by bsclifton** [comment]
@luixxiul what do you think?  You can rebase and we can merge... OR if you'd like, we could try a newer version (now that we've upgraded webpack)

**Comment by luixxiul** [comment]
rebased!

**Comment by bsclifton** [comment]
Great, thanks! 😄

**Pull request merged**
