### PR TITLE
Add search with search engine list on right click

### LINKED ISSUE #3243: Include Search with search engine list in the right click context menu
## Test plan

https://github.com/brave/browser-laptop/pull/12613#issue-287901696

----

Include Search with (available search engines from the pref menu) in the right click context menu when a user select a text.

### PR DESCRIPTION
**Pull request by sergiorojasa**
Fix #3243
Submitter Checklist:

- [X] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [X] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

Test Plan:

1. Run webpack: npm run watch
2. Run Brave: npm run start
3. In the URL bar type: https://www.brave.com/
4. Highlight "A browser with your"
5. Right click
6. Hover your mouse pointer on "Search for A browser with your".
7. Click on a search engine provider

Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by sergiorojasa** [comment]
@bsclifton

**Comment by sergiorojasa** [comment]
#12698 pull request looks like it will fix the local favicon issue.

**Comment by sergiorojasa** [comment]
Ready for review

**Comment by bsclifton** [comment]
Adding @diracdeltas who fixed a similar case (context menu in the URL bar, not in the content area). This case also uses the wrong provider

**Comment by bsclifton** [comment]
@sergiorojasa apologies that we never got a chance to fully review this ☹️

**Pull request closed without merging**
