### PR TITLE
Fixed .urlbarIcon size change

### LINKED ISSUE #6270: urlbarIcon size change with search engine selection
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Favicons size change with search engine selection 

**Expected behavior:**
All favicons in URL bar should be of the same size

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 (need to verify on older builds)

- Steps to reproduce:
    1. Open a new tab 
    2. Type any of the engine go key and press space
    3. See the change in icon size when the engine go key is selected and changed back by pressing backspace

- Screenshot if needed:
favicons

- Any related issues:
cc: @bradleyrichter

### PR DESCRIPTION
**Pull request by luixxiul**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Closes #6270

Auditors: @srirambv @bsclifton /cc: @bradleyrichter

Test Plan:
1. Open about:preferences
2. Open http site in a new tab
3. Open https site in a new tab
4. Open a new tab and hit ":yt" in the url bar to display Youtube icon
5. Open a new tab and hit ":g" to display Google icon
6. Make sure .urlbarIcon does not change its size on each step

urlbaricon

### CODE REVIEW

**Comment by bradleyrichter** [comment]
Looks good!

**Comment by luixxiul** [comment]
@bsclifton please merge this if it is ok for you too :+1:

**Comment by bsclifton** [comment]
Looks good to me! I marked it with 0.13.1 and will tag it with ready for merge.  We want to avoid merging into master right now until 0.13.0 is release :smile:

**Comment by luixxiul** [comment]
I'll rebase. Because the release date was changed, I'm wondering if this could be merged in 0.13

**Comment by luixxiul** [comment]
Rebased. It's ready for review ;-)

**Comment by bsclifton** [comment]
I'll go ahead and pull this into 0.13.0, since it's only style changes

**Pull request merged**
