### PR TITLE
Fixes #2835: Brave hangs in development (npm start) on Ubuntu

### LINKED ISSUE #2835: Brave hangs in development with red "Loading..." text (Ubuntu 14.04)
[x] **Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
On a fresh pull Brave hangs when run via `npm start`stuck displaying "Loading" in red on a white background.

Ran `git bisect` and it seems to be broken by a single commit: 823dbf03a07a19d99546bf8c20d75da03b217802:
```
commit 823dbf03a07a19d99546bf8c20d75da03b217802
Author: Brian R. Bondy <netzen@gmail.com>
Date:   Tue Jul 26 13:21:37 2016 -0400

    Revert "Revert "don't allow scaling or zooming of the ui""
    
    This reverts commit d4258e05bf3222bda0f5668b7246960b53221fdf.

 js/entry.js | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)
```

Brave runs fine if I revert this commit. 

Anyone else have this issue?

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 14.04 LTS 

- Brave Version:
Fresh pull on master, commit 011ed743f82e1a22e382a99071078a7cfe203e83 

- Steps to reproduce:
    1. Switch to master branch, pull latest.
    2. Run `npm run watch`
    3. In a separate terminal, run `npm start`
    4. Observe Brave window contains only red text "Loading..." on a white background, and remains like this.

- Screenshot if needed:
brave-stuck-loading

### PR DESCRIPTION
**Pull request by willy-b**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist: Issue #2835 
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.

### CODE REVIEW

**Comment by bbondy** [comment]
I think you might just need a new npm install and also rm -Rf ~/.electron.
I think the code you are removing should stay so closing this. Let me know if the above doesn't fix the issue though.

**Comment by kingscott** [comment]
@bbondy Getting the same issue on OS X, any suggestions? I tried the steps you mentioned, but cannot seem to get anywhere.

**Comment by bbondy** [comment]
are you on a fully updated master branch with no code changes?

**Comment by kingscott** [comment]
I ran `npm run clean` and did a re-install. Works fine - turned out to be to generic error reporting for a syntax error.

**Pull request closed without merging**
