### PR TITLE
Update react to ~16.0.0

### LINKED ISSUE #11229: Update react to ~16.0.0
### Description

Update react to `~16.0.0`.

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #11229

- react
- react-dom
- react-test-renderer

Auditors: @bbondy

Test Plan:
1. npm install

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by luixxiul** [comment]
By running npm install, you'll get:

````
 ERROR in ./node_modules/react-addons-perf/index.js
    Module not found: Error: Can't resolve 'react-dom/lib/ReactPerf' in '/Users/Suguru/browser-laptop/node_modules/react-addons-perf'
     @ ./node_modules/react-addons-perf/index.js 1:17-51
     @ ./app/renderer/components/main/main.js
     @ ./app/renderer/components/window.js
     @ ./js/entry.js
     @ multi ./js/entry.js
````

**Comment by bbondy** [comment]
You can probably remove the menu option for react perf unless there's a replacement for it available.

**Comment by luixxiul** [comment]
With the latest commit https://github.com/brave/browser-laptop/pull/11230/commits/148c11717f30bf830afb75af226be7ae136ee8a5 `npm run unittest` causes a lot of fails such as:

````
  1) NewTab component unit tests Object properties showImages returns true when `showImages` and `backgroundImage` are true:
     TypeError: Cannot read property 'setState' of undefined
      at node_modules/enzyme/build/ShallowWrapper.js:377:30
      at withSetStateAllowed (node_modules/enzyme/build/Utils.js:284:3)
      at ShallowWrapper.<anonymous> (node_modules/enzyme/build/ShallowWrapper.js:376:42)
      at ShallowWrapper.single (node_modules/enzyme/build/ShallowWrapper.js:1518:25)
      at ShallowWrapper.setState (node_modules/enzyme/build/ShallowWrapper.js:375:14)
      at Context.<anonymous> (test/unit/about/newTabPageTest.js:93:17)
````

**Comment by cezaraugusto** [comment]
thanks for leading this @luixxiul I'll help on this one but for now setting as `PR/blocked` just in case, should land in 0.21.x for sure but only after 0.19.x ships

**Comment by luixxiul** [comment]
I'm closing this for now :-)

**Pull request closed without merging**
