### PR TITLE
Removes non-primitive props from Frame

### LINKED ISSUE #9760: Only primitives in Frame
**Describe the issue you encountered:**
Remove `allSiteSettings` from mergeProps.

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #9760

Auditors: @bridiver @bsclifton

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@bbondy @bridiver @bsclifton Any idea how to remove `allSiteSettings` from `mergeProps`

We use it in 3 places:
https://github.com/brave/browser-laptop/blob/master/app/renderer/components/frame/frame.js#L116

https://github.com/brave/browser-laptop/blob/master/app/renderer/components/frame/frame.js#L133

https://github.com/brave/browser-laptop/blob/master/app/renderer/components/frame/frame.js#L143

**Comment by NejcZdovc** [comment]
This PR will probably not be needed, because of this PR #9702

**Comment by bridiver** [comment]
yea, closing in favor of #9702

**Comment by luixxiul** [comment]
When closing please remove the milestone, thanks.

**Pull request closed without merging**
