### PR TITLE
Making the Clear Browsing Data panel stateful

### LINKED ISSUE #4082: "Clear browsing data" user settings
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**

**Expected behavior:**
Settings to stay On
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Linux Mint 18 - Cinnamon
- Brave Version:
  See screenshot
- Steps to reproduce:
  1. From the History menu, click "Clear all Cookies and Site Data."
  2. Move the selector bars for Browser History & Download History from off to on
  3. Click Clear
- Screenshot if needed:
  see screen shots
- Any related issues:
  Everytime I select "Clear browsing data," I am forced to move the selector bars for Browser History & Download History from off to on. I tend to delete these items often, even hourly at times as I can visit a lot of news sites and I prefer to delete what these sites store on my computer.

Please allow your Users to make these settings default or not. I should be able to just select ON as my prefer setting and have them stay ON!
default settings
settings i prefer
brave version

### PR DESCRIPTION
**Pull request by maaz93**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fixes #4082 
Majorly, the change affects 2 places in the UI. The Clear Browsing
Data… option in the History menu and the Clear Browsing Data Now…
button in the Security tab in Preferences. We store the state of the
toggled options when the user clears anytime, so that the next time
he/she opens this dialog, the options are pre-populated as per the last
selected options

From a technical perspective, we have moved away from saving the
current state of the SwitchControls in the windowState. We only save
the visibility on the windowState. The whole state is managed by the
panel itself and just updates the appState on clicking Clear.

Auditors:
@bsclifton 

## Test plan
1. Launch Brave visit preferences
2. On the left, choose Security tab
3. Click `Clear Browsing Data`
4. Choose very specific options; like `download history` and `all site cookies` and click `Clear`
5. After window closes, click `Clear Browsing Data` again 
6. The same options should be selected now. Close the window with `Cancel`.
7. Pick `Clear Browsing Data` from the `History` menu
8. Confirm the same options from step 4 are shown. Hit cancel to close
9. Load about:history and click `Clear Browsing Data`
10. Confirm the same options from step 4 are shown. Hit cancel to close

## Automated test plan
```bash
#window 1
npm run watch
#window 2
npm run uitest -- --grep="state is preserved"
npm run uitest -- --grep="Clear Browsing Panel"
npm run uitest -- --grep="urlBar tests"
```

### CODE REVIEW

**Comment by maaz93** [comment]
Please don't consider this PR yet. I've missed out one of my changes while resolving a merge conflict. Will resubmit.

**Comment by bsclifton** [comment]
@maaz93 no worries :smile: Take your time; we won't be able to pull into this next release, but we'll instead pull into the one after that

**Comment by maaz93** [comment]
This PR is ready for review.

**Comment by bsclifton** [comment]
Awesome, thanks @maaz93! We're working hard on a next release right now, so there may be a delay for the review... but I can promise you that we'll review and pull this in :smile:

**Comment by bsclifton** [comment]
Last Travis-ci run shows errors, but I re-ran those locally and it's working as expected :smile: Merging...

**Comment by maaz93** [comment]
@bsclifton Thanks for doing the rebase and adding test steps! 😄

**Pull request merged**
