### PR TITLE
Ledger list should not have maximum height

### LINKED ISSUE #4537: Ledger list should not have maximum height
This relates to #3888

Right now the list has a max height causing it to have a separate scroll container. It would be better if it went the entire page height so there was only a scrollbar on the window.

### PR DESCRIPTION
**Pull request by jkup**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fix #4537

Test Plan:

Instead of a fixed-height box with it's own scroll. The entire Payments page should scroll if you have enough publishers.

screen shot 2016-10-07 at 3 11 06 pm

### CODE REVIEW

**Comment by diracdeltas** [comment]
i added the fixed-height thing because it was in one of @bradleyrichter's original design specs. just making sure he is ok with this change

**Comment by jkup** [comment]
@diracdeltas totally. People were complaining that they didn't know you could scroll so he suggested this change here: https://github.com/brave/browser-laptop/issues/3888#issuecomment-251562491

**Comment by diracdeltas** [comment]
ah ok, cool

**Comment by diracdeltas** [comment]
lgtm, thanks

**Pull request merged**
