### PR TITLE
Moves Ledger Deleted Sites List to a new dialog

### LINKED ISSUE #12833: Move Ledger Deleted Sites List to a new dialog
As a user, I need more intuitive access to the sites I may have deleted from my Brave Payments list.

Currently, users are confused by the action of deletion and the location in prefs where these sites are managed.

A new link will be added to the bottom text navigation in the ledger list as shown:
(Show Deleted Sites)
image

Clicking this link will open a dialog with scrolling content:
image

The scrolling dialog will use the same list that is already maintained within the Prefs/Shields list. 

A new feature with button "Clear All" will be added to assist in resetting the deleted sites list if needed.

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves #12833 

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

### Plan a
1) enable payments and add few publishers
2) make sure that delete link is not present in the footer
3) delete few of them
4) make sure that delete link is added
5) click on it an make sure that deleted publisher is on the list
6) click on X on one of them and make sure that publishers can be added back to the list

### Plan b
1) do steps 1-5 from plan a
2) click clear all and make sure that publishers can be added back to the list

### Plan c
1) Visit a few sites and toggle the shield setting (turn shields off for example)
2) Visit Preferences > Shields and confirm the entries show there under "Saved Site Exceptions"

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bradleyrichter** [comment]
One addition I'd like to add to this PR is to hide or disable the link string until the first site appears in the list.

prevents this case:
image

**Comment by NejcZdovc** [comment]
link is now removed, when you don't have deleted sites

**Comment by bsclifton** [comment]
master a0cfa58157fa0e44819d31efbc1ee7fbfb197d93
0.22.x 7aedbb35bbe49b7ea9de1082382bd496ad248e5b
0.21.x in progress

**Comment by NejcZdovc** [comment]
0.21 914ec89fa71f406de7d545c2e1e113be93af69ff

**Comment by NejcZdovc** [comment]
0.21 twitch 2a58dc2cb

**Pull request merged**
