### PR TITLE
Style updates to bookmark manager per @bradleyrichter

### PR DESCRIPTION
**Pull request by bsclifton**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fixes https://github.com/brave/browser-laptop/issues/4562 

Auditors: @jkup @bbondy

Test Plan:
1. Launch bookmarks manager
2. Ensure it looks like the latest mockup here: https://github.com/brave/browser-laptop/issues/4562
3. Try resizing the window
4. Enjoy :smile:

### CODE REVIEW

**Comment by bsclifton** [comment]
Here's a screenshot showing the **flex**ability of the folders area, which fixes https://github.com/brave/browser-laptop/issues/1187

*How low can you go?*
screen shot 2016-10-12 at 12 05 33 am

**Comment by bbondy** [comment]
@bradleyrichter could you review?

**Comment by srirambv** [comment]
@bsclifton The import button doesn't seem to be placed correctly in the preview build 
image

**Comment by srirambv** [comment]
Long folder names getting clipped 

image

**Comment by bsclifton** [comment]
@srirambv those issues will be fixed with this PR :smile: This should also fix a failing test

**Comment by bradleyrichter** [comment]
Ideally we would have ellipses after a max width and a full-text on hover. 

Later, drag-adjust column widths. 


Please don't force the column width to fit the long folder names.

**Comment by bsclifton** [comment]
@bradleyrichter should there be a max width setting? Adding that would be fairly easy.  Overflow can be handled with either ellipsis or by adding a horizontal scroll bar at the bottom

**Comment by bsclifton** [comment]
Screen caps of some of the changes we did:

New "All Folders" that shows when you do a search (otherwise hidden):
screen shot 2016-10-12 at 3 04 26 pm

Demo of the new color highlights for sortableTable cc: @darkdh 
screen shot 2016-10-12 at 3 19 15 pm

**Comment by jkup** [comment]
Looks great. A few tiny things:

1. The page has a scrollbar even with only 1 item.
2. Should we center the search bar on smaller devices?
3. Is it ok that the titles aren't scrollable on smaller devices? Not sure if it matters but it means you can't read the entire thing.

Pictures for 2 & 3
screen shot 2016-10-12 at 4 26 53 pm
screen shot 2016-10-12 at 4 26 57 pm

**Comment by bsclifton** [comment]
Sweet- thanks for the feedback, @jkup!  I'll can work on a fix for 1 and 3 in a follow up

@bradleyrichter what do you think about 2? (should the search box be centered if you reduce the window size- see @jkup's pic)

**Comment by bsclifton** [comment]
I'll go ahead and merge- @bradleyrichter I can address those items in a follow up (0.12.6, when adding folders).  Please let me know!

**Pull request merged**
