### PR TITLE
Add searx Search Engine

### LINKED ISSUE #7658: Add searx as Search Engine
Here are some comments discussing adding searx:
 #6295
 #790

## Q/A steps
   1. Open Preferences.
   2. Open the Search section and select 'searx' from the list.
   3. Activate the URL bar and type something (e.g. Brave).
   5. Press Enter.
   6. Make sure the searx search page appears with the specified search term(s).
   7. Activate the URL bar and try the engine go key :x.

### PR DESCRIPTION
**Pull request by cwmke**
Fixes #7658.

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:
QA steps are specified in the issue.

### CODE REVIEW

**Comment by bsclifton** [comment]
@Liunkae you've introduced a few new search engines for us... would you be able to give this one a spin? 😄

**Comment by Liunkae** [comment]
Sure, I'll take a look.

**Comment by cwmke** [comment]
Thanks for the quick review!

**Comment by bsclifton** [comment]
Thanks, folks! ❤️

**Pull request merged**
