### PR TITLE
add sync QR code and setup options

### PR DESCRIPTION
**Pull request by diracdeltas**
This adds most of the UX for Brave sync setup in the case where this device is the first device in the sync profile.

Auditors: @ayumi

Test Plan:
1. npm run clean-session-store
2. npm start
3. go to about:preferences#sync
4. click the orange button to set up sync for the first time
5. name the device, then click the create button
6. shut down brave, run npm start again
7. you should see the device name from (5) in the terminal console
8. go to about:preferences#sync, click 'add new device' button
9. you should see a QR code

screen shot 2017-01-13 at 8 15 43 am
screen shot 2017-01-13 at 8 14 29 am

### CODE REVIEW

**Comment by luixxiul** [comment]
@bradleyrichter Do you have mockups of the dialogs or should they be styled according to the payment dialogs? The background-color and the button alignment is I'm talking about.

screenshot 2016-12-15 3 33 58

If so, I'm happy to style them :-D

**Comment by luixxiul** [comment]
As a follow-up of course.

**Comment by diracdeltas** [comment]
@luixxiul @bradleyrichter thanks for offering to help! i would wait until the spec is finalized before working on alignment

**Comment by diracdeltas** [comment]
made some changes based on slack feedback, also added option to render the seed as a phrase (and hide the seed data because it is sensitive)
screen shot 2017-01-13 at 7 36 47 pm
screen shot 2017-01-13 at 9 30 25 pm

**Comment by ayumi** [comment]
Is this a newly breaking test?
```
12) Preferences component "before all" hook:
     Error: Cannot find module 'canvas'
      at Function.hookedLoader [as _load] (node_modules/mockery/mockery.js:111:12)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (node_modules/qrious/dist/cjs/qrious.js:23:14)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:152:7)
      at Function.hookedLoader [as _load] (node_modules/mockery/mockery.js:111:12)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (js/about/preferences.js:39:16)
      at loader (node_modules/babel-register/lib/node.js:144:5)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:154:7)
      at Function.hookedLoader [as _load] (node_modules/mockery/mockery.js:111:12)
      at require (internal/module.js:20:19)
      at Context.<anonymous> (test/unit/about/preferencesTest.js:29:19)
      at Hook.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
```

**Comment by diracdeltas** [comment]
@ayumi good catch, it is a newly breaking test. it did not break for me locally because i installed QRious with the `--no-optional` flag. but apparently this value is not preserved in package.json, so travis tries to require the optional dependencies. looks like a known issue: https://github.com/npm/npm/issues/14185#issuecomment-264879789

**Comment by diracdeltas** [comment]
aaaand i just realized browser-laptop already depends on https://github.com/alexeyten/qr-image, so i might as well use that. fixing now.

**Comment by diracdeltas** [comment]
rebased

**Comment by ayumi** [comment]
it works & lgtm 👑

**Comment by luixxiul** [comment]
Based on the comment above I added ready-for-merge label

**Pull request merged**
