### PR TITLE
fix for ledger list line height, and popup menu shadow

### PR DESCRIPTION
**Pull request by bradleyrichter**
@bbondy @mrose17

### CODE REVIEW

**Comment by bradleyrichter** [comment]
This fixes #3483.

Please check before merging.

**Comment by bradleyrichter** [comment]
image

**Comment by bbondy** [comment]
@diracdeltas can you check and get this landed? I think you'll need to manually rebase.

**Comment by bradleyrichter** [comment]
@diracdeltas Let me cherry pick this with @jkup because it now overlaps today's work...

**Comment by diracdeltas** [comment]
k please ping me when this is ready for review

**Comment by bradleyrichter** [comment]
No longer valid. Closing.

**Pull request closed without merging**
