### PR TITLE
Covers instances of 'GoogleChrome'

### LINKED ISSUE #8181: Instances of "GoogleChrome" only partially replaced
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
The `extensionsUtil.js::bravifyText` method does not cover `GoogleChrome`.

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Use Pocket on an older version of Brave
    2. Update to 0.14.2
    3. Note presence of "GoogleBrave" in new Extensions page

From session-store-1:
```
"base_path": "…Extensions/niloccemoadcdkdjlinkgdfekeahmflj/2.1.17",
"version": "2.1.17",
"id": "niloccemoadcdkdjlinkgdfekeahmflj",
"description": "__MSG_extDescriptionGoogleChrome__",
```
    
- Actual result:
_GoogleChrome_ is not covered by the `bravifyText` method, resulting in _GoogleBrave_ appearing in the new Extensions page.

- Expected result:
Brave should cover the missing case.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
No.

- Is this an issue in the currently released version?
No.

- Can this issue be consistently reproduced?
Yes.

- Screenshot if needed:
image

- Any related issues:

### PR DESCRIPTION
**Pull request by jonathansampson**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fixes #8181

Also removes old stub version of `bravifyText` from _js/about/extensions.js_.

### CODE REVIEW

**Comment by bsclifton** [comment]
@jonathansampson can you update this (and the original issue) to have testing steps? Thanks 😄

**Comment by jonathansampson** [comment]
@bsclifton In this particular case, you would need to have an older session-store-1 file that had Pocket's name/description cached. Upon updating Brave, the cached name/description from session-store-1 would be loaded, and the incorrect value would be shown.

I don't think this will be something we need to watch moving forward.

We could, and probably should, write a few unit tests for `bravifyText` though.

**Comment by bsclifton** [comment]
@jonathansampson ah ok...  unit tests work 😄  Would you be able to make some? (I can help if needed, let me know).  Then we can mark this as no QA needed, since it would be covered by automated tests

**Comment by jonathansampson** [comment]
@bsclifton I still have issues running tests on Windows, but I think Unit Tests will work easier than the Chrome Driver ones. I'll write up a couple tests, and see if they work as expected.

**Pull request merged**
