### PR TITLE
Resolves missing browserAction icon

### LINKED ISSUE #9437: Bitwarden widget not shown on webpages, shows only on about pages
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Bitwarden widget not shown on webpages, shows only on about pages

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.1
rev	84dbc8e
Muon	4.0.3

- Steps to reproduce:
    1. Clean install 0.17.1
    2. Enable bitwarden from `about:preferences#extensions`, wait till the widget is shown
    3. Click on the widget, home screen is shown
    4. Open a new tab and visit gmail.com, widget is not shown, hovering over the empty space shows the tooltip for the widget
    
- Actual result:
Bitwarden widget not shown on webpages, shows only on about pages

- Expected result:
Widget should be shown on all pages 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
bitwarden

- Any related issues:
cc: @kspearrin @bsclifton

### PR DESCRIPTION
**Pull request by jonathansampson**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Fixes #9437 

Test Plan:
1. Enable bitwarden
2. Navigate to google.com

Ensure that bitwarden browserAction icon is visible.

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
I just tried it again and this fix fixes icon problem, but if you click on an icon nothing happens. But if you click on an icon when you are on new tab, popup is shown.

**Comment by jonathansampson** [comment]
@NejcZdovc This PR is meant only to resolve the missing icon issue. I'm going to look into the reason behind unresponsive icons next. Also testing the latest version of bitwarden in the process; attempting to take out as many birds with as few stones as possible :)

**Comment by bsclifton** [comment]
@NejcZdovc looks like you missed 0.20.x when cherry-picking into branches. I went ahead and made sure it's included in there: https://github.com/brave/browser-laptop/commit/e4e0cf671d1cb8ff5e92e605fbfba72885d2c9ed

**Comment by bsclifton** [comment]
BTW- awesome job knocking this out, @jonathansampson 😄

**Comment by NejcZdovc** [comment]
@bsclifton you are right, I forgot that we are already on 0.21 :smile: thank you

**Pull request merged**
