### PR TITLE
Track `isAudioMuted` so that a re-render is triggered via ReduxCompon…

### PR DESCRIPTION
**Pull request by bsclifton**
…ent when state changes

Fixes https://github.com/brave/browser-laptop/issues/10545

Auditors: @NejcZdovc

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
See https://github.com/brave/browser-laptop/issues/10545

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@bsclifton so if I understand correctly this PR, we only have this prop here so that we trigger re-render? If this is the case, can you please add a small comment about it so that someone will not remove it (it's not used anywhere).

**Comment by bsclifton** [comment]
@NejcZdovc that is correct

**Comment by bsclifton** [comment]
@NejcZdovc updated 😄 👍

**Comment by NejcZdovc** [comment]
master eefeaad80d0ffe9ae6ee8f4b19f99794a98cff1d
0.21 8b83b2706
0.20 707522cd7

**Pull request merged**
