### PR TITLE
Menu on Windows now properly responds to ALT

### PR DESCRIPTION
**Pull request by bsclifton**
## Test Plan:
Make sure "Hide menu bar by default" is set to true in Preferences > General

### Alt codes (ensure behavior has not regressed)
1. Launch Brave on Windows and visit `duckduckgo.com`
2. Put cursor inside the search box
3. Hold alt (left alt) and then use number pad to enter 227, then let go of alt
4. Menu status should **not** have changed and there should be the Pi symbol (π) in the search box

### AltGr (ensure behavior has not regressed)
1. Press the right alt button (AltGr) and let go
2. Menu status should **not** have changed

### Multiple keys at the same time
1. Press and hold shift and then also (with shift still pressed in) press left alt (this is commonly used to switch keyboard layout)
2. Menu status should **not** have changed
3. Press and hold shift, then press and hold left alt. Once left alt is pushed in, let go of shift and then let go of alt. You can try to do this slow or fast to simulate someone hitting shift + alt (but letting go of shift first)
4. Menu status should **not** have changed

### Happy path
1. Press left alt (and only left alt) and then let go
2. Menu should toggle 😄 

## Description
Menu on Windows now properly responds to ALT

Menu is now toggled only under these conditions:
- the left ALT key is pressed (ignore AltGr)
- last key pressed was ALT (typing ALT codes should not toggle menu)
- no other key is being pushed simultaneously
- since initial keydown, ALT has been the only key pressed

NOTE: key state is reset when window blurs (in case you used a shortcut that opened a new window, which prevents the keyup handler from firing on release)

Auditors: @jonathansampson, @bbondy

Fixes https://github.com/brave/browser-laptop/issues/5775

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

### CODE REVIEW

**Comment by bsclifton** [comment]
@srirambv would you be able to try this out too before we merge?

**Comment by srirambv** [comment]
- Unable to test the Alt codes using onscreen keyboard. Clicking on Alt+2 in onscreen keyboard is recognized properly and puts the ASCII code in the search box but subsequent 2 is not recognized along with Alt and ends up adding 2 after the ASCII code. 
- AltGtr is working as expected 
- Multiple keys at the same time still needs testing

**Comment by bsclifton** [comment]
quick update- @srirambv and I had tested in person after he plugged in an external keyboard which has the number pad

- Alt codes worked great
- Multiple keys worked OK... except when doing ALT + printscreen. This was captured with https://github.com/brave/browser-laptop/issues/7566

I also updated the text of the original post here to make it clear what functionality worked prior to this PR (meaning we are testing it for regression)

**Comment by bsclifton** [comment]
Given the above, I'll go ahead and merge this one 😄

**Pull request merged**
