### PR TITLE
Active tab update issue

### PR DESCRIPTION
**Pull request by bridiver**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fixes https://github.com/brave/browser-laptop/issues/8974

Test Plan:

Reviewer Checklist:
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

**Comment by bsclifton** [comment]
I think a new Muon version is needed (build is in progress).  This includes the following patch:
https://github.com/brave/muon/commit/4fdf666cf6b8b0492dbf7f5fbdbb9d9f99e1d4bb

When using this code as-is, I was able to cause an issue by setting tab close behavior to the default (parent).  Will retest when new Muon is available 😄

**Comment by bsclifton** [comment]
After the Muon PR, the issues I saw were fixed 👍 

I think he only remaining issue is:
Behaviors for close (when you pick one of the three options) don't seem to work as described
screen shot 2017-05-25 at 8 54 51 am

**Comment by bsclifton** [comment]
My setup:
2 pinned tabs (https://slashdot.org/, https://www.roboform.com/filling-test-all-fields)

`select the last viewed tab` - this always seems to be choosing the 2nd pinned tab, no matter what I do

`select the next tab` - this behavior is inconsistent. Sometimes, it picks the previous tab, sometimes it picks what seems to be a random tab (maybe the previous index?).  If I have two tabs open and try to close the first, it selects the first pinned tab.

`select its parent tab` - this seems to be working for the most part. It doesn't always select the parent though.  If I open the same link via middle clicking 3 times, closing one of them chooses another one (not necessarily the opener)

**Comment by bridiver** [comment]
I pushed a fix for "last active", but I can't replicate any issues with "next tab". "parent" should only go back to the parent if it is also the last active tab, otherwise it should go to "next"

**Pull request merged**
