### PR TITLE
Fixes ledger related tests

### LINKED ISSUE #11477: Failing automated tests on about:preferences#payments
### Description

There are several failing automated tests on `about:preferences#payments`. 

on 0.19.x: https://travis-ci.org/brave/browser-laptop/jobs/286804381#L3491
on master: https://travis-ci.org/brave/browser-laptop/jobs/286804780#L3466

````
  2) Regular payment panel tests add funds welcome screen renders the welcome screen:
     Error: element ("[data-test-id="batWelcomeScreen"]") still not existing after 10000ms
      at elements("[data-test-id="batWelcomeScreen"]") - isExisting.js:46:17
      at isExisting("[data-test-id="batWelcomeScreen"]") - waitForExist.js:67:22

  3) Regular payment panel tests add funds welcome screen renders the wizard when you click next button:
     Error: element ("[data-test-id="batWelcomeScreen"]") still not existing after 10000ms
      at elements("[data-test-id="batWelcomeScreen"]") - isExisting.js:46:17
      at isExisting("[data-test-id="batWelcom
eScreen"]") - waitForExist.js:67:22

  4) Ledger table 2 publishers pin publisher:
     Error: Promise was rejected with the following reason: Cannot read property 'get' of undefined
      at elements("[data-tbody-index="0"] [data-row-index="0"] [data-test-id="siteName"]") - getText.js:18:17
      at getText("[data-tbody-index="0"] [data-row-index="0"] [data-test-id="siteName"]") - ledgerTableTest.js:104:23

  5) Ledger table 2 publishers pin excluded publisher:
     Error: element ("[data-tbody-index="1"] [data-row-index="0"] [data-switch-status="false"]") still not visible after 10000ms
      at elements("[data-tbody-index="1"] [data-row-index="0"] [data-switch-status="false"]") - isVisible.js:54:17
      at isVisible("[data-tbody-index="1"] [data-row-index="0"] [data-switch-status="false"]") - waitForVisible.js:73:22

  6) Ledger table 4 publishers pin 3 publishers and check unpinned value:
     Promise was rejected with the following reason: timeout
  Error
````

### Steps to Reproduce

  1. npm run test

### Brave Version

**about:brave info:**

https://github.com/brave/browser-laptop/commit/52e8d8d24d683aaa33e3bc58e646501204337d48

**Reproducible on current live release:**

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves #11477

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
sadly travis has some problems with windows and it's not working. For now I focused so that it's working locally and will try to fix it later when I will have some time.

Run this command locally `npm run test-ledger`

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@bsclifton tests fixed, can you please re-review

**Comment by bsclifton** [comment]
Looks like now it fails every time for me... none of the tests even run
```
0 passing (28s)
  2 failing

  1) Ledger table 2 publishers "before each" hook for "check if all sites are on the unpinned by default":
     element ("[data-test-id="urlInput"]") still not visible after 10000ms
  Error

  2) Ledger table 4 publishers "before each" hook for "check if all sites are on the unpinned list":
     element ("[data-test-id="urlInput"]") still not visible after 10000ms
  Error
```

**Comment by NejcZdovc** [comment]
@bsclifton for me all tests are passing. Can you try again with clean install? I just rebased it again.

**Comment by bsclifton** [comment]
@NejcZdovc I did a completely fresh install and still get the issue.  What I've tried:
- rebooting
- `npm cache clean --force && rm -rf ~/.node-gyp && rm -rf ~/.electron && rm -rf ./node_modules/ && npm install`
- running with `LEDGER_ENVIRONMENT=staging`

Launching the test opens a new Brave instance... but nothing happens

**Comment by bsclifton** [comment]
Removing milestone; doesn't deliver a feature for the release and I still can't the tests working

The error I'm getting now:
```
clifton@Brians-MacBook-Pro-2 (tests/#11477-ledger *=) $ npm run test-ledger

> brave@0.22.0 test-ledger /Users/clifton/Documents/browser-laptop
> npm run test -- --grep='Ledger table' && npm run test -- --grep='Regular payment panel tests' && npm run test -- --grep='synopsis' && npm run test -- --grep='Advanced payment panel tests'


> brave@0.22.0 test /Users/clifton/Documents/browser-laptop
> cross-env NODE_ENV=test mocha "test/**/*Test.js" "--grep=Ledger table"



  Ledger table
    2 publishers
      1) "before each" hook for "check if all sites are on the unpinned by default"
    4 publishers
      2) "before each" hook for "check if all sites are on the unpinned list"


  0 passing (30s)
  2 failing

  1) Ledger table 2 publishers "before each" hook for "check if all sites are on the unpinned by default":
     element ("[data-test-id="urlInput"]") still not visible after 10000ms
  Error

  2) Ledger table 4 publishers "before each" hook for "check if all sites are on the unpinned list":
     element ("[data-test-id="urlInput"]") still not visible after 10000ms
  Error
```

**Comment by NejcZdovc** [comment]
@bsclifton this is not a problem with this PR, but all tests are failing because of this error now 😢

**Comment by jasonrsadler** [comment]
@NejcZdovc, can you rebase and we'll see if this passes through?

**Comment by NejcZdovc** [comment]
it's still not ready. I see a lot of `Uncaught no such window` errors which I hope will be fixed when single webview is merged into the master. I will run some iterations locally, so that we have at lest local suite working.

**Comment by petemill** [comment]
@NejcZdovc single-webview does not fix anything related to tests. Probably breaks many of them that relied on the `<Frame />` component's DOM elements. Is there something else blocking these tests from working now that automated tests in general are working after #13788 ?

**Comment by NejcZdovc** [comment]
closing in favour of #13874, ported most of the stuff in that PR

**Pull request closed without merging**
