### PR TITLE
Fixes Issue #10752, allows for sorting by publisher verification

### LINKED ISSUE #10752: cannot sort by publisher verification status in about:preferences#payments
- Did you search for similar issues before submitting this one?
yes

- Platform (Win7, 8, 10? macOS? Linux distro?):
macos

- Brave Version (revision SHA):
0.18.23

- Steps to reproduce:
    1. go to about:preferences#payments
    2. click on the first column header to sort by publisher verification status
    
- Actual result:

the table is not sorted

- Expected result:

the table should be sorted

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by ryanml**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

Resolves #10752

Test Plan:
   This can be done through the UI.

   1. Navigate to about:preferences#payments
   2. Click on the first column header to sort by publisher verification status
   3. Ensure that the ordering toggles for verified publishers (ASC/DESC)

Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [x] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

This is a very simple fix for issue #10752. The SortableTable component looks to the 'value' property of a row object as its basis for sorting (We should mimic the configuration for the included row object, where the value property is either set to 1 or 0, depending on whether its turned on). Now the Verified Publisher column sorts as expected. Thanks!

### CODE REVIEW

**Comment by ryanml** [comment]
@NejcZdovc thanks for taking a look at this! :)

**Comment by ryanml** [comment]
@NejcZdovc there is one possible improvment I can make to this PR (It serves more of a visual purpose than a functional one)

Currently, if a publisher is verified and included, the verification icon is green, if a publisher is verified and not included, the verification icon is not filled and is gray.

The fix in this PR is technically functionally satisfying, as it does sort by whether a publisher is _verified_ or not, but it does look a little odd if the non included publishers are staggered throughout the ordering.

If you feel that it would beneficial for inclusion to factor in to the ordering as well, I can adjust the ternary in that value property to:

`verified ? (this.enabledForSite(synopsis) ? 2 : 1) : 0`

This will assign a value of 2 to verified and included publishers, a value of 1 to verified but not included publishers, and 0 for neither verified nor included. (I think this ends up looking a little nicer :)

Let me know your thoughts and I can push this in a commit to this PR.

screen shot 2018-01-21 at 2 39 44 pm

**Comment by NejcZdovc** [comment]
@ryanml I like the idea, go for it

**Comment by ryanml** [comment]
@NejcZdovc I've pushed the improvement :)

**Comment by ryanml** [comment]
@NejcZdovc awesome! :) Thanks so much

**Comment by ryanml** [comment]
@NejcZdovc was 0.20 released? :)

**Comment by NejcZdovc** [comment]
@ryanml it was 😃

**Comment by ryanml** [comment]
@NejcZdovc great! Excited to see this fix in place, I'm working on another as we speak :)

**Comment by NejcZdovc** [comment]
master fd95339d80a63f90ed2e44767babd54092edce2f
0.22 2d14fb394
0.21 d3f8fd1f8

**Comment by NejcZdovc** [comment]
0.21 twitch e0670fd99

**Pull request merged**
