### PR TITLE
replace yes/no to allow/deny for notifcation bar

### LINKED ISSUE #9750: Rename Yes/No buttons to Allow/Deny for easier understanding
## Test plan

https://github.com/brave/browser-laptop/pull/10180#issue-246192245

----

- Did you search for similar issues before submitting this one
Yes?

- Describe the issue you encountered:
>making the controls "Deny" and "Allow" (again, as for Flash) instead of "No" and "Yes" would be more clear to me. More than once, I've nearly clicked "Yes" with the feeling that I was confirming the "remember for this site" checkbox.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
0.16.9

- Screenshot if needed:

- Any related issues:
https://community.brave.com/t/requests-re-block-autoplay-controls/4324

### PR DESCRIPTION
**Pull request by cezaraugusto**
<hr>

### dear reviewer, do not land before #10178. thanks!

<hr>

/cc @bradleyrichter pls see screenshots below. maybe we want to change strings for some questions too?

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Auditors: @luixxiul, @srirambv
close #9750

Test Plan:

notifications bar test should pass

```
npm run test -- --grep="notificationBar permissions"
```

### Autoplay:
got to prefs->security and set autoplay to "always ask"
go to https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_video_autoplay
screen shot 2017-07-27 at 3 23 33 pm

### Restart:
go to  prefs->general and try to switch languages.

screen shot 2017-07-27 at 3 14 43 pm

### Autofill:
go to prefs->security and set pw manager to _built-in_
go to any page that you have to write things so Brave can ask to save that for you
screen shot 2017-07-27 at 3 13 33 pm

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by srirambv** [comment]
Manually tested. Looks good to go

**Comment by bsclifton** [comment]
@cezaraugusto can you rebase? then we're ready for merge 😄

**Comment by cezaraugusto** [comment]
ok rebased waiting travis

**Comment by luixxiul** [comment]
isn't this ready to be merged? :-)

**Comment by srirambv** [comment]
Somethings broken Seeing Yes/No for browser restart 
image

**Comment by cezaraugusto** [comment]
@srirambv what's wrong? should it be no/yes instead?

**Comment by cezaraugusto** [comment]
actually for restart notification it should be yes/no (not sure about the order) but not allow/deny

**Comment by bradleyrichter** [comment]
Should be No/Yes.

**Pull request merged**
