### PR TITLE
fixes failing tab transfer test

### PR DESCRIPTION
**Pull request by bridiver**
https://travis-ci.org/brave/browser-laptop/jobs/239787005#L3218

Strictly speaking this was only a test issue, but I did a small refactoring to make the functionality more consistent and easier to test

Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
can you please check if any of tests that are failing now are related to your change

```
  1) pinnedTabs gets pins from external windows when pinning after creating:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at elements(".pinnedTabs [data-test-id="tab"]") - brave.js:428:21

  2) tab tests tab transfer can move into an existing window:
     undefined: Cannot read property 'tabId' of undefined
      at execute(<Function>) - brave.js:526:19

  3) tab tests tab transfer can detach the last tab into an existing window:
     Promise was rejected with the following reason: timeout
  Error
```

**Comment by bridiver** [comment]
this fixes #3 and was passing for me locally. I'll check on the others

**Comment by bridiver** [comment]
yep, read it wrong. I'll check all 3

**Comment by bridiver** [comment]
looks like a problem with the test themselves, not the code changes. I'll update them

**Comment by NejcZdovc** [comment]
thank you very much

**Comment by bridiver** [comment]
the pinned tab test passes for me and the others are updated

**Pull request merged**
