### PR TITLE
[WiP] extend blue outline in url bar

### LINKED ISSUE #5439: extend blue outline in URL bar to include bookmark button
old: 

image

new:
image

### PR DESCRIPTION
**Pull request by jkup**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fix #5439

Work in progress as I got it working on Mac but I'm still having trouble setting up my Windows VM with Brave.

Test Plan:

Need to make sure urlbar looks like this screenshot and that the bookmark button still works on Windows.

urlbar

### CODE REVIEW

**Comment by jonathansampson** [comment]
Here's what I see on Windows:

image

**Comment by luixxiul** [comment]
I think the better solution here would be to move the bookmark component from `navigationBar.js` into `urlBar.js`. I'm afraid hacking it via CSS would cause a regression someday...

**Comment by bsclifton** [comment]
This'll need a rebase- I'm curious if it would make more sense to close this out for now and revisit after https://github.com/brave/browser-laptop/issues/5891 is done (the sprite story; sprites in the URL bar)

The favicon star could potentially be a new sprite; I know @bradleyrichter was considering a different look for the filled version

Let me know what you think @jkup :smile:

**Comment by jkup** [comment]
@bsclifton that sounds good to me.. what I'm struggling with here is how to get this absolutely positioned star to be clickable in Windows when the input needs to have padding or margin to make it visible.

**Comment by jonathansampson** [comment]
@jkup Safe to delete `blue-icon` now?

**Comment by jkup** [comment]
@jonathansampson yep just got it! I usually go through once a week and remove my stale branches :)

**Comment by jonathansampson** [comment]
@jkup Awesome. Wasn't sure if you planned on keeping it around, for additional tinkering. Figured there was no harm in pinging you :)

**Pull request closed without merging**
