### PR TITLE
Auto complete for the custom bookmark titles in the address bar

### LINKED ISSUE #6104: Address bar should autocomplete from custom bookmark titles
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I sometimes bookmark URLs I'll know I'll need again. When I start typing their names (not just addresses) Brave should match it and suggest a completion.

**Expected behavior:**
Brave doesn't match anything.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac, Windows

- Brave Version:
Brave	0.12.13
Muon	1.4.30
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
Update Channel	dev
os.platform	darwin
os.release	16.3.0
os.arch	x64

- Steps to reproduce:
    1. Bookmark an URL with a distinctive title, e.g. "testmark"
    2. Type "testmark" into the URL bar

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Resolves #6104

## Auditors
@bsclifton, @aekeus, @bradleyrichter

## Test Plan
- Save bookmark with a custom title
- Search in address bar for a custom title
- You should see a bookmark with a custom title in bookmarks section

### CODE REVIEW

**Comment by NejcZdovc** [comment]
What do you think about suggestion window:

image

As you can see now you have a custom title first and then url title in parentheses. Should we display only custom title?

**Comment by bsclifton** [comment]
Reviewer note: this PR can be closed if we remove customTitle (which I believe we should do).

See note in https://github.com/brave/browser-laptop/issues/6108#issuecomment-266189750

**Comment by NejcZdovc** [comment]
@bsclifton should we then close this issue then? I can start working on removing customTitle, but I am not sure under which issue is this stated. #5738 or #6108 or both :smiley:

**Comment by bsclifton** [comment]
@NejcZdovc that would be great! :smile: I'll go ahead and close

Removing customTitle, per the discussion linked above, should fix:
https://github.com/brave/browser-laptop/issues/6104
https://github.com/brave/browser-laptop/issues/6108

I'm not sure if https://github.com/brave/browser-laptop/issues/5738 is affected; this seems like a different situation.  There are likely other issues which have this same root cause.  I'll create a new issue for removing customTitle where we can track them all

**Comment by NejcZdovc** [comment]
@bsclifton great, sounds like a plan. You can assign this issue to me.

**Pull request closed without merging**
