### PR TITLE
use async preferredSize method

### PR DESCRIPTION
**Pull request by bridiver**
requires https://github.com/brave/muon/commit/2695061ae08698a8f656d30e70d916016f256272

Test Plan:
1. Enable LastPass
2. Click on LastPass extension button
3. LastPass popup should be the correct size

### CODE REVIEW

**Comment by bsclifton** [comment]
@alexwykoff @srirambv was there ever an issue filed for the LastPass issue on Windows?  I'm curious if this would fix 😄 
image

**Comment by bridiver** [comment]
@bsclifton this won't fix any functionality afaik, it just changes the method to be async instead of sync

**Comment by bsclifton** [comment]
@bridiver ah ok- thanks for the heads up 😄

**Comment by luixxiul** [comment]
Do we have an associated issue?

**Comment by bridiver** [comment]
this falls in the same category as https://github.com/brave/browser-laptop/pull/6995 for removal of sync webview methods

**Comment by bbondy** [comment]
++

**Comment by srirambv** [comment]
image
@bridiver This is on 0.13.2 RC3 on Windows x64

**Pull request merged**
