### PR TITLE
Add Payments to Bravery system menu

### LINKED ISSUE #3592: add "Enable Brave Payments" to the bravery menu
This will help some users find Brave Payments as one of several paths.

### PR DESCRIPTION
**Pull request by ayumi**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Close #3592

Auditors: @bradleyrichter @diracdeltas

Test Plan:

1. Disable Payments
2. Open OS menu "Bravery"
3. See menu item "Start using Brave payments..." -- click it
4. Tab opens to Prefs > Payments
5. Enable Payments
6. Close tab
7. Open OS menu "Bravery" again
8. Payments menu item now says "Brave payments"
9. Close and reopen Brave
10. Menu item still says "Brave payments"

### CODE REVIEW

**Comment by luixxiul** [comment]
#3675 should be applied here too I think

**Comment by ayumi** [comment]
@luixxiul i like that – i'd like to update it in a new PR

**Comment by bsclifton** [comment]
@ayumi does this also cover the hamburger menu? I know there is shared code (so it might :smile:)
screen shot 2016-09-12 at 1 09 49 pm

**Comment by ayumi** [comment]
@bsclifton yess

screen shot 2016-09-12 at 13 39 18

**Comment by diracdeltas** [comment]
++ thanks

**Pull request merged**
