### PR TITLE
Remove unused deps and update public suffix list

### PR DESCRIPTION
**Pull request by diracdeltas**
Fix https://github.com/brave/browser-laptop/issues/12620

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [x] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by diracdeltas** [comment]
btw - i just noticed we should probably be running `npm install --save tldjs --tldjs-update-rules` and `npm run update-psl` every so often for builds, in order to update the public suffix lists.

we should probably also consolidate `js/lib/psl` and the `tldjs` node module. the browser-laptop filtering functions use `js/lib/psl` via `getBaseDomain` instead of `tldjs` because it was much faster last time i checked, and performance is important for a function that gets run in a blocking manner for every browser request.

**Comment by mrose17** [comment]
where are we calling tldjs in a blocking manner? one of the reasons that the ledger middleware is so "full-figured" is because it goes to a lot of effort to be non-blocking!

**Comment by diracdeltas** [comment]
@mrose17 
1. yes i checked and the API functions you're using from tldjs have not changed
2. it's blocking in filtering.js, not ledger. it needs to block because we can't "block" a tracker after already letting a request go through to it.

**Comment by mrose17** [comment]
@diracdeltas - great!

1. thanks for checking that.
2. understood. i'm not sure if we can actually merge the two databases, so perhaps the current dichotomy is best.

**Comment by diracdeltas** [comment]
0.23.x / 0.24.x: b7b07fc4d7330a78c1695e904f953b665d3f313c

**Pull request merged**
