### PR TITLE
default settings should be last resort

### LINKED ISSUE #6169: built-in password manager should respect preference
c6fc2bjspz

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

fix #6169

Auditors: @bsclifton, @bbondy

### CODE REVIEW

**Comment by bsclifton** [comment]
@darkdh could you add a test for this (so we don't accidentally regress in the future)?

Should be easy enough to add here: :smile: 
https://github.com/brave/browser-laptop/blob/master/test/unit/settingsTest.js

**Comment by darkdh** [comment]
will do

**Comment by darkdh** [comment]
test added in 8df802d

**Comment by bbondy** [comment]
Thanks!

**Comment by bsclifton** [comment]
Great job @darkdh, thanks! :smile:

**Pull request merged**
