### PR TITLE
Make a special opensuse rpm

### LINKED ISSUE #6946: Brave will not install on OpenSuse
- Did you search for similar issues before submitting this one?

https://github.com/brave/browser-laptop/issues/5614
https://github.com/brave/browser-laptop/issues/5580

- Describe the issue you encountered:

Yast complained that there was no GConf2 provider available.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OpenSuse 42.2

- Brave Version (revision SHA):
0.13.0 (edit and 0.13.1)

- Steps to reproduce:
   1. Download brave-0.13.0.x86_64.rpm
    2. Select in Dolphin file manager and pick Install from the right click menu
    3. Provide root password to Yast
    4. Yast shows error message.

brave install fail

I have the packages in related reports loaded and 0.12.15 is running with no issues.

gconf2

keyring

----------------------

Trying the alternate install option via the command line I get these errors:

`p3620:/home/data/download # rpm -i brave-0.13.0.x86_64.rpm
error: Failed dependencies:
        GConf2 is needed by brave-0.13.0-1.x86_64
        libXScrnSaver is needed by brave-0.13.0-1.x86_64
`

### PR DESCRIPTION
**Pull request by posix4e**
Fix #6946

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

**Comment by mati865** [comment]
@posix4e I just noticed both Fedora and openSUSE gconf2 packages seems to provide `libgconf-2.so.4` so it should be possible to use 1 config file.

Output from x86-64 Tumblweed (Leap shouldbe mostly the same):
```
LANG=C zypper info --provides gconf2
Loading repository data...
Reading installed packages...


Information for package gconf2:
-------------------------------
Repository     : openSUSE-20170808-0                
Name           : gconf2                             
Version        : 3.2.6-11.1                         
Arch           : x86_64                             
Vendor         : openSUSE                           
Installed Size : 2.0 MiB                            
Installed      : Yes                                
Status         : up-to-date                         
Source package : gconf2-3.2.6-11.1.src              
Summary        : GNOME Configuration Database System
Description    :                                    
    GConf is a configuration database system for storing application
    preferences. It supports default or mandatory settings set by the
    administrator, and changes to the database are instantly applied to all
    running applications. It is written for the GNOME desktop but doesn't
    require it.
Provides       : [9]                                
    libgconf-2.so.4()(64bit)
    libgconfbackend-oldxml.so()(64bit)
    libgconfbackend-xml.so()(64bit)
    libgsettingsgconfbackend.so()(64bit)
    typelib(GConf) = 2.0
    config(gconf2) = 3.2.6-11.1
    gconf2 = 3.2.6-11.1
    gconf2(x86-64) = 3.2.6-11.1
    /usr/bin/gconftool-2
```
I removed Fedora image some time ago so it would be great if someone could test it there.


Right now I'm building it on oS and I'll report back if it works (ancient CPU).

**Comment by mati865** [comment]
Looks like Brave have to keep using package names instead of lib names because it will download 32-bit libs on 64-bit OS:
```
LANG=C zin '/home/mateusz/Projekty/browser-laptop/dist/brave-0.20.0.x86_64.rpm' 
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 3 NEW packages are going to be installed:
  brave gconf2-32bit libXss1-32bit

3 new packages to install.
Overall download size: 69.1 MiB. Already cached: 0 B. After the operation, additional 291.8 MiB will be used.
Continue? [y/n/...? shows all options] (y): y
Retrieving package gconf2-32bit-3.2.6-11.1.x86_64                                                                                                                             (1/3), 135.0 KiB (365.1 KiB unpacked)
Retrieving: gconf2-32bit-3.2.6-11.1.x86_64.rpm ..............................................................................................................................................................[done]
Retrieving package lib

And result in brave: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory.
Styling with Markdown is supported
ProTip! Add comments to specific lines under Files changed.
Xss1-32bit-1.2.2-11.6.x86_64                                                                                                                            (2/3),  12.1 KiB ( 13.5 KiB unpacked)
Retrieving: libXss1-32bit-1.2.2-11.6.x86_64.rpm .............................................................................................................................................................[done]
Retrieving package brave-0.20.0-1.x86_64                                                                                                                                      (3/3),  68.9 MiB (291.4 MiB unpacked)
Checking for file conflicts: ................................................................................................................................................................................[done]
(1/3) Installing: gconf2-32bit-3.2.6-11.1.x86_64 ............................................................................................................................................................[done]
(2/3) Installing: libXss1-32bit-1.2.2-11.6.x86_64 ...........................................................................................................................................................[done]
(3/3) Installing: brave-0.20.0-1.x86_64 .....................................................................................................................................................................[done]
```

And result in `brave: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory`.

@posix4e Unless you know better solution replace `libXss.so.1` with `libXss1`.

CC @Garbee

**Comment by Garbee** [comment]
Is there an issue with getting a 32bit lib on a 64 bit system? afaik these aren't security libraries.

**Comment by mati865** [comment]
@Garbee This time before installation I removed `gconf2` and `libXss1`, Brave installation pulled only 32-bit libs and Brave failed to start because of missing 64-bit libs. Notice `(64bit)` in this output:
```
LANG=C zypper info --provides libXss1 
Loading repository data...
Reading installed packages...


Information for package libXss1:
--------------------------------
Repository     : openSUSE-20170808-0                      
Name           : libXss1                                  
Version        : 1.2.2-11.6                               
Arch           : x86_64                                   
Vendor         : openSUSE                                 
Installed Size : 14.2 KiB                                 
Installed      : Yes                                      
Status         : up-to-date                               
Source package : libXScrnSaver-1.2.2-11.6.src             
Summary        : X11 Screen Saver extension client library
Description    :                                          
    The X Window System provides support for changing the image on a
    display screen after a user-settable period of inactivity to avoid
    burning the cathode ray tube phosphors. This extension allows an
    external "screen saver" client to detect when the alternate image is
    to be displayed and to provide the graphics.
Provides       : [3]                                      
    libXss.so.1()(64bit)
    libXss1 = 1.2.2-11.6
    libXss1(x86-64) = 1.2.2-11.6
```

For `libXss1-32bit` package it looks like:
```
Provides       : [3]                                      
    libXss.so.1
    libXss1-32bit = 1.2.2-11.6
    libXss1-32bit(x86-32) = 1.2.2-11.6
```

**Comment by posix4e** [comment]
Sgtm

**Comment by cezaraugusto** [comment]
@posix4e in which step is this? could you pls assign reviewers if ready? thanks!

**Comment by posix4e** [comment]
@cezaraugusto  I was waiting for feedback on my package

**Comment by luixxiul** [comment]
@posix4e where is the build available? I'd like to give it a shot

**Comment by mati865** [comment]
@luixxiul `libXss.so.1` should be replaced with `libXss1` to make it work properly on 64 bit.

**Comment by posix4e** [comment]
Ok updated

**Comment by mati865** [comment]
It should be `libXss1` not `libXss` https://software.opensuse.org/package/libXss1

When it's fixed it will lgtm.

**Comment by posix4e** [comment]
woops sorry

**Comment by mati865** [comment]
lgtm

**Comment by luixxiul** [comment]
https://community.brave.com/t/opensuse-install-gconf2-needed-by-brave-0-13-0-1-x86-64/1026/11?u=suguru

> It looks as if they are not concerned about the users of openSUSE. With those error messages I have received when installing Brave on one of my computers (one which is not so important and used for testing). But with the computers I need for work every day I don’t take a risk. Unless I hear that they fixed the packaging for openSUSE I won’t use the Brave browser. I use firejail a lot for sandboxing instead.

**Comment by posix4e** [comment]
So what's blocking?

**Comment by luixxiul** [comment]
pinging @bbondy @darkdh. If nothing blocks, why wouldn't we merge this PR?

**Comment by cezaraugusto** [comment]
cc @luixxiul please help me define if this should/should not be in release notes or if there's anything else from QA side.

**Comment by luixxiul** [comment]
definitely this should be added to the release notes. I have seen many times on the community that the browser did not work on openSUSE.

**Comment by bbondy** [comment]
WE can uplift this to 0.20.x if you don't mind cherry-picking @luixxiul 
Also ok with it going in 0.19.x hotfix 3 but it'd have to wait until hotfix 2 is out.

**Comment by luixxiul** [comment]
I'd agree with going in hotfix 3 👍

**Comment by posix4e** [comment]
+1, I'd love to be around during pkg creation time to help support

**Comment by darkdh** [comment]
0.21.x: aa453f96edf77da6b90aea65a5abbe6edcdfc1e2
0.20.x: 71b210a08c8d7265b47d4d89b315d898d4bf4dec

**Pull request merged**
