### PR TITLE
Disable autoplay

### LINKED ISSUE #2227: Block autoplay videos
Would be nice if You could add an option to block videos from autoplaying as it is one of the most annoying things currently.

### LINKED ISSUE #4045: Add option to enable/disable HTML5 autoplay
**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
It would be nice if Brave had built in way to enable/disable eighter globally or per website the HTML5 autoplay attribute.

If in future we have something like website permissions where the user can choose to enable per website:
- Allow microphone
- Allow video camera
- Allow GPS

This option could be put there as well.
#2227

### LINKED ISSUE #7663: All video in Brave should default with autoplay=false, w/site level opt-in exceptions
- Did you search for similar issues before submitting this one?

Yes - Any features that appear similar also appear to be optional in nature. This specific issue is filed to make the default behavior for all video to not autoplay (requested from @BrendanEich ). 

Autoplay should be opt-in v opt-out within Brave. Minimal negative impact, as many/most mobile browsers require a tap to initiate playback (autoplay = disabled by default on mobile). User should be able to enable globally via prefs to opt-in if desired.

The fast fix for this appears to be at the DOM level, via `video-dom-autoplay.htm`
https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/media/video-dom-autoplay.html?dr=C

```
<!DOCTYPE html>
<title>Test media "autoplay" attribute set via DOM.</title>
<script src="../resources/testharness.js"></script>
<script src="../resources/testharnessreport.js"></script>
<script src="media-file.js"></script>
<video></video>
<script>
async_test(function(t) {
    var video = document.querySelector("video");
    assert_false(video.autoplay);
    video.autoplay = true;
    assert_true(video.autoplay);
    assert_not_equals(video.getAttribute("autoplay"), null);

    video.onplay = t.step_func_done(function() {
        assert_false(video.paused);
    });

    video.src = findMediaFile("video", "content/test");
});
</script>

```

This appears to be the test for ensuring the above setting functions as expected: 

https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/media/video-no-autoplay.html?dr=C

```
<!DOCTYPE html>
<title>Test that play event does not fire when "src" set with no autoplay attribute.</title>
<script src="../resources/testharness.js"></script>
<script src="../resources/testharnessreport.js"></script>
<script src="media-file.js"></script>
<video></video>
<script>
async_test(function(t) {
    var video = document.querySelector("video");
    assert_true(video.paused);

    video.onplay = t.unreached_func();

    video.oncanplaythrough = t.step_func(function() {
        setTimeout(t.step_func_done(function() {
            assert_true(video.paused);
        }), 500);
    });

    video.src = findMediaFile("video", "content/test");
});
</script>
```

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

@bridiver @BrendanEich The above = what I've been able to gather from searching the chromium source, so I'm hoping that if it doesn't provide the full solve, that it at least moves the needle to getting default video playback behavior to disable autoplay across the browser. 

IIRC mobile is a non-issue w/autoplay. 

#4045 #2227

### PR DESCRIPTION
**Pull request by jonathansampson**
Test plan
---
A.
1. Go to https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_video_autoplay
2. Video should not autoplay
3. Click bravey panel to allow autoplay
4. Video should autoplay

B.
1. Go to youtube and watch a video
2. Video should not autoplay
3. Click bravey panel to allow autoplay
4. Video should autoplay

C. Also covered by automatic test

---

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

Resolves #7663
Resolves #2227 
Resolves #4045

### CODE REVIEW

**Comment by jonathansampson** [comment]
@darkdh You mean, a switch inside _about:preferences#shields_?

**Comment by darkdh** [comment]
yeah, we should let users choose control the default global setting of it

**Comment by bridiver** [comment]
can we add tests for this? Preferably using a localhost url and not a remote site
otherwise ++

**Comment by jonathansampson** [comment]
@darkdh Global setting is now set.
@bridiver Working on test(s) next.

**Comment by jonathansampson** [comment]
@bridiver Spectron tests aren't running on Windows. I'm going to try and get it working on my Ubuntu VM, but it could be a day or two. Would you be okay with us merging prior to landing tests?

**Comment by darkdh** [comment]
I can help adding the test from Mac

**Comment by jonathansampson** [comment]
@darkdh That would be awesome! Thanks 🙂

**Comment by gary-schiltz** [comment]
I would also like to see the ability to control the preloading of HTML5 videos, since it consumes bandwidth, even if the user has no intention of watching a video. The desired behavior would be for the browser to act as if the preload attribute of all <video> tags were set to "none" or perhaps "metadata". The test for this would be to clear the browser's cache, visit https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_video_preload, and watch some type of bandwidth indicator.

**Pull request merged**
