### PR TITLE
ledger recovery should be aware of network status and localization

### LINKED ISSUE #4720: Ledger recovery should be aware of network status and give appropriate errors when the connection is down.
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While trying to recover a wallet, my network connection went down.  The error message from the system indicated that my keys were somehow incorrect. Once the network connection was restored, the keys worked without issue. 

**Expected behavior:**
The system should display appropriate error messages. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on OS X
- Brave Version:
  0.12.5
- Steps to reproduce:
  1. Generate recovery keys
  2. Remove your ~brave folder and create a new wallet
  3. Open the recovery dialog, enter keys but do not submit the form
  4. Disable your network connection (or just happen to have a really poor one)
  5. Submit the form
  6. Observe the error message
- Screenshot if needed:
  screen shot 2016-10-13 at 1 01 40 am
- Any related issues:

## Test Plan
  1. Go to Preferences > Payments
  2. Click Advanced Settings
  3. Click Recover Your Wallet
  4. Try to recover with the wrong keys
  5. You should see the "Recovery Failed" overlay
  6. Repeat steps 1-3
  7. Turn off network connection
  8. Try to recover with right or wrong keys
  9. You should see the "Network Error" overlay

### LINKED ISSUE #5806: Brave wallet recovery failure message should be localizable
**Describe the issue you encountered:** https://github.com/brave/browser-laptop/blob/55de60361097819fc0f0d1eeb744ddcf34543e17/js/about/preferences.js#L1131-L1132 is hardcoded and cannot be localized.

screenshot 2016-11-23 13 38 46

**Expected behavior:** It should be localizable

- Brave Version: master branch

- Any related issues:

## Test plan
https://github.com/brave/browser-laptop/issues/4720#issue-182585748

### PR DESCRIPTION
**Pull request by jkup**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fix #4720
Fix #5806

## Test Plan

  1. Go to Preferences > Payments
  2. Click Advanced Settings
  3. Click Recover Your Wallet
  4. Try to recover with the wrong keys
  5. You should see the "Recovery Failed" overlay
  6. Repeat steps 1-3
  7. Turn off network connection
  8. Try to recover with right or wrong keys
  9. You should see the "Network Error" overlay

## Auditors

@mrose17 can you check this logic? typeof object = network problems else data input problem?
@bradleyrichter how does the copy look for (Network Error - Please check your internet connection and try again.)
@bsclifton can you give me a review for the JS code? :) Is there a way to test the network status?

screen shot 2016-12-29 at 9 19 22 pm
screen shot 2016-12-29 at 9 21 58 pm

### CODE REVIEW

**Comment by cezaraugusto** [comment]
For reference, I rebased this commit after #6529 (branch auto-suggest-sites). May be useful when that one lands master.

bd743d9c101717b5e3f7ff98aafa0480151b152a

**Comment by bsclifton** [comment]
This ones not working when I run before or after rebase; we'll need to look into this more

**Comment by luixxiul** [comment]
Another rebase is needed

**Comment by bsclifton** [comment]
Rebased and tried again; nothing is happening when you put a wrong key in and press "recover keys". It seems completely broken

**Comment by cezaraugusto** [comment]
it worked for me while testing for the first time, but tested again now and nothing happens on any described scenario. Did something on Ledger itself have changed? /cc @mrose17.

**Comment by luixxiul** [comment]
https://travis-ci.org/brave/browser-laptop/builds/193831274#L4660

````
4) Payments Panel -> Advanced Panel shows an error popover if one recovery key is missing:
 TypeError: path must be a string or Buffer
````

**Comment by bsclifton** [comment]
Pushing back to 0.13.2 since code is not working and needs attention.  Is this something you'd be able to look at, @mrose17?

**Comment by mrose17** [comment]
i'll plan to take a look

**Comment by bradleyrichter** [comment]
@mrose17 @bsclifton 

perhaps related - this screen shot was taken and then uploaded to twitter:

image

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/pull/6838

**Pull request closed without merging**
