### PR TITLE
Drag and drop should not be allowed to pin a tab for about:blank and about:newtab tabs

### LINKED ISSUE #2395: Drag and drop should not be allowed to pin a tab for about:blank and about:newtab tabs
Currently you can still pin a tab of those types by dragging a tab into the pinnable area (which only appears when there are at least one other pinned tab)

CC @darkdh

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

fix #2395

### CODE REVIEW

**Comment by bbondy** [comment]
is it possible to not even enable the drop zone so a user doesn't think he can drag it onto the pinned tabs section?

**Comment by darkdh** [comment]
Sounds like a better solution and it's more intuitive for users. I will try to figure out how to achieve it.

**Comment by darkdh** [comment]
c12010c has the effect of disabling drop zone. Please take a look.

**Comment by bbondy** [comment]
lgtm, thanks!

**Pull request merged**
