### PR TITLE
 Adds lower amount into monthly budget

### LINKED ISSUE #12465: Add lower and higher amounts to Brave Payments monthly budget choices
As a user, I need more options for monthly budget choices to meet my contribution needs.

image

### LINKED ISSUE #12472: Mute item is missing in the context menu
### Description

While testing #10545 I noticed that menu option is only shown when you switch to another tab.

### Steps to Reproduce

  1. Open https://www.youtube.com/watch?v=kLiLOkzLetE
  2. `Mute` via context menu is missing

**Actual result:**

Mute tab is missing

**Expected result:**
Mute tab menu item should be there

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

### Additional Information

jan-03-2018 09-27-26

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

Resolves #12465

Auditors:

Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@bsclifton fix is basically the same that you did for mute/unmute

**Comment by NejcZdovc** [comment]
@bsclifton nice one, fixed

**Comment by bsclifton** [comment]
master 8a781e27abe13c4813496d1851f84688213512da
0.21.x 86fb1d0b911d273616b5d008818199fb46396b6b
0.20.x b3377bc7fa25ca5bead491934ec066375c44203e

**Comment by bradleyrichter** [comment]
thanks guys!

**Comment by bsclifton** [comment]
0.19.x 43f717b462138d750272309cddd35ebe99290cf1

**Comment by bsclifton** [comment]
Whoops! Just noticed we forgot to add the 200 option 😛

**Comment by NejcZdovc** [comment]
@bsclifton oh really, I didn't even notice it because we were only talking about 10 BAT option 😃

**Pull request merged**
