### PR TITLE
Windows About menu dialog

### PR DESCRIPTION
**Pull request by aekeus**

### CODE REVIEW

**Comment by bbondy** [comment]
Can we just use the same dialog for win and osx? Please do and then merge, thanks.

**Comment by bbondy** [comment]
I prefer to keep the electron base version there too if possible

**Comment by aekeus** [comment]
Adding the electron version should not be a problem. We will need to create a custom form if we want the About windows to look identical between versions.

**Comment by bbondy** [comment]
> Adding the electron version should not be a problem. We will need to create a custom form if we want the About windows to look identical between versions.

I just meant that I wanted the OSX and Windows ones to use the same dialog. Currently the OSX uses the built in role one which doesn't match.   Differences between windows on different Windows version is good and expected.

**Comment by aekeus** [comment]
Added electron and chrome version numbers. Confirmed on both Windows and OSx.

**Comment by bbondy** [comment]
Thanks @aekeus 
Brendan will be happy with this change!

**Comment by bbondy** [comment]
Just noting the electron one should probably read: libchromiumcontent and not Chromium if you get a sec for a followup.

**Pull request merged**
