### PR TITLE
add LastPass

### PR DESCRIPTION
**Pull request by bridiver**
@bbondy 
requires https://github.com/brave/browser-laptop/pull/2311

### CODE REVIEW

**Comment by bbondy** [comment]
yay!

**Comment by NikosEfthias** [comment]
how we can download the version with lastpass i dont see any link is it a secret ?

**Comment by bridiver** [comment]
it will be available in the next release

**Comment by roqstr** [comment]
wasn't 0.11.0 planned for 07/01/16, so yesterday?

**Comment by bbondy** [comment]
Look at github milestones, they are more exact dates.  So Tuesday is planned.  Those dates on the timeline are just estimations and actual ones can vary by a week or two, and factors like surrounding holidays also affect it.

**Comment by rosenpin** [comment]
So how can we install and use the Lastpass extension?

**Comment by NikosEfthias** [comment]
though it has problems with save pass dialog and other dialogs that lastpass opens or searching through your vault within the extension

**Pull request merged**
