### PR TITLE
Fixes window restore and fullscreen

### LINKED ISSUE #3754: Brave doesn't remember last position and size if you set it to start with homepage
## Test plan
1. Open preferences > general
2. Set `Brave starts with` to `My homepage`
3. Move the window to a unique position and resize it also
4. Close Brave and reopen
5. Window should have retained its position

## Original issue description
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
When closed Brave does not retain last window position and size as it should be when re-launched.

_**This happens only if**_ in Settings -> General you set the value for `Brave starts with` to `My homepage`. If you select `Session and tabs from last time` it correctly remembers the position and the size of the window.

**Expected behavior:**
Brave should remember the last window position and size regardless what I choose Brave to load initially.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Linux, Fedora 24
- Brave Version:
  0.12.0dev downloaded from [here](https://github.com/brave/browser-laptop/releases/download/0.12.0dev-RC2/brave-0.12.0.amd64.rpm)
- Steps to reproduce:
  1. In settings -> general set `Brave starts with` to `My homepage`
  2. https://s11.postimg.org/y5tetpkkj/window_bug.gif
- Screenshot if needed:
- Any related issues:

### LINKED ISSUE #6602: Brave does not remember vertical (y axis) amount
## Test plan
1. Open Brave on Windows
2. Position your window, taking note of the Y position
3. Close Brave and reopen
4. Position should be exactly the same as before

## Original issue description
**Did you search for similar issues before submitting this one?**
Yes 
**Describe the issue you encountered:**
When restarting Brave on Windows 10 brave will be positioned correctly in the last place it was before being closed but the vertical size is wrong and looks to be set by default to the max y axis resolution of the monitor. 
**Expected behavior:**
Brave remembers both position and size of previous window. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10
- Brave Version (revision SHA):

- Steps to reproduce:
    1. Close brave
    2. Open brave
    3. Note maximized y-axis 

- Screenshot if needed:

- Any related issues:

### LINKED ISSUE #8600: Brave is not maximized when re-launched
## Test plan
1. Launch Brave on Windows
2. Maximize the window
3. Quit Brave and relaunch
4. Window should open in the maximized state

## Original issue description
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
>However, I still experience this issue. I've only seen screenshots of Windows 10 and references to 'Windows' in general (and Mac OS X and Linux). So perhaps the issue is now limited to previous versions of Windows. I'm experiencing this problem on Windows 7, 64-bit. It does not happen for other programs. 

>User confirmed issue on clean install also

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 64bit

- Brave Version (revision SHA):
Brave: 0.15.1 
rev: ea5024d1f3e47d34de79b70e3cd74f1408c985ce 

- Steps to reproduce:
    1. Open browser in maximized window
    2. Close and  restart the browser
    3. Maximized window not retained
 
- Screenshot if needed:

- Any related issues:
#7664

### LINKED ISSUE #8925: "open in new window" should cascade instead of layering at same x/y
## Test plan
1. Open Brave
2. Use the menu and pick `File` > `New Window`
3. A new window should appear and be offset (see example pics below). Offset should be ~20px

## Original issue description
Cascade amount should be (x20px, y20px).

firefox example:

image

chrome example:
image

### LINKED ISSUE #9709: Restoring session after re-opening windows does not restore position
## Test plan
1. Open preferences > general
2. Set `Brave starts with` to `My windows / tabs from last time`
3. Open a few windows- move them around and resize them
4. Exit Brave and reopen
5. Ensure window position was saved properly

## Original issue description
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Open multiple windows; move them into unique positions
    2. Close Brave
    3. Re-open Brave
    
- Actual result:
Window positions are stacked on top of each other (see screenshot)

- Expected result:
Window position should be saved

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
image

- Any related issues:

### PR DESCRIPTION
**Pull request by NejcZdovc**
### Please don't squash commits

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #3754
Resolves #6602
Resolves #8600 
Resolves #8925 
Resolves #9709

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by luixxiul** [comment]
I'm wondering if this could be merged to 0.21 to do enough QA over releases among various environments

**Comment by NejcZdovc** [comment]
This is targeted for 0.20, so we should keep it here

**Comment by NejcZdovc** [comment]
This PR is complete, I am just writing some tests

**Comment by bsclifton** [comment]
I just did some manual testing- it seems all issues are resolved except for https://github.com/brave/browser-laptop/issues/3754

It always centers the window 🤔

**Comment by NejcZdovc** [comment]
@bsclifton #3754 should be fixed now as well. Can you please re-test?

**Comment by NejcZdovc** [comment]
Webdriver test for #3754 added

**Comment by bsclifton** [comment]
I went through all 5 issues and added steps / fixed the labels 😄  Should be good to go! Merging 👍

**Pull request merged**
