### PR TITLE
Added BetterTTV extension. Fixes #4956

### LINKED ISSUE #4956: Feature Request: BetterTTV Extension for Twitch
**Did you search for similar issues before submitting this one?**
Yes

**Where can we find the extension?**
https://chrome.google.com/webstore/detail/betterttv/ajopnjidmegmdimjlfnijceegpefgped
https://www.nightdev.com/betterttv/

**What do you like about the extension?**
This is a very common extension for viewing Twitch streams. It adds dark mode, better chat abilities, custom emotes, and so much more.

### PR DESCRIPTION
**Pull request by echosa**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:
- Load up the browser.
- Ensure BetterTTV is in `about:extensions`
- Visit https://twitch.tv.
- Ensure that BetterTTV is working:
  - Should have BetterTTV options (like dark mode) available and working
  - When logged in, should have access to BetterTTV emotes

### CODE REVIEW

**Comment by echosa** [comment]
There's currently one issue that may not be an issue. With this extension installed, each time you visit a page on Twitch, you get something like this:

```
[51912:41763:0202/163032:ERROR:ffmpeg_demuxer.cc(1595)] OnReadFrameDone result=-541478725 IsMaxMemoryUsageReached=0
```

I searched around for `ffmpeg_dmuxer`. Doesn't appear anywhere in the Brave code (that I can find), but searching the Internet seems to show it being some sort of issue with Chrome/Chromium. Everything seems to work fine with the extension, so I'm not sure what's going on here. It could be ignorable, but that's certainly not my call.

I was going to file an issue in addition to this PR, as suggested by @jonathansampson, but it feels weird to file an issue for code that's only my machine, so I'm just tacking this onto this PR.

**Comment by bsclifton** [comment]
Unless I'm mistaken, we would prefer not to include extensions in Brave by default. @jonathansampson is [tracking extension support here](https://github.com/brave/browser-laptop/projects/1) and we do plan to eventually open things up

I made sure BetterTTV is being tracked on the list there. Thanks for digging in and trying it out though.  Do all features of the extension work ok?

**Comment by jonathansampson** [comment]
Great work, @echosa!

My apologies if it wasn't initially clear, but _this process_ is only meant for testing an extensions viability in Brave. It's not the means by which we officially support an extension.

At this point, it would be helpful if you enumerated the various scenarios encountered when using this extension, and indicated which (if any) pass. If we have a 100% pass-rate, this suggests we can officially move towards supporting BetterTTV in an upcoming release.

**Comment by echosa** [comment]
Oh, I guess I misunderstood. What is the plan for getting extensions into Brave, then? The extension support card wall doesn't really explain how those extensions will be made available once they're "done". Certainly, you're not expecting everyone to have to pull the git repo and build their own Brave just to add extensions. I guess I was confused and thought that once an extension had been added/tested in a PR (this one still needs more complete testing), that it could be merged in to the public install. I'll still test this extension more extensively (pun intended) and report back here.

**Comment by echosa** [comment]
Update: I built a .app and replaced my existing officially downloaded one with my build one. So far, no issues with Twitch or BetterTTV. It all seems to be working great, which is awesome! I've used the custom emotes, turned on dark mode, gone through the settings and turned some on and some off, backed up my settings to a file. No issues that I've seen!

Still not sure what the plan is for getting it into the hands of other Brave users, though. For now, I can just keep using my own custom version of Brave (yay, open source!) to get BetterTTV and maybe other extensions I can get working (Xmarks, anyone?), but obviously that's not a good general public solution, as the average person won't pull/fork the repo and do a bit of dev work. :-)

**Comment by jonathansampson** [comment]
@echosa Regarding the long-term plan, once an extension has been tested (which is what you've excellently executed here, hehe), we can include it as an option in Brave.

We don't want to ship the source code with Brave, as that would make Brave heavier and heavier. Instead, we tell Brave how to retrieve the extension, should the user wish to enable it in their browser.

You can see how this is achieved over in our Muon project:

https://github.com/brave/muon/blob/dc56987a36a027765221784463e77d8fe3767b90/brave/browser/component_updater/default_extensions.h

**Comment by echosa** [comment]
Oh, ok. That's pretty cool, actually, and makes sense; especially not wanting to ship the source code of a bunch of random extensions. :+1: Thanks! I look forward to the day that BetterTTV is supported! :-D

**Comment by MatthewDLudwig** [comment]
Do we know how close we are to BTTV in Brave especially considering we now can pay twitch creators?  I'm sure a majority of the people who would be willing to donate to twitch creators with BAT will be heavy users who use BTTV or some similar extension.

This extension would be a great selling point!

**Comment by Cackalator** [comment]
really want to use Brave but not having this extension really stops me from using Brave as my main browser

**Comment by jonathansampson** [comment]
@MatthewDLudwig @IceeHot Would you two be willing to hop on a call with me sometime and run through some tests? I'd love to have the ears of two users who are familiar with the extension.

If you're interested, please join the Brave Community Discord: discord.gg/k57tYrS

**Pull request closed without merging**
