### PR TITLE
Fix loading tab regression

### LINKED ISSUE #8550: No progress indicator when reloading page
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
It's a User Experience issue:  I don't see any indication that a page is loading, while it's loading.  I'm sure there's supposed to be a progress indication someplace, but it's either not working or escaping my attention.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS X 10.11.6

- Brave Version (revision SHA):
71fb730

- Steps to reproduce:
    1. Open browser (I've been using it for a number of days, and usually just close the laptop's lid as opposed to shutting down)
    2. Open some website.  
    3. Hit Cmd+r.  Multiple times fi you want.  
    
- Actual result:
I NEVER get a progress indication anywhere.

- Expected result:
Visible indication that the browser has received and understood my keystroke, and that it's now performing some progress - i.e. I can wait for it to complete as opposed to repeating my keystroke.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
I'm not sure I know what this question means.  I've only been using Brave for a week or so, but don't remember this being an issue before - if that helps.

- Is this an issue in the currently released version?
Yes, I updated recently (yesterday?  I can't remember exactly)

- Can this issue be consistently reproduced?
On _my_ machine... every time.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by cezaraugusto**
Auditors: @bbondy, @bsclifton
Fix #8550

Test Plan: 
loading icon should be visible while reloading a tab

### CODE REVIEW

**Comment by bsclifton** [comment]
It might not be straightforward, but I'd love to see tests around this if you are able to @cezaraugusto 😄 

We'd need to mock `AppDispatcher`, from which we can get the reference to `doAction` when register is called.  Then we can call passing in `windowConstants.WINDOW_WEBVIEW_LOAD_START` and verify the result modified the window state appropriately

**Comment by cezaraugusto** [comment]
ok rebased + amended some more tests, ready for re-review

**Comment by bbondy** [comment]
++, took me a minute to see it, but was resulting in `['tabs', 'frames', ...]`

**Comment by bsclifton** [comment]
++! 😄

**Pull request merged**
