### PR TITLE
Fixed display for multiple homepage

### LINKED ISSUE #7442: Multiple homepage not working
## Test plan
1. open preferences
2. Add multiple sites using `%7C` and set Brave to start with Homepage
3. Verify that | is not transformed to %7C (see image below)
4. Relaunch browser, all sites should now be open in tabs

## original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Reported from community https://community.brave.com/t/multiple-home-pages-error-bug/1481/
Adding `|` automatically converts to `%7C` in homepage textfield

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
0.13.4

- Steps to reproduce:
    1. Add `|` in homepage field
    2. Automatically converts to `%7C`
    3. Add multiple sites using `%7C` and set Brave to start with Homepage
    4. Relaunch browser, URL contains the entire list of sites with `%7C` and doesn't load each site in a new tab
    
- Actual result:
Multiple homepage doesnt load

- Expected result:
Multiple homepage should load as per what is set 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes, verified on 0.13.3

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
homepage

- Any related issues:
cc: @NejcZdovc 
#6913 #3110

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [X] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [X] Ran `git rebase -i` to squash commits (if needed).

Resolves #7442

Auditors: @darkdh

## Test Plan
- described in #7442

### CODE REVIEW

**Comment by NejcZdovc** [comment]
Change was introduced here 2d9c234

**Comment by darkdh** [comment]
Could you also add a test to `test/about/preferencesTest.js`?

**Comment by NejcZdovc** [comment]
@darkdh Added test

**Comment by darkdh** [comment]
lgtm. ++!

**Pull request merged**
