### PR TITLE
Ledger server is configurable by ENV variable "LEDGER_SERVER_URL"

### PR DESCRIPTION
**Pull request by willy-b**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist

This supports #4286 (since this makes it easy to point Brave to a Ledger server using Bitcoin testnet)

- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.

### CODE REVIEW

**Comment by willy-b** [comment]
Test plan:
1. Clear local Ledger data
2. Check in browser if my unreliable testnet Ledger server is available: http://ledger-testnet.entropi.info/documentation
3. If it is, run Brave with `LEDGER_SERVER_URL=http://ledger-testnet.entropi.info'
4. Open Preferences->Payments
5. Confirm Wallet can be created
6. Grab wallet address (from Add Funds)
7. Visit a testnet faucet (https://testnet.manu.backend.hamburg/faucet)
8. Confirm testnet bitcoin can be transferred to address

**Comment by mrose17** [comment]
lgtm.

**Comment by willy-b** [comment]
thanks for the review+merge @mrose17!

**Comment by luixxiul** [comment]
I am testing it out and it looks working well. I had to delete the local `ledger-*` files at first.

@willy-b it would be nice if it becomes possible to avoid the 30 min waiting time and funds are added instantly.

screenshot 2016-10-19 0 06 29

**Comment by luixxiul** [comment]
Though the wallet became ready, some kind of error is happening.

screenshot 2016-10-19 0 46 20

**Comment by luixxiul** [comment]
Nevermind, I just restarted brave without the env. it works now 👍 

screenshot 2016-10-19 0 50 25

**Pull request merged**
