### PR TITLE
Site settings cache

### PR DESCRIPTION
**Pull request by bbondy**
Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bsclifton** [comment]
@bbondy is this still a work in progress? Or should we close

**Comment by bsclifton** [comment]
Closing as stale

**Comment by bbondy** [comment]
I have no idea what this is, but seems I wrote a lot of code for it :P . I think it was not working though when I moved to something else.

I think that it is what @diracdeltas properly implemented for a perf gain in Chicago.

**Comment by diracdeltas** [comment]
i only implemented caching for isResourceEnabled, not siteSettings (or at least i don't remember doing it)

**Comment by bbondy** [comment]
I think it was meant to address the same perf problem though, but in any case this isn't needed anymore.

**Pull request closed without merging**
