### PR TITLE
replace eyeball icon for private tab

### PR DESCRIPTION
**Pull request by luixxiul**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Ran `git rebase -i` to squash commits if needed.

partially addresses #547

This PR is intended to submit a temp fix until sunglasses icon will become available in a future release of Font Awesome.

### CODE REVIEW

**Comment by bbondy** [comment]
@bradleyrichter did you want this change?

**Comment by bradleyrichter** [comment]
Nice idea but let's skip this step and just switch to the PNG or SVG files of the "shades".

**Comment by luixxiul** [comment]
OK, got it.

**Comment by bradleyrichter** [comment]
thanks!

**Pull request closed without merging**
