### PR TITLE
Add Copy Image to context menu

### LINKED ISSUE #1174: Add Copying an Image Directly to the Clipboard Through the Context Menu
In most other browsers, you're able to copy an image directly to the clipboard through the context menu by right-clicking it, but in Brave you can't do that. I know copying the image link was recently added to the context menu but it'd be nice to have this feature as well

### PR DESCRIPTION
**Pull request by bbondy**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

I mainly just implemented what I suggested in issue #1174

Fix #1174

Auditors: @diracdeltas

### CODE REVIEW

**Comment by bsclifton** [comment]
LGTM :+1: I can definitely see the code in imageUtil.js being reused when implementing a "Search <engine> for image" feature

**Comment by BrendanEich** [comment]
Indentation of template.push's multiple arguments was off-by-one-indentation-level before, now seems even funkier. Seems better to indent all actual parameters and break lines after commas that separate actuals (so no `, {' at end of line in middle of arg list). Sorry for the drive-by nit, love this feature!

**Comment by bbondy** [comment]
ya it looks wrong but standardJS lints it correctly. I changed to what you said though and it looks nicer, thx for the suggestion.  PR is updated.

**Comment by diracdeltas** [comment]
lgtm!

**Pull request merged**
