### PR TITLE
 Enable swipe gesture only when cursor is in content

### LINKED ISSUE #2684: Trackpad Scrolls Browser Chrome
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Tabs and browser window itself can be scrolled using trackpad. The location bar can become very long and extend beyond, and is clipped by the scrollable window. Scrolling sideways to get to the back button results in history navigation.

**Expected behavior:**
Tabs should not scroll up. The window should not have an outer invisible scrollable area.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS

- Brave Version:

- Steps to reproduce:
I do not know what causes this bug.

- Screenshot if needed:

- Any related issues:
The "trackpad scrolls history" issue.

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

fix #2684

### CODE REVIEW

**Comment by bbondy** [comment]
We should work like chrome here, I think that they disable the gesture but not sure how only when the mouse pointers is on top of the urlbar .

**Comment by bbondy** [comment]
This doesn't seem like a huge thing btw, if there's not an easy solution we could just sit on the issue.

**Comment by darkdh** [comment]
Yeah, focus seems not enough. When cursor is on the urlbar, swipe back/forward can still happen when scrolling.

**Comment by darkdh** [comment]
We should consider only enable gesture when cursor is in content window like Chrome does

**Comment by bbondy** [comment]
Looks great but could you call it enable/disable swipe gesture? start/stop sounds to me like the motion of the swipe gesture is starting.

**Comment by darkdh** [comment]
Sorry for the naming. Already fixed.

**Comment by bbondy** [comment]
++ thanks

**Pull request merged**
