### PR TITLE
Amazon SQS and SNS support

### PR DESCRIPTION
**Pull request by SergeyZhukovsky**
The fix for the sync library. Added support of SQS, SNS notifications.

### CODE REVIEW

**Comment by luixxiul** [comment]
Is this no-qa-needed?

**Comment by ayumi** [comment]
@luixxiul it's currently not manually verifiable, as the required code is in the https://github.com/brave/sync staging branch. after we do a new sync release with SNS+SQS support, we should QA sync within browser-laptop.

**Comment by bsclifton** [comment]
@SergeyZhukovsky @ayumi does there need to be an update to the sync library before this can be merged?  What milestone do you all think it should be in?

**Comment by SergeyZhukovsky** [comment]
@bsclifton we need that to be able to test sync functionality. I would tell we need it as soon as possible. Everything is merged on sync library side.

**Comment by bsclifton** [comment]
@ayumi is this safe to merge before sync is released? If so, maybe we can merge it and tentatively put it (and the issue, if there is one) in the 0.22.x milestone 😄

**Comment by ayumi** [comment]
@bsclifton yes, this is safe to merge

**Comment by kjozwiak** [comment]
Removing the `QA/test-plan-required` tag as per https://github.com/brave/browser-laptop/pull/11655#issuecomment-340216208.

**Pull request merged**
