### PR TITLE
fallback to placeholder when currency address is fetching

### LINKED ISSUE #11460: add error to Transition Overlay if error occurs when changing wallet from BTC -> BAT
### Description
BTC --> BAT wallet is taking more time than expected during QA (30-40+ minutes). Per discussions, if an error occurs during this process we should display this error on the transition overlay/progress screen. TBD: wording for this and if we show generic error or raw error. cc @davidtemkin @bsclifton @NejcZdovc 

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**
If error occurs, there isn't an indication on the transition overlay.

**Expected result:**
Error to be displayed, text and what kind of error are TBD.

**Reproduces how often:** [What percentage of the time does it reproduce?] unknown

### Brave Version

**about:brave info:**
Brave | 0.19.43
rev | 24df93d
Muon | 4.4.27

**Reproducible on current live release:**
n/a

### LINKED ISSUE #11589: addresses & QR codes not always being displayed when creating wallet
### Description

It looks like the funding address are appearing instantly under ` 0.19.48`. Under `0.19.53`, the addresses appear once Brave has contacted the payment service and retrieves the rates which seems like a regression.

If you have a really slow internet connection or our backend payment service is slow for some reason, new users will see a blank address/QR code when attempting to fund their wallets. The first case where a users internet/network is slow isn't the end of the world, but if our servers are having issues, new users won't be getting addresses nor QR codes. When we were having issues earlier in the week with the servers, it took a while for funding address and QR codes to appear.

### Steps to Reproduce

  1. start bogging down the network to simulate a slow internet connection... I usually start syncing the ethereum mainnet and download an Ubuntu ISO at the same time
  2. launch `0.19.53` with a new profile and visit `about:preferences#payments`
  3. enable payments and quickly click on "Add Funds" -> "Next" and select a funding option

Once Brave starts pulling the rates from the payment service, the address and QR codes will appear.

**Actual result:**

Funding addresses not appearing under Brave with a new profile until contact with the payment service has been made and the rates have been pulled into the browser.

qr

**Expected result:**

Funding addresses should be generated and appear right after the wallet has been created.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% reproducible when

### Brave Version

**about:brave info:**

> Brave: 0.19.53 - Reproducible
> rev: e09025bf61debc46c03459def2501b3367f182d7 
> Muon: 4.4.29 
> libchromiumcontent: 61.0.3163.100 

**Reproducible on current live release:**

No, not reproducible in the latest released version:

> Brave: 0.19.48 - Couldn't Reproduce
> rev: de939f6dcd1647f43de544b22dfdd103585b4ec2 
> Muon: 4.4.28 
> libchromiumcontent: 61.0.3163.100

### PR DESCRIPTION
**Pull request by cezaraugusto**
fix #11460
fix #11589 

Input placeholder should be filled in case the wallet address is still fetching. Solution matches Brad spec.

screen shot 2017-11-02 at 4 38 12 pm

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@cezaraugusto not sure why this PR would close #11460?

**Comment by cezaraugusto** [comment]
ya @bradleyrichter said so

**Comment by NejcZdovc** [comment]
ok :smile:

**Comment by bsclifton** [comment]
master https://github.com/brave/browser-laptop/commit/e64969359ea1bc253478477e4adb41f983805e43
0.21.x https://github.com/brave/browser-laptop/commit/d40a7937b50a4762343cb066d60cd9f114f60dea
0.20.x https://github.com/brave/browser-laptop/commit/134f8ee1360a62e7b24d4dfaf875673089da4151
0.19.x https://github.com/brave/browser-laptop/commit/33e990e8eab5741cc6348dc37bcfdd092027b336

**Comment by kjozwiak** [comment]
Use case mentioned in https://github.com/brave/browser-laptop/issues/11589#issue-266370336.

**Pull request merged**
