### PR TITLE
Fixes sortTable default sort

### LINKED ISSUE #13721: Sort ledger table based on %
### Test Plan
https://github.com/brave/browser-laptop/pull/13726

### Description

Ledger table should be sorted based on % in desc order.

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves #13721

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
1) start browser on clean profile
2) enable payments
3) close browser
4) run `npm run add-simulated-synopsis-visits 20`
5) start browser again and make sure that table is sorted by % desc 

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by jasonrsadler** [comment]
screen shot 2018-04-10 at 3 27 48 pm

This works great but if I keep the preferences tab open it doesn't update until I close preferences and reopen

**Comment by NejcZdovc** [comment]
@jasonrsadler nice find. I think that I need to re-think this one. Because if I add specific default sort row then refresh table is not triggered correctly anymore from `tableSort` library

**Comment by jasonrsadler** [comment]
Let me know if I can help

**Comment by NejcZdovc** [comment]
master 12d502f
0.23 2cb1beb07
0.22 43770d03e

**Comment by NejcZdovc** [comment]
this PR was reverted in #14106

**Pull request merged**
