### PR TITLE
Use non-script version of DuckDuckGo when blocking script

### LINKED ISSUE #3118: Minor:Brave uses incorrect search URL for DuckDuckGo with JS disabled
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Disabled javascript, set DuckDuckGo as main search engine, searching from URL bar leads to https://duckduckgo.com/?q=test&t=brave instead of https://duckduckgo.com/html?q=test&t=brave

**Expected behavior:**
Should search at https://duckduckgo.com/html?q=test&t=brave

- Platform (Win7, 8, 10? macOS? Linux distro?):
any

- Brave Version:
0.11.4

- Steps to reproduce:
    1. set javascript to off
    2. set duckduckgo as search engine
    3. search from URL bar

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

fix #3118

Auditors: @bbondy

### CODE REVIEW

**Comment by bbondy** [comment]
++

**Comment by bbondy** [comment]
If we find this is common for other engines we might want to put it in the json file but I don't think it is.

**Comment by darkdh** [comment]
Sure thing.

**Comment by pira** [comment]
thanks for prompt fix!

**Pull request merged**
