### PR TITLE
Disable View page source on chrome-extension pages

### LINKED ISSUE #4812: "View Page Source" on about:history opens nothing
**Describe the issue you encountered:** If you click "view page source" of the common context menu on about:history, nothing is shown

clipboard01

**Expected behavior:** it should be either removed or grayed out
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.5 RC1
- Any related issues: #4811

### PR DESCRIPTION
**Pull request by Sh1d0w**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fixes #4812

Auditors:
@bbondy

### CODE REVIEW

**Comment by luixxiul** [comment]
Rather I'm thinking that the common context menu itself on about pages should be disabled.

**Comment by Sh1d0w** [comment]
@luixxiul Ok I am closing the PR. I read in the original issue you have opened you wanted the element eighter hidden or grayed out ... :)

**Comment by luixxiul** [comment]
yes sorry @Sh1d0w still you don't have to close the issue as it was not decided to disable it. Also in this case other elements should be grayed out too like 1Password, reload page, etc. Find, print, bookmark page would be useful here too.

**Comment by Sh1d0w** [comment]
@luixxiul I have removed Reload, Back, Forward, View Source and 1Password entries if you are on extension page. Can you please confirm the behaviour is correct like this? Thanks

**Comment by bbondy** [comment]
We should only disable the things which do not work, can you confirm if that's the case in the PR?
Do any of these work?
> Also in this case other elements should be grayed out too like 1Password, reload page, etc, while Find, print, bookmark page would be useful here.

**Comment by Sh1d0w** [comment]
@luixxiul Can you confirm the items I have removed are ones that do not work?

**Comment by luixxiul** [comment]
These do not work
- 1Password
- Reload page

These work
- Back
- Forward
- Find 
- Print
- Bookmark page
- Inspect Element

**Comment by Sh1d0w** [comment]
@bbondy The PR is updated. Let me know if I have to amend anything else.

**Comment by bbondy** [comment]
What doesn't work about extension pages and reload? I'm wondering because our pdf viewing is done without reloading.  Are you sure it doesn't work?

**Comment by bbondy** [comment]
It seems like it should

**Comment by bsclifton** [comment]
Closing this PR in favor of https://github.com/brave/browser-laptop/pull/5559 which disables context menu items ONLY on the about pages.

Apologies that we didn't communicate more about this one :frowning_face: It probably should have only solved the about pages, unless there is an existing issue for the other work

**Pull request closed without merging**
