### PR TITLE
Made all place of Cubits/buybitcoinworldwide.com button clickable

### LINKED ISSUE #6050: Not all place of Cubits/buybitcoinworldwide.com button is clickable
**Describe the issue you encountered:** Not all place of "Cubits" button is clickable

screenshot 2016-12-07 4 47 23

**Expected behavior:** It should be clickable

- Brave Version: master branch

- Steps to reproduce:
    1. Disable `worldWidePanel`
    2. Open about:preferences#payments 
    3. Click the top left corner of "Cubits" button

- Screenshot if needed:

- Any related issues: #5679

### PR DESCRIPTION
**Pull request by luixxiul**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Auditors: @bsclifton @bbondy

Fixes #6050

Test Plan:
1. Disable "worldWidePanel"
2. Open about:preferences#payments
3. Click the top left corner of "Cubits" button
4. Enable "worldWidePanel"
5. Open about:preferences#payments
6. Click the top left corner of "buybitcoinworldwide.com" button

### CODE REVIEW

**Comment by jkup** [comment]
This could probably just be an anchor, right?

**Comment by luixxiul** [comment]
Because having `button` element here maintains the consistency (the other buttons on the modal have been replaced from `span` to `button`) I think we should keep it.

**Comment by bsclifton** [comment]
After reviewing, I believe the same change needs to be made here:
https://github.com/brave/browser-laptop/pull/6051/files#diff-e3eeb751016b2ce9f8278efce585a461R373

I ran into the same issue when I was shown the `buybitcoinworldwide.com` button

**Comment by luixxiul** [comment]
Updated, thanks @bsclifton :-)

**Comment by bsclifton** [comment]
Works great, thanks! :smile:

**Pull request merged**
