### PR TITLE
Show history on long click over back button

### PR DESCRIPTION
**Pull request by bsclifton**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

Shows context menu when click-and-hold over back button. Works great, except it'll continue to propagate the click (opening this PR while I figure that part out- help is appreciated)

Will fix https://github.com/brave/browser-laptop/issues/1622 (although, it doesn't match the wireframe yet)

### CODE REVIEW

**Comment by bbondy** [comment]
Looking good but still needs some things before we can merge it in:
- We should show titles instead of URLs, it would be ideal to get it from electron if available there, but if not you can use the app state's `sites`.
- Pls also add favicons to the left of the items.
- The amount of time you have to hold is too long currently. See chrome/firefox for a comparison.
- Pls also do the same type of thing for the forward button.

**Comment by bsclifton** [comment]
Awesome feedback- I'll be doing my best to get it matching the mockup provided by @bradleyrichter 

Would it make sense to encapsulate the back/foward buttons as a React component? It could help keep main.js clean and would encapsulate the event handlers too

**Comment by bbondy** [comment]
Yep, in general, the more smaller react components the better.

**Comment by bsclifton** [comment]
Going to close this PR for the moment while I implement the feedback.  Thanks, folks :smile:

**Pull request closed without merging**
