### PR TITLE
Remove 'chrome-extension://*' prefix from URL bar

### LINKED ISSUE #2534: Remove prefix from URL bar of PDF files
**Describe the issue you encountered:**
Remove the prefix ``chrome-extension://jkpcbbnkhhgoelcjhhgknpjcopjeande/`` from the URL of a tab which opens a PDF file with the html5 reader. It must be annoying for users when they want to copy the URL.

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: master branch

- Screenshot if needed:
screenshot 2016-07-17 13 54 04

- Any related issues: #2513 #2527 #2530

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Ran `git rebase -i` to squash commits if needed.

fix #2534

### CODE REVIEW

**Comment by bbondy** [comment]
Thanks for the patch, we should go with the more generalized `startsWith` then substring exact check though because there are some extension URLs we don't want to truncate.  One example is if you enable dashlane it will open a sign in chrome extension page and make available a dashlane preferences page which is a chrome-extension URL.

**Comment by darkdh** [comment]
You are right. We cannot always truncate all the chrome-extension URL. 
888c5fa will be more flexible.

**Comment by diracdeltas** [comment]
This should probably only happen if PDFJS is enabled in prefs. Otherwise LGTM!

**Comment by darkdh** [comment]
Thanks @diracdeltas. Checking prefs is in bba8abf.

**Comment by diracdeltas** [comment]
lgtm! please squash commits and i'll merge

**Pull request merged**
