### PR TITLE
Make *Submit feedback* link go to wanted page

### LINKED ISSUE #6252: Submit feedback under helpful hints opens about:blank page and not community webpage
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Submit feedback under helpful hints opens about:blank page and not community webpage

**Expected behavior:**
Should launch https://community.brave.com/ when click on submit feedback

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 4

- Steps to reproduce:
    1. Open preferences page
    2. Click on Submit feedback link under helpful hints
    3. Opens about:blank tab but doesn't open community webpage
    4. Select Submit Feedback/Report an issue from menu, opens up community webpage
    5. Select Submit Feedback/Report an issue from hamburger menu, opens up community webpage

- Screenshot if needed:
feedback

- Any related issues:

### PR DESCRIPTION
**Pull request by cezaraugusto**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits (if needed).

Auditors: @bsclifton

Fix #6252

Test Plan:

* Open preferences page
* On page sidebar, Click on *Submit feedback* link under helpful hints
* Link should open and go to https://community.brave.com/

### CODE REVIEW

**Comment by bsclifton** [comment]
I'm not sure this is needed- although this does work around the issue, the root cause seems to be captured with https://github.com/brave/browser-laptop/issues/5880

It seems that any anchor tag is having an issue when trying to open a target=_blank.  @darkdh do you agree?  For example, this button also is broken on Preferences > Payment
screen shot 2016-12-18 at 12 40 54 am
:

**Comment by luixxiul** [comment]
Also #6152? The link to cubits.com does not work either.

**Comment by bbondy** [comment]
We should keep the code as is and wait for @bridiver to fix #5880. I'm going to close this.

**Comment by darkdh** [comment]
Agree with @bbondy

**Pull request closed without merging**
