### PR TITLE
Optimize PNG images losslessly via zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
As this is not a code level change so I didn't use the original pull request template, hope it's sitll fine for you guys.

This lossless recompression optimized 50 PNG images as below to help deliver smaller :package: ! Save a little bit disk space and bandwidth for the users :tada: 
```
 app/extensions/brave/img/braveAbout.png                           | Bin 12109 -> 8965 bytes
 app/extensions/brave/img/braveBtn.png                             | Bin 2130 -> 1000 bytes
 app/extensions/brave/img/braveBtn2x.png                           | Bin 18101 -> 2796 bytes
 app/extensions/brave/img/braveBtn2x_hover.png                     | Bin 4689 -> 3474 bytes
 app/extensions/brave/img/braveBtn3x.png                           | Bin 5913 -> 4337 bytes
 app/extensions/brave/img/braveBtn3x_hover.png                     | Bin 7219 -> 5854 bytes
 app/extensions/brave/img/braveBtn_hover.png                       | Bin 2386 -> 1349 bytes
 app/extensions/brave/img/bravePluginAlert.png                     | Bin 4463 -> 3613 bytes
 app/extensions/brave/img/coinbase_logo.png                        | Bin 8993 -> 6405 bytes
 app/extensions/brave/img/empty_favicon.png                        | Bin 990 -> 85 bytes
 app/extensions/brave/img/extensions/1password-128.png             | Bin 15150 -> 11892 bytes
 app/extensions/brave/img/extensions/bitwarden-128.png             | Bin 2443 -> 1674 bytes
 app/extensions/brave/img/extensions/dashlane-128.png              | Bin 13716 -> 10076 bytes
 app/extensions/brave/img/extensions/enpass-128.png                | Bin 17757 -> 13069 bytes
 app/extensions/brave/img/extensions/honey-128.png                 | Bin 16030 -> 10013 bytes
 app/extensions/brave/img/extensions/lastpass-128.png              | Bin 2654 -> 1224 bytes
 app/extensions/brave/img/extensions/metamask-128.png              | Bin 5770 -> 4607 bytes
 app/extensions/brave/img/extensions/pinterest-128.png             | Bin 7334 -> 4623 bytes
 app/extensions/brave/img/extensions/pocket-128.png                | Bin 8525 -> 6427 bytes
 app/extensions/brave/img/favicons/semanticscholar.png             | Bin 2467 -> 986 bytes
 app/extensions/brave/img/favicons/startpage.png                   | Bin 1344 -> 577 bytes
 app/extensions/brave/img/ledger/fakeQRcode.png                    | Bin 12654 -> 7807 bytes
 app/extensions/brave/img/ledger/uphold_logo_medium.png            | Bin 25102 -> 20960 bytes
 app/extensions/brave/img/ledger/uphold_logo_small.png             | Bin 11100 -> 9508 bytes
 app/extensions/brave/img/newtab/defaultTopSitesIcon/appstore.png  | Bin 10070 -> 4505 bytes
 app/extensions/brave/img/newtab/defaultTopSitesIcon/facebook.png  | Bin 3711 -> 2099 bytes
 app/extensions/brave/img/newtab/defaultTopSitesIcon/playstore.png | Bin 7062 -> 5548 bytes
 app/extensions/brave/img/newtab/defaultTopSitesIcon/twitter.png   | Bin 2113 -> 2109 bytes
 app/extensions/brave/img/newtab/defaultTopSitesIcon/youtube.png   | Bin 1510 -> 1491 bytes
 app/extensions/brave/img/private_internet_access.png              | Bin 2933 -> 2909 bytes
 app/extensions/brave/img/private_internet_access_2x.png           | Bin 2700 -> 2693 bytes
 app/extensions/brave/img/sync-128.png                             | Bin 6703 -> 3378 bytes
 app/extensions/brave/img/sync-16.png                              | Bin 1093 -> 419 bytes
 app/extensions/brave/img/sync-48.png                              | Bin 2436 -> 1109 bytes
 app/extensions/torrent/img/webtorrent-128.png                     | Bin 5762 -> 4123 bytes
 app/extensions/torrent/img/webtorrent-16.png                      | Bin 1295 -> 510 bytes
 app/extensions/torrent/img/webtorrent-48.png                      | Bin 1876 -> 1297 bytes
 app/extensions/torrent/img/webtorrent.png                         | Bin 21521 -> 21475 bytes
 img/mediaProviders/youtube.png                                    | Bin 348 -> 231 bytes
 res/background.png                                                | Bin 24793 -> 15996 bytes
 res/beta/app.png                                                  | Bin 111572 -> 57919 bytes
 res/beta/brave_installer.png                                      | Bin 172496 -> 123375 bytes
 res/dev/app.png                                                   | Bin 111926 -> 57121 bytes
 res/dev/brave_installer.png                                       | Bin 170679 -> 120661 bytes
 res/developer/app.png                                             | Bin 152127 -> 80512 bytes
 res/developer/brave_installer.png                                 | Bin 186937 -> 133503 bytes
 res/nightly/app.png                                               | Bin 156295 -> 82425 bytes
 res/nightly/brave_installer.png                                   | Bin 187797 -> 132689 bytes
 res/start-tile-150.png                                            | Bin 6956 -> 5123 bytes
 res/start-tile-70.png                                             | Bin 3338 -> 2167 bytes
```

### CODE REVIEW

**Comment by srirambv** [comment]
@PeterDaveHello could you please open an issue for this and link in the PR?

**Comment by RasPat1** [comment]
While this is a great improvement it seems that the benefit will be lost over time when images are added/modified/removed. Should we add image compression to the build process to ensure that we are shipping the smallest size images? Alternatively, we can add a utility or a command that allows the dev to compress specific images before committing. This would be added to docs and a developer could run them in same way they could run a local test suite.

**Comment by bsclifton** [comment]
@RasPat1 that would be my vote too- simply having the optimized images isn't enough since they may change. The ideal solution would be to have an npm task like `npm run optimize-images`. 

@PeterDaveHello I'd recommend opening an issue capturing this 😄 I'll close this PR for now in favor of that approach

**Comment by PeterDaveHello** [comment]
I'm not sure how the issue would look like, to discuss to optimize or not ... or the method to optimize, etc? Thanks.

**Pull request closed without merging**
