### PR TITLE
Refactor autofillAddressPanel.js and autofillCreditCardPanel.js

### LINKED ISSUE #8099: Refactor autofillAddressPanel.js with commonForm
**Describe the issue you encountered:**

Refactor autofillAddressPanel.js, replacing `.genericForm` with `commonForm`.

- Any related issues: #8010

### LINKED ISSUE #8100: Refactor autofillCreditCardPanel.js with commonForm
**Describe the issue you encountered:**

Refactor autofillCreditCardPanel.js, replacing `.genericForm` with `commonForm`.

- Any related issues: #8010 #8099

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #8099
Closes #8100
Addresses #7989

- Added CommonFormLarge
- Added cx to dialog.js for more readability
- Refactored with commonForm, replacing it with genericForm
  Aligned labels to the left and input textboxes to the right by applying display:flex
- Removed .manageAutofillDataPanel from form.less

Also:
- Edited autofillTest.js and autofill.js
  TODO: refactor autofill.js with Aphrodite
- Edited selectors.js

Auditors:

Test Plan:
1. Automated tests should pass
2. Open about:autofill
3. Add an address
4. Add a credit card
5. Visit https://www.roboform.com/filling-test-all-fields
6. Make sure the input forms can be filled

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

### CODE REVIEW

**Comment by luixxiul** [comment]
screenshot 2017-04-07 3 47 26
screenshot 2017-04-07 3 47 38

**Comment by cezaraugusto** [comment]
sorry for delaying on this, could you rebase?

**Comment by luixxiul** [comment]
np, after QA work.

**Comment by luixxiul** [comment]
@cezaraugusto would you review again? if OK I'll merge this in, thanks.

**Pull request merged**
