### PR TITLE
Replace End-User-FAQ link on preferences.js

### LINKED ISSUE #11946: Fix broken link to FAQ for home page setting (in preferences)
### Description

Replace the End-User-FAQ link on preferences.js.

The info icon on about:preferences is linked to https://github.com/brave/browser-laptop/wiki/End-User-FAQ#how-to-set-up-multiple-home-pages, which was deprecated in favor of https://community.brave.com/t/how-to-set-up-multiple-home-pages. Since anyone can edit the wiki, the link is (actually has been) a security risk.

### Steps to Reproduce

  1. Open about:preferences
  2. Click the info icon

**Actual result:**

The wiki edit page is opened.

**Expected result:**

The community topic should be opened

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

Yes.

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #11946

Auditors:

Test Plan:
1. Open about:preferences
2. Click the info icon
3. Make sure https://community.brave.com/t/how-to-set-up-multiple-home-pages/9998 is opened

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by luixxiul** [comment]
Since this is a security risk, I'm adding the nearest milestone.

**Comment by bsclifton** [comment]
master 7024bff5a32cb955efac287d53a0f2bb4c85b5f9
0.21.x 404cab0ad1e4d0e06bc5013d7672a2c61f527147
0.20.x 4d7df39c72cf879a1add05afa3257329b0f4e63d
0.19.x in progress

**Comment by luixxiul** [comment]
OK, I'm checking 😄

**Comment by luixxiul** [comment]
preferences.js on `0.19.x` does not have `globalStyles` yet 😮 

`const globalStyles = require('../../app/renderer/components/styles/global') `

See: https://github.com/brave/browser-laptop/commit/75e8f557b6f21e5b1a8292bacf465cd9960cbf08#commitcomment-25606250

**Comment by bsclifton** [comment]
@luixxiul ah ok

I reverted in 0.19.x with https://github.com/brave/browser-laptop/commit/54c1e07aed2e4896f2ccd4cb903cfe552dac8998 and did a bare-bones update (URL only) with https://github.com/brave/browser-laptop/commit/499688e9eb59ea5a8edf86533454676270f6cdf4

**Comment by luixxiul** [comment]
Thanks!!

**Pull request merged**
