### PR TITLE
History page now properly opens new tab w/ link that was clicked

### PR DESCRIPTION
**Pull request by bsclifton**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fixes https://github.com/brave/browser-laptop/issues/4909

Auditors: @darkdh

Test Plan:
1. Launch Brave and visit a few sites
2. Visit about:history
3. Double click one of the entries and confirm it opens the location in a new tab

### CODE REVIEW

**Comment by bsclifton** [comment]
NOTE: I did not see any code change responsible for this. All that was changed was updating the code to use the immutable.js style accessors (versus directly accessing)

**Comment by darkdh** [comment]
I think it's https://github.com/brave/browser-laptop/commit/57086b8c73d9494d0d61b497872379e5c38cd4d3#diff-237402632b025505a0517d846e9e32c1R28

**Comment by darkdh** [comment]
++

**Comment by bbondy** [comment]
It wasn't because that commit is from 0.116 and this worked in 0.12.4.  But probably someone changed the callback handling inside SortableTable or something similar within the last week.

**Comment by darkdh** [comment]
Sorry for the wrong reference. The malfunction start from this commit eea84e53ac1bd57a9586f99373e2eb1f6061ca57

**Comment by bsclifton** [comment]
Good find @darkdh, that is indeed it. Unfortunately, this bug exists in 0.12.5 and was shipped :frowning_face:

**Comment by bbondy** [comment]
we were aware just before shipping but decided not to cancel the release yesterday for a respin.

**Pull request merged**
