### PR TITLE
Removes unnecessary width/height

### LINKED ISSUE #7403: Right click not dismissing / hiding an open menu  (Windows only)
## Test plan
1. Launch Brave on Windows
2. Visit Preferences, disable `Hide the menu bar by default`, and confirm the menu shows up
3. Click any menu item, such as the `View` menu and wait for the menu to display
4. Right click any area to the right of the menu and confirm the menu closes

See the GIF below (in this post) for what it looks like when it fails to close

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Right click doesn't clear menu bar 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	7373a01

- Steps to reproduce:
    1. Enable menu bar from settings
    2. Open any menu bar item
    3. Right click on the browser window, menu item is not dismissed 
    
- Actual result:
Menu item is not dismissed on right click 

- Expected result:
Should dismiss menu item when right click/left click

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
rclick

- Any related issues:
cc: @NejcZdovc

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Resolves #7403 #7662 #1589

## Auditors 
@bsclifton

## Test Plan
- see each issue for detailed steps

### CODE REVIEW

**Comment by luixxiul** [comment]
@NejcZdovc does this close #1589 too?

**Comment by NejcZdovc** [comment]
@luixxiul yeah I think it does

**Comment by luixxiul** [comment]
@NejcZdovc Sweet :-)

**Comment by NejcZdovc** [comment]
@bsclifton what do you mean exactly with the overflow?

**Comment by bsclifton** [comment]
@NejcZdovc the screenshot doesn't capture it very well, but the div itself is overflowing on the Y axis which causes the scrollbar to be shown to the right of the context menu

**Comment by NejcZdovc** [comment]
Yes scroll bar should be there and `overflow-y: hidden` will prevent scrolling. Should we add a custom scroll bar?

cc @bradleyrichter

**Comment by bsclifton** [comment]
Moving back to 0.13.7 because of the design feedback needed

**Comment by cezaraugusto** [comment]
I think this case could benefit from using [scrollbar](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) pseudo-element since we're on Webkit

**Comment by NejcZdovc** [comment]
@bsclifton @cezaraugusto @bradleyrichter I would suggest that for this version 0.14.1 we add webkit scroller (as suggested by @cezaraugusto) on the left side of the root context menu. For the next release we do a complete rewrite of a context menu to the macOS way and some more improvements. What do you think?

**Comment by NejcZdovc** [comment]
@bsclifton @cezaraugusto Based on @cezaraugusto suggestion I used pseudo-element, but instead of adding a custom css, I just hide it (made transparent), so now we have the same behavior that we have in the current version, but we also fix all problems that this PR wants to solve. What do you think?

**Comment by bsclifton** [comment]
I updated all 3 issues to have more detailed test plan; feel free to edit/adjust, @NejcZdovc 😄

**Pull request merged**
