### PR TITLE
Add clock component

### PR DESCRIPTION
**Pull request by cezaraugusto**
Just a commit split for the current implemented clock (#3199) for usage in #3001

Auditors: @bbondy

### CODE REVIEW

**Comment by bbondy** [comment]
++

**Comment by bsclifton** [comment]
@cezaraugusto should this be using JavaScript's toLocaleTimeString to format the hours and separator? (which also includes the period suffix, like AM/PM)

**Comment by bbondy** [comment]
I think that'd be great, pls do in a follow up

**Comment by cezaraugusto** [comment]
@bsclifton @bbondy there are a few considerations about using `.toLocaleTimeString`:

* Will we support variations in localized time formats? i.e. Korean: `오후 05:00`.
* Current spec displays a different font-size for period suffix. If the above is true, which will be the preferred method to keep it loyal to spec, given that suffix will be set according to locale?

cc'ing @bradleyrichter for any thoughts

**Comment by bsclifton** [comment]
Having the the time formatted according to the browser's locale setting is definitely the ideal case; I'd personally recommend just starting off implementing it using toLocaleTimeString() and then capturing the edge cases as separate issues :smile: 

toLocaleTimeString is used on the history page and it'll be important (the more timestamps, etc we introduce) to be consistent within the app.

**Comment by bbondy** [comment]
yep it's ok to use here and exact look on spec doesn't matter here.

**Comment by bradleyrichter** [comment]
We could start with a combined string. Maybe create a special case for English?

**Pull request merged**
