### PR TITLE
Adjust new tab button position fixes #3208

### LINKED ISSUE #3208: New tab button too high
I find that the new tab button on the tab bar is just a bit too high. It looks off-center. It would look better if it were centered.

### PR DESCRIPTION
**Pull request by Sh1d0w**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist. #3208 
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

Before:

After:

cc @bbondy @bridiver @diracdeltas

### CODE REVIEW

**Comment by bbondy** [comment]
This currently breaks the alignment on macOS (probably windows too)

New code in this PR:
screenshot 2016-08-17 12 34 44

Old code:
screenshot 2016-08-17 12 35 03

I guess this is a font issue of some sort. Can you think of a way to solve it across both OS?

**Comment by Sh1d0w** [comment]
@bbondy Yes you are right, it seems like a font issue. It can be easilly solved by putting an icon instead of text there.

@bradleyrichter Can you provide some icon that you think should fit, or should I just make one looking exactly like the current one?

**Comment by bradleyrichter** [comment]
@Sh1d0w 

This should work:
[ic_add_24px.svg.zip](https://github.com/brave/browser-laptop/files/423100/ic_add_24px.svg.zip)

**Comment by bradleyrichter** [comment]
ic_add_48pt_3x

**Comment by Sh1d0w** [comment]
@bradleyrichter Thanks. Implemented and looks good. 

@bbondy Can you please test it on macOS? Should be ok now I think.

**Comment by bbondy** [comment]
Works but this changes the look as well. @bradleyrichter did you want the new look or old?

Old:
screenshot 2016-08-17 13 47 11

New:
screenshot 2016-08-17 13 47 31

**Comment by bradleyrichter** [comment]
We can scale it up a bit and set the opacity down to 0.7.

**Comment by Sh1d0w** [comment]
@bradleyrichter Add `opacity: 0.7` but couldn't find much difference



Let me know if this is ok for you or should I change it to lower value.

**Comment by Sh1d0w** [comment]
@bradleyrichter This is the look with `0.5` opacity

**Comment by bbondy** [comment]
++

**Pull request merged**
