### PR TITLE
Refine tab's element position

### LINKED ISSUE #5431: Disable close button on tabs if tab size is too small
## Test plan

Under "QA steps" on https://github.com/brave/browser-laptop/pull/7799#issue-215652883

----

**Describe the issue you encountered:** if you click the close button of tab whose size is too small, sometimes you click the close button accidently.

**Expected behavior:** Disable close button on tabs if tab size is too small.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.8 RC1 

- Steps to reproduce:
    1. Open many tabs
    2. Minimize the width of the window
    3. Select any tab carefully not to close it...

- Screenshot if needed:

clipboard01

- Any related issues:

### LINKED ISSUE #6511: Session tab/private tab icon and text is too spaced out
## Test plan

https://github.com/brave/browser-laptop/pull/6900#issue-203781822

<hr>

**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Session tab/private tab icon and text is too spaced out

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	0c7a64d

- Screenshot if needed:
0.13.0 vs 0.12.15
image

- Any related issues: #5936

### PR DESCRIPTION
**Pull request by cezaraugusto**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits (if needed).

Auditors: @bsclifton, @bbondy, @bradleyrichter, @jkup

Fix #5431
Fix #6511

This PR follows this @bradleyrichter spec for tabs:

brad-tab-spec

**Test Plan:**

* All previous tab's test must pass:

`npm run test -- --grep="tab tests"`

**Manual Tests**

* Open 20 tabs with the following included:
* new session with audio
* new session without audio
* private with audio
* private without audio
* default with audio
* default no audio
* about:newtab or about:blank
* Add any other 2 tabs
* Resize window's width
* At each random breakpoint, tab's content should work based on above spec
* Icons must be hidden/shown gracefully (no icons overflowing tab's container)
* There should be no UI inconsistency

### CODE REVIEW

**Comment by cezaraugusto** [comment]
Setting as WIP since it doesn't fit well when user has 20 tabs open.

**Comment by bsclifton** [comment]
While reviewing https://github.com/brave/browser-laptop/pull/6031, I had some feedback for this PR

Next time we look at this (perhaps after 0.13.0 is closed out), we can consider making the tab size responsive like we had talked about :smile: For example, there could be 4 "breakpoints" for a tab:
  - (smallest) - only show the favicon (not private/session, audio, or close button). This will then look like a pinned tab.
  - (smaller) - show both the favicon and the audio. Similar to how a pinned tab works.
  - (larger) - show favicon, audio, and close button
  - (full size) - show favicon, audio, private or session, and close button

cc: @bradleyrichter 

Some other interesting food for thought :smile: 
- https://github.com/brave/browser-laptop/issues/879
- https://github.com/brave/browser-laptop/issues/100

**Comment by cezaraugusto** [comment]
@bsclifton agree. My suggestion is more like to use throttle for window resize and grab each tab's size using `.getBoundingClientRect` based on that. This way we can add a class for each view we want, and can also easily scale if some viewport is not at its best. I'm pretty sure it will be a definitive fix for all our tab-resizing issue.

**Comment by bsclifton** [comment]
@cezaraugusto you'll need to work out the conflicts (https://github.com/brave/browser-laptop/pull/6031 was just merged), but you should be good to go here :smile: 

Here's the image that @bradleyrichter shared in the other issue (and over Slack):
image

**Comment by cezaraugusto** [comment]
PR updated, ready for review

**Comment by cezaraugusto** [comment]
Rebased but tagged as WIP for further improvements.

**Comment by bsclifton** [comment]
@cezaraugusto what's left on this one? have you gotten the feedback you need?

cc: @bradleyrichter, @jkup

**Comment by cezaraugusto** [comment]
@bsclifton I would like some UI feedback from @bradleyrichter and @jkup first. I rebased this PR and cherry-picked on [auto-suggest-sites](https://github.com/brave/browser-laptop/tree/auto-suggest-sites) branch, so it's good to test both here or there.

From my part, WIP as I'll need to tweak it again to keep it working with ImmutableComponent.

**Comment by jkup** [comment]
Taking a look now!

**Comment by bradleyrichter** [comment]
I'll paste some snaps of little issues I am finding. But overall, it's awesome! Really great work here @cezaraugusto !

**Comment by bradleyrichter** [comment]
First, to see these remaining issues, set the tabs per set to 20 and reduce the window width to the minimum allowed.

With 20 tabs, the favicons disapear until you grab the window and resize it again, followed by reducing back to minimum. The icons then reappear.

image

image



Next, after they repaint, you can see a white oval present in the selected tab.
image


Another issue is that a tab which contains no favicon shows the close button instead. While it does work, it should only appear on mouse hover, regardless of the tab width.
image

**Comment by bsclifton** [comment]
Great job, @cezaraugusto :smile: Lots of small details, but you're getting really close on this one. I think these changes will have a huge positive impact on our users :smile:

**Comment by cezaraugusto** [comment]
thanks @bradleyrichter @bsclifton. It would need another set of eyes after ready since I'm migrating all tab component to Aphrodite, but I took note of those issues and will be fixed on the next request.

**Comment by luixxiul** [comment]
@bradleyrichter @cezaraugusto 
> Another issue is that a tab which contains no favicon shows the close button instead

How about hiding the close button at all under the certain minimum width of the tab?

**Comment by cezaraugusto** [comment]
@luixxiul I like that. I think for the smallest possible tab width we should replicate pinned tabs. If needed we could resize favicon (i.e. from 16px to 14px) just to make sure it fits their container.

**Comment by cezaraugusto** [comment]
Having closeTab icon on hover would make it difficult to select the tab if we have a lot of them open. Mimicking pinned seems a good solution for that as well. @bradleyrichter WDYT?

**Comment by bradleyrichter** [comment]
We do have a problem to solve which is how to display the entire tab set of tabs when the user minimizes the window. Setting min-width will cause overflow but we should deal with it anyway.

**Comment by bradleyrichter** [comment]
Upon reviewing the latest version, it is nearly perfect!

Hhere are some remaining UI related issues that would be good to solve:

1. Close button overlap at small tab widths.

before hover:
image

on hover:
image

zoomed view:
image

proposed fix: tell string to truncate further on mouse hover.



2. Favicon moves over at time of mouse over.

Not sure if this only happens below a certain width. I think so...but it only happened with a fresh set of tabs.


3. We need to solve the colored-tab hiding the favicon issue. 

proposed solution: place a 16x background square behind the favicon when the tab text is white. The color can be 50% of the current tab color. This would only be applied with tab theme colors enabled.

**Comment by cezaraugusto** [comment]
Closed in favor of #6900

**Pull request closed without merging**
