### PR TITLE
Update Mocha to 5.x

### PR DESCRIPTION
**Pull request by diracdeltas**
Fix https://github.com/brave/browser-laptop/issues/15164

Test plan:
* Travis shows green
* npm audit shows 0 critical sec vulnerabilities

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bsclifton** [comment]
For some reason, the code coverage run is failing 🤔 Haven't had time to debug yet

**Comment by diracdeltas** [comment]
for reference here are the codecov failures:

```
  1) dispatchAction unit test
       If run in Chrome
         should dispatch action to IPC renderer:
     Error: global leak detected: chrome
  

  2) requestHandler unit test
       "before all" hook:
     Error: global leaks detected: DOMParser, XMLSerializer
  
```

**Comment by diracdeltas** [comment]
@bsclifton it looks like our coverage reporting is broken anyway: https://travis-ci.org/brave/browser-laptop/jobs/427324193#L5774

i can push a change to make it appear green, but it will be equally broken as it is now on master i think

**Comment by diracdeltas** [comment]
@bsclifton this passes now

**Pull request merged**
