### PR TITLE
don't show loading spinner for 'about:' urls, prevents brief flicker …

### PR DESCRIPTION
**Pull request by psimyn**
…on new tab creation mentioned in https://github.com/brave/browser-laptop/issues/481

### CODE REVIEW

**Comment by bbondy** [comment]
Looks great, can you also document this in `docs/state.md`?  After that I'll gladly merge :+1:

**Comment by psimyn** [comment]
sure, does that mean adding a comment to loading?

```
    loading: boolean, // show the loading indicator
```

Is there a way to run `npm test` in minimized mode? I tried running it locally before pushing but the constant flashing/focus-stealing forced me to kill it

**Comment by bbondy** [comment]
Sorry actually please either store `indicateLoading` in state and then use that to determine whether to render. Or an alternate way would be just to check the frameProps's location protocol inside the render directly as well.  The way you have it might have slightly better perf though, but the other way would be a more simpler patch.

**Comment by psimyn** [comment]
ah, putting in loading getter of tab component is much simpler. Thoughts on this:

```
  get loading () {
    return this.props.frameProps &&
    this.props.frameProps.get('loading') &&
+    !this.props.frameProps.get('location').startsWith('about:')
  }
```

Should this be different PR/squashed if I'm going to revert other commit?

**Comment by bbondy** [comment]
yep that's what I was thinking, let's go with that exactly.
Whatever's easier for you.  If you want to close and open a new one or change and then git commit --amend and force push to your branch.

**Comment by psimyn** [comment]
forget to revert when amending, then abandoned ship. New PR at https://github.com/brave/browser-laptop/pull/554 :)

**Pull request closed without merging**
