### PR TITLE
See https://github.com/brave/browser-laptop/issues/1253

### PR DESCRIPTION
**Pull request by bsclifton**
Added search to context menu (for urls and for selection). Text could use updating, per the spec ("Search **engine** for '**term**'").

### CODE REVIEW

**Comment by bsclifton** [comment]
cc: @bradleyrichter

**Comment by bbondy** [comment]
@bradleyrichter I think Copy is used a lot more than search, I know the spec says differently but could we put those commands first, and then the search related ones in its own section after?

For reference:
https://github.com/brave/browser-laptop/issues/1253

Also I think we need to update the text as it looks to me currently like it's something related to OpenSearch which is an xml format.  And the ... is reserved for when there's a secondary action coming up.

**Comment by bradleyrichter** [comment]
@bbondy I'm guessing that the order used by chrome and safari places the unique actions on top for access priority and "mode recognition" over "Copy" because copy the most common keyboard shortcut? 

Firefox has the order as you are suggesting but I prefer the chrome/safari approach in this case.

Regarding Open Search... - this is a place holder until we can connect the variables to the menu?

**Comment by bsclifton** [comment]
@bradleyrichter yes, that would be the next step :smile: I'd have to dig in more to read the search engine preference. That change would need to include a change to the menu.properties file with a token replaceable entry like "Search {{engine}} with '{{term}}'" so that other languages would display properly (since they could have a different ordering for the words)

**Comment by bradleyrichter** [comment]
@bsclifton Can you start with "Search the web for [selected variable]"?

(if it's not too long)

**Comment by bsclifton** [comment]
Will do :+1:

**Comment by bsclifton** [comment]
@bradleyrichter fixed, per your comment (went with Search for [selected variable])

Here's a pic

**Comment by bbondy** [comment]
Great addition, thanks!

**Pull request merged**
