### PR TITLE
Adjusts layout of download items

### LINKED ISSUE #8143: download item styling is broken when clicking trash bin icon
**Describe the issue you encountered:** download item styling is broken when clicking trash bin icon.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.2 preview 1

- Steps to reproduce:
    1. Download something
    2. Click trash bin icon
    
- Actual result: 
  downloaditem

- Expected result: Everything except the confirmation stuff should remain the same place.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues: #7468

### PR DESCRIPTION
**Pull request by jonathansampson**
# Test Plan:
Click the trash bin on a download item
Note that the bottom alignment with other items isn't broken

# PR Details:
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Resolves #8143 

download-items

### CODE REVIEW

**Comment by luixxiul** [comment]
@jonathansampson would you mind adding margin below the border which appears when you click the trash bin icon?

**Comment by jonathansampson** [comment]
@luixxiul Please see the updated GIF and commit.

**Comment by luixxiul** [comment]
LGTM!

**Comment by bsclifton** [comment]
++! 😄

**Pull request merged**
