### PR TITLE
Added margin-bottom to the transfer funds button on about:preferences#payments

### LINKED ISSUE #6048: Transfer funds button needs margin-bottom
**Describe the issue you encountered:** Transfer funds button (Transfer BTC) needs margin-bottom.

screenshot 2016-12-07 4 10 03

**Expected behavior:**

screenshot 2016-12-07 4 10 40

- Brave Version: master branch

- Any related issues: #6009 

I'm sending a quick PR.

### PR DESCRIPTION
**Pull request by luixxiul**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Closes #6048

Auditors: @bbondy

Test Plan:
1. Open https://jsfiddle.net/LnwtLckc/5/
2. Click register
3. Make sure "Transfer BTC" button has the margin-bottom on add funds dialog on about:preferences#payments:
screenshot 2016-12-07 4 10 40

### CODE REVIEW

**Comment by bsclifton** [comment]
The change looks good but I don't believe I have a way to verify this one (because I'm in the US, where the default is Coinbase).  Here's what it shows like for me (BTC address intentionally removed):
screen shot 2016-12-06 at 11 41 57 pm

@cezaraugusto can you pull this and give it a shot?  You should see the 15px margin over "Your Brave wallet address is:" :smile:

**Comment by bsclifton** [comment]
Previous comment deleted- I didn't read your instructions, @luixxiul :laughing: 

After opening the jsfiddle link and adding handler, it shows as expected and margin looks great :smile: Nice cleanup

**Comment by luixxiul** [comment]
For QA: test plan is descirbed in the first post of this ticket (I forgot to add it in the commit message).

**Comment by luixxiul** [comment]
Labelled `QA/no qa needed` since this will be fixed with 402dcde of #6047

**Comment by luixxiul** [comment]
Labelled `QA/no qa needed` as this was superseded with https://github.com/brave/browser-laptop/pull/6047/commits/a8e5b8949e53bbef9c6d8a46e222a1972a6b7460 of #6047

**Pull request merged**
