### PR TITLE
enabling MetaMask via notification when visiting DApp website

### LINKED ISSUE #11532: add notification that installs MetaMask when visiting DApp websites
### Description

When a user visits a DApp website, Brave should prompt the user if they would like to enabled the MetaMask extension if it's currently disabled via a notification.

### Steps to Reproduce

* ensure MetaMask is disabled via about:preferences#extensions
* visit https://tokenfactory.surge.sh
* ensure that you receive a "This page contains a Dapp, would you like to enable the MetaMask extension?" notification
* click on "Install MetaMask"
* ensure that MetaMask is installed (verify via about:preferences#extensions)
* once installed, refresh  visit https://tokenfactory.surge.sh
* ensure that you can see the "Block Numbers" being updated

### Brave Version

**about:brave info:**

> Brave: 0.19.49 
> rev: 67959340e713e5e9f9e564f764acf493befb9b67 
> Muon: 4.4.28 
> libchromiumcontent: 61.0.3163.100

### PR DESCRIPTION
**Pull request by kjozwiak**
Fixed #11532

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Case 1:

* ensure MetaMask is disabled via about:preferences#extensions
* visit https://tokenfactory.surge.sh
* ensure that you receive a "This page contains a Dapp, would you like to enable the MetaMask extension?" notification
* click on "Install MetaMask"
* ensure that MetaMask is installed (verify via about:preferences#extensions)
* once installed, refresh  visit https://tokenfactory.surge.sh
* ensure that you can see the "Block Numbers" being updated

Case 2:

* ensure MetaMask is disabled via about:preferences#extensions
* visit https://tokenfactory.surge.sh
* ensure that you receive a "This page contains a Dapp, would you like to enable the MetaMask extension?" notification
* click on "No Thanks"
* refresh the website and ensure that the notification isn't being displayed anymore

Case 3:

* ensure MetaMask is enabled via about:preferences#extensions
* visit https://tokenfactory.surge.sh
* ensure that the "DApp" notification isn't being displayed

Case 4:

* ensure MetaMask is disabled via about:preferences#extensions
* visit https://brianbondy.com/
* ensure that the "DApp" notification isn't being displayed

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bbondy** [comment]
0.19.x: 5b4382f8b4986ea26c67850c6b73f548e705d089

0.20.x: 6af62cb3d7fd88ad422ff5cd149c5310243b1611

0.21.x: def745517bfc954b4cb29aac08fc4c4faed7632b

master: 4313f43a27e5b9d349a0f8655c864a26d2dc337b

**Comment by bbondy** [comment]
metamask

**Comment by bbondy** [comment]
screenshot thanks to @kjozwiak

**Comment by srirambv** [comment]
Case 2 fails
metamask

**Pull request merged**
