### PR TITLE
If directly-entered URL load fails, show the location of the displayed page

### LINKED ISSUE #3851: urlbar location may be incorrect when load fails
reported by eric lawrence:

- Steps to reproduce:
    1. open any site, ex: bankofamerica.com, in a tab
    2. put http://bayden.com/test/redir/goscript.aspx in the urlbar and hit enter

- Expected behavior
the page doesn't load, so the urlbar should still say bankofamerica.com

- Actual behavior
the urlbar says http://bayden.com/test/redir/goscript.aspx

- Any related issues:

### PR DESCRIPTION
**Pull request by diracdeltas**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fix #3851
Add regression test for #2723

Auditors: @bridiver

Test Plan:
open bankofamerica.com in a tab
put http://bayden.com/test/redir/goscript.aspx in the urlbar and hit enter
verify that the URL bar still says bankofamerica.com

### CODE REVIEW

**Comment by bbondy** [comment]
++

**Comment by luixxiul** [comment]
@diracdeltas pasting ``http://bayden.com/test/redir/goscript.aspx`` after 1st try makes the url to it instead of bankofamerica.com, which is intended?

**Comment by diracdeltas** [comment]
@luixxiul that appears to be a bug

**Comment by luixxiul** [comment]
I created follow-up: https://github.com/brave/browser-laptop/issues/3928

**Pull request merged**
