### PR TITLE
Added two pinned tab tests as requested [issue #123] & updated pin test

### PR DESCRIPTION
**Pull request by rob-blasetti**
Here are the tests requested in issue #123 

- Test closing a pinned tab should go to next tab
- Test closing a pinned tab when no other tabs exist should close the window

I have added a skip to all of them for now because they don't pass just yet, in order to make them pass(and properly test them) I need to access a selector to close a tab when it is pinned.

### CODE REVIEW

**Comment by bbondy** [comment]
Could you rebase this on tip, the last test was disabled because it was failing for me.  I'll retry it before merging after you rebase. Thanks!

**Comment by rob-blasetti** [comment]
The branch is rebased now.

Does the team have a slack channel, or any chat? I could use some tips on accessing the Context Menu to harden these tests.

**Comment by bbondy** [comment]
pls email brian at brave.com

**Comment by bbondy** [comment]
>  I could use some tips on accessing the Context Menu to harden these tests.

I don't know how to solve context menus yet because they aren't part of the DOM.  Would love it if you could find a solution for it though.

**Comment by bbondy** [comment]
Merging, tests work great, thanks.

**Pull request merged**
