### PR TITLE
set webrtc handling policy in the browser process

### PR DESCRIPTION
**Pull request by bridiver**
Submitter Checklist:

@diracdeltas what is a good way to test this?

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

**Comment by diracdeltas** [comment]
@bridiver i tested this originally by navigating between https://diafygi.github.io/webrtc-ips/ and https://browserleaks.com/webrtc (having shields down for one of them). it's also covered in the fingerprinting tests.

**Comment by NejcZdovc** [comment]
@bridiver what is the status of this PR? is it ready for a review?

**Comment by bridiver** [comment]
yea, just need to verify tests

**Comment by bsclifton** [comment]
@bridiver if we'd like manual QA testing for this, can you create an issue? It sounds like the steps @diracdeltas mentioned can be used in the test plan (navigating between https://diafygi.github.io/webrtc-ips/ and https://browserleaks.com/webrtc (having shields down for one of them))

**Comment by bsclifton** [comment]
Because it relies on previous commits (specifically, https://github.com/brave/browser-laptop/pull/9154), this can't go into 0.17.x.  Updating milestone to be 0.18.x

**Pull request merged**
