### PR TITLE
Updates to README.md, package.json

### PR DESCRIPTION
**Pull request by bsclifton**
- link to Twitter page
- additional link to downloads page
- links to iOS/Android versions of the browser
- link to contribution guidelines
- link to in-depth testing doc

Also added myself to package.json :)

### CODE REVIEW

**Comment by bsclifton** [comment]
Feedback very welcome- if you wanted to visualize the changes, please check out:
https://github.com/bsclifton/browser-laptop/tree/docs-update#user-content-brave-browser

**Comment by luixxiul** [comment]
It would be greatly welcomed if you add information about how to install Visual Studio itself to build Brave on Windows. @bbondy helped me on slack but still I'm not able to build it (I'm asking you because I know you are a good Windows developer ;-)

**Comment by bsclifton** [comment]
Great suggestion :+1: I will update it with information about that :smile: It's definitely not trivial

**Comment by bsclifton** [comment]
Updated :smile: I also updated the wiki to accompany the change

**Comment by luixxiul** [comment]
Wow thank you @bsclifton! Will try later :-)

**Comment by bbondy** [comment]
great updates, thanks for taking the time!

**Pull request merged**
