### PR TITLE
convert UrlBar to redux component

### PR DESCRIPTION
**Pull request by bridiver**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

related #7538

Test Plan:
Automated tests

### CODE REVIEW

**Comment by bsclifton** [comment]
@bridiver @NejcZdovc is this ready for review? 😄

**Comment by NejcZdovc** [comment]
@bsclifton not yet

**Comment by NejcZdovc** [comment]
@bridiver can we close this one? I think it's not relevant anymore, because you created separate commit for this component already.

**Comment by NejcZdovc** [comment]
I will close this one, because is out of date. @bridiver if we need to reopen it later on, please do

**Pull request closed without merging**
