### PR TITLE
add support for legacy ledger settings

### PR DESCRIPTION
**Pull request by cezaraugusto**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:
```
npm run test -- --grep="runPreMigrations"
```

Manual test plan:

- Go to payments tab, enable and:

**before checking this PR**

1. set `auto-incude` to OFF
2. set `Show only included sites` to ON
3. click the gear on top-right
4. set `Minimum page time before logging a visit` to 8 seconds
5. set `Minimum visits for publisher relevancy` to 10 visits
6. set `Allow contributions to non-verified sites` to false
7. scroll down publishers list, toggle the bottom button to show more sites (button now says `show less`)

**checkout this pr**
ensure the above data is persisted:
1. `auto-incude` is OFF
2. `Show only included sites` is ON
3. `Minimum page time before logging a visit` is 8 seconds
4. `Minimum visits for publisher relevancy` is 10 visits
5. `Allow contributions to non-verified sites` is false
6. scroll down publishers list, bottom button should say `show less`

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by cezaraugusto** [comment]
xoxo codecov

**Comment by darkdh** [comment]
++ except missing delete legacy addressed in 9ad7b4f

**Comment by bsclifton** [comment]
We're running into issues and unfortunately, this PR is causing issues with the BAT Mercury work (since settings were renamed). I'm going to pull this into 0.19.x

**Comment by bsclifton** [comment]
master https://github.com/brave/browser-laptop/commit/052277d76b0630ea40197ef4d66f6b3a82d29d82
0.20.x https://github.com/brave/browser-laptop/commit/3bc7c1f5bca72db7cf0db7600bffd50abe953813
0.19.x https://github.com/brave/browser-laptop/commit/be048b8835a681175178c720bb5e203767bb6505

**Pull request merged**
