### PR TITLE
Improves badge-counter positioning

### LINKED ISSUE #7977: Brave badge too close to edge
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
The Brave shield counter is rendered to close to the window's edge

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/c23efa3eedf3b56058d991492e30c24cd186d138

- Steps to reproduce:
On macOS, navigate to a site with blocked resources (tmz.com)
On Windows, navigate to a site with blocked resources, and press <kbd>alt</kbd> to reveal the menubar.
    
- Actual result:
Badge counter is rendered too close to the window's edge.

- Expected result:
Badge counter should be comfortably displayed.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:
image
image

- Any related issues:

### PR DESCRIPTION
**Pull request by jonathansampson**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

Fixes #7977 

image
image 
image

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@clifton how about Windows?

**Comment by bsclifton** [comment]
moved to 0.14.1; ubuntu needs some love:
screen shot 2017-03-30 at 12 20 20 am

**Comment by bsclifton** [comment]
Reviewed updated version on Ubuntu 14 and macOS; looks great 👍

**Comment by jonathansampson** [comment]
macOS, Linux, and Windows:

image image image

**Comment by NejcZdovc** [comment]
what is happening with a font on Linux? We are using `Arial Narrow` is this not supported in Linux? @bradleyrichter

**Comment by bsclifton** [comment]
Changes look great to me! @NejcZdovc, I created an issue to track the concern you had: https://github.com/brave/browser-laptop/issues/8007

**Pull request merged**
