### PR TITLE
Faster travis  (waiting on https://github.com/brave/browser-laptop/pull/6599/files)

### PR DESCRIPTION
**Pull request by posix4e**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

### CODE REVIEW

**Comment by luixxiul** [comment]
If no qa is required, please add the label, thanks!

**Comment by luixxiul** [comment]
Is there an issue associated with this? If not, please create one, thanks.

**Comment by bbondy** [comment]
++

**Comment by luixxiul** [comment]
The commits were reverted with https://github.com/brave/browser-laptop/commit/ddfe4e576731c3934164a72ed920b5bde976ad5c

**Pull request merged**
