### PR TITLE
Close tab settings

### LINKED ISSUE #6553: Add close tab settings
It would be nice to provide options for what to do when a tab is closed. Currently we will return to the parent tab first, and if no parent go to the next. 

Cross posting from community.brave.com:

```
Normally these are the possibilities when we close an active tab.

1.Activate the last active tab
The default setting returns focus to the most recently used tab
2.Activate the next tab
This setting returns focus to the next tab on the tab bar
3.Activate first tab 
But I don't see a preference setting like these in the "Tab Setting" section. This would be a nice addition.
```

Reference:
https://community.brave.com/t/tab-focus-when-an-active-tab-is-closed-if-there-are-multiple-tabs-open/540

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Resolves #6553

## Auditors
@bbondy @bsclifton

## Test Plan
- Go to Preferences and set desired action in the tab section
- Close tab
- New active tab should opened as defined in preferences

## Automated tests
- `npm run watch-test`
- `npm run unittest -- --grep="frameStateUtil"`

### CODE REVIEW

**Comment by NejcZdovc** [comment]
I added suggested options and kept old implementation with parent tab.

**Comment by luixxiul** [comment]
CI passed: https://travis-ci.org/brave/browser-laptop/builds/190734051

**Comment by NejcZdovc** [comment]
@bsclifton test's are added. The only scenarion that I found and is failing is new tab links. If you open links from new tab then parent it's not working. I tested this on current branch 0.13.1-branch and behavior is the same. If you close tab where parent tab is `about:newtab` tab next to closed tab is opened

**Comment by bradleyrichter** [comment]
@bsclifton Did this make it to master?

**Comment by NejcZdovc** [comment]
Yes it's in the master

**Comment by bsclifton** [comment]
@bradleyrichter that is correct (what @NejcZdovc said! 😄 )

**Pull request merged**
