### PR TITLE
Fix regression: privateTabPaddingHorizontal

### PR DESCRIPTION
**Pull request by luixxiul**
Addresses #8895

Auditors: @cezaraugusto

Test Plan:
1. new private tab paragraphs should be properly spaced

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bsclifton** [comment]
Here before
screen shot 2017-05-17 at 9 20 22 am

and after
screen shot 2017-05-17 at 9 28 55 am

**Comment by cezaraugusto** [comment]
thanks but I think as we move more things to Aphrodite we should avoid using global styles for spacing and keep that file specific for future-friendly theming

**Comment by luixxiul** [comment]
For the sake of that I have added the prefix *privateTab* to the var :-)

**Comment by NejcZdovc** [comment]
I agree here with @cezaraugusto, because this will probably only used in private tab, we don't need it in global. We should keep global as slick as possible.

**Comment by luixxiul** [comment]
My thought on ^: https://github.com/brave/browser-laptop/issues/8340#issuecomment-298558379

**Pull request merged**
