### PR TITLE
Hide downloads bar when in downloads tab.

### LINKED ISSUE #2012: add shortcut to hide downloads bar
When you press the shortcut to go to the downloads page, it should also hide the downloads toolbar.

### PR DESCRIPTION
**Pull request by ludable**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

Fix #2012

### CODE REVIEW

**Comment by bbondy** [comment]
Thanks for the PR!  The implementation here although correct doesn't match what was proposed though.  
Let me try to explain the difference:

The PR contains:
- If you navigate to a downloads page, it hides the downloads bar.  But then if you change tabs it shows it again.

The proposed task is:
- If you use the downloads menu item, it should hide the downloads bar. I.e. close the downloads toolbar.  If you then move to other tabs, it should stay closed.

Pls implement the latter.  You can `git commit --amend` your changeset and `git push -f` when done as well to update this PR.

**Comment by ludable** [comment]
Sorry for the confusion Brian. I've submitted an amended PR.

Thanks!

**Comment by bbondy** [comment]
Looks great thanks for your help!
Normally we require tests but we don't have download tests yet, so that's not needed until we get those for downloads.

**Comment by ludable** [comment]
Thanks Brian.

I checked out https://github.com/brave/browser-laptop/blob/master/.github/CONTRIBUTING.md , but it doesn't mention tests.

Is there any other doc that I can read to learn more about the project and be an effective contributor?

**Comment by bbondy** [comment]
Good catch we'll update the contributor guide.

Everything you did is great, thanks!

There is this doc for debugging if it helps for future things:
https://github.com/brave/browser-laptop/blob/master/docs/debugging.md

**Comment by ludable** [comment]
Thanks Brian.

**Pull request merged**
