### PR TITLE
Issue #9053: Making country field in autofill a dropdown list instead of text input box.

### LINKED ISSUE #9053: Make Autofill country field into a dropdown list
## Test plan

https://github.com/brave/browser-laptop/pull/10821#issue-255571235

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Make country into a dropdown list

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.15.308
rev	fc4b892
Muon	3.0.200

- Screenshot if needed:
screen shot 2017-05-25 at 10 28 30 am

Future enhancement: make state field also drop down. [Ref here](https://blog.nightly.mozilla.org/2017/05/23/preview-form-autofill-in-firefox-nightly/)
- Any related issues: #3727

### PR DESCRIPTION
**Pull request by luixxiul**
Fixes #9053

I mistakenly closed #10300 opened by @dfperry5. I picked up the 4 commits from the PR and added a commit to add `CommonFormFullWidthDropdown`. Apologies to @dfperry5.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

## Test Plan:
1. Open `about:autofill`
2. Click `Add Address`
3. Click `Country`
4. Input `united states`
5. Make sure `United States` is selected
6. Hit enter key
7. Click `Save`
8. Open https://www.roboform.com/filling-test-all-fields
9. Select `Country`
10. Make sure `United States` appears on the candidate list

## Automated test plan:
`npm run test -- --grep="Autofill"`

## Reviewer Checklist:

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

**Comment by luixxiul** [comment]
With this PR:

screenshot 2017-09-06 20 36 12

**Comment by luixxiul** [comment]
I forgot to set replace the data-test-id for `CommonFormFullWidthDropdown`. I'm fixing it soon.

**Comment by luixxiul** [comment]
It looks like the country is not correctly selected from the dropdown.

````
waitForElementFocus("[data-test-id="nameOnAddress"]", "undefined")
typeText([data-test-id="nameOnAddress"], Brave Lion, undefined)
typeText([data-test-id="organization"], Brave, undefined)
typeText([data-test-id="streetAddress"], 1161 Mission Street, #401, undefined)
typeText([data-test-id="city"], San Francisco, undefined)
typeText([data-test-id="state"], CA, undefined)
typeText([data-test-id="postalCode"], 94103-1550, undefined)
typeText([data-test-id="country"], US, undefined)
      2) "before each" hook for "adds an autofill address"
waitForBrowserWindow()
windowByUrl("chrome://brave/Users/Suguru/browser-laptop/app/extensions/brave/index.html")


  0 passing (58s)
  2 failing

````

Locally I noticed `Uganda` was selected instead of `United States`, leaving the dropdown open.

**Comment by bsclifton** [comment]
@luixxiul for the selection to work, you'd have to type what the actual value in the listbox is: ex "United" or "United States".  Typing US is going to match countries like "us*"

**Comment by luixxiul** [comment]
@bsclifton I think I tried that too, but it did not work for me. I think I am doing something wrong. Would you mind helping me out? thanks!

**Comment by bsclifton** [comment]
@luixxiul I fixed the tests- unfortunately, your fork does not allow updates though. Did you specifically uncheck this box on purpose when creating the PR?

**Comment by bsclifton** [comment]
@luixxiul please cherry-pick this commit in:
https://github.com/brave/browser-laptop/commit/3351c6d4b2782d14ba598fb1d7f0ee8ea42546f7

**Comment by luixxiul** [comment]
@bsclifton I see! thanks for your commit. I'll check it out and cherry-pick it.

**Comment by luixxiul** [comment]
I get another new error which I'm not sure if this PR causes: https://travis-ci.org/brave/browser-laptop/jobs/273571165#L3754

````
  1) Autofill address autofills the updated address when edited:
     unknown error: Element is not clickable at point (1131, 189)
  Error: An unknown server-side error occurred while processing the command.
      at elementIdClick("0.05012787194082691-1") - click.js:20:22
````

@bsclifton @NejcZdovc do you know how to fix this?

**Comment by bsclifton** [comment]
I can't repro the issue locally- going to try on Linux

**Comment by bsclifton** [comment]
Also works when I run with Ubuntu 14.04 locally... hmm

**Comment by luixxiul** [comment]
related? https://www.drupal.org/node/2869464

**Comment by dfperry5** [comment]
@bsclifton @luixxiul  Hi guys, I've been keeping up with the thread - is there anything I can do to help? I know Brian said it could be something yall need to look at with the test.

**Comment by bsclifton** [comment]
@dfperry5 we're good to go from your end- maybe @NejcZdovc can help me figure out what's wrong with the test (or more specifically, where it's breaking).  I'll be looking into it also 😄  Hopefully we'll get that squared away and get this merged for you.  Thanks for hanging in there 😄

**Comment by bsclifton** [comment]
Looking back at travis-ci, previous builds failed on this same issue
https://travis-ci.org/brave/browser-laptop/jobs/273315807#L3610

I created an issue to track the failing test (since it has been present for a while)
https://github.com/brave/browser-laptop/issues/10879

**Comment by bsclifton** [comment]
Congrats on your first contribution, @dfperry5 😄 🎉 

Let us know if there's another issue we can help with (and apologies this one took so long to get sorted out)

**Comment by NejcZdovc** [comment]
@bsclifton we started getting this errors with this commit https://github.com/brave/browser-laptop/commit/3e38aee0e184dd48f87b07b68f255eb30a0b1c9e and it's not related to this PR. I am still figuring out what is going on and once I do it will fix multiple failing tests.

**Pull request merged**
