### PR TITLE
Show only favicons

### LINKED ISSUE #1657: Suggestion: "show only favicon" on bookmark bar
Why don't you add "show only favicon" mode like this?

It would be nice to show the title as a tooltip.

I'd love to see this implemented, but maybe kinda personal preference.

Idea: https://addons.mozilla.org/en-US/firefox/addon/smart-bookmarks-bar/
ref: #1454

### PR DESCRIPTION
**Pull request by dlion**
screenshot - 05142016 - 12 14 46 am

screenshot - 05142016 - 12 14 58 am

Close #1657

### CODE REVIEW

**Comment by luixxiul** [comment]
Nice! I tried it by pulling your repo, and I noticed some points.

- Enabling this option should not be applied to bookmarks in the folder (pulldown)
- Padding between bookmarks should be narrower
- Disabling the option should show the titles again. Currently those of the bookmarks added after disabling are shown properly. When you click the pull down, the titles are displayed again

Thanks!

**Comment by dlion** [comment]
Thanks, I'm new to brave development so any suggestions to do this is appreciated! :smiley:

**Comment by bbondy** [comment]
any update on the above? Also please rebase the commits to clean up history a bit to squash the commits `git rebase -i master`. Thanks!

**Comment by dlion** [comment]
Sorry for the delay (academic reasons), currently I'm working on it :smile:
- [X] Not applied to bookmarks in the folder
- [ ] Padding between bookmakrs should be narrower
- [ ] Render the bar when option change

**Comment by luixxiul** [comment]
@dlion, I like the margin and padding of ``.bookmarksToolbar .bookmarkToolbarButton`` and the margin of ``.bookmarksToolbar .bookmarkToolbarButton .bookmarkFavicon`` is set to 0px like this:

**Comment by dlion** [comment]
Currently I don't understand how to render the bookmarks bar after changing the option, any suggestions ? @luixxiul 
And yes no problem, after all I will squash my commits. Thanks!

**Comment by bsclifton** [comment]
@dlion I downloaded your code locally, ran it, and see the issue

When the preferences change, the items aren't recreated. I created a handler for this situation (my use case was having the menu show/auto hide, which requires changes to the BrowserWindow object).

Please see here:
https://github.com/brave/browser-laptop/blob/master/js/stores/appStore.js#L250

**Comment by bsclifton** [comment]
Here's a demo of the change that would need to be made there:
```
case settings.SHOW_BOOKMARKS_TOOLBAR_ONLY_FAVICON:
  // TODO: recreate the BookmarksToolbar instance here, so it re-renders with the change
  break
```

**Comment by bbondy** [comment]
@bsclifton in your situation you had to explicitly do it because state changes aren't propagated into electron actions. But in this case, and anything in React rendered UI, if the setting changes, it calls render on the component so no explicit action is necessary.  You just have to handle the re-rendering.  So trying to re-crete a BookmarksToolbar instance or any other React component isn't right.

**Comment by dlion** [comment]
So if the @bsclifton solution isn't right, how can I re-render the bookmarksToolbar ? @bbondy

**Comment by bbondy** [comment]
If you change state then render will be called on BookmarkToolbar.  You just need to define how to display the UI based on the state there.

**Comment by bsclifton** [comment]
How's it going @dlion? Do you need help checking out this last item?

**Comment by dlion** [comment]
Sure @bsclifton , I didn't figure out how to change the state of the bookmarksToolbar element in the appStore file. (I'm a newbie about React and Electron but I want to learn)

**Comment by bsclifton** [comment]
Here we go @dlion, got it fixed and working :smile: 
https://github.com/bsclifton/browser-laptop/commit/77c1de72bdfeea207c52f91cc4246c266622e502

I'm glad this came up because I also had the chance to clean up the code I did initially for the favicons

##Why does this work?
main.js creates the BookmarkToolbar control. My change was to bind the settings to the control directly. Then in the child controls, it only checks it's property state.

React triggers a re-render when any properties it's observing (used while rendering) change. So now changing the settings causes the full re-render.

**Comment by bsclifton** [comment]
@dlion you might want to rebase against master... then you should be able to cherry pick my commit (please let me know if you have trouble doing that)

Worst case scenario, you can just manually apply my changes in your branch :smile:

**Comment by dlion** [comment]
Thanks @bsclifton, I learned a lot!
I've done everything.

**Comment by luixxiul** [comment]
@dlion and @bsclifton, nice work!

I tried it and got this: 


In the mode there should be ``padding-left: 10px;`` added (6px is based on ``.tabs``, 4px on ``.tabIcon`` ) to ``.bookmarksToolbar``.

**Comment by dlion** [comment]
@luixxiul I added the `padding-left: 10px;` to `.showOnlyFavicon` and this is the result:
screenshot - 05292016 - 05 21 32 pm

**Comment by luixxiul** [comment]
Thanks, I'm working on it too, wait for a moment.

**Comment by luixxiul** [comment]
OK, it's like this:


How do you think?

**Comment by dlion** [comment]
@luixxiul great, committed and pushed!

**Comment by luixxiul** [comment]
@dlion in the commit message you're trying to close the PR itself, but maybe you're closing #1657, aren't you?

**Comment by dlion** [comment]
ops, you are right, corrected! :fast_forward:

**Comment by bsclifton** [comment]
tested it out, lgtm!  Well done, @dlion :smile:

**Pull request merged**
