### PR TITLE
Add warning about the privacy risks of torrenting

### PR DESCRIPTION
**Pull request by diracdeltas**
Fix https://github.com/brave/browser-laptop/issues/12631

Old page:
screen shot 2018-01-12 at 11 26 03 pm

New page:
screen shot 2018-01-13 at 12 22 46 am

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [x] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

Test Plan:

Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by flamsmark** [comment]
I'd rather we not call this a "legal notice": AFAICT, it's about functionality and privacy risk. What about the following text?
> "Torrenting involves downloading pieces of a file from other users and uploading pieces to them in turn. This will share the fact that you're downloading this file: other people will know what you're downloading, and they may also have access to your IP address."

**Comment by flamsmark** [comment]
What about the following text?
> "Torrenting involves downloading pieces of a file from other users and uploading pieces to them in turn. This will share the fact that you're downloading this file: other people will know what you're downloading, and they may also have access to your IP address."

**Comment by diracdeltas** [comment]
@flamsmark i like the new text but i think it should clarify that 'torrenting' is the thing that happens when you click 'start torrent'. what about

> When you click "Start Torrent",  Brave will download pieces of the torrent file from other users and upload pieces to them in turn. This will share the fact that you're downloading this file: other people will know what you're downloading, and they may also have access to your public IP address.

**Comment by flamsmark** [comment]
I'd prefer logical punctuation, but otherwise: 👌🏻

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by diracdeltas** [comment]
@flamsmark done (with logical/british punctuation)!

**Comment by bsclifton** [comment]
master 1e43f3df19a687723d7d343b16c34f3cf54e2fe5
0.21.x fd925af6a1f71a8b70a1dbe5435c2bb07da58969
0.20.x 6b829cd8531dcff1cdba56d138e19c39dc5cad30

**Pull request merged**
