### PR TITLE
Change verb tense of paymentHistoryFooter to past tense

### LINKED ISSUE #6059: Payment history footer message needs correct past/future context
problem: (your next contribution is 6 days ago)

image

code point:

https://github.com/brave/browser-laptop/blob/d86d9638f141c890276bc9d90c5a1dd01d3c6bd5/js/about/preferences.js#L963

### PR DESCRIPTION
**Pull request by bkilrain**
This commit changes the paymentHistoryFooter text to match the fact that
reconcileDate will always be in the past (it is generated from [moment.js's
fromNow() method](http://momentjs.com/docs/#/displaying/fromnow/)).

Fixes #6059

Auditors: @bsclifton

Tests: n/a

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan: n/a

### CODE REVIEW

**Comment by bkilrain** [comment]
by the way - I suspect my git workflow is lacking. If you have a tip, please let me know :)

**Comment by luixxiul** [comment]
@bkilrain I'm sorry but @mrose17 got another way to fix the issue, so let me close this.

If you are interested, please have a look at the contributors backlog for more tasks :-)

https://github.com/brave/browser-laptop/milestone/47

Thanks for your understanding.

**Comment by bsclifton** [comment]
@bkilrain sorry I didn't get to this sooner- we've had an unusually large backlog of items recently.  The good news is our major blockers have been resolved and we're starting to work through all the PRs :smile: 

Please hit me up any time if you have questions.  You're welcome to join our Slack too (shoot me a message at `clifton@brave.com` if you're interested) :smile:

**Comment by bkilrain** [comment]
All good~ I'll check out the backlog 👍

**Comment by mrose17** [comment]
many thanks!

**Pull request closed without merging**
