### PR TITLE
make panel wider to fit strings better, and fix missing class for popup

### PR DESCRIPTION
**Pull request by bradleyrichter**
auditors: @bsclifton @luixxiul 

fixes: #5715

image

now looks like this:
image

### CODE REVIEW

**Comment by bsclifton** [comment]
++!

**Comment by luixxiul** [comment]
screenshot 2016-11-18 19 38 20

The panel should be much wider. It is too small for Japanese, at least.

**Comment by luixxiul** [comment]
By setting ``width: 540px`` you will get this.

screenshot 2016-11-18 19 43 56

**Comment by alexwykoff** [comment]
Label issues covered in https://github.com/brave/browser-laptop/issues/5726

**Pull request merged**
