### PR TITLE
First steps at getting the spectron/webdriver tests working

### PR DESCRIPTION
**Pull request by bsclifton**
Tonite's progress. Brave crashes on shutdown which needs investigation

Feel free to merge (it's against chromium54) or keep it open as a WIP and I'll continue working on tests :smile: 

Auditors: @bridiver, @darkdh

### CODE REVIEW

**Comment by darkdh** [comment]
++ on c9f8030a160a3bd7e20c51992ec895be052869ce

**Comment by bsclifton** [comment]
@bridiver per your comment https://github.com/brave/browser-laptop/pull/5995#issuecomment-264659372

I updated the code in `js/flash.js` to use the methods in `lib/urlutil.js`. Take a peek at the PR and if that looks good, this should be ready for merge (into chromium54 branch) :smile:

**Comment by luixxiul** [comment]
Do we have an tracking issue for this? If not, please create one and add `QA/no qa needed` to it, thanks.

**Comment by bsclifton** [comment]
@luixxiul https://github.com/brave/browser-laptop/issues/5691 is the closest to tracking there is (which you already shared). Marking as `QA/no qa needed` because these are automated tests

**Pull request merged**
