### PR TITLE
send updates to `about` pages more efficiently

### PR DESCRIPTION
**Pull request by bridiver**
Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:
Check that each about page updates when settings, etc... change

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bridiver** [comment]
this also gets rid of some of the max listener messages on the console

**Comment by bridiver** [comment]
rebased

**Comment by NejcZdovc** [comment]
@bsclifton can we pull this into 0.19 or is to risky? This PR solves one problem that is still on my TODO regarding sending `ledgerPaymentsPresent` flag

**Comment by bsclifton** [comment]
@bridiver can we get one more rebase on this? I'll merge right after that (I promise!)

**Comment by bbondy** [comment]
Posted this issue to track the work
https://github.com/brave/browser-laptop/issues/11615

**Comment by bbondy** [comment]
0.19.x: 5017bdded9db6b2634c73a675e3275076f3e84f5
0.20.x: 2a5540892e4d13e7835422ad26f703eb4d04a554
0..21.x: 650a3ad553da8bb2555731fad26a7cfcbc325920
master: 1bb9aa2f0aa0cba75f5838da9539b57fd31aa3f2

**Pull request merged**
