### PR TITLE
check for valid data before upgrading and assign defaults after cleaning

### PR DESCRIPTION
**Pull request by bridiver**
Fixes https://github.com/brave/browser-laptop/issues/3550

Auditors: @bbondy @bsclifton

### CODE REVIEW

**Comment by bsclifton** [comment]
👍

**Comment by bbondy** [comment]
Is there an issue for this? If not please post and update PR. Also to ensure it is tested the issue should be marked in the 0.11.6 milestone.

**Comment by bridiver** [comment]
@bsclifton can you create an issue for the original problem you had?

**Comment by bsclifton** [comment]
@bridiver beat me to creating an issue, but I captured some good steps :smile: 

[Check out the issue and steps here](https://github.com/brave/browser-laptop/issues/3550)

**Comment by bsclifton** [comment]
To verify the fix:
- Ensure all Brave instances are closed
- Download [session-store-1_bsc0.11.1.zip](https://github.com/brave/browser-laptop/files/443932/session-store-1_bsc0.11.1.zip)
- Move this session file to the appropriate location (Mac is ~/Libraries/Application\ Support/brave/, making sure to rename it as session-state-1
- Install a version of Brave which has the fix
- Launch into Brave and inspect the browser developer tools (Shift + F8)

**Comment by bbondy** [comment]
++

**Pull request merged**
