### PR TITLE
Fix Travis errors related with data-l10n-id

### LINKED ISSUE #11454: Automated tests fail on Travis due to data-l10n-id not visible
### Description

Automated tests fail on Travis due to data-l10n-id.

https://travis-ci.org/brave/browser-laptop/jobs/286524924#L3411

````
2) Regular payment panel tests can setup payments shows welcome page:
     Error: element ("[data-l10n-id="payments"]") still not visible after 10000ms
      at elements("[data-l10n-id="payments"]") - isVisible.js:54:17
      at isVisible("[data-l10n-id="payments"]") - waitForVisible.js:73:22

  3) Regular payment panel tests can setup payments payments can be enabled:
     Error: element ("[data-l10n-id="payments"]") still not visible after 10000ms
      at elements("[data-l10n-id="payments"]") - isVisible.js:54:17
      at isVisible("[data-l10n-id="payments"]") - waitForVisible.js:73:22
````

### Additional Information

These errors are related with a npm package, because the same error happens on every PR of `master` branch which has once successfully finished, by restarting builds manually. Manual trials indicate that `moment` is a cause of the errors.

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #11454

Fix failures on Travis related with data-l10n-id. See https://travis-ci.org/brave/browser-laptop/jobs/286524924#L3411 for examples

[`moment`](https://www.npmjs.com/package/moment) was updated from `2.18.1` to `2.19.0` yesterday.
See https://gist.github.com/ichernev/5f3f4eb02761b4f765a0cccf02cec603 for the full changelog. 

diff: https://github.com/moment/moment/compare/2.18.1...2.19.0

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by luixxiul** [comment]
This change looks working: https://travis-ci.org/brave/browser-laptop/jobs/286654321#L3827

It seems to me that that we would have to consider to replace carets with tildes on `package.json` for now to accept patch updates only. Minor updates could break builds and it will take quite long time (took me a day) to find which package causes that breakage. IMO we should eventually remove semver dependency and update `package.json` manually (until we get ready for using Greenkeeper #1701 for example ).

If this is worth discussing, I'll open another issue for that.

**Comment by luixxiul** [comment]
This change is required for `master` only.

master: https://travis-ci.org/brave/browser-laptop/jobs/286615666#L3387
0.20.x: https://travis-ci.org/brave/browser-laptop/jobs/286620747#L3490
0.19.x: https://travis-ci.org/brave/browser-laptop/jobs/286625961#L3534

so it might be `master` that has a bug / incompatibility with `moment`.

**Comment by luixxiul** [comment]
`moment` was added with https://github.com/brave/browser-laptop/commit/18cf5df5dbdf197286b8fd8034e39a6b43ddd3e5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R97 for #4370.

**Comment by ayumi** [comment]
do we need to update `package-lock.json` as well?

**Comment by luixxiul** [comment]
Right, I'm going to do that. Thanks for reminding me.

**Comment by luixxiul** [comment]
It's done.

**Pull request merged**
