### PR TITLE
Fixes bookmark move location cache

### LINKED ISSUE #7032: Bookmark hanger shows a wrong folder name
## Test plan

specified below

----

**Describe the issue you encountered:** Bookmark hanger shows a wrong folder name

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 x64

- Brave Version (revision SHA): 0.13.2 ce14f5d

----

- Steps to reproduce:
    1. Add a bookmark
    1. move it to a different folder
     2. Click on the bookmark icon
        - Make sure folder is selected as `bookmark toolbar`, instead of the new folder in which you put it 
     3. Import boomarks from file/browser which has folders in it
     4. Open the bookmarked page
    5. Click on the bookmark icon
        - `Bookmark toolbar` remains location rather than the folder name

----

- Actual result: Root folder name is displayed, even if the bookmark exists under nested folder

- Expected result: Correct folder name where the bookmark exist should be displayed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No. Shows correct folder name in 0.13.1

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues: #4983

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #7032

Auditors:

Test Plan: specified in https://github.com/brave/browser-laptop/issues/7032#issue-205198969

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
tests will be added in #10310

**Comment by luixxiul** [comment]
@ayumi please see: https://github.com/brave/browser-laptop/issues/7032#issue-205198969

bug

**Comment by ayumi** [comment]
@luixxiul the test plan seems to work on OSX on master?

STR is kind of confusing. First there are these two steps:

> Make sure folder is selected as bookmark toolbar, instead of the new folder in which you put it

> Bookmark toolbar remains location rather than the folder name

The steps don't seem to agree with: "Actual result: Root folder name is displayed, even if the bookmark exists under nested folder" because during STR the bookmark was specified as "bookmark toolbar".

I tried:
A) "Bookmark to top level / toolbar, create folder, move bookmark to folder, import"
B) "Create folder, bookmark and change dialog folder to folder, import"

Both seemed okay.

**Comment by luixxiul** [comment]
CC @srirambv

**Comment by srirambv** [comment]
Worked fine on Windows

**Pull request merged**
