### PR TITLE
Add local search history to url bar suggestions

### PR DESCRIPTION
**Pull request by bsclifton**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fixes https://github.com/brave/browser-laptop/issues/5919

Originally submitted with https://github.com/brave/browser-laptop/pull/6115

I had to back out those 2 commits because they were causing tests to fail completely :frowning_face: 

@aekeus when you have a chance, can you check out this code? You should be able to reproduce the problem just by doing the following:
```
#rename or delete the existing lss branch, if you had one
git checkout lss
rm -rf node_modules && npm install
#window 1
npm run watch-test
#window 2
npm run test -- --grep="navigationBar tests lockIcon Shows insecure URL icon"
```
When test runs, it'll pop up a blank white window and will eventually timeout. I didn't see any new npm dependencies, so it was a big puzzling what broke. The tests DID pass originally, so it might be an issue with the 2nd commit

### CODE REVIEW

**Comment by aekeus** [comment]
There are a couple of features not implemented for this pull request (click to delete, clear history). Moving to next milestone.

**Comment by bsclifton** [comment]
Friendly ping on this one @aekeus 😄

**Comment by aekeus** [comment]
Thanks @clifton. Other priorities have bumped me from this. Will return as time allows.

**Comment by bsclifton** [comment]
Closing as stale / bitrotten; code is still in the `lss` branch 😄

**Pull request closed without merging**
