### PR TITLE
Fix webtorrent, don't exclude dependencies

### LINKED ISSUE #5849: LSOpenURLsWithRole() failed with error -10810 on the packaged build
From Terminal when I try to open the packaged build, I get this.
````
Brave-MacBook-Pro:browser-laptop Suguru$ open ./Brave-darwin-x64/Brave.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/Suguru/browser-laptop/Brave-darwin-x64/Brave.app.
````

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Any related issues: #5818

CC @dcposch

### PR DESCRIPTION
**Pull request by dcposch**
Fixes #5849

Also lazy-load `webtorrent-remote` in the browser process.

* This should make startup a bit faster, since `require('webtorrent-remote/server')` will pull in `webtorrent`, which is a big module.
* It also makes exceptions like #5849 easier to debug. Instead of getting a cryptic error, you get a stack trace at runtime when you try to load your first torrent URL.

BTW, I recommend:
* Measuring startup time. This can be as simple as adding a `console.time` ... `console.timeEnd`. We do that in WebTorrent Desktop and it helps catch performance regressions.
* Add a bit more error handling on startup. If the packaged app crashes on launch because of a `require()` error, it would be better to print the stacktrace than the `LSOpenURLsWithRole` exception.

### CODE REVIEW

**Comment by dcposch** [comment]
@feross @bbondy @luixxiul

**Comment by bbondy** [comment]
++

**Comment by luixxiul** [comment]
Should this fix #5855 too? @dcposch

**Comment by dcposch** [comment]
@luixxiul yes

**Pull request merged**
