### PR TITLE
Add hover effect on the "back forward" button

### PR DESCRIPTION
**Pull request by RacioN**
- Add hover effect on the "back forward" button.
(When I saw "back forward" button, I couldn't understanding in an instant.)

- Change url bar selection color.

### CODE REVIEW

**Comment by bbondy** [comment]
@bradleyrichter could you do a design review on this? Thanks!

**Comment by bradleyrichter** [comment]
Thanks @RacioN - I'll review it today. Adding more prominent hover states to all buttons to the do-list.

**Comment by bbondy** [comment]
Brad should this be closed? I think you mentioned it would be incorporated to your hover states changes.

**Comment by bradleyrichter** [comment]
@bbondy yes, I like the look. Incorporating it into the next round of UI improvements.

**Pull request closed without merging**
