### PR TITLE
Try to interpret last cmdline argument as url

### LINKED ISSUE #9193: opening URL from external application (Thunderbird/LibreOffice) does not work any more
Xubuntu 16.10
Brave	0.15.310 rev	6b5e4e2
os.platform	linux
os.release	4.8.0-53-generic
os.arch	x64

- Issue:
opening URL from external application (Thunderbird/LibreOffice) does not work any more. It works only when there is no Brave instance running yet. When Brave is running already, it focuses the Brave Window, but no tab is opened :/

- Steps to reproduce:
    1. Have Brave opened alread with several tabs
    2. click on link URL from Thunderbird and/or other application
    
- Actual result:
When Brave is running already, it focuses the Brave Window, but no tab is opened :/

- Expected result:
URL gets opened in Brave as before

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Do not know

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes, various restarts performed

### PR DESCRIPTION
**Pull request by ghost**
The cased treated before were very limited and unlike other browsers e.g

  - `firefox [OPTIONS] [url]`
  - `chromium-browser [OPTION] [PATH|URL]`

This commit assumes (like other browsers) that the last argument
 is an url and tries to interpret it as such.
 If that fails, then it simply returns `undefined`, as before.

Resolves brave/browser-laptop#9193 opening URL from external application (Thunderbird/LibreOffice) does not work any more

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests). **changed untested code**
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

# Test Plan:
  

# Reviewer Checklist:

# Tests:

## Valid URL

 1. Build `CHANNEL=dev npm run build-package`
 2. Start an instance from the build
 3. Start a second instance from the build with a valid url appended in the commandline e.g `Brave-linux-x64/brave https://duckduckgo.com`
 4. Verify that URL was opened in existing window

## Invalid URL

 1. Build `CHANNEL=dev npm run build-package`
 2. Start an instance from the build
 3. Start a second instance from the build with an invalid url appended in the commandline e.g `Brave-linux-x64/brave http:/bad.url.com`
 4. Verify that no URL was opened

## File URL

 1. Build `CHANNEL=dev npm run build-package`
 2. Start an instance from the build
 3. Start a second instance from the build with a valid file url appended in the commandline e.g `Brave-linux-x64/brave file:///`
 4. Verify that URL was opened in existing window

- [x] Adequate test coverage exists to prevent regressions **- previously untested --> no tests added**
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

**Comment by LoveIsGrief** [comment]
Changed your code @bbondy , so you might want to review this.

**Comment by NejcZdovc** [comment]
@bbondy set milestone to 0.19, because issue is set to 0.19 as well. If we want to push this back to 0.20, please do so.

**Comment by call-cc** [comment]
Pages like "about:preferences" should also be tested as arguments to Brave.

**Comment by LoveIsGrief** [comment]
@call-cc there were no automatic tests prior to this and there are none in this PR. That said, it doesn't change the underlying algorithm that checks the URLs, just the argument passed (the last one).

Simple tests with `brave -- about:preferences` in the old version and `brave about:preferences` show identical behavior.

**Comment by Liunkae** [comment]
Changed milestone to match issue #9193.

**Comment by bsclifton** [comment]
I'm not sure this is the right fix... the code in question hasn't been changed for 9 months - 1 year. This functionality worked up until 0.15.3 and was broken by 0.15.301.  I'll continue to investigate

**Comment by bsclifton** [comment]
OK found out what is different- in versions starting with 0.15.301, extra command line args are passed in (which prevents the URL from being opened)
`--disable-setuid-sandbox`
`--enable-features=BlockSmallPluginContent,PreferHtmlOverPlugins`

@bbondy @bridiver are we safe to just check if the last param is a file / URL?  I had thought we required escaping it so that we don't accidentally parse values coming after the `--` parameters (ex:  `--myFlag valueHere`)

**Comment by bsclifton** [comment]
@LoveIsGrief can you please try the solution outlined here?
https://github.com/brave/browser-laptop/issues/9193#issuecomment-318933076

I believe the fix described there is a more appropriate one.  If it works for you, I'll work on a fix tonite 😄

**Comment by LoveIsGrief** [comment]
Hi @bsclifton 

That fix also works. I maintain however, that I'm not a fan of diverging from the quasi-standard (firefox, chrome, chromium). If that is not a problem for this project, then I guess this PR can be rejected.

Cheers

**Comment by bsclifton** [comment]
@LoveIsGrief thanks for confirming 😄  Realistically, I think most cases would work fine with this PR... but the escaped method (`-- %U`) ensures the filename won't conflict with any of the arguments which are directly passed to Chromium

I'll go ahead and close this issue- just need to test the potential fix on RedHat OSes and it should be good to go 😄

**Comment by LoveIsGrief** [comment]
@bsclifton Alright, I understand that reasoning.

Thanks for the consideration 🙂

**Comment by bsclifton** [comment]
You're very welcome- thanks for taking the time to create the patch 😄  I'll try to get something up ASAP so that you (and others) are fixed going forward 😄

**Pull request closed without merging**
