### PR TITLE
fix verified publisher icon in Contribution Statement PDF

### PR DESCRIPTION
**Pull request by willy-b**
for #6039

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:
- Open Contribution PDF for transaction including a verified publisher
- Observe green check hexagon

### CODE REVIEW

**Comment by willy-b** [comment]
note, a rebased version of this commit (https://github.com/brave/browser-laptop/commit/f57a6ee3ea0a635d6edaab966c53094aadb71d1c) was pulled in by @cezaraugusto to his branch https://github.com/brave/browser-laptop/compare/auto-suggest-sites , so this PR may no longer be needed.

**Comment by cezaraugusto** [comment]
@willy-b that branch is for testing purposes only, and will likely never land in master. All open [ledger-related PRs](https://github.com/brave/browser-laptop/pulls?q=is%3Aopen+is%3Apr+label%3Afeature%2Fledger) (including yours) were cherry-picked and rebased. No need to close this one.

**Comment by bsclifton** [comment]
I can get all the tests passing, but I'm having some trouble here... @bbondy were all the issues with the PDF worked out in 0.13.0? What's happening to me is when I click the link to open the PDF, it opens and then closes within 1 second.

Issue happens on this branch, `0.13.1-branch`, and `master` :frowning_face:

**Comment by bsclifton** [comment]
Tests were already good to go; I verified that PDF is saved properly again (we had a rocky time in 0.13.0 where it was not working as expected).

I edited my `ledger-state.json` and verified this works great!  Awesome job, @willy-b :smile: 

Here's a screenshot of it in action:
screen shot 2017-01-23 at 1 20 17 pm

**Pull request merged**
