### PR TITLE
About page language support + Multiple Language locales

### PR DESCRIPTION
**Pull request by aekeus**
* Added support for async transfer of language code from main to renderer process
  * Added language request for about* pages
  * Send language codes to web pages to avoid head.meta.availableLanguage changes
  * Modified about*.html files to accept language codes and modify head.meta.availableLanguages
  * Added language labels to en-US/preferences.properties
  * Added language codes to app/locales.js
  * Modified General Preferences tab to use passed language list in Select form element
  * Updated tools/downloadLanguages.js with language constant support
  * Added all languages which have translations

### CODE REVIEW

**Comment by aekeus** [comment]
Updated to include multiple languages and re-factorings to eliminate code duplication

**Comment by bbondy** [comment]
@aekeus I'd like to merge this in, please rebase and let me know when it's ready. Thanks!

**Comment by aekeus** [comment]
This required a bit of refactoring to make work. I have a merged branch in progress, will submit PR tomorrow. (Also current download of translations)

**Comment by luixxiul** [comment]
please don't forget this one: https://github.com/brave/browser-laptop/pull/1574

**Comment by aekeus** [comment]
Thanks, not forgetting #1574. Working on getting a merge done.

**Comment by luixxiul** [comment]
thanks :+1:

**Comment by aekeus** [comment]
Closing, issuing new PR with downloaded languages

**Pull request closed without merging**
