### PR TITLE
Fix issue found in my session which prevented about:bookmarks from lo…

### PR DESCRIPTION
**Pull request by bsclifton**
Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by luixxiul** [comment]
@bsclifton I'm just wondering if it is OK to merge to `0.20.x` with the milestone set to 0.18 at the same time. ❓

**Comment by darkdh** [comment]
++

**Comment by bsclifton** [comment]
@luixxiul yup- this fix is needed for 0.20, 0.19, and 0.18. Master (0.21) reworks the way history/bookmarks are done, which no longer uses tags

**Comment by luixxiul** [comment]
@bsclifton ah, I just didn't notice that you merged to those branches as well (maybe you did when I was writing the comment above).

**Pull request merged**
