### PR TITLE
Add sync

### LINKED ISSUE #1854: Implement sync
Does Brave support sync ?       linux  Brave: 0.10.0 

I see sync mentioned in your code base yet sync does not appear in Preferences

### PR DESCRIPTION
**Pull request by diracdeltas**
this adds basic support for browser sync, using https://github.com/brave/sync

Fix #1854

# Test Plan:

## setup
- make sure automated tests related to sync are passing
- `npm install` to add dependencies
- `npm run download-sync-client` to download the sync client to the right subdirectory
- add the following to package.json to create a separate browser 'device' to sync to:
```
 "start2": "node ./tools/start.js --user-data-dir=brave-development-2 --debug=5859 --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck"
```

## test
- npm start
- go to about:preferences#sync
- enable sync
- restart, then click 'add device...'
- npm run start2
- in device 2, go to about:preferences#sync > i have an existing code > enter the code from device 1
- go to any website in either of the browsers, bookmark it and make some changes to the siteSettings. after a minute, it should show up in the other browser.

# todos before public release (not necessarily before merge)
- https://github.com/brave/sync/milestone/2

### CODE REVIEW

**Comment by ayumi** [comment]
I tested this on my browser data, consisting of 241 bookmarks and 525 preferences.

It took ~80 seconds of beachball spinning to sync over to pyramid 2, so we might want to sync more gradually or show a "Now syncing" notice.

**Comment by luixxiul** [comment]
Rebase needed

**Comment by ayumi** [comment]
Rebased to `0.13.1-branch` @187fa9a

**Comment by luixxiul** [comment]
Please create an associated issue? ;-) thanks

**Comment by ayumi** [comment]
Rebased to `0.13.1-branch` @e69d86f119018a433ebec7718e8c707999c6033e

Bookmark folders might have issues when syncing (should be resolved by https://github.com/brave/sync/issues/47 and https://github.com/brave/sync/issues/48 )

Regular bookmarks, history and site settings (eg Shields up/down) should sync correctly.

**Comment by ayumi** [comment]
Rebased on `0.13.1-branch` @ 134ad76b486d83a3834c99d3204365847801040d

**Comment by diracdeltas** [comment]
@bsclifton is this supposed to be rebased on master now?

**Comment by bsclifton** [comment]
0.13.1 is now merged 😄  Sorry for all the rebasing you've had to do to keep up with the merges. You all should be good now 👍

**Comment by diracdeltas** [comment]
closing in favor of https://github.com/brave/browser-laptop/pull/6882 which is against master

**Pull request closed without merging**
