### PR TITLE
remove favicon on navigate, in case next page has no icon to replace …

### PR DESCRIPTION
**Pull request by psimyn**
…it - fixes 642

### CODE REVIEW

**Comment by bradleyrichter** [comment]
Hi @psimyn. Thanks for this PR. Can you possibly attach a screen shot to show this use case?

**Comment by bbondy** [comment]
hey @bradleyrichter  this is related to #642 which isn't a design change, just a bug fix. So no screenshot needed.

**Comment by bbondy** [comment]
Thanks for the patch @psimyn
Please change to how `audioPlaybackActive` is reset (in 3 places) in `js/stores/windowStore.js`.

**Comment by psimyn** [comment]
thanks @bbondy updated those 3

**Comment by bbondy** [comment]
++ thanks for fixing.

**Pull request merged**
