### PR TITLE
Adding correct shortcut (⌃ ⌘ F) for toggleFullScreenView

### LINKED ISSUE #2194: Add correct shortcut for toggleFullScreenView on Mac OS X
**Describe the issue you encountered:**
Currently toggling the FullScreenView on Mac OS X is triggered via `⇧⌘F (Shift+Cmd+F)` or `⇧⌃F  (Shift+Ctrl+F)`. Does not correspondent with native OS behavior.
 
**Expected behavior:**
Shortcut that toggles the FullScreenView: `⌃⌘F (Ctrl+Cmd+F)`
- Platform (Win7, 8, 10? OS X? Linux distro?):
OS X 10.11.5
- Brave Version:
0.10.3

### PR DESCRIPTION
**Pull request by raphaelokon**
Closes #2194
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

### CODE REVIEW

**Comment by raphaelokon** [comment]
I added and force pushed a rebased patch to my fork. Should I close this PR and reopen it with my changes?

**Comment by luixxiul** [comment]
````
git rebase -i master

pick 8a4d0f6
s c8938c2

git push -f 
````

This would work, wouldn't it?

**Comment by raphaelokon** [comment]
Aye … I rebased my commits and force pushed (didn't know GH can handle forces pushes to already open PRs). Thanks @luixxiul

**Comment by bbondy** [comment]
Could you change the non OSX case to be F11 instead? Then you can also remove app/localShortcut.js's code for handling F11.  I think the shortcut we have there isn't used on Windows/linux in other browsers.

**Comment by raphaelokon** [comment]
@bbondy Aye aye – one sec.

**Comment by raphaelokon** [comment]
@bbondy Done.

**Comment by bbondy** [comment]
Excellent, thanks so much for the help!

**Pull request merged**
