### PR TITLE
Speed up ledger startup

### PR DESCRIPTION
**Pull request by mrose17**
Auditor: @bsclifton 

Test Plan:

1. LEDGER_LOGGING=true
2. launch browser with contributions off
3. verify that no ledger stuff prints out at all
4. turn on contributions
5. wait for system to create wallet, etc.
6. restart browser
7. verify that at least 3 seconds elapses before ledger code makes network calls

### CODE REVIEW

**Comment by bsclifton** [comment]
I rebased against master instead, since we're going to want to make sure performance is great there :smile: Will give this a go here and report back...

**Comment by bsclifton** [comment]
Tested on mac + Windows; looks good :smile:

**Comment by luixxiul** [comment]
Please create an associated issue, thanks :-)

**Comment by mrose17** [comment]
Fixes https://github.com/brave/browser-laptop/issues/6833

**Pull request merged**
