### PR TITLE
Replace Payment History CSV export with Contribution Statement PDF 

### PR DESCRIPTION
**Pull request by willy-b**
This is a Work-In-Progress PR, implementing #4769, so feel free to ignore, critique, fix, or replace with your own solution as you please.
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist. (issue #4769 )
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message. (This is WIP, will be rebased)
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (This is WIP, will be rebased)

Test Plan:
1. Open Brave
2. Open Preferences -> Payments, and ensure it is enabled
3. If you don't have a Payment History, you can generate a fake one at terminal with `npm run add-simulated-payment-history`
4. Click "Show Payment History"
5. Observe "Receipt Link" column now has links ending in ".pdf"
6. Click a receipt link, and confirm that a Save dialog opens and suggested filename is same as the one displayed in Receipt Link column
7. Click "Save", and observe that the PDF is downloaded and appears in the Downloads bar at bottom of screen
8. Double click the downloaded file
9. Check PDF against mockup

### CODE REVIEW

**Comment by willy-b** [comment]
I think this is ready for preliminary review.

Still fixing a few last nits (the copyright symbol gets corrupted due to some encoding issue!) but I think this is very close now.

Finally factored it all out of about:preferences and got all the strings localized last night (little tricky since had been generating a static data URL, but static rendering wouldn't play nice with l20n localization...).

Here's what it looks like:
contribution_statement_download

And here's a link to the PDF generated in example above:
[Brave_Payments_7-15-2016.pdf](https://github.com/brave/browser-laptop/files/592934/Brave_Payments_7-15-2016.pdf)

**Comment by bsclifton** [comment]
@willy-b this looks great! I'm going to set aside time to review this PR, hang in there with me :smile: 

Are there any opens from your side? (ex: are you actively fixing anything based on feedback?)  If not, you're welcome to squash up the commits.  Since this is a fairly large PR, you could squash them into logical chunks if you prefer instead of one massive one

**Comment by willy-b** [comment]
Hey @bsclifton, I can squash it up into one commit and open a new PR if you like.

**Comment by bsclifton** [comment]
Checking this out now :smile: Sorry for the huge delay here

**Comment by bsclifton** [comment]
OK @willy-b, just got some testing it... Looking really good!

## Changes I made
- moved ledgerExportUtil / ledgerExportUtilTest to new location
- moved exampleLedgerData to fixtures directory
- updated style of ledgerExportUtil to be more consistent with rest of codebase
- added tests for new sort functionality

I also fixed a JavaScript error I got when trying to save (data was regular array, not immutable; was failing the .get() call).

## Issues noticed (see pictures):
1. **_Â character in front of copyright_**
  The [l20n library](https://github.com/l20n/l20n.js/) seems to be putting a "Â" char in front of the copyright symbol. I see that the doc is being saved as UTF-8, which is correct... but you may need to just do a manual string replacement (when rendering the outerHTML)
  screen shot 2016-11-25 at 3 26 00 pm
2. **_Date in dialog is not correct; window is also not proper size_**
  I suspect this might be a platform specific issue (I'm testing on macOS).  The save dialog is always defaulting itself to the first file that I tried saving. Notice in this pic, it doesn't match the doc being shown.  Also, the doc being shown has scrollbars (even though I have enough room to show the whole thing).
  screen shot 2016-11-25 at 3 26 24 pm

**Comment by bsclifton** [comment]
@willy-b how's it looking? I saw your two commits... is this ready for re-review?

**Comment by willy-b** [comment]
Hey @bsclifton, thanks for the thorough review and fixes!

Yes, this is ready for re-review. Appreciate it!

**Comment by bsclifton** [comment]
@willy-b this looks great! Can you go ahead and squash it up? I can merge after that :smile: 

@bbondy, would you be up for us pulling this into 0.13.0? It's a really nice feature (great job, @willy-b!)

**Comment by bbondy** [comment]
yes please go ahead! Thanks!

**Comment by bsclifton** [comment]
Rebasing it right now... I should be able to push a rebase to your remote, @willy-b :smile:

**Comment by willy-b** [comment]
hey @bsclifton, I just rebased it, no need, opening a new PR now

**Comment by bsclifton** [comment]
@willy-b OK nice! :smile:

**Comment by willy-b** [comment]
this PR is replaced by rebased work in #5909

**Pull request closed without merging**
