### PR TITLE
add babel react plugins

### LINKED ISSUE #53: Check that we're using these babel / webpack optimizations
Check that we're using these babel / webpack optimizations:
> "optimisation.react.constantElements",
> "optimisation.react.inlineElements",

### PR DESCRIPTION
**Pull request by hzoo**
Fixes #53

### CODE REVIEW

**Comment by hzoo** [comment]
Are the PR's running travis/tests? (I'm still `npm i` locally)

**Comment by bbondy** [comment]
They were but I think when we opened the repo it got messed, will fix soon.

**Comment by bbondy** [comment]
Thank you so much for this!

**Comment by hzoo** [comment]
Looking at the webpack config - I think we can remove the ones there since the babelrc should cover it?

https://github.com/brave/browser-laptop/blob/master/webpack.config.js#L37 - doesn't seem to be a reason to keep both.

**Pull request merged**
