### PR TITLE
General improvements to install instruction updates for Linux

### PR DESCRIPTION
**Pull request by Jacalz**
Adds install instructions for Solus, adds Debian Buster and Stretch and removes old unmaintained versions of Ubuntu...

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:

Not really, just needs to be merged after https://github.com/brave/browser-laptop/pull/15210 get's deployed in a new update.

### CODE REVIEW

**Comment by Jacalz** [comment]
Will need to rebase this, before getting merged...

**Comment by Jacalz** [comment]
Rebased!

**Comment by Jacalz** [comment]
cc @bsclifton

**Comment by bsclifton** [comment]
The new version of Brave is live at https://brave.com/download/

If any improvements can be suggested for Linux users, please let us know on Community 😄

**Pull request closed without merging**
