### PR TITLE
Create BraveLink component

### LINKED ISSUE #12033: Manage BAT's TOS link as a component
### Description

Manage BAT's TOS link as a component to make it sure that the link is updated. Having the hard-coded link inside the two files (enabledContent.js and disabledContent.js) increases the risk that it would not be updated on either of them. 

### Brave Version

**about:brave info:**

93d7a771066c60bb56bcf0a07825861d447d2d88

**Reproducible on current live release:**

No.

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #12033

Auditors: @bsclifton

Test Plan:
1. Open about:preferences#payments
2. Disable payments
3. Click the TOS link
4. Make sure https://basicattentiontoken.org/contributor-terms-of-service/ is opened in a new tab
5. Disable payments
6. Click the link again
7. Make sure https://basicattentiontoken.org/contributor-terms-of-service/ is opened in another new tab

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
Can we move font size and color in this component as well, so that we don't duplicate css?

**Comment by luixxiul** [comment]
Ah right, except styles related with placement, I'm moving the styles to the component. Thanks for notifying =)

**Comment by bsclifton** [comment]
@cezaraugusto can you help me review this one? 😄

**Comment by cezaraugusto** [comment]
I'm wondering if it's not better to broaden the component for something like "braveLink" or similar otherwise we can potentially have several components for links. 

This way all links can share the same styles. URL can be set as prop if that's an issue like `<BraveLink termsOfService />` with its proper locale. wdyt @luixxiul?

**Comment by cezaraugusto** [comment]
this can solve the case where `noreferrer noopener` needs to be set for every link, so we don't forget. Target can be fixed too as I can't recall any link we have opening in the same webview

**Comment by luixxiul** [comment]
> this can solve the case where noreferrer noopener needs to be set for every link, so we don't forget

I was thinking the same thing, and going to try to create a stuff link `<Anchor>`. I like the idea `<BraveLink termsOfService />` 😄

**Comment by luixxiul** [comment]
Is `<Anchor BraveLink termsOfService />` too much maybe?

**Comment by cezaraugusto** [comment]
wouldn't `anchor` and `braveLink` be the same thing?

**Comment by bsclifton** [comment]
@luixxiul did you have an update for this one?

**Comment by luixxiul** [comment]
It turned out that `BraveLink` components would be applied to links on payments page, so I'll be waiting until 0.20.x is released like https://github.com/brave/browser-laptop/pull/12062 🙂

**Comment by luixxiul** [comment]
I'm closing the PR to review the conflicts and fix them.

**Pull request closed without merging**
