### PR TITLE
fix undefined active frame for back/forward button after tab close by cl…

### PR DESCRIPTION
**Pull request by jiangyang**
…icking

### CODE REVIEW

**Comment by bridiver** [comment]
Thanks for the PR! Is there a test we can add for this to prevent regressions?

**Comment by bridiver** [comment]
It looks to me like the props are not updating in main.js when the activeFrameKey changes. I think the issue may be in shouldComponentUpdate.

**Comment by bridiver** [comment]
The root cause of this is a call to set the active frame after the frame is closed. Should have a fix for it very soon. Thanks for your help! The steps to replicate the issue you provided were critical to fixing it.

**Comment by bbondy** [comment]
@bridiver should this be closed now?

**Comment by bridiver** [comment]
No, still working on the fix for this issue. The other PR was just a side issue that I initially thought was related

**Comment by bridiver** [comment]
actually I guess we can close it because I'll have a new PR for it

**Comment by bridiver** [comment]
Closing this and I'll reference it from my PR. Thanks again @jiangyang !

**Comment by bridiver** [comment]
I was initially skeptical, but after more investigation those does look like the right solution. It doesn't appear to need ```event.nativeEvent.stopImmediatePropagation()``` though. I'm putting together a test case for it now

**Comment by jiangyang** [comment]
late to reply...thanks for looking into this. I didn't go for the tests as I wasn't sure how to assert on the active frame but oh well. I've removed the nativeEvent stop as requested. Thanks again.

**Comment by bridiver** [comment]
closed by #232

**Comment by bridiver** [comment]
ha, sorry, beat you to it but your commit is in there

**Comment by jiangyang** [comment]
lol, no worries.

**Pull request closed without merging**
