### PR TITLE
Allow unblocking of scripts from urls containing ip addresses

### LINKED ISSUE #2988: Site specific script unblocking has no effect on URL containing an IP address.
**Did you search for similar issues before submitting this one?** Yup.

**Describe the issue you encountered:** With script blocking in the global Bravery settings, trying to unblock scripts in site-specific Bravery settings has no affect if the URL contains an IP address (and perhaps port number).

**Expected behavior:** Site-specific script unblocking should work regardless of the URL.
- Platform (Win7, 8, 10? macOS? Linux distro?): Tested on Linux (Ubuntu 16.04)
- Brave Version: 0.11.2
- Steps to reproduce:
  1. Enable script blocking in the global Bravery settings.
  2. Navigate to a JavaScript powered webpage containing an IP address in its URL, rather than a domain name.
  3. Attempt to unblock scripts in the site-specific Bravery settings (or disable shields).
  4. Notice that scripts still fail to work.

I've tested this issue with local (127.0.0.1) and LAN (192.168.1.*) IPs.

### PR DESCRIPTION
**Pull request by evq**
Auditors: @diracdeltas

Fixes #2988
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:
1. Create a temporary folder with `index.html` containing:
```
<html>
<p> welcome 2 mi web sight </p>
<p id="sneaky" style="display:none"> y u allow js </p>
<script>
document.getElementById('sneaky').style.display='block';
</script>
</html>
````
2. Run `python -m SimpleHTTPServer` inside the temporary folder.
3. Open Brave, go to Preferences and disable scripts globally.
3. Open the url `http://127.0.0.1:8000`.
4. Verify unblocking the script adds the additional text `y u allow js`.

I also added automated tests to the noscript info tests which can be run via:
```
npm run test -- --grep="^noscript"
```

### CODE REVIEW

**Comment by evq** [comment]
Looks like the ipv6 test failed on Travis, seems they pulled ipv6 support some time back. Two options:

1. I can delete the ipv6 test
2. I can programmatically skip execution of the ipv6 test based on the env var `TRAVIS` which is set to `true` when running on Travis

**Comment by diracdeltas** [comment]
> I can programmatically skip execution of the ipv6 test based on the env var TRAVIS which is set to true when running on Travis

sgtm

**Comment by diracdeltas** [comment]
lgtm, plz `rebase -i` it

**Comment by evq** [comment]
👌

**Pull request merged**
