### PR TITLE
Fixes auto unpinning for payment publishers

### LINKED ISSUE #11369: Pinned publishers keeps getting auto unpinned
### Description

Pinned publishers keeps getting auto unpinned
### Steps to Reproduce

  1. Upgrade to 0.19.35
  2. Have three publishers pinned
  3. One at 90%, second at 4%, third at 4%
  4. Have one publisher enabled, set at 2% completing 100%
  5. Use browser normally for a while
  6. Open payments
  7. One of the pinned publisher with 4% is unpinned but still enabled

**Actual result:**
Pinned publishers keeps getting auto unpinned

**Expected result:**
Pinned publishers should remain pinned

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%. Have seen this happen twice
### Brave Version

**about:brave info:**

Brave | 0.19.35
-- | --
rev | eda2732
Muon | 4.4.25

**Reproducible on current live release:**
No

### Additional Information

cc: @mrose17 @evq

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #11369

Auditors:

Test Plan:

1. Upgrade to 0.19.35
2. Have three publishers pinned
3. One at 90%, second at 4%, third at 4%
4. Have one publisher enabled, set at 2% completing 100%
5. Use browser normally for a while
6. Open payments
7. One of the pinned publisher with 4% is unpinned but still enabled

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by cezaraugusto** [comment]
I think STR are very clear and would be cool to have it as a webdriver test

**Comment by NejcZdovc** [comment]
@cezaraugusto I wouldn't add web driver, but unit tests

**Comment by luixxiul** [comment]
Is there a test plan different from the steps to reproduce the issue https://github.com/brave/browser-laptop/issues/11369#issue-263729417 ? It is not quite clear how it should be tested (how long should `for a while` be?)

**Comment by cezaraugusto** [comment]
I personally think user interactions should be handled by webdriver but some tests is better than no tests so +1 for unit test if you prefer

**Comment by srirambv** [comment]
> It is not quite clear how it should be tested (how long should for a while be?)

I found the issue after about an hour of usage. It could be much less. As you need to use the browser normally after enabling I feel best way to test is upgrade with the fix and use it ~1 hour and see if  the fix  works.

**Comment by luixxiul** [comment]
IF there isn't an exact way of testing the issue, please add `no-qa-needed`.

**Comment by bsclifton** [comment]
master https://github.com/brave/browser-laptop/commit/a03730a2f0909c882a86f10f8453dc8c7fcf4070
0.20.x https://github.com/brave/browser-laptop/commit/a6e2dad44aec415e830e886d00d8db0ef8fbd27f
0.19.x https://github.com/brave/browser-laptop/commit/be33dfc814d1ea75400b4a253cc3df4aad74de56

**Pull request merged**
