### PR TITLE
ledger recovery should be aware of network status and localization

### PR DESCRIPTION
**Pull request by mrose17**
@bsclifton  this is an incomplete replacement for https://github.com/brave/browser-laptop/pull/6456 

Fixes https://github.com/brave/browser-laptop/issues/4720
Fixes https://github.com/brave/browser-laptop/issues/5806

if you look [here](https://github.com/brave/browser-laptop/blob/0.13.1-ledger-recovery/js/about/preferences.js#L1154) you will see the code that runs when the "Recover Your Brave Wallet" modal is rendered. i put the calls to `console.log` there to see when that happens. it happens initially, just fine, but it should also happen when [this](https://github.com/brave/browser-laptop/blob/0.13.1-ledger-recovery/js/about/preferences.js#L1154) or [this](https://github.com/brave/browser-laptop/blob/0.13.1-ledger-recovery/js/stores/appStore.js#L683) is invoked and it doesn't.

i submitted this as a new branch/PR to help focus the effort. also, i fixed a typo [here](https://github.com/brave/browser-laptop/blob/0.13.1-ledger-recovery/js/about/preferences.js#L1194).

## Test Plan
https://github.com/brave/browser-laptop/issues/4720#issue-182585748

### CODE REVIEW

**Comment by bsclifton** [comment]
@mrose17 I fixed the appState issues. Happy paths work great!

I test locally and after disabling the network, getting the error, and then re-enabling... I kept getting network errors (even when using valid wallet codes). I can open new tabs and browse just fine; but ledger still things network is down it seems.  Can you check that part out?

**Comment by mrose17** [comment]
@bsclifton - i suspect that your network wasn't re-enabled for the ledger. when i run that test, i get this:

**Comment by mrose17** [comment]
however, when i dismiss that, i see this:

**Comment by bsclifton** [comment]
@mrose17 perfect 😄  Once you solve that, I think we're good for merge!

**Comment by bsclifton** [comment]
Rebasing this one and will work on merging it next 😄

**Comment by bsclifton** [comment]
OK rebased! Will watch CI here 😄

**Comment by bsclifton** [comment]
Not ready for merge yet- some of the tests are failing.  Will look into this tonite

Specifically:
`npm run test -- --grep="Payments Panel -> Advanced Panel"`

**Comment by bsclifton** [comment]
Advanced Panel tests could use some love... definitely intermittent failures. However, manual testing is successful.  Merging

**Pull request merged**
