### PR TITLE
show message when no payments have been made

### LINKED ISSUE #6555: No contributions yet!
As suggested [here](https://community.brave.com/t/bitcoin-payments-where-did-my-money-go/526/6): to avoid confusion for new users, when no contributions have been made yet, have other text go where the "View Payment History..." link will go after the first contribution.

### PR DESCRIPTION
**Pull request by jkup**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fix #6555

Auditors @bsclifton @mrose17 @bradleyrichter 

## Test Plan

1. Go to Preferences#payments
2. Make sure it now reads "Your first payment will be in".. some amount of time
3. Simulate a payment
4. Make sure it now reads "Your last payment was"... some amount of time

screen shot 2017-01-11 at 9 32 17 pm

### CODE REVIEW

**Comment by bradleyrichter** [comment]
@mrose - does the timer start before funds are added?

@jkup - I think the new orange style is nice but it should work fine to group it in the status column rather than adding a redundant message.

**Comment by jkup** [comment]
@mrose17 @bradleyrichter Can I get some clarity on what this ticket should include? Should there be any link or text in that left column or only one in the status column that changes if you haven't made a payment yet?

**Comment by mrose17** [comment]
@jkup & @bradleyrichter - i'd prefer exactly the text i listed above, on the left and with no links, as it i believe it deals with a specific cognitive dissonance that cost me a lot of time last week.

my only issue with orange text is that the line spacing should match what we have on the right. thanks1

**Comment by bsclifton** [comment]
[Last travis-ci run](https://travis-ci.org/brave/browser-laptop/builds/191561883) shows 5 errors; I re-ran those locally and it's working as expected :smile: Merging...

**Pull request merged**
