### PR TITLE
remove getURL

### PR DESCRIPTION
**Pull request by bridiver**
cc @bbondy

### CODE REVIEW

**Comment by luixxiul** [comment]
Don't we need to have an associated issue for this?

**Comment by bridiver** [comment]
@bbondy did you create an umbrella issue for removing the sync webview methods?

**Comment by bbondy** [comment]
@bridiver  https://github.com/brave/browser-laptop/issues/7002

**Comment by bbondy** [comment]
++

**Comment by luixxiul** [comment]
@bbondy will this be included in 0.13.3?

**Comment by bbondy** [comment]
no issue is ok on this one, it will bypass QA but this would break from general regression pass if it was a problem.

**Pull request merged**
