### PR TITLE
don't active tabs on preview

### PR DESCRIPTION
**Pull request by bridiver**
depends on https://github.com/brave/electron/commit/9e830080e038842df51fbc8e8938c0376e354c66

@bbondy  - don't merge until electron is updated ^^

#1916

### CODE REVIEW

**Comment by bbondy** [comment]
Merged into chromium51 branch which will be merged to master soon.

**Comment by luixxiul** [comment]
Wasn't the branch merged? Still I get the same issue.

**Comment by bbondy** [comment]
works for me you probably need a fresh npm install or possibly to clear out your ~/.electron first too.

**Comment by luixxiul** [comment]
OK I'll try.

**Comment by luixxiul** [comment]
Confirmed it works.

**Pull request closed without merging**
