### PR TITLE
always return copy of parse url and remove option for query as object

### LINKED ISSUE #11101: urlParse returns inconsistent types for `.query`
There are really no steps to replicate the problem because it was partially addressed here https://github.com/brave/browser-laptop/commit/d142b243150684da669d86c4d1e83cc5d20769a5

### PR DESCRIPTION
**Pull request by bridiver**
fix #11101

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:
As mentioned in the ticket there really isn't a good way to QA this

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bridiver** [comment]
this is also for legacy node url.parse and muon.url.parse compat because muon always returns a string

**Comment by NejcZdovc** [comment]
Yeah we have this scenario in `ledger.js` `urlParse(location, true)`

**Comment by bridiver** [comment]
@NejcZdovc but the query string is never used so it has no effect

**Comment by bbondy** [comment]
This was also needed for 0.21.x and 0.20.x


0.20.x: 498ce5ce8600ffe4c342329c70384596a98eda70
0.21.x: 6e5b80b51b6eb16e470ea677962d7e0a87dbc191

**Pull request merged**
