### PR TITLE
restyled hamburger menu

### PR DESCRIPTION
**Pull request by bradleyrichter**
@bbondy

### CODE REVIEW

**Comment by bsclifton** [comment]
This looks great to me! Just so everyone else can see:

## Before
burger-before

## After
burger-after

**Comment by bbondy** [comment]
The 3px gap needs to be fixed, I think there's also some alignment issues on the bookmarks toolbar folders last I checked.

**Comment by bradleyrichter** [comment]
Ideally this menu would overlap the tabs toolbar but I was unable to get that to work.

Chrome example:

image


(ours can come from the top right corner in order to stay within the browser window frame. (unfortunate but current limitation)

**Comment by bbondy** [comment]
I'll merge this in and work on fixes.

**Comment by luixxiul** [comment]
I think this change broke dragging items in the bookmark folder.

**Comment by luixxiul** [comment]
I filed an issue for it, #1975.

**Comment by luixxiul** [comment]
Icon size or padding should be fixed.

**Pull request merged**
