### PR TITLE
Removes PIA

### LINKED ISSUE #14763: remove PIA
we decided to not use PIA anymore

are there infrastructure changes needed for this or is it just a matter of changing the endpoints in browser-laptop? @evq @mrose17 

related: https://github.com/brave/browser-laptop/issues/12923

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves #14763

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
- make sure that PIA is not referenced any more
image
- run browser with LEDGER_VERBOSE and make sure that requests don't go through PIA

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@ryanml yeah we can remove it in bat-client as well

**Comment by diracdeltas** [comment]
@NejcZdovc is there anything in bat-client that uses PIA? (if so we should get rid of that too)

**Comment by NejcZdovc** [comment]
@diracdeltas no we don't use any reference to PIA in bat-client

**Comment by NejcZdovc** [comment]
master c07fe93
0.24 325802532
0.23 a38be75cc

**Pull request merged**
