### PR TITLE
Open brave payments contrib pdf in PDF.js after generated (WIP)

### PR DESCRIPTION
**Pull request by willy-b**
part of issue #6039

opening this as WIP because it depends on PDF.js being able to open local files (#2714 ~~, I think, but may have been fixed in #6330~~)

I'm looking into PDF.js myself right now but I am at total newbie with Chrome extensions so feel free to let me know if you have tips on how to fix it.

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests). (not yet)
- [ ] Ran `git rebase -i` to squash commits (if needed). (not squashed yet)

Test Plan:
- Navigate to `about:preferences#payments`
- Click 'View Payment History'
- Click one of the receipt ilnks
- Choose path to save PDF
- Observe PDF is also opened in new tab

### CODE REVIEW

**Comment by srirambv** [comment]
pdfcontribution

@willy-b  Clicking the link doesn't offer to save the pdf nor retain the pdf opened in new tab. This is on 0.13.0 Preview 7 on Windows 10 x64

**Comment by willy-b** [comment]
@srirambv yes, contribution PDF feature is still broken following Chromium54 upgrade (#4769) as the Muon API webview.printToPDF fix from @bbondy (#6450) has not made it into `browser-laptop` yet.

**Comment by willy-b** [comment]
since the underlying feature is broken right now by Chromium54 upgrade I am going to cancel this PR, thanks

**Comment by willy-b** [comment]
@srirambv, I was wrong:
 @bbondy's fix actually came into `brave/browser-laptop` with the Preview7 tag, and I can confirm the underlying feature is working on Linux there, so your observation above was a very useful one. Thanks.

**Comment by bbondy** [comment]
Ya, I don't think I had it in on all platforms but I think mac and linux probably got it.

**Pull request closed without merging**
