### PR TITLE
fix flickering effect between tabs. closes #2817

### LINKED ISSUE #2817: Tab transitions now cause flicker
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When hovering over multiple tabs, the 'peeking' functionality leaps back to the active tab causing a flickering effect.

**Expected behavior:**
This is a UX call, but my opinion would be to persist the view of the peeked tab until we're sure they are no longer scanning across tabs. Perhaps track mouse dx and infer behavior?

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.11.2

- Steps to reproduce:
    1. Open multiple tabs for different sites
    2. Move the mouse across the tabs

- Screenshot if needed:
tab_switching

- Any related issues:
https://github.com/brave/browser-laptop/issues/2765

### PR DESCRIPTION
**Pull request by cezaraugusto**
**Preview:**

tab_preview_fix

### CODE REVIEW

**Comment by cezaraugusto** [comment]
I noticed now that's better to add a gutter to first non-pinned tab instead of last pinned one. Working on it.

**Comment by cezaraugusto** [comment]
Ready for review :+1:

**Comment by cezaraugusto** [comment]
Squashed a commit improving experience while going from/to urlBar.

Current delay for non-previews was changed to 200ms. Could be altered if appropriate.

**Preview:** (CC @alexwykoff)

flickening

**Comment by bbondy** [comment]
++

**Comment by luixxiul** [comment]
in 0.11.2?

**Pull request merged**
