### PR TITLE
Fixes noScriptButton not being displayed

### LINKED ISSUE #8752: noScriptButton is no longer displayed
**Describe the issue you encountered:** noScriptButton is no longer displayed.

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA): b9ac832

- Steps to reproduce:
    - Open twitter.com and `Block Scripts`, or
    - `npm run test -- --grep='blocks scripts in a regular tab'`

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Resolves #8752

Auditors: @luixxiul @bsclifton

Test Plan:
- `npm run test -- --grep='blocks scripts'`

### CODE REVIEW

**Comment by diracdeltas** [comment]
The script blocking test isn't being run on Travis because a test before it is broken: https://travis-ci.org/brave/browser-laptop/jobs/229859531

**Comment by NejcZdovc** [comment]
I know, I tried tests locally.

**Comment by diracdeltas** [comment]
maybe skip that test for now so the tests after it can run? (or move it to the end)

**Comment by luixxiul** [comment]
> The script blocking test isn't being run on Travis because a test before it is broken: https://travis-ci.org/brave/browser-laptop/jobs/229859531

that issue is a duplicate here: https://github.com/brave/browser-laptop/issues/8760

Currently the tests after these two failing ones do not run. I'm moving them to the bottom as a temporary workaround, until our own iframe page becomes ready.

**Pull request merged**
