### PR TITLE
shallow clone for install

### PR DESCRIPTION
**Pull request by edouard-lopez**
Most people won't need to pull the whole history

### CODE REVIEW

**Comment by bridiver** [comment]
These instructions are primarily targeted at developers who want to contribute so I'm not sure if we'd want to change that. @bbondy ?

**Comment by bbondy** [comment]
Thanks for the PR! 
I prefer getting the whole history locally, I suspect a lot of devs do too.  Could you amend the commit to provide an alternate installation step?

**Comment by bbondy** [comment]
Thanks!

**Comment by bridiver** [comment]
great addition, thanks!

**Pull request merged**
