### PR TITLE
numerous small adjustments to buttons and some other style fixes

### LINKED ISSUE #5527: small adjustments to toolbar icons, hover states, colors, etc needed.
PR: #5526

testing required:

- all icons should be vertically aligned on mac, windows, linux, 
        - in normal 
        - and "retina" resolution

### PR DESCRIPTION
**Pull request by bradleyrichter**
cc @jkup @bsclifton 

Fix #5527

### CODE REVIEW

**Comment by bsclifton** [comment]
On Mac here- noticed the home button is not horizontally aligned:
screen shot 2016-11-10 at 9 15 58 am

**Comment by bradleyrichter** [comment]
thanks. I'll fix...

**Comment by srirambv** [comment]
@bradleyrichter This is how it looks on Windows. The mouse hover isn't very prominent. Plus the stop button looks a little lighter than the refresh and the home buttons

image

**Comment by jkup** [comment]
Colors look great! Agree with other fixes on here then we're good to go!

**Comment by bradleyrichter** [comment]
ok, all of the above should be fixed but we still need a windows review to check the button alignments.

**Comment by bbondy** [comment]
++ merging.

**Comment by bradleyrichter** [comment]
@bbondy @bsclifton @jkup  This will need windows adjustment unless all planets aligned.

**Comment by srirambv** [comment]
@bradleyrichter @jkup @bsclifton  

Stop loading SVG is still not fixed on Windows
Refresh SVG is still not center aligned

image

Clearly visible when zoomed in 
image

**Comment by luixxiul** [comment]
> Stop loading SVG is still not fixed on Windows

+1 on macOS

**Comment by luixxiul** [comment]
#5737 should fix the alignment issue.

**Pull request merged**
