### PR TITLE
Increase tabs bar height by 2px

### PR DESCRIPTION
**Pull request by jamesmudgett**
Fixes https://github.com/brave/browser-laptop/issues/8263

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

### CODE REVIEW

**Comment by luixxiul** [comment]
This reduces margin-top of `navigationWrapper` from 7px to 4px as well, which is OK?

**Comment by luixxiul** [comment]
This change reduces the 3px margin between the top edge of the window and the URL bar, which is surely expected?

clipboard01

**Comment by bradleyrichter** [comment]
No, we don't want that. It's important grab area space.

**Comment by luixxiul** [comment]
it is that what I have mentioned, but maybe I should have paste the picture. will work on fix.

**Pull request merged**
