### PR TITLE
Show history on long click over back button

### LINKED ISSUE #1622: Holding on back button should show the list of previous pages to choose
When holding on Back button, I'd like to see list of previous pages, so I can choose from, without having to click Back button too many times when my history is quiet long.

Similar thing works in Chrome as shown below:

screen shot 2016-05-08 at 00 54 59

The same should be implemented for Forward button.

Currently when I'm holding on either Back or Forward button, the whole window moves.

This is especially trouble when the previous page is a redirect page (#1633), so you can't easily skip that page.

### PR DESCRIPTION
**Pull request by bsclifton**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

History now shows in context menu after a long press on back button or forward button.

~~Depends on brave/electron#30 (must be merged before this can be accepted)~~
Fixes #1622
(although it doesn't match the proposed mockup- a new issue can be filed for that)

Ready for review!
cc: @bbondy @bridiver

- Adds dependency for jsdom-global (used for mocking window)
- Includes extra tests for urlutilTest.js

### CODE REVIEW

**Comment by bsclifton** [comment]
(original feedback was given with https://github.com/brave/browser-laptop/pull/2435)

**Comment by bbondy** [comment]
So great to have this, I might have some follow up comments but let's do that in future commits if so.

**Comment by luixxiul** [comment]
works like a charm! thanks :-)

**Comment by luixxiul** [comment]
I noticed that the comment above was not reflected when I went back from another page until I reloaded this page. Is it as it should be?

**Comment by bsclifton** [comment]
@luixxiul not sure what you mean- will shoot you a msg

**Comment by luixxiul** [comment]
Also is it possible to use cache there? Favicons are reloaded in the pulldown list :-S

**Pull request merged**
