### PR TITLE
clean up element styling

### LINKED ISSUE #5095: Form elements are nested too deeply
This also relates to #4884 but our form elements like input[type="text"] and general button.browserButton are nested too deeply (inside 3 classes) so that in order to get the styling you need to import settingsList and settingsListItem.

Since we want consistent form styling all throughout the settings pages we should pull those styles out into the top level of preferences.js.

### PR DESCRIPTION
**Pull request by jkup**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Auditors: @bsclifton @bradleyrichter 

Fix #5095 #5094

Testing:

1. Check all Preferences pages to make sure no form styles are broken. The input and select fields should look identical to master.
2. Go to about:styles and make sure the documentation and UI is acceptable for shipping.

screen shot 2016-11-14 at 11 38 47 am

### CODE REVIEW

**Comment by bsclifton** [comment]
Looking good so far :smile: 

**The select boxes and some of the input fields (like homepage) look a little small on Mac:**
screen shot 2016-11-07 at 1 54 43 pm

**Versus the Windows ones, for comparison**
screen shot 2016-11-07 at 1 59 17 pm

**Comment by jkup** [comment]
@bsclifton my fault! I think I wasn't clear, I just wanted to put up a WiP to get your opinion on whether the adding of the class should be done manually or hidden away in a separate <BraveSelect /> type component?

**Comment by bsclifton** [comment]
@jkup doh- sorry, I had totally missed that :frowning: 

That sounds like a great idea for a rev1 :smile: Pulling each item out to a control (let's make sure to put into the new structure, which is `app/renderer/components/` and then we can iterate from there

**Comment by bsclifton** [comment]
Deleted my above comments from when this was a WIP :smile: 

Preferences still look great. When going to about:styles, it seems like the `text` and `select` inputs both are smaller than on the preferences page (wasn't sure if this was expected).

One consideration (curious what both you and @bradleyrichter think) would be changing styles on focus. One usability problem in Brave is that using keyboard navigation is near impossible in certain scenarios (like the preferences page).  It would be great to have a visual indicator of where the tab focus currently is

**Comment by bsclifton** [comment]
From comparing to other parts of the app, it looks like the White app button is missing it's hover style; if you go to Preferences > Payments, you can see a demo there which I believe is @buttonColor and then #000 on hover

**Comment by bsclifton** [comment]
Another consideration too might be to put:
`cursor: default` and -webkit-user-select: none` on some of the elements, like the h1, h2, etc.  Since we'd want to make it more app-like.

**Comment by bsclifton** [comment]
Looks great! :smile: (comments left above)

**Comment by jkup** [comment]
Comments sound good:

1. They do look a bit smaller. I'll figure out where that size or padding is coming from and fix it.
2. I would very much like to add focus styles on our form elements. It's nice for all users but a huge accessibility win as well.
3. I see the white button as having the right colors: #444 regularly and #000 on hover.
4. Happy to add cursors to the headers! Let me know what we should do!

**Comment by jkup** [comment]
@bsclifton I fixed the sizing thing! Should we merge this for now and sync with @bradleyrichter later about cursors and focus state?

**Comment by bradleyrichter** [comment]
Does this include the dream (mine) of having all buttons now connected so I can refine the styles across the entire app? Or is this just the first step to that dream?

**Comment by bsclifton** [comment]
@bradleyrichter this should be that dream! :smile:  What do do you think about the app cursor comments I had above?

**Comment by bsclifton** [comment]
Merging :smile: If we need any changes, let's create a new issue

**Pull request merged**
