### PR TITLE
Temporary fix for #9056

### PR DESCRIPTION
**Pull request by diracdeltas**
Test Plan:
1. go to http://alexwykoff.com/tests/testlinks.html
2. open downloadme.org directly in the urlbar, via a link, via right-click to open in new tab, and via cmd+click. all should eventually redirect to the safebrowsing page, and the safebrowsing text should be visible.
3. safebrowsing travis test should still pass
4. go to about:preferences#shields and disable safebrowsing
5. go back to  http://alexwykoff.com/tests/testlinks.html and cmd+click on downloadme.org. the site should now load.

this is a temporary workaround. it causes the safebrowsing page to flicker while loading in some cases.

### CODE REVIEW

**Comment by alexwykoff** [comment]
I tested vs a clean profile. cmd+click did not appear to work
safebrowsing

**Comment by diracdeltas** [comment]
@alexwykoff does right-click to open in new tab work? does it work intermittently?

**Comment by diracdeltas** [comment]
nvm  i can repro

**Comment by diracdeltas** [comment]
@alexwykoff please try this new fix

@luixxiul i think this also fixes #8978 or at least turns it into a different bug. :)

**Comment by alexwykoff** [comment]
++ lgtm

**Comment by diracdeltas** [comment]
@alexwykoff added tests

**Comment by bbondy** [comment]
@diracdeltas I'm going to merge but please do a follow up to remove that code from tabs.js.  Alex mentioned that you can't reproduce this in 0.15.2 so I'd start with doing a regression range find to see.

**Pull request merged**
