### PR TITLE
enable file access from main window

### PR DESCRIPTION
**Pull request by bridiver**
required changes for https://github.com/brave/electron/commit/f0bd45b6e8984d1448d459c08799adc2411436f8

### CODE REVIEW

**Comment by bridiver** [comment]
cc @bbondy

**Comment by bbondy** [comment]
Could you explain more what the options do exactly and why the motivation for the change? thanks.

**Comment by bridiver** [comment]
do be honest it wasn't clear to me exactly what the options do, but they were previously enabled by default in electron and disabled by default in Chrome. https://github.com/brave/electron/commit/f0bd45b6e8984d1448d459c08799adc2411436f8 disables them be default in electron, but they appear to be required for node and disabling them breaks some things in the main window. I tested file urls and they still work fine and other file resources with a problem.

**Comment by bbondy** [comment]
k thx, matching chrome is best as long as it still works.

**Pull request merged**
