### PR TITLE
Allow standard to validate flow type annotations

### PR DESCRIPTION
**Pull request by petemill**
Uses babel-eslint and the flowtype plugin - https://standardjs.com/index.html#flow
babel-eslint must be kept at v.7.2.1 as later versions do not correctly identify flow types with the flowtype plugin and standard (see https://github.com/standard/standard/issues/984)

I'm creating this PR with only this config to allow for an isolated review, as some upcoming code depends on this.

Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

Test Plan:

Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by petemill** [comment]
@cezaraugusto actually we need to keep this in 0.21.x as it is a dependency of #11720

**Comment by cezaraugusto** [comment]
ok let me uplift then

**Comment by cezaraugusto** [comment]
master ffd6cc
0.21.x 878d190664c6132e39f2405c0a0a687f525c3f2f

**Comment by petemill** [comment]
thanks @cezaraugusto !

**Pull request merged**
