### PR TITLE
Tabs fine tuning

### PR DESCRIPTION
**Pull request by bradleyrichter**
Test Plan:

Confirm styling and alignments changes are OK on windows 7, 8, 10.

image

### CODE REVIEW

**Comment by bsclifton** [comment]
Here's a shot from Windows 10
image

**Comment by bsclifton** [comment]
Windows 7 at 150% DPI
image

**Comment by bsclifton** [comment]
And lastly, here's Windows 8. Looks and feels consistent across the board 😄 
image

**Comment by bradleyrichter** [comment]
@bsclifton thanks for the check...

It looks like the lock icon is moving up, and appears to be larger. Do you have a separate windows adjustment for it?

**Comment by bsclifton** [comment]
image

**Comment by bsclifton** [comment]
Here's where the margin comes from (on Windows) that pushes the text in the input down:
https://github.com/brave/browser-laptop/blob/f62306a67e868b0b5d45b8c92b77b0e35182fadd/less/navigationBar.less#L731

**Comment by bsclifton** [comment]
@bradleyrichter if you want to resolve the conflict, I think this is good for merge :smile: 

The issue I pointed out is already captured with https://github.com/brave/browser-laptop/issues/4814

**Comment by bbondy** [comment]
Part of this was reverted here:
https://github.com/brave/browser-laptop/commit/1e0d74caff8101743b3d7c4bf33d628ea42eeecb

For regressions described here:
https://github.com/brave/browser-laptop/issues/5005

Please post a follow up labeled with `release/non blocking` to track,  i can be tracked in 0.12.6 for now.

**Pull request merged**
