### PR TITLE
Follow-up of #7547

### LINKED ISSUE #7739: Follow up of #7547
## Test plan

https://github.com/brave/browser-laptop/pull/7740#issue-214511262

----

**Describe the issue you encountered:**

screenshot 2017-03-16 5 00 39
screenshot 2017-03-16 5 00 48
screenshot 2017-03-16 5 01 41

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA): master

- Screenshot if needed:

- Any related issues: #7546

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #7739

Auditors:

Test Plan:

**Test case 1 - default status**
1. Clear your profile
2. Start the browser
3. Make sure that the area between the URL bar and the tabs bar is draggable

screenshot 2017-03-16 11 47 29

**Test case 2 - text only**
4. Open https://github.com/ in a new tab
5. Open https://github.com/features in a new tab
6. Open https://github.com/explore in a new tab
7. Open https://github.com/pricing in a new tab
8. Display the bookmark toolbar
9. Bookmark them **by dragging the lock icon on the URL bar to the bookmark toolbar**
10. Make sure that the area between the bookmarked items and the URL bar is draggable
11. Make sure that the area between the bookmarked items and the tabs bar is draggable

screenshot 2017-03-16 11 56 11

**Test case 3 - text only with tab sets**
12. Open about:preferences#tabs
13. Set the number of tabs per tab set to 6
14. Open several new tabs to create another tab page
15. Narrow the window size to place the tab page indicators under the bookmarked items
16. Make sure that the area between the tab page indicators and the bookmark bar is draggable (the tiny area between the indicators is NOT draggable)
17. Make sure that the area between the tab page indicators and the tabs bar is draggable

screenshot 2017-03-16 11 57 14

**Test case 4 - text and favicons with tab sets**
18. Open about:preferences
19. Change "Text only" to "Text and Favicons"
20. Repeat the step 16 and 17
21. Close several tabs to clear the 2nd tab set
22. Make sure that the area around the bookmarks is draggable

screenshot 2017-03-16 11 57 34

screenshot 2017-03-17 16 41 48

**Test case 5 - only tab sets**
23. Hide the bookmark toolbar
24. Make sure that the area around the tab page indicators is draggable

screenshot 2017-03-16 11 50 55

**Test case 6 - favicon only with and without tab sets**
25. Bookmark several other GitHub pages
26. Open about:preferences
27. Change "Text and Favicons" to "Favicon only"
28. Change window size to place the tab page indicators under the bookmark favicons
29. Repeat the step 16 and 17
29. Close tabs to clear the 2nd tab set
30. Make sure that the area around favicons is draggable

screenshot 2017-03-16 12 31 24 screenshot 2017-03-16 12 31 38

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

### CODE REVIEW

**Comment by jamesmudgett** [comment]
Final result should look like this: 
screen shot 2017-03-15 at 4 51 13 pm

**Comment by luixxiul** [comment]
Updated with some tweaks, focusing on draggability.

**Comment by luixxiul** [comment]
Thanks, I'll take a look.

**Comment by luixxiul** [comment]
It is because of the margin-bottom of URL bar, specifically `.navigationWrapper`.

**Comment by luixxiul** [comment]
Updated. It looks hacky a bit and also it is not compatible with Aphrodite for now, still it works better.

The modification based on the feedback by @bsclifton is covered with the Test case 2 in the 1st post of this PR, which is also updated.

**Comment by luixxiul** [comment]
@NejcZdovc I see the same thing on master as well.

**Comment by NejcZdovc** [comment]
@luixxiul Can you fix it in this PR as well?

**Comment by luixxiul** [comment]
Sorry, I don't know how to.

**Comment by NejcZdovc** [comment]
You can try something like this

```diff
 less/navigationBar.less | 2 --
 1 file changed, 2 deletions(-)

diff --git a/less/navigationBar.less b/less/navigationBar.less
index fc6e272..25e1217 100644
--- a/less/navigationBar.less
+++ b/less/navigationBar.less
@@ -725,8 +725,6 @@
   &:not(.titleMode) {
     > * {
       animation: fadeIn .6s;
-      opacity: 0;
-      animation-fill-mode: forwards;
     }
```

**Pull request merged**
