### PR TITLE
Initial commit for default site settings

### LINKED ISSUE #8890: Sites needs to be added to the allow autoplay defaults

### LINKED ISSUE #8929: Autoplay notification shown for local files
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Autoplay notification shown for local files instead of playing the video upload load

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.15.304
rev	b872523
Muon	3.0.103

- Steps to reproduce:
    1. Open a new tab and open a .mp4 file from machine
    2. Auto play notification is shown instead of playing the video automatically
    3.
    
- Actual result:
Autoplay notification shown for local files

- Expected result:
For local files loaded in browser there should not be any autoplay notification shown. 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
image

- Any related issues:
cc: @darkdh

### PR DESCRIPTION
**Pull request by darkdh**
fix #8890
fix #8929 

Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by Jacalz** [comment]
Here are some the swedish sites that is big and widely used:
http://tv.aftonbladet.se (This should only be default on tv.aftonbladet and not on the whole site)
https://stvplay.se
https://viaplay.se
https://viafree.se
https://tv4play.se

**Comment by luixxiul** [comment]
From my viewpoint, adding exceptions is ok but the number of people who may want to disable autoplay must be large on the large sites, so adding the large sites as exceptions can be almost missing the point, the main object what the feature is thought to achieve.

ie. it is ok to add youtube/facebook/netflix/dailymotion/... as exceptions, but the number of the users who actually want the feature and ask "please disable autoplay!" should be larger than small/domesitc sites, therefore we should be very careful to add exceptions and investigate how much users on which sites actually disable autoplay (via telemetry for example) and change the rulesets on the investigation constantly, tracking the statistics.

that means ... if almost nobody disables autoplay, IMHO enabling autoplay by default is a reasonable way, instead of adding a number of sites as exceptions.

**Comment by darkdh** [comment]
we should revisit this after https://github.com/brave/muon/pull/264 landed. There will definitely be less sites to add

**Comment by bsclifton** [comment]
Closing for now, since this is a bit stale.  @darkdh please re-open or issue a new PR when you're ready for a re-evaluation 😄 👍

**Pull request closed without merging**
