### PR TITLE
add terms of service to payments

### LINKED ISSUE #11942: Add link on about:preferences#payments panel to Brave Payments Contributors Terms of Service
as noted in the mockup above, there should be a link on about:preferences#payments labelled "Terms of Service" that opens a new tab at https://basicattentiontoken.org/contributor-terms-of-service/

**New mock for ledger table**

### PR DESCRIPTION
**Pull request by cezaraugusto**
close #11942

screen shot 2017-11-14 at 4 46 32 pm

### CODE REVIEW

**Comment by NejcZdovc** [comment]
I would suggest to something less intrusive (it's just a terms of service)

reduce height from 50 to 30

and set link to 
```
    color: #999;
    font-size: 13px;
```

so end result is something like this

image

**Comment by NejcZdovc** [comment]
maybe even decrease spacing above link

@cezaraugusto @bradleyrichter

**Comment by bradleyrichter** [comment]
Please put it at the bottom of the window where fine print normally goes. We are trying to reduce the visual noise/complexity at the top of the UI.

cc @mrose17 @NejcZdovc

**Comment by cezaraugusto** [comment]
@bradleyrichter could you make a spec for this? I just followed the raw image in issue's comment

**Comment by NejcZdovc** [comment]
sounds totally good with me to put it at the bottom of the page

**Comment by bsclifton** [comment]
Mockup from @bradleyrichter:
image

**Comment by bradleyrichter** [comment]
@cezaraugusto @bsclifton 

image


15pt normal weight, dark grey color, right aligned

**Comment by cezaraugusto** [comment]
updated:

### Without "view all" button

screen shot 2017-11-14 at 11 19 06 pm

### with "view all" button

screen shot 2017-11-14 at 11 17 55 pm

**Comment by bradleyrichter** [comment]
Looks good.

**Comment by bsclifton** [comment]
master 05113200755776b770318517710f8827cf640659
0.21.x 90942a6a7476b809c78b9794f02b5e7e4f0937d1
0.20.x ce815a82437321fd6ca10db53cb842d761329b5c
0.19.x f284dbe63c3683dc24b0ab403cb2568314bc9292

**Pull request merged**
