### PR TITLE
Re-introduce bookmark modal

### PR DESCRIPTION
**Pull request by bsclifton**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Re-introduce bookmark modal

- add/edit current site uses the bookmark hanger
- all other cases use a new control which wraps a modal around a slightly different
  version of the bookmark hanger.

Fixes https://github.com/brave/browser-laptop/issues/5103

Auditors: @jkup, @bbondy

### CODE REVIEW

**Comment by bsclifton** [comment]
This might need some small tweaks (ex: it should auto-focus on text field when opened, etc) but it's working good :smile:

**Comment by bsclifton** [comment]
Has a positioning issue and (if time allows) would be nice to match modal closer to mockup in https://github.com/brave/browser-laptop/issues/2894#issuecomment-255921575

**new bookmark folder**
screen shot 2016-10-25 at 9 08 31 am

**create new bookmark**


**add bookmark (with the hanger)**
screen shot 2016-10-25 at 9 09 00 am

**Comment by jkup** [comment]
Moving the code into a separate file LGTM! I think we need the modal centered and the input auto-focused before we ship but looking great so far!

**Comment by bsclifton** [comment]
@jkup @bbondy updated PR-  I fixed the centering of the modal and then added a close button in the top right

screen shot 2016-10-25 at 4 38 26 pm
This does not show for the bookhanger mode

Ready for re-review / merge

**Comment by jkup** [comment]
@bsclifton looking great! I think it's ready to ship, just one question for @bradleyrichter:

When a bookmark from the bookmarks bar is right clicked on and you click edit, should it be the centered no arrow or the arrow pointing at the star? I know the final design wants the arrow to point to the bookmark but I mean for now..

Other than that ready to ship!

**Comment by bbondy** [comment]
merging!

**Comment by luixxiul** [comment]
@bbondy Was this included in 0.12.7 Preview1?

**Comment by bbondy** [comment]
no

**Comment by bsclifton** [comment]
Created https://github.com/brave/browser-laptop/issues/5163 for the remaining style work. @bradleyrichter if you get a chance, can you pls check it out, add notes, and prioritize?  thanks :smile:

**Pull request merged**
