### PR TITLE
New electron dialog changes

### LINKED ISSUE #1985: File extensions not auto added to some downloads
I have a user report from support that file extensions are not being added for downloaded files.  The user says they have to guess the file extension so the file gets saved.

### LINKED ISSUE #3313: Modal save dialog causing lockup on macOS
**Did you search for similar issues before submitting this one?**
Yes.
**Describe the issue you encountered:**
Switching tasks on OS X with save dialog open in a multi-tab window renders that window unavailable.

**Expected behavior:**
Window should remain accessible so operation can be completed or cancelled and session can be used (as does happen if only a single tab was open in that window).
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OS X 'El Capitan' (10.11.6)
- Brave Version:
  0.11.5 (update channel: dev; checked for updates before replicating, no updates currently available)
- Steps to reproduce:
  1. Open 2+ tabs; on one of those tabs, trigger any file download from the web, so modal 'save as' dialog appears. (Doesn't seem to occur on single-tab windows.)
  2. Switch away, e.g. with command-Tab
     3.Switch back. Brave no longer operational. (Can be selected from command-tab list, but no longer shows the affected window; most menu items disabled, presumably because the no-longer-visible save dialog is still waiting for input it will never get.) Rough guess: modal message pump swallowing activation event so the main window never activates; some interaction with the tab/window association so this is multi-tab specific.
- Screenshot if needed:
- Any related issues:

### LINKED ISSUE #3784: Save As/file selection dialog appears twice when offline
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When offline, using the Save As command results in the file selection dialog appearing twice

**Expected behavior:**
Dialog should only appear once
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.12.0
- Steps to reproduce:
  1. Load a page
  2. Disconnect from network
  3. File | Save As
  4. Choose a file name and press Save

Expected: Page saved, no further activity

Actual: Page is not saved (#3783) and the Save As/file-selection dialog appears again
- Screenshot if needed:
- Any related issues:

### LINKED ISSUE #3864: "Save as" dialog can't be closed with ESC key
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**
When the "Save as" dialog appears asking you where to save the file you want to download, it can't be closed with the ESC key and you have to move the mouse to the Cancel button and click it in order to close the modal.

The source of the problem is that when the modal appears it does not gain focus on it, the focus is still on the webview.

**Expected behavior:**
Hitting ESC key when the Save as modal is opened should close it and the active tab should gain focus again.
- Platform (Win7, 8, 10? macOS? Linux distro?): Linux
- Brave Version:
  0.12.1
- Steps to reproduce:
  1. Try to download file
  2. When the Save as modal appears press ESC
  3. See nothing happens
- Screenshot if needed:
- Any related issues:

### LINKED ISSUE #8096: Set the file type filter when presenting a save dialog
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When saving an image, Brave does not populate the _Save as type_ value in the dialog.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/3de60d52df3ef48d12d9696a076b72079beb9658

- Steps to reproduce:
    1. Navigate to https://i.imgur.com/3w0l0MM.png
    2. Right click, and select _Save Image_
    3. Note that _Save as type_ is "All Files (\*.\*)" rather than "PNG Image"
    
- Actual result:

image

- Expected result:

image

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

### LINKED ISSUE #8854: The Linux/Gtk File Uploader Dialog does not show any image preview on the side.
> Platform and version:

Linux (Gtk) - Xubuntu 16.04
Brave: 0.15.2 
rev: af7ef42ad622f899312a38bdd0e2138154393627 
Muon: 2.58.9 
libchromiumcontent: 58.0.3029.96 
V8: 5.8.283.37 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: linux 
os.release: 4.8.0-49-generic 
os.arch: x64

> - Steps to reproduce:
   
    1. Open any image sharing site, upload image/picture
    2. The file chooser dialog pops up; however unlike firefox/chromium, the side preview is not visible
 
Chromium currently uses gtk2, however it has side preview too. 
problem

### LINKED ISSUE #9409: File picker does not function on Windows Server Core
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
File upload buttons do not open a file selector.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows Server 2016 Core (specifically, Windows Hyper-V Server 2016)

- Brave Version (revision SHA):
fba98fc

- Steps to reproduce:
    1. Visit a page with a file upload field.
    2. Click the "Choose File" button.
    
- Actual result:
No user-visible action. No ability to select a file.

- Expected result:
File Open dialog or similar file picker should appear to allow the user to select a file.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
N/A

- Any related issues:
None found.

### LINKED ISSUE #9435: File downloads crash Brave on Windows Server Core
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
File downloads crash the browser.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows Server 2016 Core (specifically, Windows Hyper-V Server 2016)

- Brave Version (revision SHA):
fba98fc

- Steps to reproduce:
    1. Visit a page with a file download link.
    2. Click the download link.
    
- Actual result:
Browser crashes without any dialog or other grace.

- Expected result:
File should download

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
N/A

- Any related issues:
Potentially #9409

### LINKED ISSUE #10260: Choose default download path not working
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
It is not possible to choose where to save downloads the menu appears but nothing happens when you choose where to download.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS X 10.9.5
- Brave Version (revision SHA):
0.18.14
- Steps to reproduce:
    1. Open brave with new profile
    2. Choose where to download a file
    
- Actual result:
Does not work, the download destination never gets set
- Expected result:
Default download path should be setable
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

### LINKED ISSUE #10653: "Save Image..." very often crashes the browser
- Describe the issue you encountered:
When I right-click on an image and choose "Save Image...", the save dialog appears. Sometimes this works fine. However, very often the browser will crash as the dialog window appears.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 Pro.

- Brave Version (revision SHA):
36ae2ec

- Steps to reproduce:
    1. Right-click on an image.
    2. Choose "Save Image..."
    
- Actual result:
The browser crashes.

- Expected result:
I should be able to save the image without issues.

- Can this issue be consistently reproduced?
No.

I save images quite often. As a result, I'm experiencing browser crashes at least 20+ times a day, and then when I restart the browser I end up with a session from some time ago. There are various other bugs with Brave that I can overlook, but unfortunately this one is becoming way too big of an issue for me. I'm becoming very frustrated with the browser crashing constantly over and over and over and over again, and then as a result losing my open tabs, losing my position in videos, losing my current input into forms, losing my scroll position on long pages...

I love Brave for the clean and compact UI, the Shields system, and for being designed with privacy in mind... But sadly I am going to have to stop using it as my main browser until it becomes more stable. :(

### LINKED ISSUE #11452: "Save Torrent" button does not seem to do anything
Similar, but seemingly different, issue: #8146

### Description
Pressing the "Save Torrent File..." button on a torrent download doesn't seem to do anything.

### Steps to Reproduce
  1. Go to e.g. https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/
  2. Click on a torrent and open the torrent download page, e.g. https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-9.2.0-amd64-netinst.iso.torrent
  3. Click on the 'Save Torrent File...' button.

**Actual result:**
Nothing, no indication that anything happens.

**Expected result:**
Save-as popup with option to save the .torrent file.

**Reproduces how often:**
Always, tried with some torrents.

### Brave Version

0.18.36 on Ubuntu 16.04.3 installed with snap
0.19.42 on Windows 10

**Reproducible on current live release:**
Don't know what this means.

### Additional Information
(Why is there a torrent downloader at all? Where do the files go that it downloads?)

### PR DESCRIPTION
**Pull request by darkdh**
requires https://github.com/brave/muon/pull/385

fix #1985
fix #3313
fix #3784
fix #3864
fix #8096
fix #8854
fix #9409
fix #9435
fix #10260
fix #10653
fix #11452

Auditors: @bridiver, @bbondy, @bsclifton

Test Plan:

a. download things from web page
1. Go to https://brave.com/about/images/brave_icon_512x.png
2. Save Image
3. The dialog should have extension option with `png`
4. The default path should be your download path
5. Test it can be saved or cancel successfully

b. dev tools performance profile upload/download
1. Open dev tools and go to Performance
2. Hit Record to generate the profile
3. Save Profile
4. The default path should be your download path
5. Test it can be saved or cancel successfully
6. Upload Profile
7. Test it can be uploaded and accepted by devtool

c. Ledger recovery file
1. Go to about:preferences#payments
2. Recover your wallet by import recovery key
3. The default path should be your user profile
4. The dialog should have extension option with `txt`
5. Test it can be imported or cancel successfully

d. export bookmark
1. Menu->Bookmarks->Export bookmarks
2. The default path should be your download path
3. The dialog should have extension option with `html`
4. Default extension is `html`
5. Test it can be saved or cancel successfully

c. import bookmark by html
1. Menu->Bookmarks->Import Browser Data.. and select HTML file
2. The default path should be your download path
3. The dialog should have extension option with `html`
4. Default extension is `html`
5. Test it can be imported or cancel successfully

d. Open Files
1. Menu->File->Open File...
2. The default path should be your download path
3. Make sure you can multiple select
4. (Linux) If you choose pictures, there should be preview
5. Test they can be imported or cancel successfully

e. torrent download
1. Go to https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-9.2.1-amd64-netinst.iso.torrent
2. Click Save Torrent File...
3. The default path should be your download path
4. The dialog should have extension option with `torrent`
5. Test it can be saved or cancel successfully

f. Webpage save
1. Go to https://brave.com/
2. Context Menu-> Save Page as..
3. The default path should be your download path
4. The dialog should have extension option with `html`
5.  Test it can be saved or cancel successfully

g. Save link
1. Go to https://brave.com/
2. Right click on Download Brave
3. Save Link As
4. The default path should be your download path
5. The dialog should have extension option with `dmg`/`exe`/`deb`
6. Test it can be saved or cancel successfully

h. Test esc 
1. Go to https://brave.com/
2. Context Menu-> Save Page as..
3. Press ESC
4. Dialog should be dismissed

i Image preview (Linux)
1. Go to https://imgur.com/
2. Click New Post and browser files
3. Click on any images 
4. There will be a preview on the side

j Set Download path
1. Open brave with new profile
2. Got to about:preferences#general
3. Choose where to download a file
4. Download path can be set

Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by darkdh** [comment]
Test plan specified. Ready for review

**Comment by darkdh** [comment]
This PR has API changes. Please do upgrade to muon 5.0 and merge this PR simultaneously, @bsclifton.

**Comment by darkdh** [comment]
master: 76e7d6828fed45d30725213d843ed20b387feb75
0.21.x: 1c7b3ffd4f7bb9f8e78467cb7579c1b48a59a8fd

**Comment by srirambv** [comment]
@darkdh does this also detect pdf?

**Comment by darkdh** [comment]
@srirambv yes.
screen shot 2018-02-01 at 8 22 35 am

**Comment by bsclifton** [comment]
So awesome seeing this merged! Great work, @darkdh! 😄

**Comment by srirambv** [comment]
@darkdh scenario e fails. Shows `All files` but doesn't have `Torrent` 
11906-torrent

**Comment by srirambv** [comment]
Scenario d also fails on a clean profile. Points to desktop instead of default download path

11906-openfile

**Comment by darkdh** [comment]
@srirambv please open issues in milestone 0.21.x for those scenarios and assign them to me. Thanks

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Pull request merged**
