### PR TITLE
replace node classList with dataset

### LINKED ISSUE #10443: replace node classList instances with dataset
This unblocks #10234

### PR DESCRIPTION
**Pull request by cezaraugusto**
fix #10443 
unblocks #10234

1. have enough bookmarks to show the overflow indicator
2. click the overflow, should open
3. open a bookmark pull down with children
4. you should be able to click the second level child
5. second level child should be nested visually with its parent

### CODE REVIEW

**Comment by srirambv** [comment]
Not seeing any second level child due to https://github.com/brave/browser-laptop/issues/12052

**Comment by srirambv** [comment]
@cezaraugusto Is this expected?

**Comment by cezaraugusto** [comment]
can't see a bug in the screenshot what's missing?

**Comment by srirambv** [comment]
The nested items open on to the left used to be right

**Comment by cezaraugusto** [comment]
ya it's expected because the parent menu is on the right. Chrome does the same

**Pull request merged**
