### PR TITLE
Resolves issue 13123

### LINKED ISSUE #13123: Salon detects Brave as ad-blocker
### Description
Users who visit salon.com will be presented with an ad-block message.

### Steps to Reproduce
Navigate to Salon.com

**Actual result:**
Ad-blocker message is presented

**Expected result:**
User is able to browse uninterrupted

**Reproduces how often:**
Always

### Brave Version
0.20.30

**about:brave info:**
``` 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119
```

**Reproducible on current live release:**
Yes

### PR DESCRIPTION
**Pull request by jonathansampson**
## Submitter Checklist:

Resolves #13123 

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
1. Navigate to Salon.com
2. Note that ad-blocker message is not shown

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by lukemulks** [comment]
@jonathansampson this tests well for me. Not sure re: the conflict above with `app/extensions.js` - but confirm that your fix here removes the overlay as expected.

**Comment by bsclifton** [comment]
@jonathansampson can you give this a rebase?

**Comment by bsclifton** [comment]
@jonathansampson is this still needed? Looks like it's working now?

**Comment by jonathansampson** [comment]
@bsclifton I'm not able to repro any longer; may have benefited from ad-block list somewhere :)

**Pull request closed without merging**
