### PR TITLE
Replaced as many var as possible using ES6 let and const

### PR DESCRIPTION
**Pull request by joshstevens19**
It would be great if we can kill a lot of the old `var` syntax and use the ES6 `let` and `const` where applicable. 

I have ran through the entire library and replaced every instance which i could with ES6 syntax variables. All tests work and i have ran through all the scripts, nothing has been broken. 

If someone can take a look at this PR it be brilliant to get rid of so many instances of the horrible `var` #theendofvar

### CODE REVIEW

**Comment by joshstevens19** [comment]
Can anyone look at this...?

**Comment by bsclifton** [comment]
@joshstevens19 thanks for opening the issue and the PR

Unfortunately, I think a massive change like this is going to be difficult to properly test. Our automated tests are limited and our manual QA time is also limited. If this was presented in multiple PRs which have bite-sized changes, it might be easier to accept

That said, we are moving to sunset this version of Brave (browser-laptop) in favor of a UI forked from Chromium ([brave-core](https://github.com/brave/brave-browser) - which would have a lot less JavaScript- the parts which do are using TypeScript)

For those reasons, I'm going to close this PR (and the accompanying issue). Thanks for the effort, we definitely appreciate it

**Comment by joshstevens19** [comment]
No worries Brain. I would love to be involved in the rewrite so if there's anything i can help with let me know 👍

**Comment by bsclifton** [comment]
@joshstevens19 awesome 😄 If you wanted to take a quick peek, I can walk you through some of the points of interest:

https://github.com/brave/brave-browser
This repo is the starting point if you wanted to build the new version of the browser. When you follow the steps (building can take several hours and also it takes almost 100GB of disk space), you can build the full browser

https://github.com/brave/brave-core
This project has code that we use to patch Chromium and add new functionality for the browser. There are some JavaScript files here- but it's mostly C++.  The JavaScript code is typically used for WebUI views

https://github.com/brave/brave-extension
This is the code for the actual Brave extension that gets loaded (ex: the lion that shows the # items blocked, where the shields panel is, etc). This is all JavaScript and you should see some good typescript usage here

We also have a few other projects which deal with BAT and Brave Payments which you can find here:
https://github.com/brave-intl/

Hope this helps 😄 And thanks again for the contribution- we definitely appreciate your time

**Pull request closed without merging**
