### PR TITLE
Add Swedish language to browser

### PR DESCRIPTION
**Pull request by aekeus**
Test plan in commit message

### CODE REVIEW

**Comment by Jacalz** [comment]
++

**Comment by Jacalz** [comment]
Preferably I would like to get this to the second 0.18.x hotfix if possible @bsclifton

**Comment by luixxiul** [comment]
I'm not sure why `npm run download-languages` did not download them.

**Comment by bbondy** [comment]
I don't think we want this file:
 app/extensions/brave/locales/sv-SE/swedish.zip

**Comment by aekeus** [comment]
.zip file removed

**Pull request merged**
