### PR TITLE
0.12.2dev titlebar fixes (round 2)

### PR DESCRIPTION
**Pull request by bsclifton**
- Container cleanup in main.js after properly learning how to use display:flex
- dead areas are now isolated to their own div and ONLY those have `drag` applied (versus the parent container having drag and excluded children having `no-drag`)
- Fix wrapping of new tab button (problem only visible when magnified 150%)
- Cleanup windowCaptionButton to use classSets

Fixes https://github.com/brave/browser-laptop/issues/4245
Fixes https://github.com/brave/browser-laptop/issues/4236

Appears to mostly fix https://github.com/brave/browser-laptop/issues/4235

Auditors: @bbondy

### CODE REVIEW

**Comment by bbondy** [comment]
lgtm!

**Comment by bsclifton** [comment]
after testing some more, it's got at least one issue:
menu height is not correct

Working on fix...

**Comment by bsclifton** [comment]
fixed- menu was hardcoded to 29px

**Comment by bsclifton** [comment]
and fixed the issue w/ caption buttons. Had a bad selector

**Comment by bsclifton** [comment]
Using this pic as reference:
screenshot 2016-09-23 08 16 09

There are still some dead areas

**Comment by bbondy** [comment]
++

**Pull request merged**
