### PR TITLE
cleanup about page handling and fix missing document.l10n

### LINKED ISSUE #6012: document.l10n is sometimes undefined
document.l10n is accessed in about pages, but it is loaded after the script and can be missing when it is checked

### PR DESCRIPTION
**Pull request by bridiver**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

fixes #6012

Test Plan:
For each about page:
1. Load the page
2. Ensure that the page and favicon load correctly

### CODE REVIEW

**Comment by bridiver** [comment]
@bbondy @bsclifton

**Comment by bsclifton** [comment]
++ I like this :sunglasses:

**Comment by bbondy** [comment]
++

**Comment by bbondy** [comment]
Sorry I had to back this out because it was causing development builds to not see changes. webpack-dev-server doesn't know about gen.

**Comment by bridiver** [comment]
@bbondy gen is also the path for the webpack dev server. The change to the filtering code send it to localhost or the file path depending on the env. I tested it and didn't see any problems, can you give me a specific example of something that didn't update?

**Comment by bridiver** [comment]
I just rebased it and tested updating preferences.js (for about pages) and main.js (for the main window) and both reloaded automatically

**Pull request merged**
