### PR TITLE
Cache HttpsEverywhere lookups

### PR DESCRIPTION
**Pull request by Empact**
I have a few questions for this:

* Is expiry necessary?
* Would you prefer to extract a separate function for lookup only, apart from the caching?

#1184

### CODE REVIEW

**Comment by diracdeltas** [comment]
ben working on LRU cache right now

**Comment by Empact** [comment]
Updated with an LRU cache now - but haven't done any benchmarking yet.

**Comment by diracdeltas** [comment]
++, lgtm! but @bbondy should probably sign off on the Tracking Protection changes.

**Comment by bbondy** [comment]
lgtm too, merging.

**Pull request merged**
