### PR TITLE
Split PaymentsTab into its own component

### LINKED ISSUE #5887: Add unit tests for ledger backup and minimum visits
Following this comment from @bsclifton https://github.com/brave/browser-laptop/pull/5824#issuecomment-263382889

We should add some testing around two recent fixes:

1. Advanced ledger settings stopped persisting https://github.com/brave/browser-laptop/issues/5637
2. Clean up formatting for ledger wallet backup https://github.com/brave/browser-laptop/pull/5862

### LINKED ISSUE #6528: Split PaymentsTab into its own component
This relates to both https://github.com/brave/browser-laptop/issues/3717 and https://github.com/brave/browser-laptop/issues/5887. In order to unit test the changes mentioned in https://github.com/brave/browser-laptop/issues/5887 it's easiest to split it out into its own component.

### PR DESCRIPTION
**Pull request by jkup**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

This ticket both splits PaymentsTab out into its own component and adds automated tests for its functionality.

Fix #6528, fix #5887 

@bsclifton I'm not thrilled with my fakeSetting API, can you help me make it a little more scalable? Maybe in another ticket? Eventually I assume we'll need more than just true for all or false for all which is all mine can handle!

Auditors @bsclifton @bbondy @cezaraugusto please let me know what you think!

Test Plan:
`npm run unittest -- --grep="Preferences component"`

Ready for people to take a look at this! You can change line 15 on paymentsTabTest.js to be describe.only and then with watch-all running you can just run `npm run unittest`.

#6456 #6455 #6422

### CODE REVIEW

**Comment by bsclifton** [comment]
I tried running this locally (macOS) and ran into the following:
```
1) Preferences component loads "before all" hook:
     Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
      at invariant (node_modules/fbjs/lib/invariant.js:44:15)
      at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (node_modules/react-dom/lib/instantiateReactComponent.js:68:134)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:367:22)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at mountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:104:32)
      at ReactReconcileTransaction.perform (node_modules/react-dom/lib/Transaction.js:140:20)
      at batchedMountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:126:15)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:97:27)
      at Object._renderNewRootComponent (node_modules/react-dom/lib/ReactMount.js:320:18)
      at Object._renderSubtreeIntoContainer (node_modules/react-dom/lib/ReactMount.js:401:32)
      at Object.render (node_modules/react-dom/lib/ReactMount.js:422:23)
      at Object.renderIntoDocument (node_modules/react-dom/lib/ReactTestUtils.js:79:21)
      at renderWithOptions (node_modules/enzyme/build/react-compat.js:187:26)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:94:59)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at Context.<anonymous> (test/unit/about/preferencesTest.js:40:21)
```

When I scrolled up to where the test was executed, you can see the additional errors logged via stdout:
```
Preferences component
    loads
Warning: Failed prop type: The prop `Component` is marked as required in `<<anonymous>>`, but its value is `undefined`.
    in Unknown
Warning: Failed prop type: The prop `props` is marked as required in `<<anonymous>>`, but its value is `undefined`.
    in Unknown
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
      1) "before all" hook
```

Is there something I missed?

**Comment by jkup** [comment]
@bsclifton sorry! was messing around with them late last night and made a breaking change. Should be good now although two of the (unrelated) preferencesTest.js tests are broken in master. I'll follow up on those separately with @bbondy.

**Comment by bsclifton** [comment]
@cezaraugusto this PR is also breaking the payments tab out from `preferences.js` into it's own file

**Comment by bsclifton** [comment]
If this looks good to you (either @cezaraugusto or @bbondy), please approve using GitHub and then mark with the ready-to-merge label :smile:

**Comment by cezaraugusto** [comment]
ok sorry, GitHub grouped `paymentsTab.js` which I missed.

LGTM

**Comment by luixxiul** [comment]
Please make sure that there are several PRs which will be conflicted if this is merged first.
cf: https://github.com/brave/browser-laptop/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20label%3Afeature%2Fledger%20-label%3Atests

Could I remove the ready-for-merge label for now, so that this PR will not be merged first? thanks

**Comment by luixxiul** [comment]
I moved the `release-notes/exclude ` label to #6528, which is an issue associated with this PR.

**Comment by bsclifton** [comment]
Rebasing this now... should be a great cleanup 😄

**Comment by bsclifton** [comment]
Gonna watch CI on this one; should be good to merge though! 😄

**Comment by bsclifton** [comment]
Reran failing tests locally; a few unrelated tests seem to be perma-failing ☹️  

I believe it's safe to merge this since the ledger tests are passing and the failing tests are not impacted by these code changes

**Comment by bsclifton** [comment]
re-assigned 0.13.1 milestone after merge was redone properly

**Pull request merged**
