### PR TITLE
Increase urlbar fontsize

### LINKED ISSUE #7848: increase font size in URL text to match chrome

### PR DESCRIPTION
**Pull request by cezaraugusto**
- Auditors: @bradleyrichter
- Close #7848

Test Plan:
* While this font size is pre-approved by @bradleyrichter, it's worth checking urlbar icons (list, lock, unlock and search) that must be aligned with new font size.

Tagging @bsclifton for review on Windows

Screenshots (macOS):

screen shot 2017-04-19 at 12 41 01 am
screen shot 2017-04-19 at 12 41 17 am
screen shot 2017-04-19 at 12 40 36 am
screen shot 2017-04-19 at 12 40 52 am

### CODE REVIEW

**Comment by bsclifton** [comment]
Looks good at 100%
screen shot 2017-04-19 at 2 31 47 pm

**Comment by bsclifton** [comment]
Looks good at 125% too 😄 
screen shot 2017-04-19 at 6 27 37 pm

**Comment by bsclifton** [comment]
@bradleyrichter Windows pictures shared above ^^

**Comment by cezaraugusto** [comment]
btw also tested on Ubuntu, works the same as mac

**Comment by bsclifton** [comment]
@bradleyrichter LOL 🤦‍♂️ 

I think of @cezaraugusto as the King of Tabs and subconsciously thought this PR was tweaking tab fonts. Re-checking on Windows now...

**Comment by cezaraugusto** [comment]
sorry line-height issue, reduced to 1.4 :)

**Pull request merged**
