### PR TITLE
Try to interpret last cmdline argument as url (2)

### LINKED ISSUE #9193: opening URL from external application (Thunderbird/LibreOffice) does not work any more
Xubuntu 16.10
Brave	0.15.310 rev	6b5e4e2
os.platform	linux
os.release	4.8.0-53-generic
os.arch	x64

- Issue:
opening URL from external application (Thunderbird/LibreOffice) does not work any more. It works only when there is no Brave instance running yet. When Brave is running already, it focuses the Brave Window, but no tab is opened :/

- Steps to reproduce:
    1. Have Brave opened alread with several tabs
    2. click on link URL from Thunderbird and/or other application
    
- Actual result:
When Brave is running already, it focuses the Brave Window, but no tab is opened :/

- Expected result:
URL gets opened in Brave as before

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Do not know

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes, various restarts performed

### PR DESCRIPTION
**Pull request by ghost**
Recreation of #9890

The cased treated before were very limited and unlike other browsers e.g

  - `firefox [OPTIONS] [url]`
  - `chromium-browser [OPTION] [PATH|URL]`

This commit assumes (like other browsers) that the last argument
 is an url and tries to interpret it as such.
 If that fails, then it simply returns `undefined`, as before.

Resolves brave/browser-laptop#9193 opening URL from external application (Thunderbird/LibreOffice) does not work any more

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by LoveIsGrief** [comment]
@bsclifton here's the new PR 🙂

**Review by darkdh — APPROVED** [review]
lgtm

**Comment by bsclifton** [comment]
Updated PR to revert the work-around I tried 😄

**Review by bsclifton — APPROVED** [review]
Tested using Ubuntu 14.04. I did the following:
- packaged build + created .deb files
- installed from .deb
- verified that links opened from Thunderbird correctly open in Brave

This is with the reverted .desktop file; my exec line looks like:
`Exec=brave %U`

**Comment by bsclifton** [comment]
Congrats on your first contribution, @LoveIsGrief 😄  This is a great fix

**Comment by LoveIsGrief** [comment]
Thanks for incorporating it, @bsclifton 🙂

**Comment by bridiver** [comment]
with this change I'm seeing Brave try to open the app url in dev mode

**Pull request merged**
