### PR TITLE
Re-organise comments in Issue Template

### PR DESCRIPTION
**Pull request by srirambv**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:
Ensure new format is retained for issue template

Reviewer Checklist:

Tests
Fixes : #11030

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by luixxiul** [comment]
Of my preference, these in one liners look too dense.

- `### Steps to Reproduce  <!-- Please add a series of steps to reproduce the problem. See https://stackoverflow.com/help/mcve for in depth information on how to create a mimimal, complete, and verifiable example. -->`
-  `### Additional Information <!-- Any additional information, related issues, extra QA steps, configuration or data that might be necessary to reproduce the issue. -->` 

Instead, adding another empty line before `###` seems to work better, in my opinion.

**Comment by NejcZdovc** [comment]
Personally I prefer it in one line, because when I first saw new template I was kinda confused, because I didn't know (without a little bit of thinking) where to put my text, specially if you have title then empty space and then comment.

**Comment by luixxiul** [comment]
> when I first saw new template I was kinda confused

Let's keep in mind that new contributors has never seen the old template and that we eventually could learn where to put the text. We need some investigation period.

**Comment by srirambv** [comment]
Having it like
```
<-- 
Comment
 -->
```
makes it look like we are asking the users to type the details inside the comment. Instinctively it goes inside that. Hence the reason for this PR to put the comments in one line

**Comment by NejcZdovc** [comment]
I was under the same impression as @srirambv

**Comment by cezaraugusto** [comment]
hey @srirambv I'm going to close this as stale please re-open when you have a window to make it again. Thanks!

**Pull request closed without merging**
