### PR TITLE
Replace Payment History CSV export with Contribution Statement PDF (rebased)

### PR DESCRIPTION
**Pull request by willy-b**
This is a rebase of work reviewed in PR #4771 and replaces it. Implements #4769.

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist. (issue #4769 )
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message. 
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits

Test Plan:
1. Open Brave
2. Open Preferences -> Payments, and ensure it is enabled
3. If you don't have a Payment History, you can generate a fake one at terminal with `npm run add-simulated-payment-history`
4. Click "Show Payment History"
5. Observe "Receipt Link" column now has links ending in ".pdf"
6. Click a receipt link, and confirm that a Save dialog opens and suggested filename is same as the one displayed in Receipt Link column
7. Click "Save", and observe that the PDF is downloaded and appears in the Downloads bar at bottom of screen
8. Double click the downloaded file
9. Check PDF against mockup

### CODE REVIEW

**Comment by bsclifton** [comment]
I rebased to squash the commits I had made and added the autoclosing keywords (ex: fixes)

Giving this one last spin locally before accepting... also will look at the automated tests :smile:

**Comment by bsclifton** [comment]
[tests failed for some reason](https://travis-ci.org/brave/browser-laptop/builds/179829856) (they didn't even start to run); but locally, they ran great :smile: Merging!

**Comment by willy-b** [comment]
Nice, thanks. Just to understand your process @bsclifton, did you replace the commits from this PR / my branch with your own single squashed commit in the end?

**Comment by willy-b** [comment]
Nevermind, just got confused by all the force-push rebasing :-D. Thanks for the thorough review and fixes @bsclifton!

**Pull request merged**
